### ISSUE TITLE
Shadow texture too large for android issues uncaught errors on render

### ISSUE THREAD

**Issue by jtreher** [mrdoob/three.js#9289]
##### Description of the problem 

I'm not sure if this a bug for sure as I am very green to ThreeJS. I understand that large textures are not supported in android based hardware/OS version. The latest generation supports 4096x4096. When enabling shadow.map.height /width > 4096, the shadow does not render and I get a ton of these errors below. I can easily figure out a better width/height via grabbing the max texture size supported, but I'm not sure if this should be handled differently in ThreeJS itself to more gracefully bomb. Perhaps it should remove the shadow and just issue a console warning when the shadow texture is too large or even downsize automatically.

[.CommandBufferContext.Offscreen-MainThread-0xe936f420]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
KrmoGB:1

[.CommandBufferContext.Offscreen-MainThread-0xe936f420]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete

[.CommandBufferContext.Offscreen-MainThread-0xe936f420]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

A pen to demonstrate : http://codepen.io/jtreher/pen/EyXOVR (line 59 and 60 , view in Android Chrome vs. desktop Chrome )

I have the pen using the dev version, but I also tried with r78. I did check revisions in the https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLShadowMap.js as well.

##### Three.js version

- [x ] dev
- [ x] r78

##### Browser

- [x] All of them
- [ ] Chrome

##### OS
- [ ] Android

**Comment by mrdoob** [comment]
Fixed!

**Comment by mrdoob** [comment]
Thanks!

**Comment by jtreher** [comment]
Beautiful!
