### ISSUE TITLE
Default value for material clippingPlanes

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#9294]
##### Description of the problem (r78)

In [the documentation is written that the default value for the `THREE.Material` `clippingPlanes` property](http://threejs.org/docs/#Reference/Materials/Material.clippingPlanes) is an empty array `[]`. But when I do:

    var plane = new THREE.Plane( new THREE.Vector3(0,1,0), 0 );
    material.clippingPlanes.push( plane );

I get the following error:

> Uncaught TypeError: Cannot read property 'push' of null

This is because [the default value for `clippingPlanes` is actually `null`](https://github.com/mrdoob/three.js/blob/master/src/materials/Material.js#L37) and not as expected an empty array.

##### Proposed change/fix

Not sure what fix is preferred but there are two options:

1) change default value for `material.clippingPlanes` to `[]` instead of `null`
2) update the documentation where it is explained that the default value is `null`.

**Comment by rhairston** [comment]
You have to enable clipping first. I don't know if tis has anything to do with the error though.

**Comment by WestLangley** [comment]
I would update the documentation to match the code.

**Comment by Wilt** [comment]
When setting it to an empty array by default it would be that one can push a plane into the `clippingPlanes` property directly without checking whether the variable is already an array or not. So IMHO this could be a bit easier since one could totally skip type checking working with the clipping planes.

**Comment by rhairston** [comment]
You would still have to enable localClipping in the renderer, so having it an empty array by default may cause people to forget to enable it

**Comment by Wilt** [comment]
@rhairston That is not true, **local clipping**, so when you add clipping planes to your materials (hence the name local clipping), needs the `localClippingEnabled` property of the renderer to be set to true. **Global clipping** will work immediately when you add the planes to the renderer.

**Comment by rhairston** [comment]
Did I not say enable LocalClipping in renderer? How is that NOT true? If you were talking about global clipping in the original question then you didn't make it clear.
Since both local and global objects will inherent from Object3D, they both have the same ```null``` reference for clippingPlanes.

**Comment by Wilt** [comment]
@rhairston My bad... What I meant was that for global clipping you don't need to enable this. I got confused myself apparently because I just noticed that the array for global clipping [is by default already an empty array](https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L55). So you are totally right in your comment. Sorry...

**Comment by tschw** [comment]
@Wilt 
> 2) update the documentation where it is explained that the default value is null

That one.

I guess I just forgot to update the default in the docs when pasting over the property description. We certainly don't want objects that don't use the feature to have to carry an extra object!

**Comment by Wilt** [comment]
PR here: https://github.com/mrdoob/three.js/pull/9322
