### ISSUE TITLE
JSON Exported from Maya Returns Errors

### ISSUE THREAD

**Issue by christopher4lis** [mrdoob/three.js#9305]
##### Description of the problem

Whenever I export a JSON object from Maya using the THREE.js exporter and try to import it into a scene using the JSONLoader object, I'm given the following error:

`three.min.js:395 Uncaught TypeError: Cannot read property '35' of undefined`

I've tested out other JSON objects from the web, and the scene seems to load them just fine. Only one of my JSON meshes that was exported from Maya works. The rest return the same error as above.

_UPDATE:_ I added the non-minified version so I could locate what line the error 
 occurred on. Here are the error messages:

`three.js:18797 Uncaught TypeError: Cannot read property '35' of undefined`

Line 18797 contains the following code:

`hex = colors[ colorIndex ];`
##### Three.js version
- [ ] Dev
- [x] r78
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by jamesgk** [comment]
I got this exact error when trying to export from Maya, and the issue turned out to be faces with more than 4 vertices. You might try triangulating the mesh before exporting, if you haven't already.
