### ISSUE TITLE
unable to intersect Three.Points

### ISSUE THREAD

**Issue by stilllearningthreejs** [mrdoob/three.js#9309]
##### Three.js version

- [ ] r77

##### Browser

- [x] All of them

##### OS

- [x] All of them

function init()
{
geometry = new THREE.Geometry();
vertex = new THREE.Vector3();
vertex.x=(  [i + 3 ] * 140 ) - 1330;
vertex.y = - ( [i + 3 ] * 180 ) + 990;
vertex.z = 100; 
geometry.vertices.push(vertex);

var particleTexture = THREE.ImageUtils.loadTexture(imgstr);
var materials = new THREE.PointsMaterial({
map:particleTexture,
size: 150
});
particles = new THREE.Points(geometry, materials);
scene.add(particles);
}

function onDocumentMouseMove( event ) {
                event.preventDefault();
                mouse.x = ( event.clientX / window.innerWidth ) * 2 - 1;
                mouse.y = - ( event.clientY / window.innerHeight ) * 2 + 1;
            }

            function onDocumentMouseDown(event){

            var projector = new THREE.Projector();
             var vector = new THREE.Vector3(
             (event.clientX / window.innerWidth) * 2 - 1,
             -(event.clientY / window.innerHeight) * 2 + 1,
             0.5);
             projector.unprojectVector(vector, camera);

            var raycaster = new THREE.Raycaster(camera.position,vector.sub(camera.position).normalize());
             var intersects = raycaster.intersectObjects(targetList);

 console.log(intersects.length);

            }

**Comment by WestLangley** [comment]
http://stackoverflow.com/questions/27864029/clickable-particles-in-three-js-pointcloud/27866242#27866242

http://stackoverflow.com/questions/28872583/three-js-raycasting-from-a-child-camera-to-the-scene/28873205#28873205

**Comment by stilllearningthreejs** [comment]
I tried that and all other samples that i could find, even today posted a query on Stackoverflow:http://stackoverflow.com/questions/38270733/unable-to-intersect-points but still i am unable to intersect the Three.Points. Struck on this for the past 4 days, apologize for posting it over here. Any guidance will be helpful.

**Comment by WestLangley** [comment]
Single-vertex bug: https://github.com/mrdoob/three.js/issues/7710
