### ISSUE TITLE
WebGLRenderingContext.getProgramInfoLog returns empty string of length 1

### ISSUE THREAD

**Issue by cojack** [mrdoob/three.js#9317]
##### Description of the problem

Maybe it's a bug of Chromium, but `programLog` contains a empty string of length 1
![threejs-bug](https://cloud.githubusercontent.com/assets/334297/16732848/5c727026-477f-11e6-8d9f-9680bd7d7118.png)
##### Three.js version
- [ ] Dev
- [x] r78
- [ ] ...
##### Browser
- [ ] All of them
- [x] Chrome - Version 51.0.2704.106 (64-bit)
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

AMD FX(tm)-8120 Eight-Core Processor
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Caicos [Radeon HD 6450/7450/8450 / R5 230 OEM]

Regards.

**Comment by easchwar** [comment]
I'm getting the same bug with r76, also using Chrome on Linux

**Comment by ZaWertun** [comment]
I've got same warning with threejs-r79 on Chrome 52.
Maybe it's related: https://bugs.chromium.org/p/chromium/issues/detail?id=111337.

Also when watching value of programLog in the dev console:
```javascript
programLog == ''
false
programLog == '\0'
true
```

**Comment by AlexanderPaule** [comment]
#11138 Same Warning, thrown by 4 length string.

**Comment by Mugen87** [comment]
Closing in favor for #11138
