### ISSUE TITLE
[Raycast] Problems with raycast in BufferGeometry without geometry index

### ISSUE THREAD

**Issue by carlosanunes** [mrdoob/three.js#9320]
##### Description of the problem 

Raycast fails to always detect intersections with geometry defined by BufferGeometry instances with no geometry index.

Was having problems picking objects imported via the ColladaLoader2 loader. Picking was not working for the whole object. Tested multiple collada models and the problem persisted. Tried picking a cube created via the BoxGeometry constructor and picking worked for the whole cube. Created a plane using the PlaneBufferGeometry constructor and picking worked for the whole plane. 
Inspecting the objects added to the scene via the ColladaLoader2 noticed that they were defined with BufferGeometry instances with no geometry index. While the plane created using the PlaneBufferGeometry constructor was defined with BufferGeometry instances but with geometry indices.

##### Three.js version

- [ ] Dev
- [x] r78
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by sjlynch** [comment]
Did you find a fix to this? In, I think r75, I was using the original ColladaLoader and picking worked fine then. If picking is broken in ColladaLoader2 then I think that is more of a bug and less of a "go to stackoverflow" issue.

**Comment by carlosanunes** [comment]
My fix was just checking for intersections of the bounding box of the object and not of any face. For my purposes it is also a more suitable approach in terms of user interaction, so I would probably have done it anyway. 

Not sure if I agree that this is a 'go to stackoverflow' issue as I really could not find what is/was wrong, and picking is indeed completely working for objects other than those imported via the ColladaLoader2 loader but it if no one else complains on this it might really be something very very specific or actually a 'go to stackoverflow' issue.
