### ISSUE TITLE
TextureLoader onload properties on iOS

### ISSUE THREAD

**Issue by sjfricke** [mrdoob/three.js#9321]
##### Description of the problem 

So I was loading an image with ```TextureLoader.load(url, onLoadFunction);``` and in my onLoadFunction where I pass the image I needed to find the URL via that parameter and what I found is that doing

```
onLoadFunction (texture) { 
   console.log( texture.image.currentSrc ); //full source URL
}
```
Got me the URL for desktop and android

The issue was when I tried loading the page on any iOS browser, what I found is that ```texture.image.currentSrc``` is undefined

my workaround was 
```
onLoadFunction (texture) { 
   console.log( texture.image.attributes[0].value ); //full source URL
}
```

But just curious whey this is an iOS issue, if its been noted somewhere, is there a better way of finding that source URL, and just an overall notice of this issue

##### Three.js version

- [ ] Dev
- [x] r78
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

**Comment by mrdoob** [comment]
It's an iOS issue. The library doesn't populate `currentSrc`.
