### ISSUE TITLE
THREE.AudioLoader load cached src 

### ISSUE THREAD

**Issue by mkungla** [mrdoob/three.js#9323]
##### Description of the problem

When I call to THREE.AudioLoader.load src on path which was already played on scene then I get errors

```
The buffer passed to decodeAudioData contains an unknown content type.path
EncodingError: The given encoding is not supported.
```

It seems that THREE.XHRLoader returns THREE.Cache `ArrayBuffer` and AudioLoader.decodeAudioData fails there.
##### Three.js version
- [x] Dev
- [x] 0.76.1
##### Browser
- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Oh, can you provide a jsfiddle we can work with?

**Comment by mkungla** [comment]
@mrdoob One very RAW example

````js
// Set up the scene switching between tracks after 3 sec
// For this example I have 3 mp3 tracks in directory radio
var scene = new THREE.Scene();
var camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );
var renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );
var audioListener = new THREE.AudioListener();
camera.add( audioListener );
var player = new THREE.Audio( audioListener );
player.autoplay = true;
scene.add( player );
var loader = new THREE.AudioLoader();

/**
 * You will see errors in console
 * 
 * The buffer passed to decodeAudioData contains an unknown content type.devel
 * EncodingError: The given encoding is not supported.
 */
THREE.Cache.enabled = true;

/**
 * THREE.Cache.enabled = false;
 *
 * Errors are gone and tracks switch
 */
var song_id = 1;
function switch_track() {
	if(song_id > 3) song_id = 1; 
	loader.load('radio/'+song_id+'.mp3', function ( audioBuffer ) {
		player.setBuffer( audioBuffer );
	});
	song_id++;
}
setInterval(function(){
	switch_track();
},5000);
````

> It seems that THREE.XHRLoader returns THREE.Cache ArrayBuffer and AudioLoader.decodeAudioData fails there.

**Comment by mrdoob** [comment]
I get this error:

> Uncaught InvalidStateError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': Cannot set buffer after it has been already been set

Which seems to be a limitation of the WebAudio API itself.

**Comment by mkungla** [comment]
@mrdoob your error comes from chrome I guess!? Does it switch all tracks first time and error occurs when `setInterval(function(){` goes for the next iteration of tracks, and does it switch without errors when you set `THREE.Cache.enabled = true;`?

**Comment by mkungla** [comment]
In `THREE.XHRLoader.load` you have 
````js
var cached = THREE.Cache.get( url );
if ( cached !== undefined ) {
    if ( onLoad ) {
        setTimeout( function () {
            onLoad( cached );
        }, 0 );
    }
    return cached;
}
````
Is there any scenario where `cached` would actually implement `AudioBuffer` and can be used within `THREE.AudioLoader.load`

**Comment by mrdoob** [comment]
> @mrdoob your error comes from chrome I guess!?

Yes.

>  Does it switch all tracks first time and error occurs when `setInterval(function(){` goes for the next iteration of tracks,

No. It already fails when trying to play 2.mp3

> and does it switch without errors when you set `THREE.Cache.enabled = true;`?

Neither `true` nor `false` made any difference.

**Comment by mkungla** [comment]
@mrdoob So in general seems indeed that this is not an a THREE issue, but limitation of  WebAudio API itself to update buffer after it has been already been set. It's up to you either close this issue or is there something to investigate further. So as I understand changing audio `src` on `THREE.PositionalAudio`, `THREE.AudioLoader` ... is not possible without having some custom bufferLoader *perhaps*?

**Comment by Mugen87** [comment]
I think `three.js` handles this quite well. It's rather a matter of how you use `Audio` and `PositionalAudio` in your application. It would be better if you create separate `Audio` entities for your three `mp3` files once and reuse them whenever it's necessary. For background music or lengthy ambient sound you should use an ordinary HTML5 audio element or maybe something like this #11115.
