### ISSUE TITLE
Disable lights based on object distance 

### ISSUE THREAD

**Issue by lazarmitic** [mrdoob/three.js#9325]
Hey guys, right now when rendering scene all data for each light is sent to GPU for each object we are rendering. If we are using shadows  number of available lights  is limited because we are limited with number of texture units GPU can support. 

What I was thinking is that when rendering each object, only enable lights (send data to GPU) that are in range of object we are currently rendering. 

I tried to do this myself inside WebGLRenderer.renderObjects() function by modifying WebGLRenderer.lights and WebGLRenderer._lights arrays, and it did work  for lights, but shadows were messed up. 

So if someone likes this idea and wants to help with implementation that would be awesome. @mrdoob what do you think about this? 

Yes this will introduce additional overhead when rendering because of distance testing when rendering each object, but we could have much more lights in scene overall.

**Comment by lazarmitic** [comment]
I managed to do it, I will do little more testing for bugs and performance, and report here :)

**Comment by mrdoob** [comment]
Depending on your scene it could be a bit intense as, currently, the shaders need to be recompiled when lights change.

**Comment by lazarmitic** [comment]
Will same thing happen if I use RawShaderMaterial and implement my own lightning?

**Comment by mrdoob** [comment]
If you use `RawShaderMaterial`, adding/removing lights from the scene shouldn't trigger shader re-compiling.
