### ISSUE TITLE
Setting WebGLRenderTarget.texture.needsUpdate results in error.

### ISSUE THREAD

**Issue by jkinman** [mrdoob/three.js#9327]
I'm setting a WebGLRenderTarget's texture's needsUpdate property to true. This results with the following error. 

`three.js?c9d6:31114 THREE.WebGLRenderer: Texture marked for update but image is undefined 
`
##### Three.js version
- [x] r78

##### Browser

- [x] Chrome

##### OS

- [x] osx

**Comment by mrdoob** [comment]
Could you provide a jsfiddle?

**Comment by jkinman** [comment]
http://codepen.io/anon/pen/mEqYoX

**Comment by WestLangley** [comment]
Why are you calling

    bufferTexture.texture.needsUpdate = true;

Is there an example you are following?

**Comment by WestLangley** [comment]
I think this can be closed.
