### ISSUE TITLE
In R76, something problem with vertex animation

### ISSUE THREAD

**Issue by df257** [mrdoob/three.js#9331]
In r72, there is no problem! But in r76 it report:
Uncaught TypeError: this.setFrameRange is not a function

**Comment by df257** [comment]
I solved it. I'm copy r72 method to r76. This method:
THREE.SEA3D.VertexAnimationMesh.prototype.play=function( name, offset ) {){.......}

**Comment by mrdoob** [comment]
Could you do a Pull Request with the fix?
