### ISSUE TITLE
MapQuest tiles not available

### ISSUE THREAD

**Issue by adgoncal** [mrdoob/three.js#9332]
##### Description of the problem 
MapQuest tiles are not showing because "As of July 11, 2016, direct tile access has been discontinued."

See http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

![image](https://cloud.githubusercontent.com/assets/10856791/16842212/9a11b59a-49aa-11e6-99fa-f726a66c3171.png)

You can check that on the New York Example https://cesiumjs.org/NewYork/index.html?view=-74.01881302800247%2C40.69114333714821%2C753.2406554180401%2C21.27879878293835%2C-21.343905508724674%2C0.0716951918898415

**Comment by mrdoob** [comment]
Hmm... wrong project?
