### ISSUE TITLE
cubeCamera.renderTarget not clearing when autoClear is set to true

### ISSUE THREAD

**Issue by funwithtriangles** [mrdoob/three.js#9333]
##### Description of the problem

I have two scenes which I am rendering separately and overlaying, so have `renderer.autoClear` set to `false`. I am `using renderer.clear()` inside the rendering loop, and all is well:

``` javascript
// This works fine!
renderer.clear();
renderer.render( bgScene, bgCamera )
renderer.clearDepth();
renderer.render( scene, camera );
```

However, I have now added a cubecamera to the scene, to make a reflective object. Unfortunately, having `renderer.autoClear` set to `false` is causing issues, where the texture of the reflective object isn't clearing when the surroundings change, causing that typical "painting" effect:

``` javascript
// Causes "painting" effect
cubeCamera.updateCubeMap( renderer, scene );
```

Here is a simplified fiddle that replicates the issue. I haven't included the two scenes, to keep things simple. This seems to be a bug to me as I can't see any way to get the cubeMap to clear. Apologies if I am mistaken.

https://jsfiddle.net/pqoz74rf/4/
##### Three.js version
- [x] Dev
- [x] r78
##### Browser
- [x] Chrome
- [x] Safari
- [x] Firefox
##### OS
- [x] OSX

**Comment by WestLangley** [comment]
```javascript
renderer.autoClear = true;
cubeCamera.updateCubeMap( renderer, scene );

renderer.render( bgScene, bgCamera )
renderer.autoClear = false;

renderer.clearDepth();
renderer.render( scene, camera );
```

**Comment by funwithtriangles** [comment]
Thanks @WestLangley, that has fixed my issue completely. 

Do you think there should be a way to manually clear the cubemap renderer instead of the solution you've given by turning flags on and off? I'm intrigued by what is actually going on here.

**Comment by WestLangley** [comment]
Oops. Sorry, I missed your question... Stepping through with a debugger should help you understand.
