### ISSUE TITLE
Changing the texture of a material makes the object flicker

### ISSUE THREAD

**Issue by oemmes** [mrdoob/three.js#9337]
##### Description of the problem

When changing the texture (map) of a material the object flickers even if the image has already been loaded before.

I think this is caused by the change in #8904 which _always_ creates a new blob and ObjectUrl for the image. You can also track this in the networks panel of Chrome dev tools.
The old code (simple `image.src = url;`) changed the texture/image without a delay.

See codepen: http://codepen.io/anon/pen/KrkXGJ
When I click one of the buttons multiple times I often see the cube becoming black before the texture is (re)applied.

Using r77 it is not the case: http://codepen.io/anon/pen/JKrAQR

In my real application the effect is more obvious as in the codepen example. And apparently in the codepen it's most obvious in Chrome.

Maybe there could be an option whether blobs (new code) or just the image/url (old code) should be used?
##### Three.js version
- [ ] Dev
- [x] r79
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them (probably)
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdumb** [comment]
> When changing the texture (map) of a material the object flickers even if the image has already been loaded before. 

That's because your method to change the texture is not the right one.
Use this method and you won't get any flickering:
http://necromanthus.com/Test/html5/sims_room.html

**Comment by oemmes** [comment]
@mrdumb: Thanks for your reply. So you actually preload every image as texture and then assign it later, right?

In my application the available textures are depending on the loaded objects and their configuration. There could be 50+ different textures to select and I only want to load the ones the user really wants to assign.

Previously there was a cache in the ImageLoader which was removed in the mentioned issue/commit.
So I think I would have to create a texture cache in my application to reuse any previously selected texture? Or is there another way that ThreeJS would use cached images/textures again?

**Comment by mrdumb** [comment]
> There could be 50+ different textures to select and I only want to load the ones the user really wants to assign.

These days most of the computers have 16-46 GB RAM and most of the graphic cards have 2-8 GB VRAM.
So preloading is the best approach by far.

**Comment by oemmes** [comment]
Sorry, but for me it's not suitable to preload all of the textures. Independent from the number of textures I cannot know beforehand which image file matches the configuration.

Example:
A furniture surface can have a number of different materials. For wood materials the texture/image file also depends on the graining direction (horizontal/vertical) - which doubles the texture count.
Actually which image is used for a specific configuration depends on a "lookup table" in our application.

And besides the (V)RAM amount one would transfer a lot of unnecessary (kilo/mega)bytes over the client's web connection if all images are preloaded.

**Comment by mrdumb** [comment]
> Sorry, but for me it's not suitable to preload all of the textures. 

All the 3D engines of the modern games do that.
Some time ago I've made a Sims like WebGL demo for a client.
256 Hi-Res (1024x1024) preloaded textures.
It runs perfect on a computer with 8GB RAM (with shared 1.5 VRAM !).
p.s.
Of course, if you want to follow another path you're free to do it.

**Comment by carstenschwede** [comment]
You should update the material after the texture has been loaded, e.g. use the `onLoad` callback of the `TextureLoader`.
