### ISSUE TITLE
Displacement maps aren't included in shadowing.

### ISSUE THREAD

**Issue by Sarah-C** [mrdoob/three.js#9342]
##### Description of the problem 
Displaced vertices and polygons don't self shadow, nor cast shadows on other objects.
An example is here:
http://codepen.io/SarahC/pen/AXbaBx

##### Three.js version
https://cdnjs.cloudflare.com/ajax/libs/three.js/r78/three.min.js

- [ ] Dev
- [x] r78
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
WebGL enabled PC.

**Comment by mrdumb** [comment]
A displacement map (or any kind of map) is not a piece of geometry.
So it cannot cast or receive shadows.

**Comment by Sarah-C** [comment]
But the map alters the vertices of the model - and those are what shadows
are calculated from.

This isn't the same as a flat bump map, is it.

**Comment by mrdumb** [comment]
> But the map alters the vertices of the model 

Not at all.
A displacement map generates fake details (fake 3D),  but that's all.
The geometry is the same (it cannot be modified by any map).

**Comment by WestLangley** [comment]
@Sarah-C 

See http://stackoverflow.com/questions/35873776/shadow-wont-update-when-geometry-is-changed-using-vertexshader

That answer should still work, but is a bit outdated. The following pattern will also work with r.76 or later:

```javascript
mesh.customDepthMaterial = new THREE.MeshDepthMaterial( {

	depthPacking: THREE.RGBADepthPacking,

	displacementMap: displacementMap,
	displacementScale: displacementScale,
	displacementBias: displacementBias

});
```

Try it in your codepen, and your vertex-shader-displaced vertices will cast proper shadows.

**Comment by mrdumb** [comment]
> http://stackoverflow.com/questions/35873776/shadow-wont-update-when-geometry-is-changed-using-vertexshader 

That's a solution for sub-pixel displacement (new generated geometry).
Many people use the "displacement map" term, but they don't understand it ...

**Comment by Sarah-C** [comment]
It makes fake details?

I had to increase the vertex count on my sphere to 200 to get it to work
though. When it was 20, the vertices weren't there to be moved by the
displacement map.

The geometry is the same though? How does the displacement map make the
silhouette change? I don't  understand.

**Comment by Sarah-C** [comment]
Could you help me? A couple of people think it works the same as I did.
Could you please explain what happens when the displacement map is applied
to a sphere for insrance?

I've got confused because of all the descriptions online for different
effects.

**Comment by Sarah-C** [comment]
I'll  try it in a bit. Thank you lots.

On 16 Jul 2016 14:22, "WestLangley" <notifications@github.com> wrote:
>
> @Sarah-C
>
> See
http://stackoverflow.com/questions/35873776/shadow-wont-update-when-geometry-is-changed-using-vertexshader
>
> That answer should still work, but is a bit outdated. The following
pattern will also work with r.76 or later:
>
> mesh.customDepthMaterial = new THREE.MeshDepthMaterial( { depthPacking:
THREE.RGBADepthPacking, displacementMap: displacementMap,
displacementScale: displacementScale, displacementBias: displacementBias });
>
> Try it in your codepen, and your vertex-shader-displaced vertices will
cast proper shadows.

**Comment by mrdumb** [comment]
> I had to increase the vertex count on my sphere to 200 to get it to work though.
> When it was 20, the vertices weren't there to be moved by the displacement map.

As I said before, any kind of texture mapping does NOT modify the geometry.
They generate fake details on the given geometry.
You're talking about something else: re-tessellation of geometry.
Your case is about sub-pixel displacement: based on an image, you re-tessellate the geometry into microtriangles.
The vertices of the new generated geometry get moved along normals and that's the displacement.
WestLangley's custom shader is a good idea.
I hope it's clear enough now.
cheers

**Comment by Sarah-C** [comment]
I get it now. Thanks for your explanation.
