### ISSUE TITLE
Change default PR target branch to "dev

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#9344]
##### Description of the problem 

There is a setting in Github to specify the default target branch for PRs.  ThreeJS has it defaulting to "master' but no one should be doing PRs to master.  Would simplify things if we made it "dev" instead.

To change this go to "settings" > "branches" and change the default PR branch.

##### Three.js version

- [ ] Dev
- [ ] r78
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Oh, I was not aware. This may have side-effects but we'll deal with them.
Changed! Thanks!
