### ISSUE TITLE
Skinned meshes are lit incorrectly.

### ISSUE THREAD

**Issue by manthrax** [mrdoob/three.js#9345]
##### Description of the problem 

Skinned meshes aren't showing transformed lighting.

When I rotate a skinned mesh, the reflected normals look correct, but the normals used in lighting the mesh, don't appear correct. The character will remain lit from one side only.

This has been bugging me for a while, but now I'm wondering if the problem is in my setup or in three.js.

I am presently working with animation from r73, but I've repro'd this in the dev branch.

Anyone noticed this behavior?

##### Three.js version

- [*] Dev
- [ ] r78
- [ *] r73

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Any way you could create a jsfiddle that shows the issue?

**Comment by manthrax** [comment]
I've now tried a couple different skinned meshes, and only some of them show the problem.
So now I'm thinking its something to do with the materials they are importing... I'll have to dig around more and figure it out. I'll close this for now.. thanks for response though. :D
