### ISSUE TITLE
Why some libraries assume that THREE is global? 

### ISSUE THREAD

**Issue by PolGuixe** [mrdoob/three.js#9350]
There are some libraries that assume THREE as a global variables such as the [TrackBall controller](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/TrackballControls.js). 

I don't think that it is considered a good practice, and is problematic when using a more modular approach. 

Is there some sort of guideline when writing components for THREE that states that THREE could be  assumed global?

**Comment by csulok** [comment]
three.js exposes itself as a global, and when you'd use a more modular approach - for instance browserify - you'll quickly run into [instanceof](https://github.com/mrdoob/three.js/issues/6362) issues. For now, you'd better use three as a global and keep an eye on issues/pull requests dealing with modularization.

**Comment by PolGuixe** [comment]
@csulok True... I have been trying to use Three in a modular approach. And I am already running into instanceof problems.... 😄
