### ISSUE TITLE
Rendering issue on Android tablet Webview

### ISSUE THREAD

**Issue by kusan-thana** [mrdoob/three.js#9354]
##### Description of the problem 

The rendering doesn't work on the Android Webview browser, getting these errors:

07-18 11:15:43.827 20707-20707/com.safran_engineering.safrandroid I/chromium: [INFO:CONSOLE(622)] "THREE.WebGLRenderer", source: file:///android_asset/three.min.js (622)
07-18 11:15:43.828 20707-20707/com.safran_engineering.safrandroid I/chromium: [INFO:CONSOLE(626)] "THREE.WebGLRenderer: Error creating WebGL context.", source: file:///android_asset/three.min.js (626

##### Three.js version

- [ ] Dev
- [x] r78
- [ ] ...

##### Browser

- [ ] Android Webview v33

##### OS

- [x] Android

##### User Agent

 UA : Mozilla/5.0 (Linux; Android 6.0; Android SDK built for x86 Build/MASTER; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Safari/537.36

**Comment by danrossi** [comment]
I have tested WebGL in a Cordova / ionic based app and it's ok. It uses Chromium.

**Comment by danrossi** [comment]
I can't re-confirm as it's now not launching on an emulator or phone for no reason. I had tested launching on an S7 and it was fine.  It is launching on IOS fine however. 

But a "pinned to home screen" page is a Chromium WebView and it's rendering WebGL. Probably even better than Chrome itself for my old S3 / Android 4.3. 

Try and see if you can update the underlying Chromium version for WebViews ?
