### ISSUE TITLE
shadowMap can't detect all instances on THREE.InstancedBufferGeometry

### ISSUE THREAD

**Issue by andrevenancio** [mrdoob/three.js#9360]
Since my question is lost in stackoverflow, I decided to post it here as a bug, as I think it is.

http://stackoverflow.com/questions/38342266/shadowmap-cant-detect-all-instances-on-three-instancedbuffergeometry

Basically the idea is having one bufferGeometry duplicated and having an attribute array with the offsets of my objects (like they have in the above example).

If I try to add shadows, I only get shadows on 1 object, which I assume is because we only have 1 geometry.

Is there a way of adding shadows to all my objects?

**Comment by WestLangley** [comment]
http://stackoverflow.com/questions/34205069/three-instancedbuffergeometry-and-shadows

**Comment by andrevenancio** [comment]
Thanks for the reply, I wish I had seen that before. Is this the same solution for fixing the SSAO shader you created? It doesn't take in consideration noise introduced via vertex shader. so, the AO always represent the original object without before the vertices got the offset. (via noise)

**Comment by WestLangley** [comment]
Yes. A custom depth material would be required.

**Comment by andrevenancio** [comment]
coolio. Cheers for the help! 👍
