### ISSUE TITLE
increase fog with time?

### ISSUE THREAD

**Issue by Djuelich** [mrdoob/three.js#9363]
is there a possibily to increase the fog density with the time? 

my thought was to make a calculated value by multiplying with clock.getElapsedTime()
The Idea is to simulate the filling of a room with smoke.

**Comment by mrdumb** [comment]
function animate() {
			requestAnimationFrame( animate);
			myfog += 0.000001;
			scene.fog = new THREE.FogExp2( 0xc0a070, 0.0004 + myfog ); 
			//

The values depend on your 3D world size and density speed.
