### ISSUE TITLE
multiple instances on same page?

### ISSUE THREAD

**Issue by v3nt** [mrdoob/three.js#9364]
##### Description of the problem 

I'm trying to get 2 small instances working on the same page but only the last one works. Is this possible?
(panorama / equirectangular)
http://abadev.jynk.net/project/test-pano-project/
http://abadev.jynk.net/wp-content/themes/aba-master/assets/js/vendor/three_custom.js

current code...

`
html / php.
<div id="pano_container<?=($id ? '_'.$id : '')?>" data-panoimage="<?=$panoimage[0]?>" class="pano_container" ></div>

js.
                $('.pano_container').each(function() {
                    var myid = $(this).attr('id');
                    var panoimage = $(this).data('panoimage');
                    init(myid, panoimage);
                    animate();
                });`

From the log i see 'THREE.WebGLRenderer – "76" '

##### Three.js version

- [ ] Dev
- [ ] r78
- [x] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

none.

**Comment by rhairston** [comment]
First: This is a question for stackoverflow
Second: Yes you can: http://threejs.org/examples/#webgl_multiple_renderers
