### ISSUE TITLE
Is Camera.copy() a supported method?

### ISSUE THREAD

**Issue by chpatrick** [mrdoob/three.js#9365]
[We're discussing](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10131) whether `Camera`'s `copy` method should be included in the TypeScript type definitions for three.js. The current definition is incorrect and breaks compilation on TypeScript 2.0, but if it's just an internal method I think we should remove it from the definitions altogether instead of changing it. Since it's not in the documentation it seems internal, but could you clarify?

**Comment by mrdoob** [comment]
`Camera` is an abstract object... One shouldn't use it directly...

**Comment by looeee** [comment]
Does that resolve this issue?
