### ISSUE TITLE
THREE.Mirror breaks in VR

### ISSUE THREAD

**Issue by davidlyons** [mrdoob/three.js#9367]
After adding VREffect and VRControls into the [ocean](http://threejs.org/examples/webgl_shaders_ocean.html) and [mirror](http://threejs.org/examples/webgl_mirror.html) examples, the mirror breaks when presenting to the vrDisplay.

[vr + 1 mirror](http://davidscottlyons.com/threejs/vr-mirror/1-mirror.html) - ground mirror breaks
[vr + 2 mirrors](http://davidscottlyons.com/threejs/vr-mirror/2-mirrors.html) - ground mirror works, vertical mirror breaks

screenshot from the 1 mirror link:
![vr-mirror](https://cloud.githubusercontent.com/assets/1305201/17005250/1c4394ba-4e8e-11e6-9028-a67457837402.png)

cc: @Slayvin @jbouny

Any ideas?
Thanks!

---

Three.js r79, [WebVR Chromium](https://webvr.info/get-chrome/), Windows, Vive

**Comment by mkeblx** [comment]
Yes, I was playing around with your samples. As both VREffect and Mirror use render targets suspected conflict between clearing. Not necessarily anything to fix, but trying `renderer.autoClear = false`, and also `renderer.clear()` in loop fixes immediate issue.
https://github.com/mkeblx/three.js/blob/mirror-fix-vr/examples/2-mirrors.html

Note that another issue present with mirrors haven't resolved yet, view is sometimes 'clipped' depending on camera orientation. Also, mirrors and 'mono', would have to add one per-eye to work in stereo.

**Comment by davidlyons** [comment]
Ahh awesome, thanks!

**Comment by mflux** [comment]
What's the correct way to get the resolution of the mirror?

    const groundMirror = new THREE.Mirror( renderer, camera, { clipBias: 0.003, textureWidth: renderSize.width, textureHeight: renderSize.height, color: 0x777777 } );

Doing this leaves streaks at the bottom as the aspect ratio will be incorrect.

**Comment by Slayvin** [comment]
There is no 'correct way', it's up to you to define the resolution.
Using renderSize.width
or renderSize.height is fine, but not necessarily a 'must-have' (I don't
know how non-power of two textures are handled with webgl).

Also, have you tried to decrease the clipBias value: it has to be as small
as possible, try 0.0001 ?

2016-09-12 3:39 GMT+02:00 Michael Chang <notifications@github.com>:

**Comment by mrdoob** [comment]
Can you guys check if... maybe #9695 fixed this?

**Comment by mkeblx** [comment]
Yep, that fixes.

**Comment by mflux** [comment]
It's fixed the rendering issue but technically mirrors still do not work properly (not stereo, smears at the bottom of the viewport, etc). Should we add a different issue or re-open this one?

**Comment by mrdoob** [comment]
New issue I think

**Comment by mkeblx** [comment]
Maybe two separate issues.. The smearing effect is unlikely to be VR specific and due to some (camera?) values being out of range of what mirror currently handles. For not rendering in stereo you are going to need to have a mirror for each eye and attach correct eye camera to each. Would be useful to have a webvr-mirror example demonstrating.
