### ISSUE TITLE
THREE.TextureLoader - Send 'withCredentials' to `XHRLoader `

### ISSUE THREAD

**Issue by karimbeyrouti** [mrdoob/three.js#9371]
##### Description of the problem

The loader updates now loads images using the `XHRLoader`, loads a `blob` calls `createObjectURL` and gets the image that way. Which is great as we can load different texture types.

However it is currently not possible to tell the texture loader to load the image `withCredentials=true` - and curry that to the `XHRLoader`. 

I just ended up monkey patching `THREE.XHRLoader` to fix this: 

```
      this._textureLoader = new THREE.TextureLoader(); // Texture loaded
      this._textureLoader.crossOrigin = 'use-credentials';
      var oldLoad = THREE.XHRLoader.prototype.load;
      var newLoad = function() {
        this.withCredentials = true;
        oldLoad.apply(this, arguments);
      };
      THREE.XHRLoader.prototype.load = newLoad;
      this._loadedTexture = this._textureLoader.load(image, ()=>this._onTextureLoaded());
```

Edit: I could also have done this:

`THREE.XHRLoader.prototype.withCredentials = true;`

Since the image is being loaded as a blob - it might be nicer to be able to do something like this: 

`this._textureLoader.withCredentials = true; // and pass that to the XHRLoader`

Edit: `setWithCredentials` is on the JSON loader - might be nice to have on the `TextureLoader` as that is working with the `XHRLoader`
##### Three.js version
- [ ] Dev
- [x] r78
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
> Edit: `setWithCredentials` is on the JSON loader - might be nice to have on the `TextureLoader` as that is working with the `XHRLoader`

That sounds good to me. Would you like to do a PR?

**Comment by karimbeyrouti** [comment]
Certainly ! A little short of time for the next couple weeks, but will try to.

**Comment by karimbeyrouti** [comment]
Our little one is having a lie in today. Here is the PR: https://github.com/mrdoob/three.js/pull/9391
