### ISSUE TITLE
Extrude geometry bevel is sinusoidal not elliptical.

### ISSUE THREAD

**Issue by flagstone78** [mrdoob/three.js#9372]
##### Description of the problem 

I needed the bevel to be eliptical to look nice for my project. I looked through the source code for the extrude geometry and noticed that of the two parameters, bs and z, z steps linearly while bs is a sine function. 

So I changed: `z = bevelThickness * ( 1 - t );`
to: `z = bevelThickness * Math.cos( t * Math.PI / 2 );`
And that made it work like I expected. (And looks way better)

Is there a reason that it's sinusoidal? I think the default should be eliptical.

##### Three.js version

- [x] Dev
- [x] r78
- [x] r72
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by bhouston** [comment]
Why not make this an option and PR it? :)

**Comment by zz85** [comment]
Hmm, interesting I've never given thought to this. Do you have an example or screenshots of what the difference would look with the different easing functions?

**Comment by flagstone78** [comment]
@bhouston This is actually only my second time even interacting with github so I am in no way familiar with the process of making a pull request.

@zz85 Here are some screen shots:
![sinusoidal](https://cloud.githubusercontent.com/assets/6675762/17112247/e3dfc0ea-526a-11e6-8619-e8ffbf2828fb.png)
![sinusoidal box](https://cloud.githubusercontent.com/assets/6675762/17112248/e3e5d28c-526a-11e6-96e0-0b936a6bf154.png)

As you can see it makes a very noticeable square outline at the end where it doesn't smoothly align.

![eliptical bevel](https://cloud.githubusercontent.com/assets/6675762/17112249/e3e82dca-526a-11e6-89ed-207acb7b7b58.png)
![beveled box](https://cloud.githubusercontent.com/assets/6675762/17112246/e3dc57e8-526a-11e6-9360-74ebee7cbef8.png)

Where as the new function makes it look nicely rounded.

**Comment by zz85** [comment]
Thanks @flagstone78 for illustrating it nicely. From the looks of it I think it should be a function of cos function, and I guess should have give more attention to the details when I wrote that 😜

For making a Pull Request, you could either fork the repository to push your git commits, or use the [online github editor to make a change](https://github.com/mrdoob/three.js/edit/dev/src/extras/geometries/ExtrudeGeometry.js).

Let me know if you would like to try that, otherwise I could help with a patch for this :)

**Comment by WestLangley** [comment]
@flagstone78 [This wiki article](https://github.com/mrdoob/three.js/wiki/A-Contributor%27s-Guide-to-the-Git-Galaxy) may also help. Don't worry if you mess up, we will help you. : - )

**Comment by flagstone78** [comment]
@zz85 I used the online editor and referenced it above.
