### ISSUE TITLE
Maybe a bug of r79 for safari ReferenceError: Can't find variable: URL

### ISSUE THREAD

**Issue by guzuomuse** [mrdoob/three.js#9374]
##### Description of the problem 
I'v tested in some browsers such as firefox chrome IEx and some others,verything is ok but Safari bowser---version 5.1.7 for windows;

The Error Message in console is : ReferenceError: Can't find variable: URL, 

i use three.min.js about at line 389; there is "URL"

thank u.
##### Three.js version

- [ ] Dev
- [x] r79

##### Browser

- [ ] All of them
- [x] Safari

##### OS

- [ ] All of them
- [x] Windows(7)

**Comment by mrdoob** [comment]
Can you share a link that shows that error?

**Comment by sirxemic** [comment]
Well, Safari doesn't support the URL interface before version 6. Version 5.1.7 is 4 years old.

**Comment by guzuomuse** [comment]
All right, here we use , the lasted version for win7 is 5.1.7, i'll rollback r75, thank u

**Comment by mrdoob** [comment]
Ah, I guess this is the commit to blame?
https://github.com/mrdoob/three.js/commit/a2a8589afc12b5cabb33bca18e1c20daaaef2b32
