### ISSUE TITLE
IE10: Object doesn't support property or method 'overrideMimeType

### ISSUE THREAD

**Issue by DustinJSilk** [mrdoob/three.js#9376]
##### Description of the problem 

Line 18389 is throwing the following error:
Object doesn't support property or method 'overrideMimeType'

This is when using the TextureLoader class like so:

new THREE.TextureLoader().load('...')

##### Three.js version
- [X] r79

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [X] Internet Explorer (10)

##### OS

- [ ] All of them
- [X] Windows (Virtual machine from a mac)
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
`XMLHttpRequest` doesn't have `overrideMimeType()` on IE10?

**Comment by DustinJSilk** [comment]
Exactly. Its only available in IE11 and later
https://msdn.microsoft.com/en-us/library/dn448456(v=vs.85).aspx

**Comment by DustinJSilk** [comment]
I replaced that line with this:

```javascript
if (request.overrideMimeType) {
    request.overrideMimeType( 'text/plain' );
}
```

Which now gets it working in all browsers (So long as i use the canvas renderer if there is no webgl renderer of course)
