### ISSUE TITLE
BufferGeometry.toJSON does not write attribute data when geometry.parameters exists

### ISSUE THREAD

**Issue by SteveOW** [mrdoob/three.js#9377]
[BufferGeometry.toJSON()](https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L880) does NOT write BufferGeometry.attribute arrays to output when geometry.parameters EXISTS.  This is because if geometry.parameters does exist then the code writes parameter info to data then returns without writing the attribute arrays.

Whereas, if  geometry.parameters does NOT exist then the attribute arrays are written.

Apologies if this logic is deliberate but the logic of it is not apparent to me.  

In my particular use case the geometry attributes have been modified after creation of the BufferGeometry so the geometry.parameters alone do not provide sufficient information to reconstruct the geometry.

I have raised a [question on StackOverflow](http://stackoverflow.com/questions/38510714/three-js-buffergeometry-tojson-why-are-the-attribute-data-not-exported) but no explanation as yet.  I have drilled down to find the responsible code - which looks illogical.
##### Three.js version
- [ ] Dev
- [ ] r78
- [ x] r79
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by borodaev** [comment]
+1

**Comment by Mugen87** [comment]
All standard geometries in `three.js` (`BoxGeometry`, `SphereGeometry`, `CylinderGeometry` etc.) are procedurally generated from a given set of parameters. When `three.js` serializes these entities, it's more lightweight to save only the parameters and not the entire geometry data (vertices, normals, uvs and maybe indices).

If you use one of the standard geometries and still want to serialize the geometry data, you can delete the `parameters` property or you copy to attribute data to a new instance of `BufferGeometry`.
