### ISSUE TITLE
gl.getProgramInfoLog warning in ubuntu chrome

### ISSUE THREAD

**Issue by chrisj** [mrdoob/three.js#9383]
##### Description of the problem 

Only seen so far in Ubuntu Chrome. I saw it in r76 and tried r79. This line is firing https://github.com/mrdoob/three.js/blob/f65e669af99feb518e31756d793a9688a2578fbd/src/renderers/webgl/WebGLProgram.js#L541

programLog is a string of length 1. The only character is ASCII 0, null char.

I am curious about this issue because we are also getting a weird "crash" on the same ubuntu/chrome combo where all the rendering disappears except for the gray background color. It also causes the dev tools to disconnect.

##### Three.js version

- [ ] Dev
- [x] r79
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome 51
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

**Comment by ZaWertun** [comment]
Diplicate of #9317.
