### ISSUE TITLE
THREEJSExporter "How much of it is undoable?"

### ISSUE THREAD

**Issue by johnhu84** [mrdoob/three.js#9390]
##### Description of the problem

I notice a lot of the 3D effects are not actually exported using the THREEJSExporter, does anyone know if this is work that remains to be done, and if so, how much of it remains to be done, or if this is work that is undoable?

Thanks,
-Chunlin
john.chunlin@gmail.com
##### Three.js version
- [ ] Dev
- [ ] r79
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
What 3D effects are you referring to?

**Comment by johnhu84** [comment]
1. Exporting vertex colors, 2. Use vertex normals, 3. Export Bitmaptexture materials 4. Export lighting and gloss effects.  
I just want to know if any/all of these are completely undoable with maxscript, and/if doable in another language like C++ or Python, can I get some helpful opinions on these (this is all for exporting to a JSON format)?

**Comment by mrdoob** [comment]
Ah, I see. I was not aware you were talking about the 3dsmax exporter.

**Comment by johnhu84** [comment]
Yes, the 3dsmax THREEJSExporter doesn't seem to export all the 3D information from 3D max, so I'm trying to figure out how I can make it more complete.  Can you help, please?

**Comment by bhouston** [comment]
I would instead focus on the FBX converter.  Then it will work for 3DS Max, Maya, etc.  The application specific exporters are really hard to maintain.

**Comment by johnhu84** [comment]
the FBX converter already says animation is impossible to do, I really need a lot of stuff, including animation.  Can somebody just give me some really good advice on how to improve the ThreeJSExporter?  Thanks!

**Comment by johnhu84** [comment]
I'm getting the following error when I'm trying to convert the xsi_man_skinning.fbx from the three.js example:
AttributeError: 'FbxGeometryConverter' object has no attribute 'TriangulateInPlace'
Does this look familiar?  I'm using Python 3.3 with the FBX SDK.

the command I ran from my command prompt is this: 
C:\Apache24\htdocs\three.js\utils\converters\fbx>convert_to_threejs.py C:\Apache24\htdocs\three.js\examples\models\fbx\xsi_man.fbx xsi_man_skinning.js
