### ISSUE TITLE
Specific OBJ file can not be displayed correctly in r76 or later.

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#9392]
##### Description of the problem 

I was not able to display the Gophe 3D model in the obj file. 

![image](https://cloud.githubusercontent.com/assets/1833979/17077620/db534510-5110-11e6-8bb8-5c839035c7e7.png)
-> OK : three.js(r73) + MTLLoader.js + OBJMTLLoader.js (http://jsdo.it/cx20/OQ5X)

![image](https://cloud.githubusercontent.com/assets/1833979/17077622/ec0e59c6-5110-11e6-8d0e-ebda5c51b688.png)
-> NG : three.js(r76) + MTLLoader.js + OBJLoader.js (http://jsdo.it/cx20/cblg)

![image](https://cloud.githubusercontent.com/assets/1833979/17077624/fa7030de-5110-11e6-807e-02b73a4871be.png)
-> NG : three.js(r79) + MTLLoader.js + OBJLoader.js (http://jsdo.it/cx20/gxsj)

Gopher 3D model has reduced the number of vertices in the following procedure.

1. open a gopher.blend file in Blender 2.72.  (see: https://github.com/golang-samples/gopher-3d)
2. reduce the number of vertices of the model.
3. export to a gopher.obj file

##### Three.js version

- [x] Dev
- [x] r79
- [x] r78
- [x] r77
- [x] r76

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] Microsoft Edge

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

Windows 10 + ThinkPad X201(Intel HD Graphics)

**Comment by mrdumb** [comment]
That OBJ file was not properly exported (from Blender).
Here is the fixed version (with 3DS Max) and open with THREE r79:
http://necromanthus.com/Test/html5/gopher.html

**Comment by cx20** [comment]
Is this the OBJ file exporter problem? (from Blender)

![image](https://cloud.githubusercontent.com/assets/1833979/17078481/35ef0f18-512f-11e6-94b5-14bf03368f83.png)
-> OK three.js(r79) + MTLLoader.js + OBJLoader.js (using modifed obj file) (http://jsdo.it/cx20/erfU)

I was modifying the file as below, it is now successfully display.

gopher.obj (before)
```
l 7472 7351
l 7351 7473
l 7774 7707
l 7707 7775
```

gopher_modified.obj (after)
```
# l 7472 7351
# l 7351 7473
# l 7774 7707
# l 7707 7775
```
