### ISSUE TITLE
AnimationAction and scoping

### ISSUE THREAD

**Issue by sirxemic** [mrdoob/three.js#9395]
Since we're using modules now, do you think it's possible to get rid of the `AnimationMixer._Action = AnimationAction._new` construction? By simply importing AnimationAction as-is and not export it in Three.js, the issue of it having to be private should be solved automatically, right?

Furthermore, I see in files like WebGLShader.js, WebGLProgram.js and WebGLUniforms.js the usage of IIFEs to scope variables. I presume that is being done to restrict the visibility of variables and function. It should be fine to get rid of IIFEs here and there also, right? Because we're using modules?

**Comment by mrdoob** [comment]
> Since we're using modules now, do you think it's possible to get rid of the `AnimationMixer._Action = AnimationAction._new` construction? By simply importing AnimationAction as-is and not export it in Three.js, the issue of it having to be private should be solved automatically, right?

/ping @tschw 

> Furthermore, I see in files like WebGLShader.js, WebGLProgram.js and WebGLUniforms.js the usage of IIFEs to scope variables. I presume that is being done to restrict the visibility of variables and function. It should be fine to get rid of IIFEs here and there also, right? Because we're using modules?

Yep! That sounds good to me!

**Comment by tschw** [comment]
Yes, all makes sense to me too.
