### ISSUE TITLE
THREE.Math is now _Math, probably need a better name that doesn't conflict with built-in Math.

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#9399]
##### Description of the problem

We should probably figure out a new name for this class as without the THREE namespace, it conflicts with the built in JavaScript Math class.

See here:

https://github.com/mrdoob/three.js/blob/dev/src/math/Math.js
##### Three.js version
- [x] Dev
- [ ] r79
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by fraguada** [comment]
Probably not a great idea, but why not use the British 'Maths'?

**Comment by GGAlanSmithee** [comment]
Here are som synonyms of math from google:

* arithmetic
* calculus
* ciphering
* computation
* figures
* figuring
* calculation
* mathematics
* number crunching
* numbers
* reckoning

Not very helpful though I guess...

Maybe we could have a few, more specific, classes and call them `Math2D`/`Math3D` etc.

**Comment by bhouston** [comment]
How about MathUtils?  (I've used that name before in similar situations.)

**Comment by msimpson** [comment]
@fraguada Not just British, but correct as well: "Math(ematic)s."

**Comment by tentone** [comment]
Usually i would call this MathUtils (i actually do call it MathUtils in my IDKwGL library).

**Comment by andrevenancio** [comment]
Just bump into this right now. I wish we could go back in time...
