### ISSUE TITLE
Can't set the drawMode of a mesh in an json-model

### ISSUE THREAD

**Issue by padjon** [mrdoob/three.js#9408]
##### Description of the problem

Can't set the drawMode of a mesh in an json-model
##### Three.js version
- [ ] Dev
- [x] r79
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Could you create a jsfiddle showing the issue?

**Comment by padjon** [comment]
Maybe i explained wrong. Im writing an JSON model generator to convert from JT to JSON and then read this model with the JSON loader in three.js.

The problem is, that three.js does not support to set drawMode of a mesh in the json model.

From the three.js wiki (https://github.com/mrdoob/three.js/wiki/JSON-Object-Scene-format-4); **bold inserted by me**
[...]
            {
                "uuid": "33FA38D9-0AAC-4657-9BBE-5E5780DDFB2F",
                "name": "Box 1",
                "type": "Mesh",
                "geometry": "C3BF1E70-0BE7-4E6D-B184-C9F1E84A3423",
                "material": "87D95D6C-6BB4-4B8F-8166-A3A6945BA5E3",
                "matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
                **"drawMode": 1**
            },

**Comment by mrdoob** [comment]
Ah, I guess `ObjectLoader` doesn't support `Mesh.drawMode` yet. Maybe we should not implement it actually, as we're considering moving it to the geometry instead... #9980

**Comment by Mugen87** [comment]
Solved via #15646
