### ISSUE TITLE
How to modify the interpupillary distance of StereoEffect?

### ISSUE THREAD

**Issue by df257** [mrdoob/three.js#9418]
Who can tell me?

**Comment by mkeblx** [comment]
That property is not exposed by the `StereoCamera` that `StereoEffect` uses: https://github.com/mrdoob/three.js/blob/dev/src/cameras/StereoCamera.js#L52
You could make a copy of both and use those, and modify the `eyeSep`. But you should be able to put your whole scene in a Group and scale it to achieve the same effect.
