### ISSUE TITLE
IOS Ipad 3 Performance Problems Dropping Frames

### ISSUE THREAD

**Issue by danrossi** [mrdoob/three.js#9421]
Hi there. I'm not sure if any performance tweaks can be done to the WebGL on IOS. 

There is a very old webkit bug ticket here which may be related and has gone stale. 

https://bugs.webkit.org/show_bug.cgi?id=135387

However I've had nothing but trouble getting it to not drop so many frames on the Ipad 3 / IOS 9. 

Android is much worse and random on the S3. Most of the time all features will work including orientation. Then suddenly it will force it to become unresponsive on Firefox and drop frames. Chrome still doesn't even render, randomly Chrome Dev may but it also suffers frame dropping issues and audio cuts out. 

Normal video playback is fine. As in the same high res video will playback without dropping. The actual WebGL rendering will cause audio to cut out now and then so affecting the system on IOS. 

For some reason with mp4 files I need to force an update with 

```
texture.needsUpdate = true
```

I'm not sure if that affects anything. 

I've made a simple demo here. It needs to use a cors proxy work around which I have done.  

http://dev.electroteque.org/threejs/

Most of the settings there is what I'm using. I don't resize to the window area only in fullscreen mode. The dimension numbers is replicating the player dimensions. 

If there is anything that could be done that might be doable.

**Comment by danrossi** [comment]
I've added a stats monitor to it. 

It says 5 FPS. 

I could try and reduce the video size and see if that helps ? 

This animation example from the stats example gives me 14 FPS compared to 60 FPS. 

http://dev.electroteque.org/webgl/examples/basic.html

**Comment by mrdoob** [comment]
I'm getting a `ERR_CONNECTION_TIMED_OUT` when trying to download the mp4.

![screen shot 2016-08-16 at 13 16 18](https://cloud.githubusercontent.com/assets/97088/17714249/d416679a-63b3-11e6-8812-e3a4487d6ad5.png)

**Comment by danrossi** [comment]
@mrdoob  I had my local proxy source configured. I also had to add it to the http nginx configuration as I made changes recently. 

It should be working now hopefully. 

http://dev.electroteque.org/threejs/

**Comment by mrdoob** [comment]
![screen shot 2016-08-17 at 11 57 23](https://cloud.githubusercontent.com/assets/97088/17749275/d11eb894-6471-11e6-8ad3-392c256efed9.png)

As you can see, `WebGLRenderer` takes less than 1ms per frame so not much that can be done there.

I've noticed you have already disabled `generateMipmaps` in the texture so... maybe try using `THREE.NearestFilter` for `minFilter` and `magFilter`?

**Comment by mrdoob** [comment]
Also, your video is `1280 × 640`. Try resizing it (locally) to `1024 x 512`.

**Comment by danrossi** [comment]
@mrdoob I've updated with the suggestions. The video is now 420p. It's still under 10fps for me. 

Perhaps its a bug and will work better with newer Ipad devices than the Ipad 3. So similar performance issues I have on older Android devices.

**Comment by mrdoob** [comment]
I see... Unfortunately, this is an issue you should report to Apple instead.

**Comment by danrossi** [comment]
Is your frame rate ok on your device then ? 

If its a webkit problem there is already a ticket and it will never happen. Apple wouldn't care either if I make a bug report like they haven't bothered with the CORS issue. 

So basically IOS is no good whatsoever.

**Comment by mrdoob** [comment]
> Is your frame rate ok on your device then ?

I'm getting 60fps on a Nexus 5x. I'll try on the iPad tomorrow.

**Comment by danrossi** [comment]
Yes as far as Android goes newer devices should be fine. S7 I have tested and even smoother than my 2011 macbook pro. I have tested in GearVr and apart from FOV issues and some wierd black border frame rate is ok. I need to get proper access to both for further testing.    Older ones like my S3 need a smaller resolution to prevent actual video dropping frames. Worse when combined with the new OmniTone feature.  Chrome still won't render in it. I know Chromium people only test with Nexus devices. 

This is just an IOS problem. It is probably not much you can do no worries but good for people to know.  

I will try and make a bug report but I've had nothing but trouble with Apple they seem very anti-developer to me.

**Comment by mrdoob** [comment]
30fps on a iPad Air MD785LL/A here...

**Comment by danrossi** [comment]
OK no worries sorry about the noise. So Ipad 3 works but not the best.  

This kind of rendering requires newer mobile and tablet models due to better graphics of course.
