### ISSUE TITLE
What's the difference between  THREE.animationHandler and three.AnimationMixer

### ISSUE THREAD

**Issue by asforever** [mrdoob/three.js#9426]
##### Description of the problem 

What's the difference between  THREE.animationHandler and THREE.AnimationMixer,Which should I use THREE.animationHandler and THREE.AnimationMixer,I really don't know which is better to use

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by titansoftime** [comment]
``THREE.AnimationHandler`` was deprecated as of r73. It offers some very nice improvements over the old system however there are some lingering bugs (#9056) and is devoid of documentation.
