### ISSUE TITLE
I made some changes width StereoEffect, so it can set eyeSep

### ISSUE THREAD

**Issue by df257** [mrdoob/three.js#9427]
StereoEffect.js add this function:
`this.setEyeSep=function(eyeSep){
		_stereo.eyeSep = eyeSep;
	};`

THREE.StereoCamera add this attribute:
`this.eyeSep = 0.064;`

Change update function:
`var eyeSep = 0.064 / 2;` 
to
`var eyeSep = this.eyeSep / 2;`

**Comment by mkeblx** [comment]
Okay I did as quick but you could have done do a pull request with those changes. Note that if doing anything VR related better to use VREffect, etc.
