### ISSUE TITLE
Lensflares not rendering in both views when using StereoEffect

### ISSUE THREAD

**Issue by Topograph** [mrdoob/three.js#9428]
#When using StereoEffect, lensflares will only be visible in the left camera

js fiddle of lensflare demo with stereo effect: [http://jsfiddle.net/2geuzy3q/](http://jsfiddle.net/2geuzy3q/)
##### Three.js version

- [x] r79
- [ ] Dev
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Updated jsfiddle with fixed `https` issues: http://jsfiddle.net/2geuzy3q/1/

**Comment by mrdoob** [comment]
Damn it, I fixed this last Christmas already...

**Comment by mrdoob** [comment]
Maybe this broke in the last refactoring @Mugen87?

**Comment by Mugen87** [comment]
Indeed, there was a bug when calculating the valid area for the lensflares. But the problem also existed before i've done the `Box2` refactoring. Anyway as you can see [here](http://jsfiddle.net/2geuzy3q/2/) lensflares are working now 👍

**Comment by mrdoob** [comment]
Yay!
