### ISSUE TITLE
assets models compress/decompress support

### ISSUE THREAD

**Issue by raymondwang13** [mrdoob/three.js#9429]
##### Description of the problem 

(This is NOT a help site. Please read the guidelines above before posting.)

##### Three.js version

- [ ] Dev
- [ ] r79
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by raymondwang13** [comment]
i can decompress or compress my models

**Comment by HasanAyan** [comment]
You can use external libraries for that. I don't think this should be implemented in THREE.js

**Comment by bhouston** [comment]
Myself and @spidersharma03 are working on adding this to ThreeJS.  Hopefully we'll have a PR in the near future.

**Comment by pailhead** [comment]
any more explanation on what this is?

**Comment by bhouston** [comment]
@spidersharma03 and I are trying to create a little library of reusable encoders/decoders for mesh data - quantization for position, normal, quaternions, also reordering/delta transforms, and then compression.  This is combined with a binary container format, which can be used with compression or not. @spidersharma03 is leading the development.  Our work is being created in a three.js fork so we can contribute it back.

A general high level design is here: https://docs.google.com/document/d/14NpSeDtBQHWGlqwXfs25J4d2WKTPYbudxrW6C6-rBkA/edit

**Comment by bhouston** [comment]
@pailhead we are developing this for our http://threekit.com product marketing toolset, which ties in with https://clara.io as a content management back-end.  While these are commercial products we generally contribute back the core algorithms to ThreeJS as we have been doing for a couple years.

**Comment by pailhead** [comment]
Are there more design outlines such as the one you posted above :)

**Comment by valette** [comment]
Interesting. As a side note, I think that the introduction of WebAssembly will (very positively) change this landscape!

**Comment by raymondwang13** [comment]
Ok, roger that.
