### ISSUE TITLE
sound issue with chrome 

### ISSUE THREAD

**Issue by Djuelich** [mrdoob/three.js#9444]
In my Project, i play a background-sound and a footstep-sound added to the camera
```

function createSound(filename, distance, rolloff, loop, volume, complete) {
    var sound = new THREE.PositionalAudio(audioListener);
    audioLoader.load('sounds/' + filename + '.mp3', function(buffer) {
        sound.setBuffer(buffer);
        sound.setRefDistance(distance);
        sound.setRolloffFactor(rolloff);
        sound.setLoop(loop);
        sound.setVolume(volume);
        if(complete){
         complete();
        }
    });
    return sound;
}




function createBasicSounds() {
    footsteps = createSound("footsteps", 10, 1, true, 1);
    atmosphere = createSound("atmosphere", 10, 0.1, true, 0.5, function(){
        atmosphere.play();
    });
    camera.add(footsteps);
    camera.add(atmosphere);
```

In Firefox the sounds are well played in Stereo. But when i test it on chrome, it is only on the right channel. My .mp3 are in stereo, so this can't be the problem. 

r79
Chrome
Linux

**Comment by Djuelich** [comment]
it seems to be a problem with the camera. when the sounds aren't set to the camera it is played in stereo.

**Comment by manthrax** [comment]
If you can post a fiddle, I can check it out in Chrome. Are you doing anything special to your camera that may not be updating matrices?

**Comment by Djuelich** [comment]
we solved it now with a workaround. we just made a solution with static-sounds and positional-sounds.
it now works in a way we can life with.
