### ISSUE TITLE
renderOrder is not respected when transparency is used

### ISSUE THREAD

**Issue by incinirate** [mrdoob/three.js#9447]
##### Description of the problem 
JSFiddle: https://jsfiddle.net/ov2yz786/3/
In the example, the blue cube should always render above the red cube, and it normally does, however as soon as transparency is introduced onto the red cube, the renderOrder is ignored and the red cube renders over the blue cube.

##### Three.js version

- [x] Dev
- [x] r80

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

Was only able to test on Chrome and Firefox as I don't have windows

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

Only tested on Linux

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by WestLangley** [comment]
You toggled off depth testing. Toggle it on.

**Comment by incinirate** [comment]
I meant when depth testing is off this occurs, the blue cube should _always_ be drawn on top of the red cube, this is the behavior when transparency is not used because it _should_ render after the red cube and because depth testing is turned off, it shouldn't partially hide itself or blend with the transparent cube.

**Comment by WestLangley** [comment]
Transparent objects are rendered _after_ opaque objects in three.js; `renderOrder` appiles separately to transparent and opaque.

Your demo appears to be working correctly.
