### ISSUE TITLE
ShapeGeometry:  Adding lineTo manually closing a shape, this line gets ignore

### ISSUE THREAD

**Issue by openhardwarecoza** [mrdoob/three.js#9450]
##### Description of the problem 

If I draw a rectangle (rectangle used for the simplied example, but holds true for any 2D geometry I tried.  I always ignores the last segment) with 

```
    svgShape = new THREE.Shape();
    svgShape.moveTo(0.97780502,-1.9777799999999388);
    svgShape.lineTo(0.97780502,-1.9777799999999388);
    svgShape.lineTo(198.02219502,-1.9777799999999388);
    svgShape.lineTo(198.02219502,-99.02216799999997);
    svgShape.lineTo(0.9778050200000052,-99.02216799999997);
    svgShape.lineTo(0.97780502,-1.9777799999999388);  // looking at the rendered result, this line gets ignored? 
    var svgMaterial = new THREE.MeshBasicMaterial( { color: 0x0000ff } )
    svgGeom = new THREE.ShapeGeometry( svgShape );
    var object = new THREE.Line( svgGeom, svgMaterial ) ;
    scene.add(object);
```

The result has a missing side:

![rect](https://cloud.githubusercontent.com/assets/7695323/17322261/fa82d98a-589c-11e6-84a4-73e06dbdcb25.PNG)

##### Three.js version

Tested and happens with every version I tried
- [x] 80dev
- [x] r79
- [x] r76

##### Browser

I only tested Chrome, but quite sure the others have same issue

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Replicated issue in JSFidde:

Replicated here:  https://jsfiddle.net/peter6960/e7tbg5fp/7/

**Comment by openhardwarecoza** [comment]
Related to https://github.com/openhardwarecoza/LaserWeb3/issues/56#issuecomment-236812071

**Comment by openhardwarecoza** [comment]
Additional note:

Using shape.autoclose DOES close the shape, but I do not think I need to rely on that, since our geometry is dynamically drawn, and some shapes will need to be closed, so wont,  its easier to handle drawing the closing segment manually in the upstream code (just follow the SVG path)

**Comment by mrdumb** [comment]
svgShape.moveTo(1,-2);
    svgShape.lineTo(0.97780502,-1.9777799999999388);
    svgShape.lineTo(198.02219502,-1.9777799999999388);
    svgShape.lineTo(198.02219502,-99.02216799999997);
    svgShape.lineTo(0.9778050200000052,-99.02216799999997);
    svgShape.lineTo(0.97780502,-1.9777799999999388); 

It works just fine.

**Comment by mrdumb** [comment]
> Replicated here: https://jsfiddle.net/peter6960/e7tbg5fp/7/ 

    svgShape.moveTo(0.97780502,-1.9777799999999388);
    svgShape.lineTo(0.97780502,-1.9777799999999388); 

That "LINE" does not make any sense.

**Comment by openhardwarecoza** [comment]
The 'move to' exists because some svgs we import has multiple entities,  so
we move to to match the position of that entity in relation to the rest of
the objects.

Agreed on the first line to,  that can be removed.  But removing it doesnt
add the missing last segment.

**Comment by openhardwarecoza** [comment]
Now, I still dont understand WHY it fails with the move to.
Removing the move to is not an option (See result of import in my app, without the move to:

![without move](https://cloud.githubusercontent.com/assets/7695323/17330212/3cdad49e-58c6-11e6-835c-b32357df16df.PNG)

I do admit its 99.999% sure I am doing something wrong, I guess my question is - should I not be using move to (if not, how do I get a "not drawing a line" move to the start of the first path I want to draw?
or,  is it the format in which I create the geometry?  

I can use another method - the moveto/lineto came from the threejs examples

**Comment by mrdumb** [comment]
> Now, I still dont understand WHY it fails with the move to.

It doesn't fail.
Please read again (carefully) my first posted message.
The first line must be a VALID one!

**Comment by WestLangley** [comment]
@openhardwarecoza You are not using three.js correctly.

Copy the coding patterns in http://threejs.org/examples/webgl_geometry_shapes.html.

`ShapeGeometry` is a geometry appropriate for triangular meshes -- not lines.

    // mesh
    var svgMaterial = new THREE.MeshBasicMaterial( { color: 0x0000ff } );
    svgGeom = new THREE.ShapeGeometry( svgShape );
    var object = new THREE.Mesh( svgGeom, svgMaterial ) ;

    // line
    svgShape.autoClose = true;
    var points = svgShape.createPointsGeometry();
    var object = new THREE.Line( points, new THREE.LineBasicMaterial( { color: 0x0000ff } ) );

http://jsfiddle.net/e7tbg5fp/8/

**Comment by openhardwarecoza** [comment]
Aha, thanks Westlangley! More explained reply - much appreciated! (Adding a little theory helps a lot more in teaching)  .  I have been battling the ShapeGeometry thing for a few days now!

So, taking your advice, triggered my thinking that of course, I only need lines! So.... Much better:

https://jsfiddle.net/peter6960/e7tbg5fp/10/

```
var svgGeom = new THREE.Geometry();
svgGeom.vertices.push( new THREE.Vector3( 0.97780502,-1.9777799999999388, 0 ) );
svgGeom.vertices.push( new THREE.Vector3( 198.02219502,-1.9777799999999388, 0 ) );
svgGeom.vertices.push( new THREE.Vector3( 198.02219502,-99.02216799999997, 0 ) );
svgGeom.vertices.push( new THREE.Vector3( 0.9778050200000052,-99.02216799999997, 0 ) );
svgGeom.vertices.push( new THREE.Vector3( 0.97780502,-1.9777799999999388, 0 ) );
var svgMaterial = new THREE.MeshBasicMaterial( { color: 0x0000ff } )
var object = new THREE.Line( svgGeom, svgMaterial ) ;
scene.add(object);
```

Works perfectly now!

**Comment by WestLangley** [comment]
@openhardwarecoza  Please use `LineBasicMaterial` for lines.

**Comment by openhardwarecoza** [comment]
Yeah, sorry, normally I would SO, but this looked like a bug based on what i thought lineto was supposed to do. (; I did ask MrDoob first in issue on my project (;  Wont Happen Again

**Comment by WestLangley** [comment]
@openhardwarecoza I saw that. No problem. : - )
