### ISSUE TITLE
THREE.Texture.toJSON error when called on a material's envMap set to a cube map

### ISSUE THREAD

**Issue by DodekaHydra** [mrdoob/three.js#9458]
I'm using THREE.js in a large application along with React and Redux. I have an object in the scene that has `mesh.material.envMap` set to a cube map, loaded through `THREE.CubeTextureLoader`.

Redux has a Chrome extension containing advanced dev tool features. Upon opening this extension, the following error appears:

`Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'.`

I'm not certain what causes this error to appear, but since the dev tools open in a separate panel alongside the main application, it could be something to do with loss of focus.

The stack trace pointed me to the `getDataURL` function within `THREE.Texture.toJSON`, where the six images of the cube map are attempting to be stored:

```
if ( meta.images[ image.uuid ] === undefined ) {

        meta.images[ image.uuid ] = {
            uuid: image.uuid,
            url: getDataURL( image )
        };

}
```

This fails because `image` in this case is actually an array of 6 images, thus getDataURL is useless.

I was able to fix this with the following hack. Since I'm not sure what's precisely calling it, or what the actual side effects of such a fix are, I'm hesitant to submit it as a pull request. That said, I no longer see any errors with this fix in place.

```
if ( meta.images[ image.uuid ] === undefined ) {

    if (image instanceof Array && image.length > 0) {

        meta.images[ image.uuid ] = {
            uuid: image.uuid,
            url: image.map( (val) => { getDataURL(val) } )
        };

    } else {

        meta.images[ image.uuid ] = {
            uuid: image.uuid,
            url: getDataURL( image )
        };

    }

}
```

I have only tested this on r79 running Chrome on Windows 10, but I did also come across [this StackOverflow post](http://stackoverflow.com/questions/38733369/how-can-i-save-material-with-a-envmap-property), where I also submitted my fix.
##### Three.js version
- [x] r79
##### Browser
- [x] Chrome
##### OS
- [x] Windows

**Comment by pedrorochaorg** [comment]
I'm facing the same issue, but when i try to load the exported model, it tries to load an image named ',,,,' so this hack may no be the right solution for this issue. If anyone has a fix for this please share it. :)

**Comment by Mugen87** [comment]
Test file for reproduction: https://jsfiddle.net/f2Lommf5/6659/
