### ISSUE TITLE
Blender exporter: transparency is ignored

### ISSUE THREAD

**Issue by maxkostin** [mrdoob/three.js#9461]
Transparency is not preserved when exporting from blender using THREE.js exporter.
Should be trivial to translate to "opacity": 0.8.

**Comment by yomotsu** [comment]
Could you tell me more about the issue?

When I published a model with `Alpha` with Blender Exporter, I got `opacity` in the JSON.

<img width="653" alt="screen shot 2016-08-18 at 4 15 22 am" src="https://cloud.githubusercontent.com/assets/212837/17749915/c33d99dc-64fa-11e6-891b-b7d91f277e40.png">

<img width="342" alt="screen shot 2016-08-18 at 4 14 15 am" src="https://cloud.githubusercontent.com/assets/212837/17749919/c6e35e32-64fa-11e6-9ffd-153da1204a21.png">

**Comment by maxkostin** [comment]
Hi, 
The exporter preserves transparency when you do not include Scene. Otherwise, I get this output:

`"materials":[{
        "blending":"NormalBlending",
        "shininess":50,
        "depthWrite":true,
        "depthTest":true,
        "color":10724259,
        "type":"MeshPhongMaterial",
        "transparent":true,
        "name":"mat-1",
        "vertexColors":0,
        "specular":8355711,
        "uuid":"E0AFD637-BB9D-374A-BEF2-D73C77EF7873",
        "emissive":0
    }],`

Settings:
<img width="217" alt="screen shot 2016-08-18 at 09 37 31" src="https://cloud.githubusercontent.com/assets/917536/17767466/00713ebc-6528-11e6-9fe4-1325c5a0ee63.png">

Scene:
<img width="295" alt="screen shot 2016-08-18 at 09 37 48" src="https://cloud.githubusercontent.com/assets/917536/17767487/121c79ce-6528-11e6-9d09-a65d4cdac1e8.png">

**Comment by MichaelHazani** [comment]
Hi,

I haven't been able to replicate this problem on a Macbook Pro, using the most recent exporter and Blender 2.78.
Whether Scene is included or not, and without any textures options, I get opacity data on the output.

The only way I was able to avoid exporting opacity is by unchecking "Face Materials" under Shading. Can you double check that in your export settings, Face Materials is checked?
![scr](https://cloud.githubusercontent.com/assets/10997806/20121218/128151cc-a5c5-11e6-80b4-a91e75385874.png)

If the problem persists, can you specify your exact setup, three.js version, OS, etc?

**Comment by ErikEklund** [comment]
I have this issue as well. Materials with transparency lack the "opacity" property in the exported json. I have selected the "Face materials", "Scene" and "Materials" checkbox in the exporter, using the latest exporter from the dev branch. Blender 2.78, OS X 10.11.6.

![screen shot 2016-12-19 at 20 54 27](https://cloud.githubusercontent.com/assets/1064329/21327024/674feadc-c62d-11e6-9271-37039642c7eb.png)

![screen shot 2016-12-19 at 20 55 25](https://cloud.githubusercontent.com/assets/1064329/21327046/882f581e-c62d-11e6-85a8-070ca0f8cff0.png)

Output json:
`
{
        "transparent":true,
        "specular":0,
        "shininess":11,
        "vertexColors":0,
        "emissive":0,
        "type":"MeshPhongMaterial",
        "color":13421772,
        "blending":"NormalBlending",
        "depthTest":true,
        "depthWrite":true,
        "uuid":"9509502C-E266-31C1-8173-C846C138FC54",
        "name":"03 - Default"
    }
`

Expected result is to get an `"opacity": 0.22` property.
