### ISSUE TITLE
ThreeJS's Examples - View Source button not working correctly

### ISSUE THREAD

**Issue by espnicholas** [mrdoob/three.js#9462]
##### Description of the problem 

Under ThreeJS's example page, when clicking into a example then clicking the button on the bottom right "View Source". The expected behavior in Chrome/Safari/IE is not executed and opens a blank white page. 

In Safari shows the following message:

There is no application set to open the URL view source:http://threejs.org/examples/webgl_camera.html.

Chrome and Internet Explorer 10/11 displays blank pages. about:blank is in the address bar.

The only browser that seems to work is Firefox.

##### Three.js version

- [ ] Dev
- [x] r79
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by espnicholas** [comment]
Just to follow up, I will make a pull request for the fix in a bit.

**Comment by espnicholas** [comment]
Following up on this, seems to be a browser security feature? When in chrome and the blank page shows up, the console outputs this:

http://threejs.org/examples/:301 Not allowed to load local resource: view-source:http://threejs.org/examples/webgl_animation_scene.html

**Comment by espnicholas** [comment]
Updated main issue as it actually doesn't work in firefox but is actually being caught by the conditional fallback to Github. But does not work on another other browser.

**Comment by Mugen87** [comment]
I think we can close this issue because this commit b932ba1a1bec6710e5200ddec3b3d7b427db9efa finally drops the support for the `view-source` protocol.
