### ISSUE TITLE
Build scripts failing on dev

### ISSUE THREAD

**Issue by PWhiddy** [mrdoob/three.js#9471]
When trying to build current threejs dev version with build.bat on windows or build.sh on linux, build fails and many of these pop up

ERROR - this language feature is only supported in es6 mode: modules. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
import { _Math } from '../../math/Math';
^

It's possible this is a mistake on my part, but two different machines built the master (r79) just fine, while throwing these errors on dev

**Comment by satori99** [comment]
I received that error on dev when using build.bat on the dev version.

This is because the build system has changed significantly.

The solution is to now build the Three library using `npm run build` and `npm run build-min` commands

**Comment by PWhiddy** [comment]
Hey thanks for the info!

**Comment by PWhiddy** [comment]
I still seem to be getting errors with `npm run build` and `npm run build-min`

> three.js>npm run build
> 
> three@0.79.0 build C:\Users\allco\Documents\threejs remix\three.js
> rollup -c
> 
> 'rollup' is not recognized as an internal or external command,
> operable program or batch file.
> 
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
> npm ERR! node v6.3.1
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! three@0.79.0 build: `rollup -c`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the three@0.79.0 build script 'rollup -c'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the three package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     rollup -c

With a fresh install of node and npm

**Comment by satori99** [comment]
run `npm install` first

    > npm install
    > npm run build

I should've mentioned that before

**Comment by PWhiddy** [comment]
Ah, I ran npm install before, but not in the root directory.
Thanks!
