### ISSUE TITLE
I don't get exactly the same Obj file after exporting

### ISSUE THREAD

**Issue by Brucewayne01** [mrdoob/three.js#9473]
##### Description of the problem

I'm trying to exporting to obj files, even when I import an obj file , I don't get exactly the same file. The file size is greater , here is an example :

[emerald.obj](https://github.com/mrdoob/three.js/files/407369/emerald.txt)

The exported file :

[emerald 2.obj](https://github.com/mrdoob/three.js/files/407370/emerald.2.txt)
##### Three.js version
- [x ] r79
##### Browser
- [x] All of them
##### OS
- [x] Windows
##### Hardware Requirements (graphics card, VR Device, ...)

Nvidia GeForce GTX 960M

**Comment by mrdoob** [comment]
I'm guessing you're talking about loading the obj into the editor and then exporting it...?

Unfortunately we can't match the data structure that obj uses internally so we have to convert it at load time. That's why the exported file is different.

**Comment by donmccurdy** [comment]
If the exported OBJ file is incorrect in some way please reopen the issue, but as mrdoob mentions above we don't retain the original OBJ file at runtime, so exports may have structural differences from the original file.
