### ISSUE TITLE
Create THREE.deg alias for THREE.Math.degToRad

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [mrdoob/three.js#9477]
Create:
```javascript
THREE.deg = function (deg) {
  return THREE.Math.degToRad(deg)
}
```

cuz this:
```javascript
geometry.rotateZ( THREE.deg( 90 ) ) 
```
looks better than this:

```javascript
geometry.rotateZ( THREE.Math.degToRad( 90 ) ) 
```

This is a very commonly used function, and will not be superfluous to create an alias to it. In addition, there is no reason not to do so, since THREE.deg property does not occupied.

**Comment by Wilt** [comment]
Wasn't this topic already here: https://github.com/mrdoob/three.js/issues/9475
And wasn't it closed?
