### ISSUE TITLE
Octree 

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#9483]
I also posted this issue on the GitHub repository for the original `threeoctree` from Collin Hover: https://github.com/collinhover/threeoctree/issues/13

But I thought it would be good to also mention this issue here.

##### Description of the problem 
When hovering with the mouse on (some of the) boxes in front of the statue the statue is highlighted. This is caused by the fact that the intersects array that is returned by the `intersectOctreeObjects` method is not ordering the results. This behavior is different from normal raycasting where the objects are ordered (closest object is first in the array).

Is this intentional?
Or can the code be updated to return objects in an ordered array?

**Comment by collinhover** [comment]
Discussing here: https://github.com/collinhover/threeoctree/issues/13

**Comment by Wilt** [comment]
My PR with a fix has been merged by collinhover. 
@mrdoob Maybe you can update the `THREE.Octree` in the three.js repository too?

**Comment by collinhover** [comment]
Briefly tested fixes made by @Wilt after updating his test case to use the latest Octree code and all appears to be working as expected.
