### ISSUE TITLE
Implement error handling in glTF loader

### ISSUE THREAD

**Issue by stevenvergenz** [mrdoob/three.js#9486]
##### Description of the problem

Using the glTF loader as written in the example, if the request to fetch the glTF file returns 404 or otherwise fails, the callback is not fired, and there is currently no way to detect that failure. The call to `THREE.glTFLoader.load()` should accept an additional callback to be called on XHR or Parser errors like the other loaders do.
##### Three.js version
- [x] Dev
- [ ] r79
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by donmccurdy** [comment]
The latest THREE.GLTFLoader now supports an `onError` callback:

```
gltfLoader.load ( url, onLoad, onProgress, onError );
```
