### ISSUE TITLE
multiple texture load can not track load thread id, so can not confirm texture

### ISSUE THREAD

**Issue by gogofight** [mrdoob/three.js#9488]
##### Description of the problem

because load thread is asynchronous and you can not know which texture will be loaded, so you can not confirm what texture is when thread callback ! i think it is a serious problem ...
who can tell me how to track or monitor load thread id ?
maybe addEventListener helpful ?

the code as follow:
i just want to push texture from textureUrlArr  to array textureObjArr orderly.

var textureUrlArr = new Array();
textureUrlArr[0] = 'http://127.0.0.1/xxx/4k/i0000_4k.jpg';
textureUrlArr[1] = 'http://127.0.0.1/xxx/4k/i0001_4k.jpg';

var textureObjArr = new Array();

for(var i = 0; i < textureUrlArr.length; i++) {
    textureLoader.load(
        textureUrlArr[i],
        function (texture) {
            textureObjArr.push(texture);
        },
        function (xhr) {
        },
        function (xhr) {
        }
    );
}
##### Three.js version
- [x] Master
- [x] r79
  ##### Browser
- [x] Chrome
  ##### OS
- [x] Windows

**Comment by simplePig** [comment]
`var textureUrlArr = new Array();
textureUrlArr[0] = 'http://127.0.0.1/xxx/4k/i0000_4k.jpg';
textureUrlArr[1] = 'http://127.0.0.1/xxx/4k/i0001_4k.jpg';

var textureObjArr = new Array();

for(var i = 0; i < textureUrlArr.length; i++) {
textureLoader.load(
textureUrlArr[i],
function (texture) {
textureObjArr.push(texture);
},
function (xhr) {
},
function (xhr) {
}
);
}`

**Comment by yomboprime** [comment]
You can load the textures progresively, loading the next texture in the callback of the previous one. 
That way you keep the order.

**Comment by simplePig** [comment]
3Q @yomboprime
