### ISSUE TITLE
r80 incorrectly handles "exports" as global

### ISSUE THREAD

**Issue by killroy42** [mrdoob/three.js#9489]
##### Description of the problem 

r80 tries to detect a module environment and passes "exports" as global into the factory class. But below that, there is additional code that accesses "THREE" in the global scope, not on exports. So if the environment has module/exports functions and objects, THREE will fail to load, EVEN if there is a THREE empty object in the global scope, since the factory will not write to the global scope, but to exports instead.

This worked fine in r79, which consistently operated in the same scope.

It appears this is a half-way transition to supporting modularization.

My use case is a module loader that "impersonates" exports/module and captures values written there and makes them available via "require".

Current workaround: Load THREE before initializing my module system.

##### Three.js version

- [x ] r80dev
##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by killroy42** [comment]
Looks like r80 now correctly bundles everything in the same closure, but other modules (such as /examples/../*controls) still expect a global (rather than a const THREE = require('THREE'), for example). I guess the plan is to move everything over to some kind of module format compatibility?

**Comment by GGAlanSmithee** [comment]
@killroy42 here is a related discussion regarding modularization of examples: #9562
