### ISSUE TITLE
Create THREE.DEG constant

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [mrdoob/three.js#9491]
```javascript
THREE.DEG = Math.PI / 180
```

Example:

```javascript
geometry.rotateY( 90 * THREE.DEG );
```
looks better and shorter than:
```javascript
geometry.rotateY( 90 * THREE.Math.DEG2RAD );
```

And looks semantically correct: "geometry rotate by Y to ninety degrees"
vs: "geometry rotate by Y to math ninety degrees to radians"

There is no any particular reason to pack this constant in Math module, If it is so often used.
And it will not cause confusion, but rather the opposite.

People will not ask the question "is the math, why is it not in THREE.Math ???" because we will not remove THREE.Math.DEG2RAD.

compare yourself:
===

![image](https://cloud.githubusercontent.com/assets/19378179/17639240/f5f8698e-60f8-11e6-9443-11172e189518.png)

**Comment by msimpson** [comment]
@uMaxmaxmaximus 
```javascript
geometry.rotateY( Math.PI / 2 );
```

Even more beautiful, shorter, and currently supported.

**Comment by mrdoob** [comment]
`THREE.D` is even shorter!

**Comment by mrdoob** [comment]
Jokes aside...

> There is no any particular reason to pack this constant in Math module, If it is so often used.

That's kind of a fair point.

**Comment by uMaxmaxmaximus** [comment]
@mrdoob I understand structured, everything on the shelves, and all in this spirit, but that the ultimate goal is the convenience of programmers. Did the imposition of the constants in the global object, will make a mess in the library? Of course not. 

jQuery would not become popular if the named his methods "setCssStyle" instead of "css". About API beauty, too, need to think about. If it is not to the detriment of what else. In this case it is not a detriment of what else.

**Comment by dmtaub** [comment]
I'm glad somebody else understands the value of using shorter names for APIs--as long as it's not too ambiguous. The first time I encountered THREE.Math.DEG2RAD, I tried to invoke it as a function :)

**Comment by mrdoob** [comment]
`THREE.DEG2RAD` is, maybe, more intuitive than `THREE.DEG`?

**Comment by yomotsu** [comment]
FYI: Unity has `Deg2Rad`, under the Mathf namespace.
https://docs.unity3d.com/ScriptReference/Mathf.Deg2Rad.html

**Comment by msimpson** [comment]
I blame the Babylonians ...

**Comment by uMaxmaxmaximus** [comment]
@mrdoob 
`THREE.DEG` It comprises a constant number of radians in a degree that may be obvious?

People are not fools, people will remember it perfectly. People really are not stupid, jQuery has proven that people are easier to remember short names than long.

**Comment by uMaxmaxmaximus** [comment]
@mrdoob 

compare yourself:
===

![image](https://cloud.githubusercontent.com/assets/19378179/17639240/f5f8698e-60f8-11e6-9443-11172e189518.png)

**Comment by dmtaub** [comment]
I'm not sure if you're joking or not, but THREE.D gives nearly no
indication of what it's for, and it might be impossible to search for. DEG
on the other hand, is a clearer abbreviation for degrees, and I suspect it
would be easier to search for as well

**Comment by uMaxmaxmaximus** [comment]
@mrdoob It's even shorter!

This name does not convey the essence of the content =)

**Comment by yomotsu** [comment]
- UE has [`FMath::DegreesToRadians`](https://docs.unrealengine.com/latest/INT/API/Runtime/Core/Math/FMath/DegreesToRadians/index.html)
- Unity has [`Mathf.Deg2Rad`](https://docs.unity3d.com/ScriptReference/Mathf.Deg2Rad.html)
- Away3d has [`away3d.core.math.DEGREES_TO_RADIANS`](http://away3d.com/livedocs/away3d/4.0/index.html?away3d/core/math/MathConsts.html&away3d/core/math/class-list.html)
- PlayCanvas has 
[`DEG_TO_RAD`](http://developer.playcanvas.com/en/api/pc.math.html#DEG_TO_RAD)

But no `DEG`, as far I know. We should follow the 3D programing way. three.js has `Math.DEG2RAD`.

Even you can make aliases in your code tho...

**Comment by uMaxmaxmaximus** [comment]
@yomotsu I'd better write my framework.
As a Angular2, but for 3D. 
After all, to describe 3D scenes best way to declarative than imperative. Mesha will be given through a virtual html, and their appearance through a virtual css.

**Comment by GGAlanSmithee** [comment]
@uMaxmaxmaximus You might be interested in [react-three](https://github.com/Izzimach/react-three) if you are OK with using React.. I guess you can't use CSS but it's more declarative.

**Comment by Wilt** [comment]
You opened three threads about your degree stuff:

https://github.com/mrdoob/three.js/issues/9475
https://github.com/mrdoob/three.js/issues/9477
and now this one...

You're pretty stubborn aren't you; you must be happy that you finally got the discussion going... :smile:

**Comment by uMaxmaxmaximus** [comment]
@Wilt you must be happy that people are trying to improve your library, in spite of your opposition. :smile:

**Comment by uMaxmaxmaximus** [comment]
i can cteate npm module `three-aliases`

index.js
```javascript
THREE.DEG = THREE.Math.DEG2RAD
```

needs? =)

**Comment by Wilt** [comment]
Nope :innocent:

**Comment by uMaxmaxmaximus** [comment]
i will pay!
![image](https://cloud.githubusercontent.com/assets/19378179/17675425/6a76fb78-6332-11e6-9434-055cc1e15d41.png)

**Comment by mrdoob** [comment]
> @yomotsu I'd better write my own framework.
===

Maybe you should do that.
