### ISSUE TITLE
Make Sphere be Topologically Closed

### ISSUE THREAD

**Issue by cwgreene** [mrdoob/three.js#9496]
##### Description of the problem 

SphereGeometry returns a mesh which is not closed at the poles or on the sides. If theta is Pi, then the resulting sphere should be a closed sphere, and if phi is 2*Pi, then the sides should be stitched together as well.

##### Three.js version

- [x] Dev
- [x] r79
- [x] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
For `SphereGeometry`, UVs are not continuous on the seams, hence vertices must be duplicated. So we can't do what you propose.

Add a texture to your sphere to see what happens. Or look at the changes to http://threejs.org/examples/misc_uv_tests.html.

**Comment by cwgreene** [comment]
Well that explains it then. Is there anyway to decouple the underlying mesh geometry from the skinning?

**Comment by mkeblx** [comment]
Sure but not as standard/robustly as duplicating. You're not saving that many verts by doing. But, at poles though UVs are the same so could still share common vertex at pole. Also there is ability to remove some colinear triangles at poles.

Also have to consider somewhat what custom vertex shaders might want to do which might want those verts there.

**Comment by cwgreene** [comment]
This isn't about saving vertices, I'm using the generated mesh for adjacency information. I take it I should just create a separate geometry for this use case?

**Comment by mkeblx** [comment]
Gotcha. Actually that use case might work without really having to add anything, as `Geometry` has a [mergeVertices](https://github.com/mrdoob/three.js/blob/dev/src/core/Geometry.js#L801) function that should eliminate shared vertices as a secondary step.

You could try something like this:
```js
var sphere = new THREE.SphereGeometry(1);
sphere.mergeVertices();
```

**Comment by cwgreene** [comment]
Ah cool; thanks, I'll give that a shot. Looks like this is definitely a 'working as designed'. :)
