### ISSUE TITLE
r80dev and Firefox console errors

### ISSUE THREAD

**Issue by ghost** [mrdoob/three.js#9499]
It seems everything works as expected so far, but with Firefox (the latest versions) I get this console error all the time:

```
THREE.WebGLProgram: gl.getProgramInfoLog() C:\fakepath(501,7): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll
C:\fakepath(510,7): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll
```

With r79 everything was fine.

**Comment by GGAlanSmithee** [comment]
I have also seen this occasionally, working in the editor, but have been unable to reliably reproduce it.

**Comment by satori99** [comment]
I think its related to how many lights per type you apply to lit shaders. ie: if you only have a single DirectionalLight, the shader warns you that you are using a loop that only executes once to apply the lighting properties.

You can re-produce it in the r80 editor by only having a single light of each type.

Its just a warning and can safely be ignored.

**Comment by mrdumb** [comment]
> Its just a warning and can safely be ignored.  

To ignore a warning message is never something good.
And that's not a solution anyway ...

**Comment by satori99** [comment]
It needs no solution because it makes no functional difference to anything.

Like I said, it's just the shader compiler telling you that you just compiled a shader containing a loop with only one iteration and that it was unrolled.

**Comment by GGAlanSmithee** [comment]
Isn't it kind of weird that it gives a warning for this BTW? I though loop unrolling was a common compiler optimization?

**Comment by mrdumb** [comment]
> It needs no solution because it makes no functional difference to anything.

Something was ok in r79 and is broken in r80.
You don't have to be a guru to figure out that.

**Comment by satori99** [comment]
see here https://github.com/mrdoob/three.js/issues/4834#issuecomment-122009074

**Comment by mrdumb** [comment]
> see here #4834 (comment) 

I didn't get that warning in r71 ... r79
In r80 the console is bloated with warnings like that.
There are no new features in r80, just "clean up".
There is something WRONG implemented in r80.

**Comment by mrdumb** [comment]
"Before 66 we were not showing gpu warnings in the console."

You also didn't show these warning in r71 ... r79.
In r80 I get the console bloated with warnings like that, making difficult to trace the real problems.
Is this a wise move ???

**Comment by mrdoob** [comment]
I can't reproduce...?

![screen shot 2016-08-13 at 11 37 15](https://cloud.githubusercontent.com/assets/97088/17644914/5a87af6c-614a-11e6-8a43-0c878674c05d.png)

**Comment by satori99** [comment]
I see it firefox whit only one light of any type added.

![cap](https://cloud.githubusercontent.com/assets/1762580/17646248/1a023fb4-6205-11e6-882f-75fa86d12cb4.PNG)

**Comment by Mugen87** [comment]
@satori99 What happens when enable native OpenGL in your Firefox? On this way your are using real OpenGL draw calls and not ANGLE.

see [How to use OpenGL or ANGLE rendering on Windows](https://github.com/mrdoob/three.js/wiki/)

**Comment by mybmgithub** [comment]
I'm seeing this warning on the latest Firefox and Chrome on 07/16/17. Throw my vote in to allow suppressing it, or merge a fix in. Thanks.

**Comment by mrdoob** [comment]
@mybmgithub can you share a screenshot?

**Comment by mybmgithub** [comment]
Here you go. 
![warning_shows_screen_shot_aframe](https://user-images.githubusercontent.com/27980060/28293330-9219d19e-6b21-11e7-9eba-af6b19e4c284.png)

**Comment by mrdoob** [comment]
@mybmgithub I'm not sure your console log is related to what this issue is about...

**Comment by mybmgithub** [comment]
Okay. It would be nice to suppress if it's not a show-stopper issue, and it's not something I can fix from within my own code. Thanks for the follow-up.

**Comment by Mugen87** [comment]
If this is still an issue for someone, ask the respective browser developers for a fix.

see https://github.com/mrdoob/three.js/issues/4834#issuecomment-122041257
