### ISSUE TITLE
setPixelRatio scales the viewport on iPad

### ISSUE THREAD

**Issue by GianlucaGuarini** [mrdoob/three.js#9500]
##### Description of the problem 
In my app I change the frameratio in runtime in order to avoid slow performances on slow devices. My code looks like this:
```js
if (this.fps.frame % this.fps.framerate === 0) {
   // set the framerate in runtime each second
   this.renderer.setPixelRatio(
      (window.devicePixelRatio || 1) * Math.max(this.fps.framerate / 60, 0.2)
   );
}
```

This code works beautifully on all browsers on desktop however on iPads the viewport gets somehow scaled even if the canvas stays of the same size. Side note: this problem does not appear using the CanvasRenderer.

##### Three.js version
- [x] r74 up to r79

##### Browser

- [x] Safari
- [x] FIrefox

##### OS

- [x] iPad (iOS 9.3)

##### Screenshot
The console logs the pixelRatio calculated
![acvebn4p7n](https://cloud.githubusercontent.com/assets/879612/17618387/c8678eec-607f-11e6-8000-9932269101b5.gif)

**Comment by GianlucaGuarini** [comment]
I made a quick demo to demonstrate the issue https://jsfiddle.net/gianlucaguarini/9y57bgpf/

**Comment by GianlucaGuarini** [comment]
It seems this problem does not exists in the old versions, the problem seems to be added since v74

**Comment by GianlucaGuarini** [comment]
@mrdoob should I make a pull request to solve this issue or do you know already where could be the problem? I have spent ~2 hours on it and I could not figure out what's wrong.

**Comment by mrdoob** [comment]
> This problem does not exist in the old threejs versions, it appears in threejs v74 and in all the version above

Lies!

https://jsfiddle.net/9y57bgpf/9/ (r73)
https://jsfiddle.net/9y57bgpf/7/ (r79)

Seems like this is an issue in iOS for Mobile... No matter what you set in `canvas.style.width` and `canvas.style.height` the element is always rendered with the `canvas.width` and `canvas.height` dimensions.

**Comment by GianlucaGuarini** [comment]
@mrdoob thanks for taking a bit of time for checking this issue

> Lies!

😸 @mrdoob Ah of course in my demos using the old threejs I didn't use the `setSize` that it's automatically called in via `setPixelRatio` in the newest releases so that's why the problem didn't occur, thanks for checking.

> Seems like this is an issue in iOS for Mobile... No matter what you set in canvas.style.width and canvas.style.height the element is always rendered with the canvas.width and canvas.height dimensions.

Lies! :trollface: 

This does not explain why the problem does not appear if I use the `CanvasRenderer` 
https://jsfiddle.net/gianlucaguarini/9y57bgpf/10/

**Comment by mrdoob** [comment]
> This does not explain why the problem does not appear if I use the `CanvasRenderer` 
https://jsfiddle.net/gianlucaguarini/9y57bgpf/10/

Well, it kind of does... `CanvasRenderer` is a different type of context (`2d` instead of `webgl`). So it shows that it's a Safari issue specifically when dealing with the `webgl` context.

**Comment by GianlucaGuarini** [comment]
😞 It seems really a `webgl` context issue on iOS devices.. now I have tried on Babylon.js and the problem is there as well https://jsfiddle.net/gianlucaguarini/nzexh6a6/1/

I have found this https://bugs.webkit.org/show_bug.cgi?id=152556

**Comment by GianlucaGuarini** [comment]
I will close this issue since it's not threejs specific hoping they will solve the problem soon thanks for your help @mrdoob

**Comment by mrdoob** [comment]
@GianlucaGuarini 

https://twitter.com/grorgwork/status/766353297921839104

**Comment by michaelitvin** [comment]
Is there any workaround for this?

**Comment by mrdoob** [comment]
Nope...

**Comment by GianlucaGuarini** [comment]
@michaelitvin If you landed here probably you are dealing with low performances and if it could help I ended up avoiding to use an extremely hi-res canvas on retina mobile/tablet devices (of course setting its size only at boot depending on the screen.width value). And removing the shadow has speed up my performance about ~5x (I was using ShadowMaterial for the ground)

**Comment by michaelitvin** [comment]
I already did what I knew - no shadows, ~30k vertices with 4 light sources. TrackballControlls still laggy on mobile devices, even when I reduce the resolution significantly. That makes me suspect this might be related to UI dispatch lag and not render.

**Comment by mrdoob** [comment]
> I already did what I knew - no shadows, ~30k vertices with 4 light sources.

4 light sources is a lot of light sources.

**Comment by michaelitvin** [comment]
What made a significant speedup (probably obvious to you guys) - rendering was done inside requestAnimationFrame. I only update the logic there now, and I let the TrackBallControls object to decide when to render.
