### ISSUE TITLE
Issue with MeshStandardMaterial

### ISSUE THREAD

**Issue by dirtybluejeans** [mrdoob/three.js#9501]
##### Description of the problem

While using MeshStandardMaterial on IOS, very strange behaviour is seen at low roughness values. At roughness = 0, the "specular" lit up area appears are a black blob. If a bumpmap is also applied, the blob just spreads. I've tried this with several versions of three (going back to r75), with the same result. On Android (at least on one device that I tested on), a value of zero for roughness is ignored, and other values - even though they result in specular spots - don't present very good results (broken/jagged lighting patterns).
##### Three.js version
- [x] r79
  upto
- [x] r75
##### Browser
- Safari on iOS
- Chrome on Android (to some extent)
  ##### OS

These screenshots shows comparisons between ios and desktop behaviour on various roughness values. I've tried this with both shadows switched on and off, and different levels of ambient and directional lighting, all with the same results. Unfortunately, the application I'm building is quite bulky with lots of external dependencies so I can't provide code, but if these screenshots don't help then I'll try to create some kind of pastebin. 

EDIT: Removed the earlier images because I've been able to replicate with much simpler set. 
<img width="397" alt="screen shot 2016-08-14 at 8 18 43 pm" src="https://cloud.githubusercontent.com/assets/326630/17649874/82d57aea-625c-11e6-86e5-11d9a7875c09.png">

Hopefully someone will be able to figure out by looking at the patterns themselves what might be wrong (or maybe it's a known issue? I couldn't find something on these lines).

Thanks.

**Comment by WestLangley** [comment]
> I'll try to create some kind of pastebin.

Please do. Thanks.

**Comment by mrdoob** [comment]
It'd be also be good to know what specific device you're getting that with.

**Comment by bhouston** [comment]
I am using a modern Three.js version and I am not seeing this with bumps / roughness - thus I think it is some combination of things...

**Comment by dirtybluejeans** [comment]
@mrdoob this is on an iphone 6s. 
@WestLangley, Will make a sample bit of code and put up today.
@bhouston, I first saw this when I was playing with the version where you have implemented mapSlots. I initially thought it's because of that, but then I've seen that in the regular builds as well.

**Comment by dirtybluejeans** [comment]
Hi,

I've been able to replicate the issue in a very basic 'cube' sample, and have also been able to isolate the settings that cause it (though I don't know why it happens or how to fix it). The culprit is renderer precision: setting it to 'lowp' on iOS shows the behaviour as above. I'm also looking for a place where I can put this snippet, so you'll be able to see easily.

Thanks

**Comment by dirtybluejeans** [comment]
...and here's the pen: http://codepen.io/dirtybluejeans/pen/PzVQkG
There's a green rotating cube, you'll see the black specular spot going past soon enough. 
If I change lowp to highp, the problem doesn't happen.

**Comment by bhouston** [comment]
I did raise precision to high on all devices in my fork of three.js to get
rid of these issues.

Best regards,
Ben Houston
http://Clara.io Online 3d modeling and rendering

**Comment by dirtybluejeans** [comment]
Thanks for looking into this Ben. Are you saying that's the only solution? Surely that can't be the recommended way, as that would mean that any device that doesn't support highp won't work at all - and even if it does, will take a performance hit. Should it do a graceful fallback in case of lowp, instead of breaking so severely? The target for my app is low-end, cheap phones, so this does impact significantly (though I was testing on the iphone where it actually broke :)

Thanks.

**Comment by dirtybluejeans** [comment]
...also, what's odd is that it works fine on desktops on lowp, and some android devices, but not on the iphone... could this be a bug in the shader?

**Comment by bhouston** [comment]
I've made a support bug here on what I believe is the core issue: https://github.com/mrdoob/three.js/issues/9515

**Comment by dirtybluejeans** [comment]
Thanks Ben, I'm sure now that it's been seen 'in the wild', someone will come up with ways to solve this. Usually, the effect manifests as something that looks like signal 'clipping' (to use an AV term), or values going over the range of the data type so they become negative...  but I'm not an expert at this by any means so I'll step back and hope this will be sorted :).

Many thanks for looking into this.

**Comment by Mugen87** [comment]
Closing in favor of #9515.
