### ISSUE TITLE
THREE.Clock() does not start the clock

### ISSUE THREAD

**Issue by nadous** [mrdoob/three.js#9504]
Correct me if I'm wrong but this:

``` javascript
var clock = new THREE.Clock()
console.log(clock.startTime)
```

logs `0`... which appears to be in contradiction with the [documentation](http://threejs.org/docs/index.html?q=clock#Reference/Core/Clock).

In fact, the source of `r79` should be updated like so:

``` javascript
function Clock( autoStart ) {

    this.autoStart = ( autoStart !== undefined ) ? autoStart : true;

    this.startTime = 0;
    this.oldTime = 0;
    this.elapsedTime = 0;

    this.running = false;

    if (this.autoStart === true)
    {
        this.start();
    }
}
```
##### Three.js version
- [ ] Dev
- [x] r79
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
To be honest, we should probably refactor `THREE.Clock` completely.

**Comment by nadous** [comment]
Well. I'll be happy to help, but I don't know what kind of refactoring is desired. You let me know if I can do something, or if you want me to close this issue.

Cheers.

**Comment by Mugen87** [comment]
Why not creating a new prototype called `THREE.Time` with a similar interface like the [Time](https://docs.unity3d.com/ScriptReference/Time.html) class of Unity? `THREE.Time` should also be automatically updated by the renderer so users can directly access values like this:

```javascript
THREE.Time.delta
THREE.Time.elapsed
```

**Comment by Mugen87** [comment]
#10008 improved the documentation of `Clock`. It should be more clear now how the single methods actually work.
