### ISSUE TITLE
Proposed addition to animationMixer to trigger side-effects on update.

### ISSUE THREAD

**Issue by pontiffpublishing** [mrdoob/three.js#9505]
##### Feature Request

Would you guys consider changing the action-update section of the AnimationMixer.js file (around line 150) 

From:

``` js
if ( action.enabled ) {
    action._update( time, deltaTime, timeDirection, accuIndex );
}
```

To:

``` js
if ( action.enabled ) {
    action._update( time, deltaTime, timeDirection, accuIndex );
    if ( action.onUpdate) action.onUpdate();
}
```

Sometimes side-effects are necessary when animating, and this lets that happen.  An example would be when you make a clip action to zoom an ortho camera:  you have to call updateProjectionMatrix() on the camera each time the zoom factor changes.  This code change makes that easy.

Regards
##### Three.js version
- [ ] Dev
- [ ] r79
- [X]r78 ...
##### Browser
- [] All of them
- [X ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [] All of them
- [X ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by tschw** [comment]
The use case makes some sense, but I don't like the idea of adding callbacks. It's inconsistent with the event dispatch we used elsewhere in animation.

In case of the example, wouldn't it be simpler to just update the projection matrix every frame? It's not exactly a huge overhead.

Other examples? Thoughts?

**Comment by pontiffpublishing** [comment]
Thanks for the opportunity to comment.

A second example is animation choreographing.

Sometimes you want an animation to stop/start/change when another
animation reaches some midpoint in its own execution.  And as that
scales under callback vs. animation-loop-injection vs.
event-throw-and-capture regimes, the winner, for me, is the callback
approach because it takes the least amount of code and is the most
conservative, among the three, of system resources.

That's what I give the priority to:  speed.  Because as the system you
are building becomes more complex, any performance trade-offs you made
up front quickly come back to haunt you.  At least that is how it has
been for me.

**Comment by tschw** [comment]
Javascript is a scripting language so you can always hook into it like

```javascript
myAction._update = function() {
   // do stuff before update
   this.constructor.prototype._update.apply( this, arguments );
   // do stuff after update
};
```
