### ISSUE TITLE
Transparent sphere appear wrong result.

### ISSUE THREAD

**Issue by racway** [mrdoob/three.js#9511]
##### Description of the problem 

I use three.js to make a Transparent earth(sphere)，but get some strange result。I tried depthTest、depthWrite and so on, but not get the right result。

material like below:
`var mat = new THREE.MeshBasicMaterial({map: child.material.map, transparent: true, opacity: 0.6, side:THREE.DoubleSide} );`

picture like below(green is background color), please copy the link to browser☺:
[http://www.youkumax.com/wrong.png](url)

but some angle looks like right,like below:
[http://www.youkumax.com/someAngleRight.png](url)

how can i get right result,Thanks for everybody!

##### Three.js version

- [ ] Dev
- [ ] r79
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by tentone** [comment]
Cant see the images in the links you posted, can u please upload to another place? Its possible for u to leave a code example here?

**Comment by racway** [comment]
Bother copy link to broswer Thank you

**Comment by tentone** [comment]
Oh sorry my bad, this stripes effect that u see migth be due to alpha blending without vertex sorting, probably also happens on cubes (depending on the side some faces migth not render).

**Comment by racway** [comment]
hi, tentone.thankyou for your help.is there some example reference code to solvethis problem.
