### ISSUE TITLE
readRenderTargetPixels fails to read float data in Chrome 52

### ISSUE THREAD

**Issue by jwhitfieldseed** [mrdoob/three.js#9513]
##### Description of the problem 

`readRenderTargetPixels` fails to read from a render target with `type: THREE.FloatType` in Chrome 52 on Mac. Chrome 51 (Mac) and 51/52 (Windows) are not affected.

http://jsfiddle.net/fzyq98t4/4/

Example code:

```javascript
var renderTexture = new THREE.WebGLRenderTarget(width, height, {
  format: THREE.RGBAFormat,
  type: THREE.FloatType
});

var buffer =  new Float32Array(width * height * 4)
renderer.render(scene, camera, renderTexture, true);
renderer.readRenderTargetPixels(renderTexture, 0, 0, width, height, buffer);
```

Output (Chrome 52 Mac):
```
THREE.WebGLRenderer 79
three.js:28048 THREE.WebGLRenderer: WEBGL_color_buffer_float extension not supported.
three.js:27462 THREE.WebGLRenderer.readRenderTargetPixels: renderTarget is not in UnsignedByteType or implementation defined type.
```

The warning and error come from [this check in WebGLRenderer.js](https://github.com/mrdoob/three.js/blob/b1123f4250bea5742d7920032a1e270e5ba0b138/src/renderers/WebGLRenderer.js#L2678).

* In Chrome 51, `_gl.getParameter( _gl.IMPLEMENTATION_COLOR_READ_TYPE )` returns `5126` (`_gl.FLOAT`).
* In Chrome 52, it returns `5121`, (`_gl.UNSIGNED_BYTE`).

If this check is commented out, `readRenderTargetPixels` works as expected.

The [OES_texture_float spec](https://www.khronos.org/registry/webgl/extensions/OES_texture_float/) says:

> ...Implementations supporting float rendering via this extension will implicitly enable the WEBGL_color_buffer_float extension and follow its requirements...

So I think the check can safely use that extension. I have raised #9516 to explore.

Chrome 52 is the latest stable version. I used these builds of Chrome 51 to test my repro case: [Mac](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/386246/), [Windows](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win%2F386243%2Fchrome-win32.zip?generation=1460160228206000&alt=media).

Other browsers:
* Chrome 52 (Win 10) - `_gl.getParameter( _gl.IMPLEMENTATION_COLOR_READ_TYPE )` returns `_gl.FLOAT` so the check passes.
* Firefox (Mac): also returns `_gl.UNSIGNED_BYTE`, but `WEBGL_color_buffer_float` is supported so no error.
* Safari (Mac): As far as I know Safari doesn't support reading float data.
* IE11 (Win 7): `_gl.getParameter` returns `_gl.FLOAT` so the check passes.
* Edge (Win 10): `_gl.getParameter` returns `_gl.FLOAT` so the check passes. 

I have not tested other browsers or OSs.

##### Three.js version

- [x] Dev
- [x] r79
- [x] r78

##### Browser

- [ ] All of them
- [x] Chrome -  52.0.2743.116 (64-bit)
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] OSX - 10.11.4 (El Capitan)
- [ ] Windows 
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
AMD Radeon R9 M370X 2048 MB

**Comment by kenrussell** [comment]
Sorry for the confusion here.

Chrome previously implemented the wrong behavior when reading back from floating-point framebuffers. If the framebuffer is floating-point, then the "main" supported format/type readback combination changes from the usual one (RGBA/UNSIGNED_BYTE) to RGBA/FLOAT.

Chrome previously considered RGBA/UNSIGNED_BYTE to be the "main" supported readback format and type, and RGBA/FLOAT the "implementation" color read format and type. Chrome 52 fixed this behavior.

It should continue to work in Chrome 52 to read back from a floating-point framebuffer using format RGBA and type FLOAT, with the OES_texture_float extension enabled. Please tell me if this seems to not be the case. (This is tested in the WebGL conformance suite.)
