### ISSUE TITLE
MeshStandardMaterial artifacts on many mediump devices since March 2016 (Nexus 5, Samsung Galaxy.)

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#9515]
##### Description of the problem

There are still artifacts with MeshStandardMaterial on mediump devices, such as a Nexus 5:

This is just zooming into the Standard material example scene as of August 15, 2016: http://threejs.org/examples/#webgl_materials_standard

Nexus 5: 
![screenshot_20160815-084108](https://cloud.githubusercontent.com/assets/588541/17665485/50ef0a38-62c9-11e6-8a5c-4981f0c22088.png)

Nexus 5:
![screenshot_20160815-084100](https://cloud.githubusercontent.com/assets/588541/17665486/524b148a-62c9-11e6-8a8b-54bf663772cd.png)

Samsung Galaxy Core:
![screenshot_2016-08-15-09-49-50](https://cloud.githubusercontent.com/assets/588541/17666547/991395c2-62ce-11e6-996c-ec0d49437bfe.png)

This was previously discussed here: https://github.com/mrdoob/three.js/pull/8353#issuecomment-196176489 and also here: https://github.com/mrdoob/three.js/issues/9501 and here https://github.com/mrdoob/three.js/pull/8349

In our Clara.io fork of ThreeJS we resolved this by forcing `highp` precision but this imposes a performance issue.

I suggest that we look at other mobile friendly PBR engines (OSG.js, Babylon.js, UE4?) to see how they deal with this precision issue.  I suspect they are modify the shading equations to avoid these precision issues.
##### Three.js version
- [x] Dev
- [x] r79
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

I have reproduced the error on Nexus 5, Samsung Galaxy Core.

It does not reproduce on iPod touch 6, nor does it reproduce on an iPad Air 2.

**Comment by dirtybluejeans** [comment]
Note that this issue impacts iOS as well (at least iPhone 6s)

**Comment by bhouston** [comment]
@dirtybluejeans can you reproduce using the example that I used?  Can you share a screenshot of the reproduction.  I could not reproduce this morning with that scene on an iPad Touch 6 (equivalent to iPhone 6) nor on an iPad Air 2.

**Comment by dirtybluejeans** [comment]
Sure here goes. I could easily find issues on the butt and barrel: the butt had something that appeared to be bullets, but they are actually artifacts. The barrel shows the engravings on it completely disappear during this problem. Each picture only has one issue, so you can clearly compare the two areas.
![img_5254 png](https://cloud.githubusercontent.com/assets/326630/17673577/5aaae530-633f-11e6-81e1-37a2636356b2.jpeg)
![img_5255 png](https://cloud.githubusercontent.com/assets/326630/17673578/5ab70022-633f-11e6-9e84-a3af8e9f7037.jpeg)

Please do let me know if these aren't clear enough, or if you need views from a certain angle.

**Comment by bhouston** [comment]
Those bullets are there actually.  Those it seems like it is clipping going on in your scene that isn't in mine.  I do not see shader artifacts, rather I just see clipping artifacts in your posted examples.

**Comment by dirtybluejeans** [comment]
You are right, those are actually bullets. Funny though that they show through only at certain angles (usually where they would have a specular spot). I'll look again for shader artefacts.

**Comment by dirtybluejeans** [comment]
Here's another go at it. Very hard to spot, considering I've having serious issues with the clipping when on lowp (should I file a separate bug for it?). I did spot some dots (marked) on the barrel at some angles (you can also spot the clipping happening further up the barrel, so these artifacts aren't due to it).

When I originally reported this issue, I was seeing it primarily on very high specular spots (where material roughness was zero or close to it. I haven't found such areas in the current scene, which might be why it can't be spotted so easily (in this scene). 

![from skitch png](https://cloud.githubusercontent.com/assets/326630/17674576/c08353b6-6343-11e6-8d59-175b51c342f0.jpeg)

**Comment by dirtybluejeans** [comment]
Also spotted some 'moire' like patterns on the Macbook (on lowp), but didn't give it much thought then. Only when I didn't see them in highp I thought I'd go back and take pictures, but couldn't replicate the same set of params. Will put up a picture if I see that happening again.

**Comment by bhouston** [comment]
I believe that @spidersharma03 has time to look into this.  He has both a Macbook and a Nexus 5.

**Comment by spidersharma03** [comment]
Let me try to see the cause of the issues, and hopefully get a fix :-)

**Comment by dirtybluejeans** [comment]
@bhouston should I open a separate issue for the weird clipping happening on lowp, since it's not due to shader bugs? The clipping doesn't happen when I switch to highp.

**Comment by spidersharma03** [comment]
I am sorry, but couldn't get time to look into this issue this time :-(

**Comment by dirtybluejeans** [comment]
guys, is there any action on this? Also, @bhouston, should I open a separate issue for the weird clipping happening on lowp, since it's not due to shader bugs? The clipping doesn't happen when I switch to highp.

**Comment by mrdoob** [comment]
@bhouston Your screenshots show 2 issues. 73e3b92f42b36477c8cce9d30b12156ee15bf21b fixes one of them (checker-like glitches). The moire pattern is still there though.
