### ISSUE TITLE
Shading bug in ShaderLib.phong with Directional Lights

### ISSUE THREAD

**Issue by TheJim01** [mrdoob/three.js#9517]
##### Description of the problem 

I've been toying with lighting recently, and found a problem when pairing ShaderLib.phong with directional lights. An example fiddle is here: http://jsfiddle.net/TheJim01/oqa4wq0a/

The example has two cubes. On the left uses ShaderMaterial + ShaderLib.phong. The cube on the right uses MeshPhongMaterial. As the sides of the cubes reach shallow projection angles, you can see the cube on the left washes completely black, rather than smoothly blending like the cube on the right.

This does not happen when using point lights.

##### Three.js version

- [x] Dev
- [x] r79
- [x] tested back to r71

##### Browser

- [x] All of them

##### OS

- [x] All of them
- [x] Windows
- [x] Android

**Comment by mrdoob** [comment]
Updated jsfiddle using `requestAnimationFrame`. http://jsfiddle.net/oqa4wq0a/7/

**Comment by mrdoob** [comment]
If you comment out `uniforms.shininess.value = 0;` the result is the same in both cubes.

**Comment by TheJim01** [comment]
Your suggestion gave me an "aha" moment. It seems that having a non-zero shininess is what resolves the issue. I realize that if I'm not using shininess, I should probably use Lambert or Basic, and perhaps having a non-zero shininess is basic knowledge, but would it be within reason/scope to add some kind of range checking for uniform values? I could mull over adding that if there's an appropriate place for such a thing.

**Comment by mrdoob** [comment]
We have that already:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L2158

Unfortunately we can't do anything about custom uniforms.
