### ISSUE TITLE
ObjectLoader: Ability to reference external objects

### ISSUE THREAD

**Issue by brendanmig** [mrdoob/three.js#9520]
For a project we are working on we're looking at having a lot of content that is shared between various scenes. EG: a particular chair model that's shared between various office layout scenes. Rather than having to define the geometry for these in each scene that uses them I'm looking at extending the ObjectLoader to support having external 'assemblies'. EG:

```
{
...
"assemblies": [
  {
    "uuid" : "427ea844-b1b0-4e93-af7f-a7a5445f9a3f-000c59c6",
    "url" : "parts/table.json"
  }, {
    "uuid" : "6355c06c-4de0-4e2a-b6e9-e747988941b0-000a47bc",
    "url" : "parts/chair.json"
  }
],
...
"object":{
  "uuid" : "dac7975a-efa6-4b29-aca3-0660c1ba37c5",
  "type" : "Scene",
  "matrix" : [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
  "children" : [
    {
      "uuid" : "092412c1-d5d8-4ad5-bc84-48a05d7c38a5",
      "type" : "Asssembly",
      "matrix" : [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
      "assembly" : "427ea844-b1b0-4e93-af7f-a7a5445f9a3f-000c59c6"
    }, {
      "uuid" : "11701dca-7b7f-4e06-823d-444f2eb1c01d",
      "type" : "Assembly",
      "matrix" : [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1.5, 0, 0, 1],
      "assembly" : "6355c06c-4de0-4e2a-b6e9-e747988941b0-000a47bc"
    }, {
      "uuid" : "fd951cd9-5712-4e0d-aa22-004420b4d916",
      "type" : "Assembly",
      "matrix" : [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, -1.5, 0, 0, 1],
      "assembly" : "6355c06c-4de0-4e2a-b6e9-e747988941b0-000a47bc"
    }
  ] 
}
}
```

On load this would go and download the referenced Object files from the URLs and insert them into the scene graph. Much in the same way as external Images are loaded.

Is this something that you already have plans for in 3JS? If we were to extend this would you be open to a pull request to merge it into the main code, and if so would the above format be appropriate for you?

**Comment by Benjamin-Dobell** [comment]
@brendanmig Is there any reason why you don't use a higher level file at references various scenes and assembles them, rather than modifying `ObjectLoader` and the corresponding file format?

This is the approach I've taken, albeit our scenes are not static, they're created and modified at runtime (saved and restored).

**Comment by Mugen87** [comment]
> Is there any reason why you don't use a higher level file format that references various scenes (ObjectLoader files) and assembles them, rather than modifying ObjectLoader and the corresponding file format?

Closing. @Benjamin-Dobell approach is a proper solution for this use case.
