### ISSUE TITLE
GridHelper not showing Lines

### ISSUE THREAD

**Issue by nicky-lenaers** [mrdoob/three.js#9522]
##### Description of the problem 

(This is NOT a help site. Please read the guidelines above before posting.)

GridHelper is not showing lines.

After adding in these simple lines:
``scene.add(new THREE.GridHelper(10, 1));``

I get this result:
![screen shot 2016-08-16 at 11 16 00](https://cloud.githubusercontent.com/assets/2785350/17694872/418b947a-63a6-11e6-94c5-b279c1f09e2c.png)

In r78, the Lines within the Grid showed up correctly.

##### Three.js version

- [ ] Dev
- [x] r79
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by tentone** [comment]
Hi

The grid helper now receives size, divisions, color1, color2 as arguments on its constructor.

Its not showing lines cause you are passing 1 for divisions, use a higher value.
