### ISSUE TITLE
Lensflare: Bug with OrbitControls

### ISSUE THREAD

**Issue by KentJames** [mrdoob/three.js#9523]
##### Description of the problem 

When using a lens flare in conjunction with OrbitControls, the flares render relative to the target of the control(the point it orbits around), instead of the position of the camera. Visually it doesn't look correct, especially when viewed with the camera behind the light source, but focused on an object behind the light source.

You can find my code in this repository: https://github.com/KentJames/Solar-System/tree/working-branch

See attached pictures. 
<img width="1680" alt="screen shot 2016-08-16 at 11 24 08" src="https://cloud.githubusercontent.com/assets/2029444/17696138/70d0a146-63a4-11e6-8afa-5340453070dd.png">
<img width="1680" alt="screen shot 2016-08-16 at 11 24 15" src="https://cloud.githubusercontent.com/assets/2029444/17696152/7c8be126-63a4-11e6-861a-5b7d335024d2.png">
<img width="1680" alt="screen shot 2016-08-16 at 11 24 19" src="https://cloud.githubusercontent.com/assets/2029444/17696158/87179540-63a4-11e6-9258-84986e4985a5.png">
<img width="1680" alt="screen shot 2016-08-16 at 11 24 23" src="https://cloud.githubusercontent.com/assets/2029444/17696162/9183ba04-63a4-11e6-8352-c40955c8226b.png">
<img width="1680" alt="screen shot 2016-08-16 at 11 24 31" src="https://cloud.githubusercontent.com/assets/2029444/17696168/9d7ffff2-63a4-11e6-9eae-f623e08ad23d.png">

##### Three.js version

- [x ] Dev
- [x ] r79
- [ ] ...

##### Browser

- [x] Chrome
- [x] Safari

##### OS

- [x] OSX

**Comment by mrdoob** [comment]
Could you create a live link we can check?

**Comment by KentJames** [comment]
Yeah sure, it's here:

https://kentjames.github.io/Solar-System/

Set the camera focus to anything other than the sun and try orbiting around it, you will notice that the lens flare stays fixed in a straight line axis like this <SUN> ----> <PLANET> ----> <FLARE>.

I tried tracing it through the library and it looks like the screen position vector is where the issue is?

**Comment by mrdoob** [comment]
I don't see a lensflare here...?

![screen shot 2016-08-17 at 10 26 24](https://cloud.githubusercontent.com/assets/97088/17746506/2f31bb82-6465-11e6-920a-983ba5224c6d.png)

**Comment by KentJames** [comment]
Sorry, the lens flare occurs if you pan out a bit on the control. If you zoom out a fair way and focus on a planet you should see the bug then. The code switches from the rendered sphere to a flare at a certain distance. Apologies for leaving that bit out!

**Comment by KentJames** [comment]
@mrdoob : I replicated the issue in a simpler example.

Live link: http://www.crimpspiration.com/Test/LensFlare_Test/

**Comment by mrdoob** [comment]
I'm unable to get the lensflares to show up.

![screen shot 2016-08-18 at 11 14 00](https://cloud.githubusercontent.com/assets/97088/17785291/05136668-6535-11e6-82a7-a9fdb016f29f.png)

![screen shot 2016-08-18 at 11 14 37](https://cloud.githubusercontent.com/assets/97088/17785303/10a1ac88-6535-11e6-943f-631b1d0a192e.png)

Tried on Chrome, Firefox and Safari...

**Comment by KentJames** [comment]
You should be able to zoom out a fair way, and move the camera around and see it. The flare isn't immediately visible on load in both of the examples.

**Comment by mrdoob** [comment]
Maybe you can change the start position of the camera so it's immediately visible? 😉

**Comment by KentJames** [comment]
Probably a good idea! I threw the second one together on my way out so bit rushed.

I've read into this a bit more: http://john-chapman-graphics.blogspot.co.uk/2013/02/pseudo-lens-flare.html

Looks like the three implementation is sprite based, which makes sense as its very cheap to implement, so actually I don't think this is a bug even if it doesn't look realistic.. After looking into it in a bit more detail a pseudo-realistic lens flare is a bit more work.
