### ISSUE TITLE
Support closure compiler as additional minification option besides ugly2.

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#9524]
##### Description of the problem 

Per this tweet: https://twitter.com/mrdoob/status/765319504318431233

We should support minification via the closure compiler with the new module system.

More details here: https://github.com/google/closure-compiler/issues/1956

##### Three.js version

- [x] Dev
- [ ] r79
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by spite** [comment]
I think that with rollup + uglify2 we're on a similar result, plus removing the java dependency.

**Comment by bhouston** [comment]
I guess?  There is this data point: https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016

**Comment by danrossi** [comment]
It looks like there is a closure build command now.

**Comment by mrdoob** [comment]
Yup!

**Comment by Datamance** [comment]
@mrdoob would you consider [adding docstrings](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler) so that you can leverage ADVANCED_OPTIMIZATIONS?

**Comment by mrdoob** [comment]
@Datamance I think I would rather implement ES6 classes instead.

**Comment by Datamance** [comment]
@mrdoob will that have the same effect with regards to optimizations made by CC? Sorry, I'm a bit ignorant here - it's been a while since I've used the Closure ecosystem. I bet there have been changes to compilation with the introduction of ES6 and goog.module, I'm just not aware of them
