### ISSUE TITLE
Massive memory leak when rendering PLY model with vertex colours

### ISSUE THREAD

**Issue by samcaulfield** [mrdoob/three.js#9527]
##### Description of the problem 

The following program leaks about 300 MiB per second on my machine. It continues to do this until the browser becomes unstable and crashes (when the 8 GiB of main memory is exhausted and it switches to swap).

The ASCII PLY model used in the program is [model.zip](https://github.com/mrdoob/three.js/files/421068/model.zip). If I remove the vertex colours from the model then the memory leak does not occur.

Using window.setInterval to power the main loop does not make a difference.

```
// test.js
var camera, scene, renderer;

init();

function render() {
	renderer.render(scene, camera);
	requestAnimationFrame(render); // This call seems to cause the leak over time
}

function init() {
	renderer = new THREE.WebGLRenderer();
	renderer.setSize(800, 600);
	document.body.appendChild(renderer.domElement);

	scene = new THREE.Scene();

	var directionalLight = new THREE.DirectionalLight(0xffeedd);
	directionalLight.position.set(0, 0, 1);
	scene.add(directionalLight);

	new THREE.PLYLoader().load("model.ply", function(geometry) {
		geometry.computeFaceNormals();
		var material = new THREE.MeshStandardMaterial();
		material.vertexColors = THREE.VertexColors;
		material.side = THREE.DoubleSide;
		scene.add(new THREE.Mesh(geometry, material));
	});

	camera = new THREE.PerspectiveCamera(45, 800 / 600, 1, 2000);
	camera.position.z = 500;

	render();
}
```

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="ASCII">
	</head>

	<body>
		<script src="three.js/build/three.min.js"></script>
		<script src="three.js/examples/js/loaders/PLYLoader.js"></script>
		<script src="test.js"></script>
	</body>
</html>
```

##### Three.js version

- [x] Dev
- [x] r79

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by mrdoob** [comment]
Do you mind provide a live link we can directly test?

**Comment by WestLangley** [comment]
The leak does appear to be occurring in r.79 (but not r.78) -- even with this simpler example.

```javascript
var mesh, camera, scene, renderer;

init();
animate();

function init() {

	renderer = new THREE.WebGLRenderer();
	renderer.setPixelRatio( window.devicePixelRatio );
	renderer.setSize( window.innerWidth, window.innerHeight );
	document.body.appendChild( renderer.domElement );

	scene = new THREE.Scene();

	camera = new THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 1, 2000 );
	camera.position.z = 500;

	controls = new THREE.OrbitControls( camera, renderer.domElement );

	var loader = new THREE.PLYLoader();

	loader.load( "man128.ply", function( geometry ) {

		var material = new THREE.MeshBasicMaterial( { side: THREE.DoubleSide } );

		mesh = new THREE.Mesh( geometry, material );

		scene.add( mesh );

	} );

}

function animate() {

	requestAnimationFrame( animate );

	renderer.render( scene, camera );

}
```

@samcaulfield Can you provide a live link and confirm?

**Comment by samcaulfield** [comment]
Hi all,

I have uploaded the two test cases at [sc.netsoc.ie/memleak/test0.html](url) and [sc.netsoc.ie/memleak/test1.html](url). I can confirm that both test cases produce the memory leak on my system.

The test cases are both using r.79

Thanks

**Comment by aardgoose** [comment]
This is fixed by https://github.com/mrdoob/three.js/commit/723979c0506820f66a94cc230ad7bc4e77d5dd39 by the look of it.

**Comment by samcaulfield** [comment]
The two examples in this thread seems to run fine now on latest dev version (084174b5f14360d0968bae33a5b40b91b65f1e82)

Thanks for the fix!
