### ISSUE TITLE
Correct radiusSegments to radialSegments for ConeGeometry

### ISSUE THREAD

**Issue by nicky-lenaers** [mrdoob/three.js#9528]
##### Description of the problem 

(This is NOT a help site. Please read the guidelines above before posting.)

In the [docs for ConeGeometry](http://threejs.org/docs/?q=cone#Reference/Extras.Geometries/ConeGeometry), the thrid parameter is called ``radiusSegments``. According the code, this should be called ``radialSegments``. Please correct.

##### Three.js version

- [ ] Dev
- [x] r79
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/edit/dev/docs/api/extras/geometries/ConeGeometry.html

😇

**Comment by nicky-lenaers** [comment]
Ah, gotcha :), here you go: https://github.com/mrdoob/three.js/pull/9531
