### ISSUE TITLE
Object.defineProperties performance "issue"

### ISSUE THREAD

**Issue by tentone** [mrdoob/three.js#9536]
Hi

After some research (https://bugzilla.mozilla.org/show_bug.cgi?id=626021, https://www.nczonline.net/blog/2015/11/performance-implication-object-defineproperty/), i wonder why do three.js (and other libraries) use getter and setters (or Object.defineProperties), is there any special advantage to this aproach other than variable protection?

I made some test code (https://jsfiddle.net/b5uvqeh1/)

Couldn't we get some extra performance (and reduce code size) by throwing them away when they are not needed, if so, may be a good chance to do that since threejs may move to ES6 soon?

Sorry for this (maybe dumb) question, im still a newbie to web technologies.

Cumps

**Comment by mrdoob** [comment]
It's mainly protecting variables that shouldn't be touched and for hiding others.

**Comment by tentone** [comment]
I asked cause i actually have a case where i need to override the entire constructor in order to be able to change some variables in Object3D and i noticed a small performance increase. (Still on 80fps (its my monitor refresh rate) but time between frames decreased a bit)

This was the reason that led me to do this research.

Knowing this is it worth to keep using Object.defineProperties for variable protection?

**Comment by mrdoob** [comment]
Do you have some specific numbers?

**Comment by tentone** [comment]
For now only the fiddle i posted above, (updated here https://jsfiddle.net/b5uvqeh1/2/) that show 30x to 200x speedup by just avoiding Object.defineProperties (this also apply to Function.prototype, where the function call time is reduced)

By changing the fiddle loop cycle count from 10000 to 500 (i belive at least 500 functions / variable accesses are made for a single frame), in the machine where i'm currently working on (i7 3558U), <1 ms for loop B and >3ms for loop A in booth chorme and firefox and a 8ms delta in MS Edge.

The possible 3ms gain is enough to jump from 50fps to 60fps. So its a considerable performance boost.

**Comment by mrdoob** [comment]
> I asked cause i actually have a case where i need to override the entire constructor in order to be able to change some variables in Object3D and i noticed a small performance increase. (Still on 80fps (its my monitor refresh rate) but time between frames decreased a bit)

A way of testing the impact is to use Chrome Developer Tools / Profile. Select Record Javascript CPU Profile and click Start. Let it run for a 3 or 4 seconds. Then compare the results with and wtihout your change.

For example, using threejs.org/examples/webgl_geometry_hierarchy2.html I get this:

![screen shot 2016-08-18 at 14 08 16](https://cloud.githubusercontent.com/assets/97088/17790862/413ce48a-654d-11e6-856e-3e8b049aa967.png)

Check if any of the top functions (hot code) reduces % or goes down the list.

**Comment by jupavavi** [comment]
It is true Object.defineProperties calling is slower than just direct assignment of the properties. But this covers only the initialization of the Objects. So, for objects that are not supposed to create to many instances, this could be not bad at all. The other problem is related to read/write operations over the properties. The code https://jsfiddle.net/b5uvqeh1/2/ has a poor performance while changing the properties due the lack of writable descriptor. As it is shown here https://jsfiddle.net/b5uvqeh1/13/, the performance in chrome is the same for read and write for A and B when writable descriptor is provided. At glance it seems you need to avoid Object.defineProperties in the constructor if instantiation might be big, but harmless for read and write if descriptors are provided.

**Comment by jupavavi** [comment]
In this latest test, https://jsfiddle.net/b5uvqeh1/29/ I cached the descriptors and realized that this could improve the initialization timing. But still it is considerably slow at initialization time. Also, it seems Object.defineProperty is simnifically faster per each property than bundle all in Object.defineProperties. Although this has done only for 3 properties, it might change if the amount of properties increase. After this, I think if you don't have choice about using Object.defineProperty, at least cache de descriptors.

**Comment by jamie-pate** [comment]
https://bugs.chromium.org/p/v8/issues/detail?id=3649
