### ISSUE TITLE
#RawShaderMaterial Breaks When Using Custom Defines with Custom Extensions

### ISSUE THREAD

**Issue by skyburchard** [mrdoob/three.js#9546]
When Using custom defines with RawShaderMaterial in combo with extensions (written directly at the top of the fragment shader), shader will not compile.

What is happening is the custom defines are being added in before the extensions. This causes a problem because the "extension directive should occur before any non-preprocessor tokens". An easy fix would be to add in "customExtensions," before "customDefines" in the "prefixFragment" array where rawShaderMaterial is composed.

I was happy to see that custom defines were added to rawShaderMaterial. I want them to work in combo with custom extensions.

##### Three.js version

- [x ] Dev
- [ ] r79
- [ ] ...

**Comment by WestLangley** [comment]
Is this the change you are referring to in `WebGLProgram.js`?

```javascript
prefixFragment = [

	customExtensions,
	customDefines

].filter( filterEmptyLine ).join( '\n' );
```
Would you like to file a PR yourself?

**Comment by skyburchard** [comment]
That' the change I was referring to. Thank you @WestLangley. I'll do a pull request.

**Comment by sirxemic** [comment]
I already made a pull request for this: #9349. But I think people forgot about it...

**Comment by skyburchard** [comment]
Thanks @mrdoob

**Comment by skyburchard** [comment]
@sirxemic I added in the newlines from your issue #9349 in my pull request. That was frustrating me too.

**Comment by sirxemic** [comment]
@skyburchard I saw. Thanks!
