### ISSUE TITLE
Browser crashes when trying to export large objetcs

### ISSUE THREAD

**Issue by Brucewayne01** [mrdoob/three.js#9549]
I'm using OBJ exporter , and when objects are greater than (~30 - ~40)Mb the browser crashes.
##### Three.js version
- [x ] r79
##### Browser
- [x] All of them
##### OS
- [x] Windows
##### Hardware Requirements (graphics card, VR Device, ...)

Nvidia GeForce GTX 960M

**Comment by looeee** [comment]
@Brucewayne01 can you provide an example model that is causing the browser to crash?

**Comment by donmccurdy** [comment]
Closing this, but feel free to reopen with an example we can debug — thanks.
