### ISSUE TITLE
MeshPhongMaterial breaks with envMap

### ISSUE THREAD

**Issue by riotCode** [mrdoob/three.js#9550]
##### Description of the problem 

MeshPhongMaterial doesn't play nice with envMaps, gets error `THREE.WebGLShader: Shader couldn't compile.`

I tested this on dev and r79 using three.js example `webgl_materials_envmaps_hdr.html`. JsFiddle's provided below of both, only modified MeshStandardMaterial to MeshPhongMaterial with basic settings.

##### Three.js version

- [x] Dev
- [x] r79

##### Browser

- [x] Chrome (latest, 52.0.2743.116)
- [x] Safari (latest, 9.1.1)
- [ ] Firefox (untested)
- [ ] Internet Explorer (untested)

###### System 1
- OSX El Capitan 10.11.5
- AMD Radeon R9 M370X

###### System 2
- Win10
- Nvidia GTX 970

###### System 3
- Win10
- Nvidia GTX 1080 (x4)

##### Fiddles

- Dev: http://jsfiddle.net/0h4wuukz/
- r79: http://jsfiddle.net/fknknety/

**Comment by mrdoob** [comment]
What's happening is that `MeshPhongMaterial` doesn't support `THREE.CubeUVReflectionMapping` as `texture.mapping` so this code fails: https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/envmap_fragment.glsl#L26-L42

I'll add a `else` case so at least the program is able to compile.

**Comment by riotCode** [comment]
@mrdoob cool, thanks!

**Comment by mrdoob** [comment]
Thank you!
