### ISSUE TITLE
Mac OSX NodeJS Build

### ISSUE THREAD

**Issue by FlyApple** [mrdoob/three.js#9551]
1.install NodeJS and NPM
2.install node modules:

```
sudo npm install argparse -g 
sudo npm install uglify-js -g 
```

3.set environment variables:
`export NODE_PATH=/usr/local/lib/node_modules`
4.build ThreeJS:
node build.js --include common --include extras --minify --output ../../build/three.js --minifiedoutput ../../build/three.min.js

**Comment by mrdoob** [comment]
Uh?
