### ISSUE TITLE
THREE.ObjectLoader ignores textures in json

### ISSUE THREAD

**Issue by carlosanunes** [mrdoob/three.js#9554]
##### Description of the problem

THREE.ObjectLoader does not load textures from JSON created by the Blender exporter. No error is shown but material has no texture.

Proof of bug in attached zip file.

[three.js - json scene import bug.zip](https://github.com/mrdoob/three.js/files/428587/three.js.-.json.scene.import.bug.zip)
##### Three.js version
- [ ] Dev
- [x] r79
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Somehow that attachment didn't work.

**Comment by carlosanunes** [comment]
lol, excellent...

Re uploaded the file...

**Comment by mrdoob** [comment]
![screen shot 2016-08-20 at 22 50 28](https://cloud.githubusercontent.com/assets/97088/17835591/8987316e-6728-11e6-90ff-226266ae003d.png)

Interesting... Yeah. For some reason, I have to disable and enable "map" to get the texture working...

**Comment by satori99** [comment]
The bug.json file looks a bit messed up. It has two material sections, and one of them is inside the geometry section.

**Comment by RamotionRussell** [comment]
I'm having this same issue. Latest blender, just start a new project, put a texture on a cube, export scene with the JSON exporter. Output JSON looks reasonable, but when I actually load it in the browser via ObjectLoader, I see only naked geometries. No textures.

Also, I'm sure the texture information is at least being parsed properly, because I can see a (successful) request for the texture image in my browser network debugger.

**Comment by satori99** [comment]
> Also, I'm sure the texture information is at least being parsed properly, because I can see a (successful) request for the texture image in my browser network debugger.

Image downloads are initiated by the ObjectLoader before it starts constructing Textures, Materials, and other Objects. So the fact that they appear in the network tab of the debugger is not relevant to the issue I think.

Also, I have many examples of Object Format 4 JSON files with images, both (datauri and url) that work just fine with the current ObjectLoader.

How are you generating your JSON file? do you have an example of a broken one you could post somewhere?

**Comment by RamotionRussell** [comment]
[myscene.json.zip](https://github.com/mrdoob/three.js/files/431891/myscene.json.zip)

The above scene JSON has this problem for me. I'm using r79 three.js and the most recent Blender Three JSON exporter I could find (though the exporter does not seem to be the problem--the JSON looks sensible enough to me).

> So the fact that they appear in the network tab of the debugger is not relevant to the issue I think.

Well yes, that's what I'm saying -- if the textures weren't being downloaded, then that would be the issue!

> How are you generating your JSON file?

New Blender project, add a plane, texture it, export with Three JSON exporter with all relevant options checked (basically anything that sounds like texture or material, plus scene/lights/cameras).

**Comment by satori99** [comment]
That JSON file has 3 material sections, 2 of them are inside the geometries section. That doesn't look like valid Object Format 4 (ObjectLoader) JSON to me. This looks like it is probably an exporter issue.

https://github.com/mrdoob/three.js/wiki/JSON-Object-Scene-format-4

**Comment by RamotionRussell** [comment]
Ok, if there's supposed to be exactly one global section of materials and geometries, then this is indeed probably the issue. As far as I can see, Blender uses a hierarchy, so often textures and geometries are "children" of other objects (which seems to me like a very strange way to do this, but ok...).

Maybe the exporter isn't properly flattening the Blender internal structure?

**Comment by satori99** [comment]
You are exporting using the old-style Geometry format, maybe try using BufferGeometry?

**Comment by satori99** [comment]
I am writing a new Blender addon from scratch, which is why i'm interested in these issues. My exporter is much simpler than the existing one and doesn't bother with the legacy stuff like Geometry. It uses the Blender bmesh API which makes it crazy fast compared to the exiting one too.

Are you able to share your .blend file? It would be neat to try it out on some content I didn't create myself.

**Comment by RamotionRussell** [comment]
> You are exporting using the old-style Geometry format, maybe try using BufferGeometry?

Well Geometry was the default. I tried it with BufferGeometry, and the JSON looks better, but it still  has the same problem with textures not appearing.

Here's the BufferGeometry JSON:

[myscene.json.zip](https://github.com/mrdoob/three.js/files/431932/myscene.json.zip)

> I am writing a new Blender addon from scratch

Nice. Here is the Blender file I'm using to reproduce this:

[myscene.blend.zip](https://github.com/mrdoob/three.js/files/431933/myscene.blend.zip)

Blender v. 2.77

**Comment by satori99** [comment]
@RamotionRussell my first thoughts are that the objects in that scene do not have UV coords.

Well, the Cube has Generated coords but im not sure if they are handled by the exporter. The plane has mapping set to UV coords, but no UV set is applied (or exists)

Try unwrapping the objects (Edit mode -> U) and then apply that uv to the material.

**Comment by RamotionRussell** [comment]
> Try unwrapping the objects (Edit mode -> U) and then apply that uv to the material.

Ok I tried this, and it does fix the texture appearance in Blender Render (previously it was rendering the texture weirdly split between the two triangles. You can tell this is not my area of expertise 😂 ) I do see UV changes in the output JSON, but the texture still does not appear on the plane in the browser.

Most recent .blend and output JSON:

[myscene.json.zip](https://github.com/mrdoob/three.js/files/431959/myscene.json.zip)
[myscene.blend.zip](https://github.com/mrdoob/three.js/files/431961/myscene.blend.zip)

**Comment by satori99** [comment]
@RamotionRussell can you try this JSON file with your app code?

[myscene.zip](https://github.com/mrdoob/three.js/files/431963/myscene.zip)

**Comment by RamotionRussell** [comment]
Wait scratch that. It works! Browser cache was loading stale JSON scene.

**Comment by RamotionRussell** [comment]
It uses a Phong shader, which is a bit unexpected, but at least the texture is there now.

**Comment by Mugen87** [comment]
Since the Blender exporter was removed, I recommend to export your models as `glTF` and use `GLTFLoader`. More information:

https://threejs.org/docs/index.html#manual/introduction/Loading-3D-models

**Comment by soalribeiro** [comment]
I'm having the same problem, I'm using ObjectLoader to load my JSON 3D object and then MaterialLoader to load the JSON texture to apply to the object. The thing is three js is simply ignoring the texture and marked it as undefined
