### ISSUE TITLE
setPixelRatio resizes rendered image instead or changing resolution on iPhone 6

### ISSUE THREAD

**Issue by michaelitvin** [mrdoob/three.js#9556]
##### Description of the problem 

I'm trying to set the pixel ratio dynamically before the call to renderer.render() to increase the FPS when performance is low.

This works well on:
- Macbook Pro Safari and Chrome
- Android Nexus 5 Chrome

On iPhone 6 (both Safari and Chrome), the rendered image resizes (takes less screen area), instead of just changing its resolution in place.

##### Three.js version

- [ ] Dev
- [x] r79

##### Browser

- [x] All of them
- [x] Chrome
- [X] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
iPhone 6

**Comment by michaelitvin** [comment]
Related:

http://stackoverflow.com/questions/39052433/setpixelratio-resizes-rendered-image-instead-or-changing-resolution-on-iphone-6

https://github.com/borismus/webvr-polyfill/issues/102

**Comment by mrdoob** [comment]
#9500
