### ISSUE TITLE
use THREE.WebGLRenderTarget as material.map

### ISSUE THREAD

**Issue by asforever** [mrdoob/three.js#9559]
##### Description of the problem 
if i use THREE.WebGLRenderTarget as material.map, it will  warning 

"index.html:1 [.CommandBufferContext.Offscreen-MainThread-03686968]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same."

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser
- [x] Chrome
##### OS
- [x] Windows

**Comment by mrdoob** [comment]
Does the error issue still happen with `r79`?

**Comment by asforever** [comment]
it still happen with r79
 warn
[.CommandBufferContext.Offscreen-MainThread-086C8A28]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same---index.html:1 

renderTarget=new THREE.WebGLRenderTarget( 512, 512, { wrapT: THREE.RepeatWrapping, wrapS: THREE.RepeatWrapping } );

var floorMaterial = new THREE.MeshBasicMaterial( {color: 0xeeeee1, map:renderTarget.texture, transparent: true, opacity: 1.0} );

var floor=new THREE.Mesh(new THREE.PlaneBufferGeometry(300,300,2,2),floorMaterial);
.
.
.
renderer.render(scene,camera,renderTarget,true);

**Comment by mrdoob** [comment]
Could you create a jsfiddle?

**Comment by asforever** [comment]
I will not use the jsfiddle,then i had send to "https://github.com/asforever/SnakeCube"

**Comment by mrdoob** [comment]
In order to solve bugs we need isolated code in jsfiddles that show clearly the issue. Otherwise, there is the risk that the bug is in your code and not in the library.
