### ISSUE TITLE
`WebGLRenderer#clear` does not always clear main framebuffer

### ISSUE THREAD

**Issue by kfigiela** [mrdoob/three.js#9565]
##### Description of the problem

`WebGLRenderer#clear` does not always clear main framebuffer. When `clearTarget` it calls `setRenderTarget` and doesn't revert back to the previous (i.e. default) one. If `clear` is called next, it will clear again `WebGLRenderTarget` provided to `clearTarget`, not main framebuffer as expected. 

**Expected behavior:** `clear` always clears main framebuffer (canvas), while `clearTarget` clears provided render target.

Revelant code:
- https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L506
- https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L536
##### Three.js version
- [X] Dev
- [ ] r79
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

Irrevelant

**Comment by WestLangley** [comment]
Perhaps you need to call
```javascript
renderer.setRenderTarget( null );
```
prior to calling `renderer.clear()`.

See http://threejs.org/examples/webgl_materials_cubemap_dynamic.html

**Comment by kfigiela** [comment]
Yes, it works, I already implemented this workaround.

**Comment by WestLangley** [comment]
I do not think that is a work around -- it is intended behavior.

`renderer.clear()` clears the currently bound framebuffer.
