### ISSUE TITLE
DataTexture doesn't support NPOT textures

### ISSUE THREAD

**Issue by paulmelis** [mrdoob/three.js#9566]
##### Description of the problem 

Creating a texture with DataTexture of 227x227 RGB pixels results in a " texImage2D: ArrayBufferView not big enough for request" error. 

Excerpt from my code:

var values = new Uint8Array(...);
var texture = new THREE.DataTexture(values, 227, 227, THREE.RGBFormat, THREE.UnsignedByteType);

(I double-checked values.length, it's 227x227x3=154587 as it should be).

Or using ImageUtils, which results in the same error:

var texture = THREE.ImageUtils.generateDataTexture(227, 227, new THREE.Color(0xffffff));

NPOT texture WebGL support is definitely working, as simply loading a 227x227 image from a static PNG using the TextureLoader renders correctly.

##### Three.js version

r79

##### Browser

Tested with Chrome 52.0.2743.116

##### OS

Arch Linux 64-bit

**Comment by paulmelis** [comment]
In issue #1277 the suggestion is to use power-of-2 textures instead, but that would be a shame. My data is not power-of-2 sized and WebGL supports it (although with some restrictions, as outlined in https://www.khronos.org/webgl/wiki/WebGL_and_OpenGL_Differences#Non-Power_of_Two_Texture_Support).

**Comment by mrdoob** [comment]
Hmm, could you create a jsfiddle we can work with?

**Comment by paulmelis** [comment]
Here you go: https://jsfiddle.net/qo6ooacj/3/

There's a single if in there that toggles between creating a texture by loading a 227x227 image (from an inline base64-encoded jpeg :)) and by creating a DataTexture of the same size (using a snippet from ImageUtils). Mipmapping is disabled and filtering set to linear to handle the NPOT size. The texture loaded from file renders fine, the DataTexture gives the error "WebGL: INVALID_OPERATION: texImage2D: ArrayBufferView not big enough for request" in Chrome 52 for me.

**Comment by isolin** [comment]
I fully agree, with paulmelis. I have several data textures in my new project: 1D, 2D and 3D. Having npot variants for all dimensions would be optimal. Right now quite a lot of dummy data is transfered to the GPU just for rounding up to pot. Further overhead is the addressing.

**Comment by WestLangley** [comment]
I think the solution for this use case is to set
```javascript
texture.unpackAlignment = 1; // default is 4
```
This appears to be required only with the `THREE.RGBFormat` / `THREE.UnsignedByteType` combination when `texture.width` is NPOT.

See https://devtalk.nvidia.com/default/topic/875205/opengl/how-does-gl_unpack_alignment-work-/

**Comment by mrdoob** [comment]
Specifically... https://devtalk.nvidia.com/default/topic/875205/opengl/how-does-gl_unpack_alignment-work-/post/4664521/#4664521

**Comment by mrdoob** [comment]
So the check would be this?

```js
var isPOT = THREE.Math.isPowerOfTwo;
if ( ( isPOT( width ) && isPOT( height ) ) === false && format === THREE.RGBFormat && type === THREE.UnsignedByteType ) {
    this.unpackAlignment = 1;
}
```

Should we add that to `DataTexture`?

**Comment by WestLangley** [comment]
>Should we add that to DataTexture?

That seems reasonable to me, but only the width needs to be checked for POT, I am pretty sure.
```javascript
var isPOT = THREE.Math.isPowerOfTwo;

if ( ( isPOT( width ) ) === false && format === THREE.RGBFormat && type === THREE.UnsignedByteType ) {

    this.unpackAlignment = 1;

}
```
Thing is, users can set the format and type outside of the constructor. We would have to handle that with setters.

**Comment by mrdoob** [comment]
Maybe we can set it on the renderer instead and warn the user that `unpackAlignment` was changed?

**Comment by WestLangley** [comment]
>That seems reasonable to me, but only the width needs to be checked for POT, I am pretty sure.

I am more than sure, now. : - )

>Maybe we can set it on the renderer instead.

That would be fine, too -- reset the alignment if needed and throw a warning if reset.

Maybe do both? Add the test in the constructor and the check in the renderer.

**Comment by mrdoob** [comment]
First of all... @paulmelis @isolin can you guys check if setting `texture.unpackAlignment` to `1` works for you?

**Comment by mrdoob** [comment]
Seems to work. https://jsfiddle.net/jvvwmdyy/

**Comment by WestLangley** [comment]
Looks good to me.

**Comment by mrdoob** [comment]
Hmm... How about we set `unpackAlignment` to `1` in `DataTexture` by default?

**Comment by WestLangley** [comment]
>Hmm... How about we set unpackAlignment to 1 in DataTexture by default?

I am not sure of the ramifications of doing that.

FYI, have a look at (7) and (8) in [this link](https://www.opengl.org/archives/resources/features/KilgardTechniques/oglpitfall/).

**Comment by mrdoob** [comment]
Interesting...

@kenrussell do you have any recommendations?

**Comment by kenrussell** [comment]
There should not be any performance penalty during texture uploads for setting the unpack alignment to 1. The only issue is that it changes the expected packing for the rows, so if there's code out there that's written assuming an unpack alignment of 4, setting it to 1 by default will cause the uploaded textures to look sheared diagonally, as the padding bytes at the end of each row will suddenly show up as part of the texture.

On the whole I think that setting it to 1 is the best thing to do for end users in the long run, though. It makes it much easier to understand where each pixel's data lies in the upload buffer.

**Comment by mrdoob** [comment]
Ok, good to know it has no performance penalty.

It seems a simpler solution to me as it works for any case, and I would think that anyone changing that value would also know the side effects.

**Comment by isolin** [comment]
Yes, it works perfectly!
