### ISSUE TITLE
Displacement maps broken in r80: WebGLCapabilities mis-reporting vertexTextures support

### ISSUE THREAD

**Issue by williamfields** [mrdoob/three.js#9568]
##### Description of the problem 

Displacement maps are not working in r80 because WebGLCapabilities is always returning false for vertexTextures. I believe the problem is with this line: https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLCapabilities.js#L89

`vertexTextures: this.maxVertexTextures > 0,`

It is referring to `this.maxVertexTextures`, which was removed by a recent change.

I am using the workaround: `renderer.capabilities.vertexTextures = (renderer.capabilities.maxVertexTextures > 0);`

##### Three.js version

- [ ] Dev
- [ ] r79
- [x] r80

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

NVIDIA GeForce GT 755M

**Comment by mrdoob** [comment]
Oh, yes. I totally broke that... 😟

**Comment by mrdoob** [comment]
Thanks!
