### ISSUE TITLE
Loader gltf material and technique do not respect gltf spec

### ISSUE THREAD

**Issue by martinRenou** [mrdoob/three.js#9571]
##### Description of the problem 

Hi everybody,

It seems like the gltf loader do not respect gltf spec: 

line 990 of glTFLoader.js:
`var technique = material.technique ? this.resources.getEntry(material.technique) : null;`
`values = material.values;`
`var description = technique.description;`

In the gltf spec, it is mentioned  "If material.technique is not supplied, and no extension is present that defines material properties, then the object will be rendered using a default material with 50% gray emissive color.".

But here if material.technique is false, then technique is null and the last line of the code above raise an issue.

##### Three.js version

- [x] Dev
- [ ] r80
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

**Comment by richtr** [comment]
This issue should be fixed by https://github.com/mrdoob/three.js/pull/9726.

**Comment by martinRenou** [comment]
Thanks :)
