### ISSUE TITLE
Problem with depth-cueing in MeshDepthMaterial?

### ISSUE THREAD

**Issue by ianjt** [mrdoob/three.js#9572]
##### Description of the problem

(This is NOT a help site. Please read the guidelines above before posting.)

Hi, there seems to be a problem with the depth-cueing in MeshDepthMaterial .  According to the [manual](http://threejs.org/docs/?q=depth#Reference/Materials/MeshDepthMaterial):
"white is nearest, black is farthest.".  However I see it the other way around in my applications.  You can see the same effect in the demo in the page above (click THREE.MeshDepthMaterial, turn on wireframe and reduce wireframeLineWidth to see the effect).  To my eyes, the lines are brightest when farthest way (smallest apparent radius of the tube due to perspective), which is obviously not what one expects!

You can see the same effect in this [demo](http://threejs.org/examples/?q=depth#webgl_depth_texture).  Again, from the perspective one can see that black is near, white is far, the opposite of what the manual says.  However in this case it works since the background is white, whereas in the first case and in my apps the background is black.  So the MeshDepthMaterial constructor appears to be assuming that the background is white.

Interestingly in this [example](https://github.com/josdirksen/learning-threejs): see Chapter 4, example 2, it works correctly with a black background (i.e. near objects are displayed correctly as white).  However this is using a very old version of three.js so my guess is that the library was changed at some point to work correctly with a white background?

I wonder if it would be possible to accommodate all tastes by having 2 additional parameters to set the brightness at the near and far planes (e.g. 1.0 and 0.1, so that the lines don't disappear completely near the far plane)?

Cheers

-- Ian Tickle
##### Three.js version
- [x] Dev
- [ ] r80
- [ ] ...
##### Browser
- [] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
##### OS
- [] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
White is nearest when using `BasicDepthPacking`.
