### ISSUE TITLE
Feature Request: Ranged computeVertexNormals() on large geometries

### ISSUE THREAD

**Issue by kpetrow** [mrdoob/three.js#9574]
There is currently a Ranged update for position update.  It would be nice to have this range applied to, or implemented in computeVertexNormals({offset:Int,range:int}).   The vertex normal function causes a lag when updating the shading of large geometries.

thanks

**Comment by WestLangley** [comment]
`BufferGeometry` already supports updating a sub-range of an attribute -- that includes the `normal`.

`BufferGeometry.computeVertexNormals()` supports both indexed and non-indexed geometries. Indexed geometries support shared vertices, so there may be faces outside your `index` range that must be included in the calculation to achieve proper results.

**Comment by kpetrow** [comment]
If you have a chance then...help request in SO  http://stackoverflow.com/questions/39113888/three-js-computevertexnormals-performance?noredirect=1#comment65578753_39113888

**Comment by kpetrow** [comment]
Maybe im looking at the wrong place, in bufferGeometry.js line 637 starts computeVertexNormals().  lines 654 - 663 seem to not take into account any ranged inputs.  I see it clearing the entire normal array.

				var array = attributes.normal.array;

				for ( var i = 0, il = array.length; i < il; i ++ ) {

					array[ i ] = 0;

				}

**Comment by WestLangley** [comment]
(1) Re-computing vertex normals and (2) pushing a sub-range of updated normals to the GPU, are two separate operations and are unrelated.

`BufferGeometry.computeVertexNormals()` does so on the entire geometry because it is not generally possible to correctly perform that operation on a sub-range of _indices_ when the geometry is indexed-bufferGeometry and vertices are shared.

If you know you have non-indexed-bufferGeometry, then you can write your own method that recomputes normals on a sub-range of _vertices_.

**Comment by kpetrow** [comment]
im updating the position of maybe 50 out of ~4 million positions every second.  I need the shading to respond to the new updated positions.  It seems odd that i cant just update a subset of the vertex normals even if it was a little larger than my min/max array??  Any suggestions on how to get my planeBufferGeometry shading to update more efficiently??

![image](https://cloud.githubusercontent.com/assets/18248938/17979141/663b0c44-6ab6-11e6-81ff-b7df4478d428.png)

**Comment by makc** [comment]
> Any suggestions

well he said this:

> you can write your own method that recomputes normals on a sub-range of vertices

vertex normals there are computed by averaging face normals, aren't they. so you have to keep track of faces the vertex is in, and, upon updating the vertices, recalculate all the changed faces normals before even attempting vertex normals.

**Comment by WestLangley** [comment]
@makc I said

>If you know you have non-indexed-bufferGeometry, then you can write your own method that recomputes normals on a sub-range of vertices.

Non-indexed-bufferGeometry does not share vertices.

**Comment by kpetrow** [comment]
I had sort of given up on trying to update my shading in real time, for now.  I am using an indexed bufferGeometry.  From my basic understanding of the difference between indexed and non-index, I do want to continue to use index because so many of my faces share points(its one large square grid).  I still do not understand why I couldn't just calculate a slightly larger bounding box of normals for my range.  I was hoping to get around to testing it by altering the computeVertexNormals() in bufferGeometry.js .  My plan was to just pass in a range and see what happens.  I am doubtful of its results so it has been back burner-ed, but even if i could get a half way decent shade then run the full shading every 5 seconds i would be happy.

**Comment by makc** [comment]
@WestLangley why does it matter, if there is 'a-b-c' face, and 'a' vertex changes, so do 'b' and 'c' normals, even if, as you are probably hinting at, it is just single face they are in.

**Comment by WestLangley** [comment]
@kpetrow said

>I still do not understand why I couldn't just calculate a slightly larger bounding box of normals for my range.

You can. You need to know the indices of those vertices. In your case, your geometry is a plane, so you can likely determine the indices of the neighboring vertices.

@makc said

>why does it matter

Why does what matter?

For non-indexed-bufferGeometry, the buffer contains vertices in groups of three. So if one vertex is changed, the other two vertices of the face are easily located in the buffer.

On the other hand, if you displace a vertex in a solid mesh and the mesh's geometry is non-indexed, you will have tearing unless you are able to concurrently displace all coincident vertices by the same amount.

**Comment by kpetrow** [comment]
> You can. You need to know the indices of those vertices. In your case, your geometry is a plane, so you can likely determine the indices of the neighboring vertices.

I'm already keeping track of volumes and altering the surface based on a single RTK GPS position.  I take the single position and  use tilt sensor(azimuth,pitch,roll) and machine data(length, width, height) to alter the surface from a single point.  Interpolating a little further would be no problem.

Well, I have new found hope in being able to get this to work.  Thank you.  I will give it a shot over the weekend maybe.  Would there be any value in submitting for review?  I have only used SVN and review board for work.   Not sure of GIT procedures.  Thanks again.

**Comment by mrdoob** [comment]
I don't think this is something we can do. You may want to use different geometries, compute the vertex normals for those and then merge. Somehow.
