### ISSUE TITLE
Loading an SVG with TextureLoader no longer works as of r78.

### ISSUE THREAD

**Issue by Adam-Meisen** [mrdoob/three.js#9575]
##### Description of the problem

The following code works in R77, but as of R78, the `onLoad` callback will never be called, even when `onProgress` shows the file is 100% loaded. As I was unable to find any documentation about this change, I wanted to bring it to your attention as a possible bug.

```
var url = ; //any svg
new THREE.TextureLoader().load(url, () => {console.log("texture loaded");}, (xhr) => {console.log((xhr.loaded / xhr.total * 100) + '% loaded');});
```
##### Three.js version
- [x] Dev
- [x] r80
- [x] r79
- [x] r78
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by zwitter1** [comment]
I too am having a problem with TextureLoader, though I'm uncertain yet if the issue aligns with the problem your having with svgs. In my case (I think this is the majority of the problem) I am using NodeWebkit (nwjs), and images that used to load fine in the days of THREE.ImageUtils.loadTexture no longer load using TextureLoader.

I am trying to load a simple png file to use in a particles object, but while I get a 200 status code indicating a successful load (debugging the loader in three.js) and a 100% complete from the onProgress, I do not get an image out of my texture. I simply get no errors or warnings and a bunch of black holes where my particles should be.

I'm going to try to set it up in a simple node server and test there next.

**Comment by mrdoob** [comment]
Can you create a jsfiddle using r77 and another one using the latest version?

**Comment by zwitter1** [comment]
I apologize mrdoob, I thought I had deleted my post. I had resolved my problem shortly after the post. You can disregard what I had posted. Sorry for the trouble. I greatly appreciate your work. Keep it up. 

Zach

**Comment by Adam-Meisen** [comment]
r77: https://jsfiddle.net/pffbf5ws/6/

r80: https://jsfiddle.net/47ca60pr/3/

**Comment by makc** [comment]
could it be because ImageLoader is now using XHRLoader

**Comment by mrdoob** [comment]
Meh... I knew there had to be a side effect 😕

**Comment by Villmer** [comment]
Yeah, I was hoping this would also be fixed in version 83. Alas no. 
I can't get an svg texture to load via TextureLoader or ImageLoader.
Had to completely revert all the way back to version 76. Yikes.

**Comment by makc** [comment]
@Villmer you don't have to revert whole thing, just the loader. And it's not a big deal to write your own code either, I mean
```javascript
var fu = new Image;
fu.onload = function () {
    var bar = new THREE.Texture (fu);
    ...
};
fu.src = 'my.svg';
```

**Comment by Villmer** [comment]
@ makc
Didn't work.

**Comment by makc** [comment]
@Villmer 
![ORLY](http://i1.kym-cdn.com/entries/icons/original/000/000/015/orly.jpg)

http://jsfiddle.net/hfj7gm6t/2615/

**Comment by Villmer** [comment]
@makc 
Yes, it's working now. I forgot about the crossOrigin = 'anonymous' and the needsUpdate for my THREE.Texture and THREE.SpriteMaterial( ).
Thank you! :-)

**Comment by makc** [comment]
actually, I myself do not understand why `bar.needsUpdate = true` is needed here, I mean this is new texture, it should be true by default, no? @mrdoob ?

**Comment by mrdoob** [comment]
> actually, I myself do not understand why bar.needsUpdate = true is needed here, I mean this is new texture, it should be true by default, no? @mrdoob ?

It's a common pattern to render a texture that hasn't loaded yet.

```js
material.map = loader.load( 'texture.png' ); // returns THREE.Texture but image hasn't loaded yet.
```

I think we tried setting `needsUpdate` to `true` by default, but I remember not having a robust way to know if the image has been loaded or not. `image.complete` was not always reliable.
