### ISSUE TITLE
Mesh documentation has wrong Description

### ISSUE THREAD

**Issue by SpiritBreaker** [mrdoob/three.js#9576]
##### Description of the problem 

On The Mesh documentation ( http://threejs.org/docs/?q=Mesh#Reference/Objects/Mesh) :

The description of method .updateMorphTargets() has some problem, as morphTargetForcedOrder is removed.
So i think it should be deleted on doc. 

##### Three.js version

- [ ] Dev
- [x] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
You can do the change directly 😊
https://github.com/mrdoob/three.js/edit/dev/docs/api/objects/Mesh.html

**Comment by mrdoob** [comment]
#9601
