### ISSUE TITLE
Two different glTF loader

### ISSUE THREAD

**Issue by tiagocardoso** [mrdoob/three.js#9579]
##### Description of the problem 

I'm a bit confused about the glTF loader. We have the "old" one and a new one (that is really fast and simple). Is the old one deprecated ? 
Which of both will continue to be developed and, therefor, I should use ?

Thanks!

##### Three.js version

- [x] Dev
- [ ] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Old one is complicated but complete. The new one is simpler but incomplete.
Use whichever works best for your case.
