### ISSUE TITLE
MultiMaterial will not work well with opacity

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#9581]
##### Description of the problem 
When use MultiMaterial for single mesh. If materials have various Opacity, translucent object will not work well because softObjects does not work for single mesh.

##### Three.js version

- [ ] Dev
- [x] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
You are making a very general statement.

Different models have different challenges. There are techniques that can be employed to reduce artifacts, and those techniques are typically use-case-specific.

**Comment by JulioCuellar** [comment]
i have problems with multimaterial too, i cannot sustract the clicked material array index of a JSON model, im using the raycaster class and the proyector class and i can only get the mesh of that model

**Comment by whatisor** [comment]
@WestLangley : Thank for your reply. I think it is quite specific problem.
1 models have 2 parts with 2 material index (multimaterial).
If we can support this, designer do not have to separate into some meshes.
@JulioCuellar You can get material index by face which is clicked.

**Comment by WestLangley** [comment]
@whatisor Can you please link to a simple live example to demonstrate your use case? Please also provide a live example of the designer's 2-mesh solution for comparison.

**Comment by JulioCuellar** [comment]
@whatisor you can show me an example of that 'cause i was looking in stack and i dont found any example, pls :D

**Comment by whatisor** [comment]
@WestLangley  This is simple example of MultiMaterial with opacity partly:
https://codepen.io/karoshi/pen/yaBJLa

We expect, we can see Red face because Green face is opacity=0.5.
This issue can be solve if we draw Red face as plan, Green faces as planes.

**Comment by WestLangley** [comment]
@whatisor 
```javascript
THREE.MeshBasicMaterial( {
  wireframe: false, 
  color: 0xff0000,
  opacity: 1,
  transparent:false,
  side: THREE.DoubleSide
} );
```
https://codepen.io/anon/pen/ALAqWJ?editors=0010#0

**Comment by whatisor** [comment]
:D. Amazing. 
Yes, I forgot BackSide condition.

@JulioCuellar Please check document of RayCaster :
http://threejs.org/docs/api/core/Raycaster.html
It returns Face for you.
