### ISSUE TITLE
r80 migration and "three.euler .setFromRotationMatrix given unsupported order: undefined" 

### ISSUE THREAD

**Issue by verteAzur** [mrdoob/three.js#9583]
Hello everyone,

The migration to r80 went pretty smooth, no issues nor warning found... I wanted to thank you for the stability in the latest releases. It went from 10-14 days worth of work to nothing! It sure gives us more time, but most importantly, it gives us the peace of mind needed to move toward this not so easy bleeding edge road. 

On a side note, we have encountered a new warning, which might not be specific to r80: 

three.euler .setFromRotationMatrix given unsupported order: undefined 

context:
- the warning triggers on the lookAt() member function
- the point used in the lookAt() comes from the spline getPointAt function
- the object looking is a skinning blender object added to a group

Thank you,
verteAzur

**Comment by WestLangley** [comment]
Can you please provide a jsfiddle that replicates the issue?

**Comment by verteAzur** [comment]
Here is a fiddle that simulates the steps:  http://jsfiddle.net/qnq31cax/5/
I see no warnings there! Which means, something is triggering the warning on our side. I'll keep you updated if the findings are worth mentioning.

**Comment by killroy42** [comment]
I'm encountering the warning when applying rotation via the TransformControl. I am investigating...

**Comment by killroy42** [comment]
Please note that TransformControls in the function onQuaternionChange execute: `rotation.setFromQuaternion( quaternion, undefined, false );`, passing undefined explicitly for order, which cases the warning.

**Comment by j3zusla** [comment]
Re everyone, I've finally got the time to track down the "three.euler .setFromRotationMatrix given unsupported order: undefined" warning:

when a rotation vector is copied
`object.rotation.copy(new THREE.Vector3());`

and later the object uses the lookAt function
`object.lookAt(somepoint);`

The warning is triggered...

Here is the fiddle for it: http://jsfiddle.net/qnq31cax/11/ 

This warning was not easy to find, it might be useful to others to be aware of it...

**Comment by verteAzur** [comment]
Re everyone, I've finally got the time to track down the "three.euler .setFromRotationMatrix given unsupported order: undefined" warning:

when a rotation vector is copied
`object.rotation.copy(new THREE.Vector3());`

and later the object uses the lookAt function
`object.lookAt(somepoint);`

The warning is triggered...

Here is the fiddle for it: http://jsfiddle.net/qnq31cax/11/

This warning was not easy to find, it might be useful to others to know it...

**Comment by WestLangley** [comment]
>object.rotation.copy( new THREE.Vector3() );

That is invalid code. Use

    object.rotation.setFromVector3( v, order );

or any other valid method.

**Comment by killroy42** [comment]
Good point! To clarify, Euler !== Vector3, even though it has x,y,z, since a Euler requires the order property, which a Vector3 does not have. In other words, rotation is Vector3 PLUS order!

**Comment by verteAzur** [comment]
It makes sense once the bug is found, but in the long run from a user perspective it is confusing.

The following does not trigger any warning:
`object.rotation.set(0,0,0);`

but this call triggers the warning
`object.rotation.copy( new THREE.Vector3(0,0,0) );`

Plus the warning should be triggered when it is missed used and not when the lookAt() function is called, or maybe a default value for the ordering should be set the same way it is set via rotation.set().

**Comment by mrdoob** [comment]
Maybe we can a check in `Euler`'s `copy()`?

```js
if ( euler.isEuler === undefined ) {
    console.error( 'blah' );
    return;
}
```

**Comment by killroy42** [comment]
The real culprit is that none of these methods are "typed". They simply expect {x, y, z}, not a Vector3 or similar. While I've often found that convenient, it prohibits those kinds of type checks. Also, it seems that the Three.js philosophy errs on the side of performance rather than type safety. Perhaps in the near future we could include more type checks and some kind of Babel filter to remove them for production...
