### ISSUE TITLE
Raycasting: Vector Project/Unproject becomes Inaccurate for Large Camera Positions 

### ISSUE THREAD

**Issue by victorbhchua** [mrdoob/three.js#9587]
##### Description of the problem 

If one initializes the camera's position to a large X, the mouse position does not seem to be projected correctly. 

Modified from "examples/webgl_interactive_raycasting_points.html"

```
function onDocumentMouseMove( event ) {
	event.preventDefault();
	mouse.x = ( event.clientX / window.innerWidth ) * 2 - 1;
	mouse.y = - ( event.clientY / window.innerHeight ) * 2 + 1;
}
```

```
function init() {
	...
	camera = new THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 1, 10000 );
	camera.position.set( 10000000, 0, 0 );
	...
}
```

```
var logCounter = 0;
function render() {
	...
	logCounter++;
	if (logCounter > 120) {
		logCounter = 0;
		var mouse3D = new THREE.Vector3(mouse.x, mouse.y, 0.5);
		console.log(mouse3D);
		mouse3D.unproject(camera);
		console.log(mouse3D.project(camera));
	}
	...
}
```

The above snippet in the render() function prints out the original mouse position vs. the projected one.
However, the projected mouse position will show a somewhat large discrepancy!

The problem is negligible when camera.position.x is 0. 
The problem worsens as the camera.position.x becomes large!

Take a look here: [http://jsfiddle.net/qdydpLtf/](http://jsfiddle.net/qdydpLtf/)
Point your mouse cursor anywhere in the webGL window.
It will alternate between the original camera position and a large camera postion.x. 
Open your browser's console to see some output!

##### Three.js version

- [x] r80

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [x] Windows
- [x] macOS

**Comment by mrdoob** [comment]
@WestLangley any ideas?

**Comment by WestLangley** [comment]
Likely due to floating point issues over which we have no control.
