### ISSUE TITLE
Asset management implementation in threejs

### ISSUE THREAD

**Issue by tentone** [mrdoob/three.js#9589]
Hi

I’m working on asset management solution for Three.JS (asset/Image.js, asset/Audio.js, asset/Video.js, asset/Font.js), those assets would be used to create Textures, Audio, etc. and these objects could be serialized to JSON same way the rest of Three.JS objects do.

For Audio, Video and Images I am loading files as array buffer and converting them to base64, after that I store encoding (extracted from file extension), data (base64 data) and create an UUID and name for them.

For images after loading the file it is converted to JPEG or PNG depending on transparency needs.
For Font files I’m only storing JSON data, name and UUID.

The problem I have right now is that for this to work I would need to refactor completely Texture.js.
What I’ve done was use Texture.js as a base generic class and added category variable that is used to store texture type (ImageTexture, VideoTexture, WebcamTexture, etc), and toJSON only stores base texture data (without the image serialization).

The class that have the same behavior as the old Texture.js is called ImageTexture.js and receives a image instance instead of a HTML Element instance. (Same apply for VideoTexture)
TextureLoader was also redone to be able to load all these diferent textures
Also changed Object.toJSON to store Font, Audio, Image, Video on meta object.

Opinions on this? 

Here's what video json export looks like

`	"videos": [
		{
			"name": "video",
			"uuid": "06574FC0-A17B-4316-A817-E35BCB37D649",
			"type": "Video",
			"encoding": "webm",
			"data": "GkXfowEAAAAA ...`

**Comment by mrdoob** [comment]
All this sounds good to me overall 👍

**Comment by tentone** [comment]
Nice. I will move the code to a threejs fork and open a PR soon.

**Comment by tentone** [comment]
@mrdoob 

For testing i was using NWJS (its the platform im using for my project) where i have access to FileSystem that has methods for ArrayBuffer and Base64 String loading.

Resources are loaded synchonously right now (before PR i will also add sync variable and onLoad callback).

This is was i managed as an workaround for synchonous resource load (resouces/Audio.js as an example), since synchonous XHR requests are deprecated unfortunately (i know its for better but sometimes they are usefull)

I tried to change the text enconding configuration and this seems to be working well for every case.

```
function Audio(url)
{
	this.name = "audio";
	this.uuid = THREE.Math.generateUUID();
	this.type = "Audio";

	this.encoding = ""
	this.data = null;

	if(url !== undefined)
	{
		var file = new XMLHttpRequest();
		file.open("GET", url, false);
		file.overrideMimeType("text/plain; charset=x-user-defined");
		file.send(null);

		this.encoding = url.split(".").pop();
		this.data = arrayBufferFromBinaryString(file.response);
	}
}
```

I will also need to compile all these auxiliar base64, arraybuffer and binary string conversion utils to a couple of auxiliar util classes something like (extra/utils/[Base64Utils.js,  ArrayBufferUtils.js])

Im also thinking about moving json load code off from loader instances to fromJSON factory methods something like (possible resources/Video.js), since i belive LoaderObjects are really neat to load external files but i think that would be actually better to have toJSON and fromJSON methods here or even check if url argument is a JSON (would be actually better)

```
VideoLoader.fromJSON = function(json)
{
	var video = new Video();
	video.name = json.name;
	video.uuid = json.uuid;
	video.encoding = json.encoding;
	video.data = json.data;

	return video;
}
```

**Comment by tentone** [comment]
Today i playing around with nunu studio and remembered that gif images (w/ animations) are not supported as textures because of the way im encoding data to jpeg or png. So i changed the Image.js (constructor to this).

```
function Image(url)
{
	this.name = "image";
	this.uuid = THREE.Math.generateUUID();
	this.type = "Image";

	this.format = "";
	this.encoding = ""
	this.data = null;

	if(url !== undefined)
	{
		this.enconding = url.split(".").pop();

		if(this.enconding !== "gif")
		{
			this.format = "url";
			this.data = url;
		}
		else
		{
			var file = new XMLHttpRequest();
			file.open("GET", url, false);
			file.overrideMimeType("text/plain; charset=x-user-defined");
			file.send(null);

			this.data = "data:image/" + this.encoding + ";base64," + base64BinaryString(file.response);
			this.format = "base64";
		}
	}
}
```

Any opinions on this whole topic?

**Comment by titansoftime** [comment]
What about compressed textures?

**Comment by tentone** [comment]
By compressed you mean TGA files?

Would be neat if we could use webp (https://developers.google.com/speed/webp/) since it can compress really well images (better than booth png and jpeg) but for now only chrome supports it.

Im also studying the possibylity of zip/base64 storage maybe we can recover the 30% space loss from base64 encoding, but i will leave that for now.

**Comment by titansoftime** [comment]
Nah, DDS.

**Comment by tentone** [comment]
Ah i see well since threejs does support them they can be easly added here. A just added code for TGA support (converting it to JPEG after load). Code for DDS would be similar but i have to check how DDS are being loaded into Texture.js to keep original mipmaps from file, and see how i can handle that here. 
```
		if(this.encoding === "tga")
		{
			var file = new XMLHttpRequest();
			file.open("GET", url, false);
			file.overrideMimeType("text/plain; charset=x-user-defined");
			file.send(null);

			var loader = new THREE.TGALoader();
			var canvas = loader.parse(arrayBufferBinaryString(file.response));

			this.encoding = "jpeg";
			this.format = "base64";
			this.data = canvas.toDataURL("image/jpeg", 0.8);
		}
```

**Comment by satori99** [comment]
Has anyone looked at moving to the [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) API rather than XMLHttpRequest for this type of thing?
It is Promise based API, but already has very good browser support (and a small polyfill for older browsers)

Also, [createImageBitmap ](https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmapFactories/createImageBitmap)is now supported in Chrome and Firefox, and look ideal for certain types of image preprocessing and loading without the need to create DOM objects (Image or Canvas);

    createImageBitmap(image[, options]).then(function(response) { ... });

    options Optional
        An object that sets options for . The available options are:

        imageOrientation: Indicates whether the image is presented as is or flipped vertically. Either none (default) or flipY.
        premultiplyAlpha: Indicates that the bitmaps color channels are premultiplied by the alpha channel. One of none, premultiply, or default (default).
        colorSpaceConversion: Indicates whether the image is decoded using color space conversion. Either none or default (default). The value default indicates that implementation-specific behavior is used.
        resizeWidth: A long integer that indicates the new width.
        resizeHeight: A long integer that indicates the new height.
        resizeQuality: Specifies an image scaling algorithm. One of pixelated, low (default), medium, or high.

**Comment by tentone** [comment]
@satori99 Thanks a lot. Unfortunately fetch is not supported on mobile at all. Canvas has the benefit of letting me choose what encoding to use for images.

I will try to benchmark fetch API since it migth be a better way to get data, and can be used when available instead of xhr request.

**Comment by GGAlanSmithee** [comment]
One diffetence between fetch and xhr is that it is impossible to cancel a request with fetch.. just FYI.
