### ISSUE TITLE
In dreamweaver, there is no code tips in version of 80!

### ISSUE THREAD

**Issue by df257** [mrdoob/three.js#9591]
Other version is no problem.

**Comment by mrdoob** [comment]
Hmm... Is when loading `three.min.js` or `three.js`?

**Comment by df257** [comment]
@mrdoob, both of them are no code tips in dreamweaver when loaded

**Comment by easyfrog** [comment]
yeh ~~ r80 threejs source code and other example js code use ES6 syntax.  'import' etc. In the previous verstion I use grunt and browerify to pack the project. But in r80 my framework is not work.  Because the ES6 syntax, give me some trouble.

**Comment by mrdoob** [comment]
@Rich-Harris Any ideas?

**Comment by Rich-Harris** [comment]
I'm not sure what dreamweaver code tips are – @df257 can you explain what you mean in more detail?

@easyfrog it sounds like the grunt/browserify stuff might be separate from the dreamweaver thing, would it be better to create a separate issue?

**Comment by df257** [comment]
@Rich-Harris, @mrdoob , use R76, in dreavweaver has this:
![ab1](https://cloud.githubusercontent.com/assets/7835444/18080974/509dc512-6eca-11e6-8184-895c04329646.jpg)

but in R80 is no pop up window

**Comment by makc** [comment]
this is same as #9602 isn't it
