### ISSUE TITLE
Is package "chokidar-cli" still used?

### ISSUE THREAD

**Issue by cecilemuller** [mrdoob/three.js#9598]
##### Description of the problem 

I don't see any reference to the module `chokidar-cli` besides package.json dependencies, so maybe it could be removed from dependencies ?

If it was meant to watch files to rebuild, you don't need an extra tool as [rollup has a --watch mode](https://github.com/rollup/rollup/wiki/Command-Line-Interface).

##### Three.js version

- [x] Dev
- [x] r80

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Indeed! I don't think is needed anymore.
