### ISSUE TITLE
UnicodeDecodeError in script 'convert_obj_three_for_python3.py' on Linux/Ubuntu

### ISSUE THREAD

**Issue by matthias77** [mrdoob/three.js#9607]
The script 'convert_obj_three_for_python3.py' work on windows system with no problems. With the same model on an Ubuntu an error occurs: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position...

It seems the mtl file contains not only ASCII characters (mtl generated by MAX).

This seems to be an typical problem in Python3. I have no experience with Python, maybe an Python professional can make this script more tough.

Current Threejs version (81dev)
Linux / Ubuntu

Thanks, Matthias

**Comment by donmccurdy** [comment]
Since May the Python OBJ->JSON converter has been entirely replaced with a nodejs script. It’s likely that will fix the issue (assuming THREE.OBJLoader works with your model) but if not I think we’d need access to the model for debugging

https://github.com/mrdoob/three.js/tree/dev/utils/converters
