### ISSUE TITLE
Displacement Map - Grey scale behaviour

### ISSUE THREAD

**Issue by jimshell** [mrdoob/three.js#9608]
# Description of the problem 

Hello,

First, many thanks for this awesome piece of software. I've been digging into it for a few days now and really like it! :)

I'm not a 3D expert in any way, so this post is both primarily a question and, possibly, a suggestion (if it makes sense).

I use Blender (Clara.io is OK but I needed quite a few more capabilities for my current project), and since yesterday I've been struggling a bit with displacementMap.
I've just realized what Three.js was actually doing when applying displacement maps, considering that black is "no move". Displacement maps made with Blender position the "no move" value on the median grey (127,127,127) in order to have =>

- [black - median grey[ => negative move along normals
- [median grey] => no move
- ]median grey - white] => positive move along normals

I actually don't know if Blender's way is the commonly accepted behaviour when generating/using displacement maps, but instead of trying to modify the resulting maps afterwards (with Gimp or ...) to remap values to black as the "no move" value (which I did, worked fine but this extra step is annoying), I had a deeper look into the glsl code:

    #ifdef USE_DISPLACEMENTMAP
        transformed += normal * ( texture2D( displacementMap, uv ).x * displacementScale + displacementBias );
    #endif`

So, indeed, if texture2D returns a 0.0 value (black), no move.
For my disp maps created in Blender to work without any extra work, i just tried the following change:

    #ifdef USE_DISPLACEMENTMAP
        transformed += normal * ( ( texture2D( displacementMap, uv ).x - 0.5 ) * displacementScale + displacementBias );
    #endif`

which obviously "relocates" the "no move" value to 0.5 (median grey), thus having values below .5 displacing inwards and those above .5 displacing outwards, along normals, just like it is done right within Blender.
The displacementScale and displacementBias still work as expected.

So, my question is: is this modification some sort of improvement or just a specific tweek for Blender users? 

Do you think that it would be possible (and relevant) to add a parameter to let users choose the desired behaviour (black or median grey), or for instance the exact value to use as the "no move" value (thinking of it: could be intersting to do so as it would allow fine grained adjustments without having to re-create a possible too dark or too light displacement map, or for special effects, combined with the displacementScale for instance)?

Thank you :)

##### Three.js version

- [ ] Dev
- [x] r79
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

**Comment by WestLangley** [comment]
`displacementScale` and `displacementBias` are sufficient to map the interval [ 0, 1 ] into any other arbitrary interval.

In your case, pick any positive value for `displacementScale`, and set
```javascript
displacementBias = - 0.5 * displacementScale;
```

**Comment by jimshell** [comment]
Doh! O_o

You are so right... That was basic maths, I had the formula, how could I miss that?? ^^

Thanks for your very quick reply, I'll definitely revert back to the original code.

Sorry for such a lame post... :/
