### ISSUE TITLE
Feature request - public access to intersect methods from raycast

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#9609]
##### Description of the problem

I am working on refactoring `THREE.Octree` from @collinhover. Currently it seems to work quite well with `THREE.BufferGeometry` but not when adding objects with the options `useFaces/useVertices`.

To make this work I am borrowing quite some code from the raycast methods inside `THREE.Mesh`.  I partly need methods like `uvIntersection`, `checkIntersection`, `checkBufferGeometryIntersection`. Would it be okay if I would make a PR where these methods are moved outside of the raycast method? 

I could make a container object where those methods become publicly accessible?

So this should be considered a feature request for a `THREE.IntersectUtils` or `THREE.RaycastUtils`.

Would it be okay to make such improvement in a PR for the next release?

**Comment by mrdoob** [comment]
Maybe they could be static public under `THREE.Raycaster`?

**Comment by Wilt** [comment]
Sure, that is also fine for me, whatever you prefer...

**Comment by mrdoob** [comment]
Yeah, give it a go and we can discuss the best approach in the PR itself.

**Comment by Mugen87** [comment]
Closing. We can reopen the issue when there is a new use case for this.
