### ISSUE TITLE
GridHelper docs need to be updated

### ISSUE THREAD

**Issue by LR17** [mrdoob/three.js#9613]
Threejs r80
The second parameter of GridHelper constructor is "divisions" (the number of) not the size of the step as stated in the the docs

**Comment by mrdoob** [comment]
Would you like to do the change directly?
https://github.com/mrdoob/three.js/edit/dev/docs/api/extras/helpers/GridHelper.html

**Comment by Hectate** [comment]
Since it didn't seem to have been done, I've submitted a pull request for this.
https://github.com/mrdoob/three.js/pull/10145
