### ISSUE TITLE
vector.project doesnt work if X or Y or Z is 0

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#9615]
camera.position.set( 5, 10, 10 )
camera.lookAt( new THREE.Vector3() )

 // (infinity,infiinity,infiinity)
new THREE.Vector3(0, 10, 0).project( camera )

// works fine
new THREE.Vector3(0.00001, 10, 0.00001).project( camera )

**Comment by WestLangley** [comment]
You are changing the camera position. You need to do this:
```javascript
camera.position.set( 5, 10, 10 );
camera.updateMatrixWorld();
```

**Comment by Makio64** [comment]
work, thank you!
