### ISSUE TITLE
Update docs for RayCaster

### ISSUE THREAD

**Issue by vakorol** [mrdoob/three.js#9616]
I think it's worth mentioning in the [docs for `RayCaster`](http://threejs.org/docs/api/core/Raycaster.html#intersectObject), that when intersecting `Points`, each item in the list returned by `.intersectObjects`, will contain key "`index`" (not "`indices`", as for `BufferGeometry`!), while `face` and `faceIndex` will be `undefined`. I believe, that is the "`index`" of the intersected vertex (is it?)

**Comment by mrdoob** [comment]
Would you like to do the change directly?
https://github.com/mrdoob/three.js/edit/dev/docs/api/core/Raycaster.html

**Comment by vakorol** [comment]
Created pull request
https://github.com/mrdoob/three.js/pull/9634

**Comment by looeee** [comment]
#9654

**Comment by looeee** [comment]
@vakorol the discussion is continuing on that pull request, can this be closed?
