### ISSUE TITLE
r79: Not working in Safari 5.1 (Windows latest Safari) because of using URL.createObjectURL

### ISSUE THREAD

**Issue by parth-gudhka** [mrdoob/three.js#9618]
r71 is working in Safari 5.1 but r79 is not. This is because r79 uses URL.createObjectURL to create Blobs which are not supported in Safari 5.1. Safari 5.1 is the latest Safari on Windows so it should be supported I believe.

Problem creating functions:
1. URL.createObjectURL
2. URL.revokeObjectURL

##### Three.js version

- [x] r79

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari v5.1.7
- [x] Browsers which don't support Blobs

##### OS

- [ ] All of them
- [x] Windows
- [x] Linux

**Comment by parth-gudhka** [comment]
I think this was implemented after issue #8904 and commit a2a8589afc12b5cabb33bca18e1c20daaaef2b32

**Comment by aardgoose** [comment]
Safari for windows was discontinued in 2012. Supporting a browser that is 4 years old, unsupported and  4 major releases behind the latest Safari release would only be encouraging users to use a browser with a large number of unfixed and unfixable security. It is unreasonable and a disservice to users to support this.

**Comment by parth-gudhka** [comment]
I have found a solution for my problem. I was using THREE.js TextureLoader which was leading to the problem, so I am changing that to loading the image separately and then directly creating a texture from that image. Our clients require that Safari on Windows should be supported as our tour will be embedded on their site, so I've gotta do this.

**Comment by mrdoob** [comment]
Glad that you figured out a workaround! 👌
