### ISSUE TITLE
Examples View Source Button Broke In Chrome 

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#9621]
In chrome 53 the view source button loads a blank page. It works fine in Firefox 47.

##### Three.js version

- [ ] Dev
- [x] r80
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
#9462
