### ISSUE TITLE
.json objects loaded with morph targets will incorrectly be rotated 90 degrees

### ISSUE THREAD

**Issue by jds580s** [mrdoob/three.js#9625]
##### Description of the problem 
I exported two objects from Blender using the .json exporter.  The only difference between the two objects is one has a set of 3 morph targets.  The export settings are the same.

This link demonstrates two issues; one described above and a second (#9626) that I submitted an additional issue report on.
http://webdev5.onthez.com/morph_scale_bug.html

If the object is rotated Math.PI / -2; it will correct for the issue.

This could be an error with the Blender .json export module, but I'm not sure how best to test for that.

##### Three.js version

- [ ] Dev
- [X] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
no special hardware required

**Comment by mrdoob** [comment]
I think this is a bug in the Blender exporter. Unfortunately no one seems to be whiling to take ownership of the code and solve all these issues.

**Comment by jds580s** [comment]
It looks like the blender .json exporter is what is causing this issue.
Thanks for letting me know!
