### ISSUE TITLE
WebGLRenderer Custom Uniform Update Mechanism

### ISSUE THREAD

**Issue by Ludobaka** [mrdoob/three.js#9630]
##### Asked feature

WebGLRenderer is updating ThreeJS default uniforms [here](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1694). When using custom uniforms, you must update them manually before rendering the scene. Giving a uniform configuration option to the WebGLRenderer (like a function to override, or a callback), will allow to update custom camera-related uniforms automatically at each render call. Another solution would be to give more default uniforms, but I'm not sure we can catch all the possible needed uniforms.

This feature will help to avoid modifying some ThreeJS sources and so get more robustness when upgrading versions of ThreeJS.

##### Description of the problem 

With custom shaders withThreeJS, you generally update dynamic uniforms before each render call with a code pattern like :

    yourmat.uniforms.youruniform.value = something;
    renderer.render(scene, camera);

When using ThreeJS effects like ParallaxBarrierEffect or AnaglyphEffect with custom shaders, you can update uniforms with the previous pattern when they are independent from scene data. The problem is how to update uniforms properly when they are dependent from camera or scene data ?

[ParallaxBarrierEffect](http://threejs.org/examples/?q=para#webgl_effects_parallaxbarrier) is using a StereoCamera containing two cameras. Each camera is slightly shifted compared to the scene camera. For each of those two cameras, the scene is rendered into a render target. Finally, those two render targets are merged and the scene is rendered.

In my case, I developed a sphere and a cylinder impostor shader ([example here](http://jsfiddle.net/Ludobaka/a54qLe9z/)). Those shaders needs the following uniforms :
- Viewport information (offsetWidth, offsetHeight, width, height)
- ModelView matrix inverse of the Object3D
- Projection matrix inverse of the camera

The first one, _viewportInformation_, can be just updated before calling
`parallaxBarrier.render(scene, camera);`

But for `modelViewMatrixInverse` and `projectionMatrixInverse`, I need to update my uniforms depending on which camera I am using.

For now, I had to modify the code of ParallaxBarrierEffect to update my uniforms before each render call with both cameras :

    this.render = function(scene, camera) {

        scene.updateMatrixWorld();

        if (camera.parent === null) { camera.updateMatrixWorld(); }

        _stereo.update(camera);

        this.updateUniforms(scene, _stereo.cameraL);  // Modified code
        renderer.render(scene, _stereo.cameraL, _renderTargetL, true);
        this.updateUniforms(scene, _stereo.cameraR);  // Modified code
        renderer.render(scene, _stereo.cameraR, _renderTargetR, true);
        renderer.render(_scene, _camera);

    };

I'm looking for a way to update those uniforms without having to modify ThreeJS source code and have to maintain a custom ThreeJS version.

##### Note

I'm a user of ThreeJS since 1 year. I digged a lot in it's source code and I'm not afraid to contribute if you think this idea must be implemented.

##### Three.js version
- [x] Dev

##### Browser
- [x] All of them

##### OS
- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)
Depending on the custom shaders, so it doesn't matter here

**Comment by aardgoose** [comment]
Have you looked at https://github.com/mrdoob/three.js/blob/dev/src/core/Uniform.js which allow uniforms that execute a callback from inside the renderer?

Scanning the code, the callback function is called with the camera as a parameter as a bonus for your use case:.

		if ( f !== undefined ) f.call( v, object, camera );

where v is your uniform callback function.

I have played with it in this material:

https://github.com/aardgoose/CaveView.js/blob/dev/src/js/materials/TestMaterial.js

( it is undocumented so far, something else to look at)

**Comment by Ludobaka** [comment]
I totally missed this one when reading the code ! Thank you very much. I'm sorry that it looks more like a question than an issue now...

What do you think documenting this on ShaderMaterial ? It will be the first place where developers come to look for information about custom shaders.

**Comment by aardgoose** [comment]
Easy to miss, but you shouldn't need to read the code to find it, _and_ you have to look in src/renderers/webgl/WebGLUniforms.js to find out how it works. Glad it looks like it solves your problem.
``
If I get round to it it probably wants a page of it's own. One of many bits not documented...yet.
