### ISSUE TITLE
Mesh with fewer morph targets be affected by one with more morph targets

### ISSUE THREAD

**Issue by jhclaura** [mrdoob/three.js#9635]
##### Description of the problem 
Mesh with fewer morph targets be affected by another mesh with more morph targets.

I duplicated the error [here](https://jsfiddle.net/jhclaura/bvvpx40j/8/) by adding a cube with 4 morph targets into Three.js official example [webgl_morphtargets](http://threejs.org/examples/#webgl_morphtargets). The original example only has one cube with 8 morph targets.

Top 8 input bars change the morphTargetInfluences of gray cube, and bottom 4 bars change the blue cube. Two cubes have different geometries and materials, but adjusting the top 8 input bars affects the blue cube.

Have been troubled by this for days and couldn't figure it out. Any guidance will be much appreciated, thanks!

##### Three.js version
- [x] r80

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

**Comment by takahirox** [comment]
I found a bug and sent PR to fix that.
Refer to #9640 for the detail.

**Comment by mrdoob** [comment]
Fixed.
https://jsfiddle.net/bvvpx40j/12/

**Comment by jhclaura** [comment]
AMAZING. Thanks all!

**Comment by mrdoob** [comment]
Thank you!
