### ISSUE TITLE
Suggestion: Allow material access from within dynamic uniform update callback

### ISSUE THREAD

**Issue by fallenoak** [mrdoob/three.js#9637]
##### Description of the problem 

Currently, dynamic uniform update callbacks have no direct access to the material the uniform is defined on. This can create a hoop jump that feels a bit kludgy. It'd be lovely if it were possible to directly access the material from within the callback.

How things currently work:

```
class MyMaterial extends THREE.ShaderMaterial {
  constructor(definition) {
    super();

    var self = this;

    this.textureWeightIndex = definition.textureWeightIndex;

    this.uniforms = {};

    this.uniforms.textureWeight = new THREE.Uniform(1.0);
    this.uniforms.textureWeight.onUpdate(function(object) {
      this.value = object.textureWeights[self.textureWeightIndex];
    });
  }
}
```

I'd much prefer being able to do this instead:

```
class MyMaterial extends THREE.ShaderMaterial {
  constructor(definition) {
    super();

    this.textureWeightIndex = definition.textureWeightIndex;

    this.uniforms = {};

    this.uniforms.textureWeight = new THREE.Uniform(1.0);
    this.uniforms.textureWeight.onUpdate(function(object, material) {
      this.value = object.textureWeights[material.textureWeightIndex];
    });
  }
}
```

##### Three.js version

- [x] Dev
- [ ] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
You don't like this?

```js
this.value = object.textureWeights[object.material.textureWeightIndex];
```

**Comment by fallenoak** [comment]
I'm using the ```Material``` in a ```MultiMaterial```, so I'm unable to know which index the given ```Material``` is at.

**Comment by mrdoob** [comment]
Ah! I can see it now.

**Comment by mrdoob** [comment]
Unfortunately, there is a second parameter already `onUpdate( object, camera )`. So, either we break backwards compatibility, or it'll have to be `onUpdate( object, camera, material )`.

I suspect, the only person using the second parameter at this point is @arose....?

**Comment by fallenoak** [comment]
It'd work just fine for me if it was the third param, although I suppose one might argue that it'd be more logical as the second param.

**Comment by mrdoob** [comment]
> but if ```material``` would be potentially a more popular param, maybe it belongs in the 2nd position.

Agreed. I'll implement it like that by now.

**Comment by mrdoob** [comment]
There you go! 😊

**Comment by fallenoak** [comment]
Thanks much!
