### ISSUE TITLE
WebGLRenderer + SpriteCanvasMaterial incompatible

### ISSUE THREAD

**Issue by wpk-** [mrdoob/three.js#9646]
##### Description of the problem 

The `SpriteCanvasMaterial` inherits from `Material`, which does not define the `.map` property. In some places, the presence of the map is tested using `if ( material.map !== null )`, which passes when it is actually `undefined`. This results in errors. A specific point where this causes an error for me is `SpritePlugin.render()`, but also `WebGLRenderer` has this test.

The following page produces this error on r80:

http://jsfiddle.net/akmcv7Lh/73/

I'm not 100% this is a bug, because the `SpriteCanvasMaterial` seems to be part of the `CanvasRenderer` and my example case only errors when using the `WebGLRenderer`. However, `Material` is a very general class, and also does not define `.map`. I just have no test for the latter.

##### Three.js version

- [ ] Dev
- [x] r80
- [x] r79

##### Browsers tested

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OSes tested

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

In my case it only manifested when using `WebGLRenderer`, so whatever hardware you need to use this renderer.

**Comment by WestLangley** [comment]
`SpriteCanvasMaterial` is not to be used with `WebGLRenderer`. Use `SpriteMaterial`, instead.

**Comment by mrdoob** [comment]
> I'm not 100% this is a bug, because the `SpriteCanvasMaterial` seems to be part of the `CanvasRenderer` 

Yup!
