### ISSUE TITLE
rotating with respect to screen centre after panning using trackball controls

### ISSUE THREAD

**Issue by Ashajoney** [mrdoob/three.js#9651]
##### Description of the problem 

(This is NOT a help site. Please read the guidelines above before posting.)

##### Three.js version

- [ ] Dev
- [x] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Ashajoney** [comment]
Have you fixed the rotation issues after panning?

**Comment by WestLangley** [comment]
What rotation issues after panning?

**Comment by Ashajoney** [comment]
the model is rotating still with respect to center (renderer-to be clear).

**Comment by WestLangley** [comment]
`TrackballControls` rotates (and pans) the camera, not the model.

**Comment by Ashajoney** [comment]
Thanks a lot for your reply.
I have set noRotate=true; and included some code snippets that supports
rotation from trackball controls in my project and that works cool as
expected.

**Comment by Ashajoney** [comment]
I am beginner to THREE.js.So please bare with me.
I have somehow managed to change the code for rotation  disabling the
rotation of trackball controls using controls.noRotate=true;
The model is rotating but having minor problem(on rotating a model from up
to bottom and from left to right it is not rotating correctly)
I have attached you the code along with this mail .
Kindly go through it and suggest me the way to obtain solution.

-Asha Joney

**Comment by WestLangley** [comment]
Sorry, this is not a help site.
