### ISSUE TITLE
Multiple versions of three.js in single project

### ISSUE THREAD

**Issue by vijnasu** [mrdoob/three.js#9652]
I have legacy three.js project in r71 where I used objmtlLoader to load the objects. Now new objects exported from Rhino directly (or Rhino to Blender & exported) not loading the object to the scene with old code. Several format conversion options were tried. objLoader + mtlLoader separately were also tried. But r71 & r79 editors loads these objects correctly. So can I use r71 version of objLoader & mtlLoader with my legacy r71 code. Are there any examples related related to using code from multiple versions.

(This is NOT a help site. Please read the guidelines above before posting.)

##### Three.js r71 & r79

- [x] Dev
- [ ] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by fraguada** [comment]
If you want to export from rhino, have you tried this: http://www.food4rhino.com/project/iris?etx ?  It creates a json file in the threejs format.

**Comment by vijnasu** [comment]
Iris has been tried and it works fine in isolation. But our project structure is complex. Basically models are in Autodesk Revit which are exported to Revit. Specific requirement is obj+mtl files exported from Rhino are not loaded in r71 objmtlloader included in the customized library. three.js r79 works fine. Upgrading to higher version not possible. So can two versions of three.js co-exist in a single project? How this can be understood with respect to Graphics pipeline? Are there any samples for this?
