### ISSUE TITLE
Renderer auto clearing when background color set in scene

### ISSUE THREAD

**Issue by tentone** [mrdoob/three.js#9653]
Hi

WebGL renderer is auto clearing when there is a background color defined in the Scene object, even if autoClear is set to false.

**Comment by satori99** [comment]
I ran into this issue too when I set a scene background color;

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1209-L1226

It looks like clearing is forced when a background color is set.

I had to work around it by setting all `autoClear*` flags to false

		renderer.autoClear = false
		renderer.autoClearColor = false
		renderer.autoClearDepth = false
		renderer.autoClearStencil = false

Is there as reason for the forced clearing when background is present?

**Comment by mrdoob** [comment]
That's the expected behaviour.

**Comment by WestLangley** [comment]
Why do we support `scene.background` as a color, when `renderer.setClearColor()` is available?

**Comment by mrdoob** [comment]
> Is there as reason for the forced clearing when background is present?

You may want to use the `setClearColor()` approach if you want to control clearing.

> Why do we support `scene.background` as a color, when `renderer.setClearColor()` is available?

I think it's simpler to understand. The `setClearColor()` code path is still there if someone needs it.

**Comment by tentone** [comment]
Sorry my bad wasn't aware of the autoClearColor flag, makes sense.

**Comment by WestLangley** [comment]
>I think it's simpler to understand.

Not to me. `scene.background` as a color and `renderer.setClearColor()` compete with each other.

IMHO, it is confusing to have both.

**Comment by mrdoob** [comment]
> IMHO, it is confusing to have both.

Agreed. The idea it's to "transition" to `scene.background`. Advanced users could use `renderer.setClearColor()` if needed.
