### ISSUE TITLE
Specific LOC errors if camera, camera.isCamera undefined.

### ISSUE THREAD

**Issue by dbeecham** [mrdoob/three.js#9661]
##### Description of the problem 

https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L1121

This line (currently reads: `if ( ( camera && camera.isCamera ) === false ) {`) fails if `camera` or `camera.isCamera` is undefined.

Should probably be something like:
```
if ( camera === undefined || camera.isCamera === undefined || camera.isCamera === false)
```

or
```
if ( ! (camera && camera.isCamera) )
```

##### Three.js version

- [X] Dev
- [X] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Actually, it should be `( camera !== undefined && camera.isCamera !== undefined )`. Nice catch!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Fixed. Thanks!
