### ISSUE TITLE
Suggestion: Better way to update multiple dynamic uniforms

### ISSUE THREAD

**Issue by fallenoak** [mrdoob/three.js#9662]
##### Description of the problem 

I'm curious if there's a better way to handle dynamic uniform updates.

Currently, when using dynamic uniforms, ```onUpdate``` callbacks are defined on each ```THREE.Uniform```. Unfortunately, if there are several uniforms for a given material that need dynamic updates, this means multiple callback executions per render call. Based on Chrome's profiler, I'm a little concerned about how much time is spent in ```evalDynamic()``` in my app.

Would it be acceptable to rework the renderer's handling of render list items a bit, and instead allow an object to define a single callback to update multiple material uniforms?

For example, something like this:

```
var object = new THREE.Mesh();

object.onRender(function(material, camera) {
  material.uniforms.textureWeight.value = this.textureWeights[material.textureWeightIndex];
  material.uniforms.localDiffuseColor.value = this.localDiffuseColor;
  ... etc etc ...
});
```

or flipped around:

```
var material = new THREE.ShaderMaterial();

material.onRender(function(object, camera) {
  this.uniforms.textureWeight.value = object.textureWeights[this.textureWeightIndex];
  this.uniforms.localDiffuseColor.value = object.localDiffuseColor;
  ... etc etc ...
});
```

I'm not sure if the overhead of checking for the presence of an ```onRender``` callback for each object in the scene graph would be more taxing than the cost of calling multiple callbacks per material with dynamic uniforms.

I'm happy to do the work on this, but I'd like a bit of input on whether I'm barking up the wrong tree, or there are other plans to improve uniform handling.

##### Three.js version

- [x] Dev
- [ ] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
I feel that I proposed exactly this in the past also. I would vote for placing it on the `Mesh` (`Object3D`).

**Comment by fallenoak** [comment]
Sounds good!

I can take a look at this later this week. I realize this might break @arose's code again (a la the recent update to include material in the callback params), so apologies about that.

**Comment by mrdoob** [comment]
I found where it was previously suggested:
https://github.com/mrdoob/three.js/pull/7048#issuecomment-185489120

**Comment by mrdoob** [comment]
> I realize this might break @arose's code again (a la the recent update to include material in the callback params)

Actually, it doesn't have to break. I think we can keep both code passes?

**Comment by fallenoak** [comment]
Hmm, true. I was thinking this would supersede dynamic uniforms, but it certainly doesn't have to.

What do we want to name the callback? ```onRender```? ```onWillRender```?

**Comment by mrdoob** [comment]
I think `onRender`...

**Comment by mrdoob** [comment]
Ok. I've added a `onBeforeRender` callback to start. WebGLUniforms need some refactoring but this works:

```js
var gl = renderer.getContext();

function onBeforeRender() {

	if ( this.material.program ) {

		this.material.program.getUniforms().map.diffuse.setValue( gl, this.userData.color );

	}

}

object.onBeforeRender = onBeforeRender;
```

**Comment by fallenoak** [comment]
Just to confirm, in the above example, if I'm using ```MultiMaterial```, I'll need to iterate over every element in ```this.material.materials``` from inside the ```onBeforeRender``` context, right?

**Comment by mrdoob** [comment]
In this first implementation, yes. We can improve things on the next cycle.

**Comment by fallenoak** [comment]
Sounds good!

**Comment by arose** [comment]
This seems much more elegant.

Was something like `this.material.program.getUniforms().map.diffuse.setValue( gl, this.userData.color );` even possible we implemented dynamic uniforms initially?

**Comment by mrdoob** [comment]
> Was something like `this.material.program.getUniforms().map.diffuse.setValue( gl, this.userData.color );` even possible we implemented dynamic uniforms initially?

Not sure...

**Comment by mrdoob** [comment]
@tschw FYI, I'll be changing `WebGLProgram` and `WebGLUniforms` so the API looks more like this:

```js
this.material.program.getUniform( 'diffuse' ).setValue( this.userData.color );
```

**Comment by pailhead** [comment]
Not to offend anyone, but the dynamic uniforms are what spawned this?

Can we at least add on `onHasRendererd` too? There are sooooooooo many other things that can be done with this, mainly via `gl` call injection. For example one is working with the stencil buffer which wasnt supported at r75 or so when i left fiddling with this.

**Comment by pailhead** [comment]
TL:DR :)

> I found where it was previously suggested: #7048 (comment)

https://github.com/mrdoob/three.js/pull/7806

> I realize this might break @arose's code again

The dynamic uniform becomes somewhat redundant:

```
var sharedMat = new THREE.ShaderMaterial();

var myMesh = new THREE.Mesh( geom , sharedMat );

myMesh.onWillRender = function(){
     this.material.uniforms.myUniform.value = this.customData; 
}.bind(myMesh);
```

**Comment by pailhead** [comment]
> Based on Chrome's profiler, I'm a little concerned about how much time is spent in evalDynamic() in my app.

>You really don't want to use the bind method in performance-sensitive library code: It's a whole lot slower than using a function with an upvalue, where "a whole lot" refers to a browser-dependent ~100 - ~7000% time overhead per call.

See https://jsperf.com/bind-vs-emulate/41 and earlier revisions.

**Comment by fallenoak** [comment]
I'm in favor of adding a companion `onAfterRender` callback, re: @pailhead above.

As an aside, even though it's a bit ambiguous, I think I prefer the semantics of `onBeforeRender` and `onAfterRender`, as opposed to `onWillRender` and `onHasRendered`. In the end, I don't think `onWillRender` or `onHasRendered` are any clearer about the immediacy of the draw call relative to the callback. A bit of documentation would probably clear that right up.

To briefly dip into what @pailhead proposed, would something like this be acceptable as an enhancement / replacement to the way the `onBeforeRender` callback is currently implemented?

```
if ( object.onBeforeRender !== null ) object.onBeforeRender( group, geometry, material, camera, _gl, _this );

_this.renderBufferDirect( camera, fog, geometry, material, object, group );

if ( object.onAfterRender !== null) object.onAfterRender( group, geometry, material, camera, _gl, _this );
```

I know I'd immensely prefer getting the specific material being rendered as part of the callback, rather than having to constantly iterate across all materials in a `MultiMaterial`.

**Comment by pailhead** [comment]
It's really a one liner with no bind/call calls in the render loop within the game loop. 

Here's another attempt. I disagree with the semantics, but since you've already done the `before` here's an after...

I've also added some useful arguments that one might need, 

https://github.com/mrdoob/three.js/pull/9738

@mrdoob

**Comment by pailhead** [comment]
To reiterate, "dynamic uniforms" become obsolete. They now become a problem of timing the update. Uniforms are always dynamic because it's pretty much the only thing one should update in the shader (minus some attributes some times, and instanced attributes?). 

So instead of having a **complicated** system all over the place in the renderer, the checks, the `evalDynamic` with it's bind/apply/call calls that happen per every object in the scenegraph in every frame, you use these simple 2 lines to just time these uniform updates whenever you want.

A dynamic uniform for one user would change `onButtonPressed()` for example, for another would be `onWindowResized()`, yet for others `onWillRenderObject()`. In either case, what are those uniforms if not "dynamic".

**Comment by mrdoob** [comment]
@arose could you update `webgl_interactive_instances_gpu` using the `onBeforeRender()` approach?

**Comment by arose** [comment]
> could you update webgl_interactive_instances_gpu using the onBeforeRender() approach?

yes, will do.

**Comment by mrdoob** [comment]
#9738

**Comment by arose** [comment]
I am trying to update webgl_interactive_instances_gpu using the onBeforeRender() approach.

First, it is not as simple as `material.uniforms.color.value.setHex( object.userData.color )`. This does not work because updating the material uniforms is behind the `refreshMaterial` flag in `setProgram` which is `false` when the material has not changed.

I tried setting the WebGLUniforms directly with `material.program.getUniforms().setValue( gl, "color", object.userData.color )`. Apart from GPU picking this seems to work but gives the error "WebGL: INVALID_OPERATION: uniform3fv: location is not from current program". Note that I also had to make `gl` and `object` available to the `onBeforeRender` callback.

Open to any suggestions. Here is the branch with what I have so far https://github.com/arose/three.js/commit/6d62c64fd78cf5b6bf6a67433d5f531349fa6e93.

**Comment by mrdoob** [comment]
> Note that I also had to make `gl` and `object` available to the `onBeforeRender` callback.

You can do `var gl = renderer.getContext();` inside the callback.

**Comment by pailhead** [comment]
> You can do var gl = renderer.getContext(); inside the callback.

We should test the performance of this somehow, might be better to cache gl yourself somewhere outside the callback, or pass the cached one from the renderer?

**Comment by arose** [comment]
> You can do var gl = renderer.getContext(); inside the callback.

done https://github.com/arose/three.js/commit/2c9700ddd31c65134dc3089f908ab485580a6ac6

**Comment by pailhead** [comment]
> I tried setting the WebGLUniforms directly with material.program.getUniforms().setValue( gl, "color", object.userData.color ). Apart from GPU picking this seems to work but gives the error "WebGL: INVALID_OPERATION: uniform3fv: location is not from current program". Note that I also had to make gl and object available to the onBeforeRender callback.

Ungh, this seems like a problem, it defeats the purpose if you need to set uniforms through a low level gl call. Managing those pointers and stuff can get gnarly.

**Comment by fallenoak** [comment]
I've finally had a chance to give onBeforeRender a whirl in the project I'm working on, and as @arose and @pailhead pointed out above, it's indeed rather ugly to manipulate uniforms from the callback as is.

@mrdoob Do we want to continue the discussion about working around `refreshMaterial` in this issue, or should we do that in another issue?
