### ISSUE TITLE
ThreeJS lines sometimes not appearing

### ISSUE THREAD

**Issue by gaby64** [mrdoob/three.js#9664]
http://stackoverflow.com/questions/39430559/threejs-lines-sometimes-not-appearing

##### Three.js version  
- [X] r76  

##### Browser  
- [x] Chrome
- [X] Firefox  

##### OS  
- [X] Windows

**Comment by gaby64** [comment]
it is a bug, lines appear 100% of the time in r57

**Comment by mrdoob** [comment]
Please, follow the guidelines for reporting a bug.

https://github.com/mrdoob/three.js/blob/dev/.github/CONTRIBUTING.md
