### ISSUE TITLE
lines sometimes not appearing

### ISSUE THREAD

**Issue by gaby64** [mrdoob/three.js#9668]
im trying to create a polyline sketcher, the lines sometimes do not appear, altho they are verifyably present. 

I built a test case, https://jsfiddle.net/52p3d0b0/
Just click around in the grey area, lines should be uninterupted

![Imgur](http://i.imgur.com/sfv967h.jpg)

Its even worse in the CAD application im trying to develop, the lines do not appear most of the time.

It worked fine in r57

##### Three.js version
- [X] r80

##### Browser
- [x] All of them

##### OS
- [X] Windows

**Comment by WestLangley** [comment]
This is not a help site. Use `stackoverflow` or another resource if you need help.

With all respect, it does not appear from looking at your fiddle that you really understand what you are doing.

Also, the following is not a valid construct in three.js; you can't reassign the vertices array -- you can only change the values of an existing array.
```javascript
mesh.geometry.vertices = geo.vertices; // not valid in r.80
```

This should be a helpful to you: http://stackoverflow.com/questions/31399856/drawing-a-line-with-three-js-dynamically/31411794#31411794.

**Comment by gaby64** [comment]
i have changed it, even tho it worked, im still getting lines that do not appear

**Comment by gaby64** [comment]
ok, so removing the path and just creating a geometry worked
im not sure how that was affecting how lines would not appear
