### ISSUE TITLE
AnimationClip nodeName

### ISSUE THREAD

**Issue by Milewski** [mrdoob/three.js#9669]
why do i need to set a nodeName? if the same doesn't seen to be used anywhere?... it just keeps making my ide complaining i am missing arguments...

[https://github.com/mrdoob/three.js/blob/7714fe8f6dec8fd3ecfa0266c2c4a8ef0e9f61c7/src/animation/AnimationClip.js#L238](https://github.com/mrdoob/three.js/blob/7714fe8f6dec8fd3ecfa0266c2c4a8ef0e9f61c7/src/animation/AnimationClip.js#L238)

**Comment by tschw** [comment]
I don't think I have added it, so I really have no clue what it used to be for. Since it's not referenced anywhere, I guess it'd be best to just remove it.

**Comment by mrdoob** [comment]
Fixed. Thanks!
