### ISSUE TITLE
VideoTexture toJson and parseVideoTextures missing

### ISSUE THREAD

**Issue by Amritesh** [mrdoob/three.js#9670]
##### Description of the problem 

Why is there no videoTexture toJson imlpemented. Saving state of a videoTexture saves it as Texture with an image and not VideoTexture with video. This happens because videoTexture inherits its toJson from Texture.

Also there is no support for parsing videoTexture and saving video tags. Is the video saving feature under development or are we have to stop using videoTexture and use Texture with render loop to drawImage.

##### Three.js version

- [ x] Dev
- [ x] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Amritesh** [comment]
I just found that @tentone  is working on it and his code is to be merged.
https://github.com/mrdoob/three.js/pull/9659/commits/90bfb4941522d2db52ef679463fae208a1593fcd

I am closing the issue.

**Comment by tentone** [comment]
@Amritesh I don't know if that PR even has a chance to be merge into threejs since it still requires some changes to be made, there are still some decisions that need to be taken, and i would like to get some opinions on the actual code.

If i conclude that the PR is not going to be merged i can open a new one just for VideoTexture serialization.

**Comment by Amritesh** [comment]
@tentone I pulled your commit and was trying to build three.js from it for testing.  I am getting
Error: Duplicated import 'Audio'
    at C:\Users\amrit\Desktop\Code\three.js\node_modules\rollup\src\Module.js:169:17
Also there seems to be some issue specific to import statements which I resolved by changing "/" to "\\" on my windows machine.

I am reopening the issue as it is a required feature.

**Comment by Amritesh** [comment]
Closing the thread due to inactivity. Will have to wait for full video support as texture for 3d objects.

**Comment by cortecag** [comment]
Hello,
I'm having the same problem. Has there been a fix or some kind of workaround for this?
