### ISSUE TITLE
Error: cannot parse trackName at all

### ISSUE THREAD

**Issue by bakajin** [mrdoob/three.js#9671]
When parsing (keyframe) animation from a JSON file using the mixer.clipAction method the console produces the following error:

three.min.js?ver=4.5.4:712 Uncaught Error: cannot parse trackName at all: scene:helium_balloon_model:helium_balloon_model.position

The code I am using is:

```
bgLoader.load( themePath + '/assets/balloon-grid.json', function ( object ) {
object.traverse( function ( child ) {
    switch(child.name) {
        case "dae_scene:helium_balloon_model:helium_balloon_model":
                                //do anim
                                console.log(object.animations[0]);
                                animationClips.balloon1 = object.animations[0];
                               
                                animationMixer = new THREE.AnimationMixer( child );

                                var sceneAnimation = animationMixer.clipAction(animationClips.balloon1);
                                      sceneAnimation.play();
        break;
    }
}
}, onProgress, onError );
```

- [x] Dev
- [x] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by bakajin** [comment]
Ok I seem to have figured out where it goes awry:

The blender JSON script writes, correctly in my opinion:

```
"animations":[{
        "fps":30,
        "tracks":[{
            "type":"vector3",
            "name":"scene:helium_balloon_model:helium_balloon_model.position",
            "keys":[{
                "value":[-0.598893,11.0205,252.778],
                "time":1.99999
            },

```
The name string holds the object hierarchy. The regex trips up on this hierarchy. So when edit it to state only:

`helium_balloon_model.position`

It works. I would like to add that keyframe blending seems to be very different from what you see in blender, or softimage (in my case). So I guess I just gave myself more work to do :).

Also the script exports empty key sets for all the objects in the scene, which trips up the loader. I would say empty keys are just empty keys and should not produce errors that stop parsing.

Have a nice day

O

**Comment by takahirox** [comment]
// PropertyBinding.parseTrackName
    var re = /^((?:\w+\/)*)(\w+)?(?:\.(\w+)(?:\[(.+)\])?)?\.(\w+)(?:\[(.+)\])?$/;

Maybe we should replace `\w` with `[\w:]`?

    var re = /^((?:[\w:]+\/)*)([\w:]+)?(?:\.([\w:]+)(?:\[(.+)\])?)?\.([\w:]+)(?:\[(.+)\])?$/;

**Comment by takahirox** [comment]
// PropertyBinding.parseTrackName
    var re = /^((?:\w+\/)*)(\w+)?(?:\.(\w+)(?:\[(.+)\])?)?\.(\w+)(?:\[(.+)\])?$/;

Maybe we should replace the delimiter `\/` with  `[\/:]`?

    var re = /^((?:\w+[\/:])*)(\w+)?(?:\.(\w+)(?:\[(.+)\])?)?\.(\w+)(?:\[(.+)\])?$/;

The results of `scene:helium_balloon_model:helium_balloon_model.position` will be

    var re = /^((?:\w+\/)*)(\w+)?(?:\.(\w+)(?:\[(.+)\])?)?\.(\w+)(?:\[(.+)\])?$/;    // old one
    re.exec( 'scene:helium_balloon_model:helium_balloon_model.position' );
    -> null

    var re = /^((?:\w+[\/:])*)(\w+)?(?:\.(\w+)(?:\[(.+)\])?)?\.(\w+)(?:\[(.+)\])?$/;    // new one
    re.exec( 'scene:helium_balloon_model:helium_balloon_model.position' );
    -> ["scene:helium_balloon_model:helium_balloon_model.position", "scene:helium_balloon_model:", "helium_balloon_model", undefined, undefined, "position", undefined]

**Comment by mrdoob** [comment]
Modifying the regex sounds good to me 👍

**Comment by takahirox** [comment]
ok

@bakajin

Just in case, would you check if this change works for you on the latest `dev` branch?

Replace this line in `PropertyBinding.parseTrackName`

    var re = /^((?:\w+\/)*)(\w+)?(?:\.(\w+)(?:\[(.+)\])?)?\.(\w+)(?:\[(.+)\])?$/;

with

    var re = /^((?:\w+[\/:])*)(\w+)?(?:\.(\w+)(?:\[(.+)\])?)?\.(\w+)(?:\[(.+)\])?$/;

Once you confirm, I'll make a PR.

**Comment by bakajin** [comment]
ok
@takahirox , shimashoo

Sounds like a good suggestion. And you 're in luck I just exported a new version (where I havent cut out the hierarchy path by hand).

Look forward to less hand editing. Maybe I should also bug report the empty key array problem :).

I will let you know if it works,

Thanks

**Comment by bakajin** [comment]
@takahirox arigatoo gozaimasu!

Works a treat, perfect let's PR.

Great work

**Comment by takahirox** [comment]
Thanks arigato~

**Comment by tschw** [comment]
@takahirox 
Thanks for taking care of it.

I still hope one of us will eventually find the time to factor the intelligence out of that regex and into the surrounding code. The simplified regex would then be executed in a loop to just parse the path into segments. Whatever special cases might exist could be coded out in JavaScript, rearranging segmented paths and - happy, happy, joy, joy - we'd probably arrive at a more easily maintainable solution :).
