### ISSUE TITLE
FBX in examples download

### ISSUE THREAD

**Issue by Fit2Page** [mrdoob/three.js#9673]
##### Description of the problem 

The FBX files in the examples download ZIP on the website differ from the ones used on your website.

##### Three.js version

- [ ] Dev
- [x ] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
These? https://github.com/mrdoob/three.js/tree/dev/examples/models/fbx
