### ISSUE TITLE
Raycasting a sprite uses local scale, not world scale

### ISSUE THREAD

**Issue by sbgeorge** [mrdoob/three.js#9677]
Raycasting child sprites of an object does not work. For example, if you have a sprite with a scale of (10, 10, 1), and child sprites of scale (1, 1, 1), the calculation for approximating their size in the raycast() function uses the local scale (1, 1, 1) rather than parent \* local scale. All you'd have to do to fix this is to do `var matrixScale = THREE.Vector3().setFromMatrixScale(this.worldMatrix)` and then use `var guessSizeSq = matrixScale.x * matrixScale .y / 4` rather than `var guessSizeSq = this.scale.x * this.scale.y / 4`.

**Comment by WestLangley** [comment]
Thanks for the tip. `Points.raycast()` may have the same problem.
```javascript
var localThreshold = threshold / ( ( this.scale.x + this.scale.y + this.scale.z ) / 3 );
```
