### ISSUE TITLE
Textures blurred on iPad

### ISSUE THREAD

**Issue by nagegerg** [mrdoob/three.js#9686]
##### Description of the problem 

Repeating textures that render beautifully with desktop browsers appear blurred and full of artifacts on the iPad.  An example, including a screenshot of the same scene rendered on the iPad, is here:  [Texture Test](http://gregegan.customer.netspace.net.au/tmp/TextureTest.html).

This three.js [anisotropy demo page](http://threejs.org/examples/webgl_materials_texture_anisotropy.html) also renders perfectly on my desktop browser but is blurred on my iPad.

The code running on the iPad claims to be rendering at an anisotropy of 16, so it's not something simple like iOS WebGL not supporting a high enough anisotropy.

##### Three.js version

- [x] 78

##### Browser

- [x] Safari

##### OS

- [x] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

iPad 4

**Comment by Need4Speed402** [comment]
Devices like the iPad have resolution scaling, I think it is a scale of 2 so there are 4 pixels for every pixel that the device "says" it has. What you want to do is render at native resolution by getting your regular ```window.clientWidth``` and multiply that by ```window.devicePixelRatio```. Note that I do not have an iPad but I do have a Macbook Pro which does have this resolution scaling.

**Comment by nagegerg** [comment]
@Need4Speed402 My test code, and the three.js anisotropy demo, are already rendering at native resolution by calling `renderer.setPixelRatio(window.devicePixelRatio)` so that isn't the issue.  But I will seek help on Stackoverflow.
