### ISSUE TITLE
rotation.reorder("YXZ")

### ISSUE THREAD

**Issue by HazemSamir** [mrdoob/three.js#9693]
`examples/js/controls/DeviceOrientationControls.js` has this [line](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/DeviceOrientationControls.js#L13)

```
this.object.rotation.reorder( "YXZ" );
```

In a 360 video player, I am recording camera.rotation angles(x->pitch, y->yaw, z->roll), without this line the values of them seem weird (not just the values are swapped like if the x->roll and z->pitch), when I apply this reorder(in MouseControls and VRControls), they become more sensible.

So what does this line really do? and why other controllers does not have it?

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [x] Android
- [ ] IOS

**Comment by HazemSamir** [comment]
Well, it seems that this question belongs more to stackoverflow, I will better move my question to it.

**Comment by WestLangley** [comment]
The device uses a different coordinate system than three.js does -- Z is up for the device; Y is up for three.js.

Study the [link](http://w3c.github.io/deviceorientation/spec-source-orientation.html) referenced in `DeviceOrientationControls.js`, in conjunction with the source code itself.

You will need to familiarize yourself with intrinsic Tait-Bryan representations to understand what is going on.
