### ISSUE TITLE
Raycasting in MultiMaterial ignores THREE.DoubleSide setting in sub materials array

### ISSUE THREAD

**Issue by cybafelo** [mrdoob/three.js#9694]
##### Description of the problem 

OK so here goes - 

When I have a multi material - and I set the side of its child material to THREE.DoubleSide - this value is ignored in raycasting.

I created an example fiddle:

http://jsfiddle.net/hw9rcLL8/96/

If you click on the mesh, it should change color. if you click on an invisible area, it shouldnt.

When you set the MeshPhongMaterial.side to THREE.DoubleSide, you can click on the visible yet inverted faces and the mesh will not change color, but it should.

If you then change MultiMaterial.side also to THREE.DoubleSide, then it works as expected.

- Ok, so I have an update - 

Worse, when I do set MultiMaterial.side to THREE.DoubleSide, and my MeshPhongMaterial.side to THREE.FrontSide, I can select the mesh by clicking on the inverted faces.

Anyways - this behavior for MultiMaterial is strange and I think it could be considered 'buggy'

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
The ray is intersecting both the front and back sides of the sphere, making your example confusing.

Be careful when you flip the winding order of faces without correcting the normals, too. Faces can render black. Use `MeshBasicMaterial`, instead.

Simpler fiddle: http://jsfiddle.net/hw9rcLL8/97/

It does appear that `Raycaster` does not honor sided-ness of the materials in the `Multimaterial` array -- but I have not studied it carefully.

Would someone be willing to investigate this?

>Worse, when I do set MultiMaterial.side to THREE.DoubleSide

`MultiMaterial` does not have a `side` property

**Comment by cybafelo** [comment]
Thanks for letting me know about flipping the normals too! :)

I saw later and you are right, the MultiMaterial does not have a DoubleSide option, so setting it should have no effect, but it does, and this is at least one part of the problem, and you are also right about raycaster not respecting the sidedness  of the submaterials.. 

The inverted faces is there so you can see what happens when you shoot a ray through a submaterial, with option DoubleSide and option FrontSide, through the inverted faces.. :) they should pass through the hole and not cause a collision when the submaterial is front side, which is correct sometimes, depening in setting the property which should not exist on MultiMaterial.. and then, with DoubleSide on submaterial it should hit on all faces, but it does not, it still passes through he hole (which is not visible).. :) interesting problem! :)

**Comment by mrdoob** [comment]
Raycaster doesn't support MultiMaterial.
