### ISSUE TITLE
GLTFLoader.js doesn't define bumpMap when loading the material. 

### ISSUE THREAD

**Issue by tiagocardoso** [mrdoob/three.js#9700]
##### Description of the problem 
On the loader, with dealing with materials, the "bump" value isn't used (it is there on glTF files).
It works very similar to the material map :
_material.map = library.textures[ values.diffuse ];

Maybe this would be enough:

if ( typeof( values.bump ) === 'string' ) {
  _material.bumMap = library.textures[ values.bump ];
}

This would load a texture as bumpMap.

:)

##### Three.js version

- [x] Dev
- [ ] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Would you like to do a PR with the fix?

**Comment by tiagocardoso** [comment]
I'll do a PR today or tomorrow. Thanks!
