### ISSUE TITLE
Vive examples doesn't work correctly with WebVR API 1.1

### ISSUE THREAD

**Issue by arturitu** [mrdoob/three.js#9708]
[Vive examples](http://threejs.org/examples/webvr_vive.html) doesn't render correctly with 17 Sept Chromium (API 1.1) but render well with 29 Aug version (API 1.0), the image looks with an incorrect IPD or with some problem with the matrix to render the image for each eye. Is perhaps a bug on VREffect?

##### Three.js version

- [x] r81

##### Browser

- [x] 17 Sept WebVR Chromium

##### Hardware Requirements (graphics card, VR Device, ...)

HTC Vive

**Comment by jzitelli** [comment]
I think there is a bug in how `VREffect.js` is calculating the left / right camera world matrices using the new code path which uses the view matrices provided by vrDisplay.getFrameData.  I commented out these lines in `getHeadToEyeMatrices` and it looks fixed to me:

`// headToEyeMatrixL.getInverse( headToEyeMatrixL );`
`// headToEyeMatrixR.getInverse( headToEyeMatrixR );`

**Comment by toji** [comment]
What code are you testing with and what's the exact effect that you're seeing. After some additional testing I realized that the view matricies get screwed up in http://threejs.org/examples/webvr_vive.html as you look up or down, but looking in any direction horizontally seemed fine to me. Is that the effect you're seeing as well or is it something different?

**Comment by toji** [comment]
Also the non-standing demos seem OK to me? Are you seeing problems with http://threejs.org/examples/webvr_cubes.html?

**Comment by arturitu** [comment]
I'm testing the published examples on threejs.org. And yes, the non-standing demos seem OK to me. In the standing demos is like the objects are very close and I can not focus properly, it is as if I saw double.

**Comment by arturitu** [comment]
And as @jzitelli said if I comment these two lines on VREffect my standing project works ok.

**Comment by toji** [comment]
Okay, playing around with it tonight. (Matrix math is hard, yo.)

To be honest the split between VRControl and VREffect isn't a great fit for the new spec, but I really don't want to have everyone redo their Three.js apps so we'll find a way to make it work.

**Comment by arturitu** [comment]
If comment these two lines, as @jzitelli said, looks better but as you said if you look up or down seems to be wrong.

**Comment by arturitu** [comment]
Thanks @toji & good luck with Matrix tonight.
