### ISSUE TITLE
antialias not work on Pad(Ios) ?

### ISSUE THREAD

**Issue by mustbeyouqq** [mrdoob/three.js#9710]
I hava test r79 and newest r81, antialias not work。is there someway to make it work, thanks.

there is a test, r69 antialias work fine on ios: [http://1007650105.github.io/html5dev/app/test/three-compatibility-test/#72](url)

**Comment by makc** [comment]
I do not think antialiasing ever worked on ios, and I don't think your problem is antialiasing.

Most likely you are missing
> renderer.setPixelRatio (window.devicePixelRatio);
