### ISSUE TITLE
BufferGeometry. computeBoundingSphere not working with InterleavedBufferAttribute

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#9711]
##### Description of the problem

I've discovered a problem with our example [webgl_buffergeometry_points_interleaved.html](http://threejs.org/examples/#webgl_buffergeometry_points_interleaved). Calling `computeBoundingSphere` on a `BufferGeometry` that contains `InterleavedBufferAttribute` can lead to a runtime error if multiple values (e.g. positions and colors) are stored in the same buffer. 

Instead of doing this in `computeBoundingSphere`

``` javascript
var array = positions.array;

for ( var i = 0, il = array.length; i < il; i += 3 ) {

   vector.fromArray( array, i );
   maxRadiusSq = Math.max( maxRadiusSq, center.distanceToSquared( vector ) );

}
```

i was able to solve the runtime error with:

``` javascript
for ( var i = 0, il = positions.count; i < il; i ++ ) {

   vector.x = positions.getX( i );
   vector.y = positions.getY( i );
   vector.z = positions.getZ( i );
   maxRadiusSq = Math.max( maxRadiusSq, center.distanceToSquared( vector ) );

}
```

But then i realized that there are more problematic parts in `BufferGeometry` e.g.

https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L586
https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L622

I think all this code is not compatible with `InterleavedBufferAttribute` because it's wrong to directly access the array data in the attribute. You need to work with a `stride` and `offset` value instead.
##### Three.js version
- [x] Dev
- [x] r80
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
Oh, there is already a PR for this: #9242

**Comment by mrdoob** [comment]
It has conflicts though.

**Comment by Mugen87** [comment]
What kind of?

**Comment by mrdoob** [comment]
![screen shot 2016-12-06 at 12 56 32](https://cloud.githubusercontent.com/assets/97088/20943255/83e7f7a4-bbb3-11e6-94a5-aed27ba58aac.png)

**Comment by Mugen87** [comment]
Oh sry, i've misunderstood you...

I thought there were problems with my recent PR. Indeed #9242 has many conflict and is somewhat obsolete now. 

Well, maybe it's better when i go to bed now 😉 . It was a long day...
