### ISSUE TITLE
PointLight clone castShadow = false;

### ISSUE THREAD

**Issue by mattlockyer** [mrdoob/three.js#9712]
##### Description of the problem 
I seem to have encountered an issue when cloning PointLight, castShadow was reset to false in the cloned light... quite vexing.

##### Three.js version

- [ ] r80

##### Browser

- [ ] Chrome

##### OS

- [ ] ChromeOS

**Comment by mrdoob** [comment]
Hmm, can you create a jsfiddle?

**Comment by mattlockyer** [comment]
Apologies... must have been somewhere else in my code, I was using a later version but I don't think the point lights changed.

Proven false here: https://jsfiddle.net/5zh9v3y5/

**Comment by mrdoob** [comment]
Well, this was kinda vexing...

**Comment by mattlockyer** [comment]
again, my apologies, dealing with a large code base!

**Comment by mattlockyer** [comment]
BTW you should be very proud this library is an incredible resource and tremendously well organized...
