### ISSUE TITLE
Faster Vector3.projectOnPlane function

### ISSUE THREAD

**Issue by loldrup** [mrdoob/three.js#9713]
##### Description of the problem 

It is possible to remove a vector allocation, a closure and a function call (to 'projectOnVector') from the current Vector3.projectOnPlane implementation by implementing it like this:

```
THREE.Vector3.prototype.projectOnPlane = function ( v ) {

	var x = v.x, y = v.y, z = v.z;

	var this_rejected = this.sub( v.multiplyScalar( this.dot(v) / v.lengthSq() ) );

	v.x = x; v.y = y; v.z = z;

	return this_rejected;

};
```

The current implementation looks like this
```
	projectOnPlane: function () {

		var v1;

		return function projectOnPlane( planeNormal ) {

			if ( v1 === undefined ) v1 = new Vector3();

			v1.copy( this ).projectOnVector( planeNormal );

			return this.sub( v1 );

		};

	}()
```

so basically the trick is to reuse the argument vector as a temporary storage for calculations. Given that JavaScript is single threaded, this shouldn't cause problems.

##### Three.js version

- [x] Dev
- [x] r80

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by makc** [comment]
but where is the allocation that you want to remove?
> if ( v1 === undefined ) v1 = new Vector3();

this? this happens just once in the entire run time

**Comment by loldrup** [comment]
true, the allocation is rather negligible.
but it is still accessed through a closure at every call, which impacts performance.

**Comment by loldrup** [comment]
Sorry for having wasted your time. My implementation seems to have *worse* performance than the current one. My guess for a reason would be that I allocate three extra local variables on each call, while the existing implementation just reuses the closured Vector3.

numbers are in miliseconds for 10.000.000 loop rounds:

current   proposed   baseLine
556	       537	         371
502	       534	         369
510	       541	         380
520	       530	         371
506	       536	         379
2594	       2678         1870
