### ISSUE TITLE
THREE.Geometry not copying morphNormals & morphTargets

### ISSUE THREAD

**Issue by wavesoft** [mrdoob/three.js#9714]
##### Description of the problem

Hi All. I am not sure if this is really a bug (or there is another API for cloning geometries with animation), but the default copy operator of `THREE.Geometry` is not copying `morphNormals` / `morphTargets` arrays.

(I can create a PR with a fix if that's indeed a bug)
##### Three.js version
- [x] Dev
- [x] r80
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

None

**Comment by Mugen87** [comment]
Solved with #10514
