### ISSUE TITLE
color.setHex() apply new Hex color onto recent color and mixes them. 

### ISSUE THREAD

**Issue by brknblgc** [mrdoob/three.js#9715]
as said in the title. It mixes two colors. So new color becames different than setHex() value. I made a [JsFiddle](http://jsfiddle.net/L825x65y/20)

##### Three.js version

- [ ] Dev
- [x] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

#####

**Comment by WestLangley** [comment]
As stated in [this](http://stackoverflow.com/questions/39440760/change-color-of-one-face-of-the-cube-three-js/39441082#39441082) stackoverflow post:

>The rendered face color will be the specified face color tinted by the material color.

Typically, you will want to set the material color to white, the default, if you are specifying face colors.
