### ISSUE TITLE
Doublesided material not working in loaded .JSON object (exported from Clara.io)

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#9718]
##### Description of the problem 

I created a simple model in 3ds max of a cube with one side removed - I also tested this with splitting the remaining sides of the cube into 5 separate planes. Next I applied a basic 2-sided material, exported as .FBX, imported to Clara.io and exported as scene.JSON

The scene loads fine in three, using the THREE.ObjectLoader. However the missing side of the cube is still rendered. If I set the Override material like so:

```js
    scene.overrideMaterial = new THREE.MeshPhongMaterial({
      color: 0xffffff,
      side: THREE.DoubleSide,
    });
```
Then the missing side is no longer displayed, as desired. 

I've simplified the material in scene.JSON to

```js 
    "materials": [{
        "color": 16777215,
        "side": 2,
        "uuid": "DE5349E2-C1CF-3B92-9FC5-C470BE798EE9",
        "type": "MeshPhongMaterial",
        "name": "PlaceholderMat"
    }],
```

Logging my override material and the material created from scene.JSON by THREE.MaterialLoader, the only difference I can see are the following on my override material:

```bash
__webglShader:Object
    fragmentShader:"#define REST OF SHADER CODE..."
    name:"MeshPhongMaterial"
    uniforms:Object
   vertexShader:"#define REST OF SHADER CODE..."
_listeners:
    dispose: Array[1]
```

While the loaded material does not have properties ```__webglShader``` or ```_listeners``` at all.

Additionally the loaded material has ```_needsUpdate: true``` while the my override material has ```_needsUpdate: false```

##### Three.js version
- [x ] r81

##### Browser
- [x] All of them

##### OS
- [x ] Windows

**Comment by mrdoob** [comment]
Can you create a jsfiddle?

**Comment by looeee** [comment]
I went ahead and created a situation as similar as possible to my setup on codepen, and of course it works now. Oh well. 
The codepen is [here ](http://codepen.io/looeee/pen/dpNYPm?editors=0010)for posterity, but you can go ahead and close this. Thanks.
