### ISSUE TITLE
[TransformControls] Call to quternion.copy in line 1097 will cause order undefined warning

### ISSUE THREAD

**Issue by killroy42** [mrdoob/three.js#9722]
##### Description of the problem 

At [TransformControls.js line 1097](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/TransformControls.js#L1097) a call to object.qaternion.copy will cause a warning due to an uninitialized Euler._order value.

EDIT: Narrowed down issue to TransformControls.js

##### Three.js version

- [ x] r81

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
Can you provide a fiddle to replicate the warning?

**Comment by killroy42** [comment]
Haven't fiddled in ages, will try. But you can look at those two lines and it's pretty straight forward :)

**Comment by killroy42** [comment]
While working on fiddle I noticed that Object3D.js calls quaternion.onChange( onQuaternionChange ); while there is no onChange on the quaternion, only onChangeCallback. I'm not familiar enough to know if this is the culprit...

**Comment by killroy42** [comment]
Digging further, Euler.setFromRotationMatrix does `order = order || this._order;` Which I suspect interacts negatively with TransformControls, since a naive call to Object3D.quaternion.copy() did not offer up the warning.... digging further.

**Comment by killroy42** [comment]
Ultimately tracked it down to my misunderstanding of destructuring and default values:
func({..., rotation} = defaults) did NOT in fact fill in a valid default for the Euler angle if "rotation" was missing from the original argument. The missing Euler resulted in a badly initialised Euler down the line with an _oder value of undefined. And `transform.rotation.copy(rotation || new Euler());` hid the error.
Perhaps a `new Euler()` should set the default for _order?

Feel free to close this for now.

**Comment by mrdoob** [comment]
> Perhaps a `new Euler()` should set the default for _order?

Uh?

**Comment by killroy42** [comment]
Never mind me. It already does: this._order = order || Euler.DefaultOrder;

Sorry, I guess I've been looking at this stuff for too long (and abusing dat.Gui as property inspector too much)
