### ISSUE TITLE
Latest WebVR Chromium broke ViveController

### ISSUE THREAD

**Issue by mflux** [mrdoob/three.js#9723]
##### Description of the problem 

Running the latest Chromium + THREE.ViveController will script error:

    Uncaught TypeError: Cannot read property 'position' of undefined
        at THREE.ViveController.update (three-vr-viewer.js:1172)
        at animate (three-vr-viewer.js:135)

This is because https://github.com/mrdoob/three.js/blob/dev/examples/js/ViveController.js#L64

Needs to check against undefined instead of null now. Not sure if this is due to @toji's change.

The corrected code on L64 should be

          if ( gamepad !== undefined && !gamepad.pose ) {

Where gamepad.pose is undefined when the flag isn't on, and gamepad.pose is null when no controller is available.

This will allow THREE to continue running despite there being controllers (and not visible because flag is not turned on).

##### Three.js version

- [x] Dev
- [ ] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
VR device with controllers.

**Comment by mrdoob** [comment]
Ok, I think this should be now fixed.

**Comment by mrdoob** [comment]
Thanks for reporting!
