### ISSUE TITLE
Suggestion: prevent confusing warning of paramThreeToGL of WebGLRenderer

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#9724]
##### Description of the problem 

When I use `UnsignedInt248Type(gl.UNSIGNED_INT_24_8_WEBGL)` on my browser which doesn't support `WEBGL_compressed_texture_pvrtc` extension, console shows this warning

    THREE.WebGLRenderer: WEBGL_compressed_texture_pvrtc extension not supported.

This warning is very confusing because `WEBGL_compressed_texture_pvrtc` isn't required for `UNSIGNED_INT_24_8_WEBGL`.

The root issue is here 

https://github.com/mrdoob/three.js/blob/7407b0e43609ce41ec271fea1624935c3dc04d59/src/renderers/WebGLRenderer.js#L2795-L2804

    extension = extensions.get( 'WEBGL_compressed_texture_pvrtc' );

    if ( extension !== null ) {

        if ( p === RGB_PVRTC_4BPPV1_Format ) return extension.COMPRESSED_RGB_PVRTC_4BPPV1_IMG;
        if ( p === RGB_PVRTC_2BPPV1_Format ) return extension.COMPRESSED_RGB_PVRTC_2BPPV1_IMG;
        if ( p === RGBA_PVRTC_4BPPV1_Format ) return extension.COMPRESSED_RGBA_PVRTC_4BPPV1_IMG;
        if ( p === RGBA_PVRTC_2BPPV1_Format ) return extension.COMPRESSED_RGBA_PVRTC_2BPPV1_IMG;

    }

`paramThreeToGL()` of `WebGLRenderer` calls `extensions.get()` which displays that warning
if a specified extension isn't supported.

So I suggest that we replace the above code style in `paramThreeToGL()`
with the following style to prevent the confusing warnings.

    if ( p === RGB_PVRTC_4BPPV1_Format ||
         p === RGB_PVRTC_2BPPV1_Format ||
         p === RGBA_PVRTC_4BPPV1_Format ||
         p === RGBA_PVRTC_2BPPV1_Format ) {

        extension = extensions.get( 'WEBGL_compressed_texture_pvrtc' );

        if ( extension !== null ) {

            if ( p === RGB_PVRTC_4BPPV1_Format ) return extension.COMPRESSED_RGB_PVRTC_4BPPV1_IMG;
            if ( p === RGB_PVRTC_2BPPV1_Format ) return extension.COMPRESSED_RGB_PVRTC_2BPPV1_IMG;
            if ( p === RGBA_PVRTC_4BPPV1_Format ) return extension.COMPRESSED_RGBA_PVRTC_4BPPV1_IMG;
            if ( p === RGBA_PVRTC_2BPPV1_Format ) return extension.COMPRESSED_RGBA_PVRTC_2BPPV1_IMG;

        }

    }

If this looks good to you guys, I'll make PR.

##### Three.js version

- [x] Dev
- [x] r81

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Looks good to me! 👍
