### ISSUE TITLE
Suggestion: add type check code in DepthTexture constructor

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#9725]
##### Description of the problem

According to WebGL specification about Depth Texture, Depth Texture type is limited by Depth Texture format.

https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture/
- The error INVALID_OPERATION is generated by texImage2D if format and internalformat are DEPTH_COMPONENT and type is not UNSIGNED_SHORT or UNSIGNED_INT.
- The error INVALID_OPERATION is generated by texImage2D if format and internalformat are not DEPTH_COMPONENT and type is UNSIGNED_SHORT or UNSIGNED_INT.
- The error INVALID_OPERATION is generated by texImage2D if format and internalformat are DEPTH_STENCIL and type is not UNSIGNED_INT_24_8_WEBGL.
- The error INVALID_OPERATION is generated by texImage2D if format and internalformat are not DEPTH_STENCIL and type is UNSIGNED_INT_24_8_WEBGL.

So I think it's a good idea to add type check code in `DepthTexture` constructor.

https://github.com/mrdoob/three.js/blob/9147f32ca235c9a069dd82309538ebd99f1e90d9/src/textures/DepthTexture.js#L24

```
if ( format === DepthFormat ) {

    if ( type !== UnsignedShortType && type !== UnsignedIntType ) {

        console.warn( 'DepthFormat requires UnsignedShortType or UnsignedIntType.' );

    }

} else {

    if ( type !== UnsignedInt248Type ) {

        console.warn( 'DepthStencilFormat requires UnsignedInt248Type.' );

    }

}
```

And it may also be a good to let default type for `DepthStencilFormat` be `UnsignedInt248Type`.

https://github.com/mrdoob/three.js/blob/9147f32ca235c9a069dd82309538ebd99f1e90d9/src/textures/DepthTexture.js#L23

```
if ( format === DepthFormat ) {

    this.type = type !== undefined ? type : UnsignedShortType;

} else {

    this.type = type !== undefined ? type : UnsignedInt248Type;

}
```

If this looks good to you guys, I'll make PR.
##### Three.js version
- [x] Dev
- [x] r81
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Sounds good! 👍
