### ISSUE TITLE
THREE.Math.Lerp interpolating from A to B with floating value C.

### ISSUE THREAD

**Issue by koolkap** [mrdoob/three.js#9728]
It seems we need this Math function for interpolating the value.

```
THREE.Math.lerp = function (a,  b,  c) {
    return a + c * (b - a);
}
```
we have smoothStep and smootherStep but they work in range of 0 to 1. What if we need value  between two points.

inspired from Unity  Mathf.lerp

(This is NOT a help site. Please read the guidelines above before posting.)

##### Three.js version

- [x] Dev
- [ ] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
I think I agree 😁

**Comment by koolkap** [comment]
:D thanks for acknowledge.

**Comment by Mugen87** [comment]
@koolkap Would you like to create a PR with the new function? 😊

**Comment by koolkap** [comment]
Okay I do, following the PR guideline 😊 notify you when done.

**Comment by Mugen87** [comment]
Great!

**Comment by Mugen87** [comment]
This issue can be closed now.
