### ISSUE TITLE
Animation Mixer: Setting interpolation type for Actions

### ISSUE THREAD

**Issue by bitstrider** [mrdoob/three.js#9731]
##### Description of the problem

Docs on the new animation system are a bit sparse.  Is there a way to do this?  I see there are some internal properties on actions related to interplotation: `action._interpolants` and `action._interpolantSettings`
##### Three.js version
- [x] Dev
- [ ] r80
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
The type of interpolation is configured on `KeyframeTrack` level. Please have a look at the revised documentation in `dev`  branch that explains the whole system much better than before.

**Comment by jostschmithals** [comment]
https://rawgit.com/mrdoob/three.js/dev/docs/#manual/introduction/Animation-system
