### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by adityatambe** [mrdoob/three.js#9742]
Hello,

I'm new to three.js and i want to build a 3D Diamond using geometry or other. Also on mouse move it should move accordingly. Can you guide me how should i achieve it ? 

Like this 
![diamond](https://cloud.githubusercontent.com/assets/14750809/18748189/bd95c6d4-80ee-11e6-90cb-7eb6ba531f4b.PNG)

**Comment by koolkap** [comment]
Please review the [guidelines for contributing](https://github.com/mrdoob/three.js/blob/dev/.github/CONTRIBUTING.md) to this repository.
