### ISSUE TITLE
Vtkloader range error when loading unstructured grid in binary format (Uncaught Rangerror: Offset is outside the bounds of the dataview).

### ISSUE THREAD

**Issue by smurthy** [mrdoob/three.js#9744]
##### Description of the problem

Uncaught Rangerror: Offset is outside the bounds of the dataview

VTKLoader failing on loading legacy format VTU file in binary, unstructured data grid.

I have the model and some screenshots of the error here:
https://www.dropbox.com/sh/ti1s42u4nx8nj9r/AAC4gcUsvYVunh968xZB3YNda?dl=0

 I am able to load said model in paraview (which is VTK's own desktop client viewer) so I don't think it's a problem with the model itself? I am not sure.

line 492 in vtkloader.js:

```
    } else if ( line.indexOf ( 'POINT_DATA' ) === 0 ) {

                numberOfPoints = parseInt ( line.split( ' ' )[ 1 ], 10 );

                // Grab the next line
                state = findString ( buffer, state.next );

                // Now grab the binary data
                count = numberOfPoints * 4 * 3;

                normals = new Float32Array( numberOfPoints * 3 );
                pointIndex = state.next;
                for ( i = 0; i < numberOfPoints; i ++ ) {

     error here-->              normals[ 3 * i ] = dataView.getFloat32( pointIndex, false );
                    normals[ 3 * i + 1 ] = dataView.getFloat32( pointIndex + 4, false );
                    normals[ 3 * i + 2 ] = dataView.getFloat32( pointIndex + 8, false );
                    pointIndex += 12;
```

I noticed there is a similar issue here: https://github.com/mrdoob/three.js/pull/8208 not sure if related.
##### Three.js version
- [x] Dev
- [x] r80
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
The loader is not able to handle the dataset format "unstructured grid" yet. The addition of for more dataset format is tracked by #13386.

Closing this one as a duplicate.
