### ISSUE TITLE
Flicker when using VRControls accel/gyro compared DeviceOrientationControls

### ISSUE THREAD

**Issue by dustinkerstein** [mrdoob/three.js#9748]
I originally [posted](https://github.com/borismus/webvr-boilerplate/issues/158) this over on the webvr boilerplate GitHub but have since narrowed it down a bit. It appears as though the VRControls camera/rendering is much smoother when rotating via touch compared to the accelerator/gyro on Android Chrome (Galaxy S7). With the gyro I see micro flickering as if it were rendering <30fps. I checked to make sure the fps weren't dropping and they in fact were stable at 60fps the entire time (while rotating via gyro and touch).

It can be reproduced on the webvr boilerplate demo using Android Chrome via - http://borismus.github.io/webvr-boilerplate/ - Compare that to http://threejs.org/examples/?q=Devic#misc_controls_deviceorientation - with gyro/accel control. 

After a little looking around I found that DeviceOrientationControls.js doesn't exhibit this behavior. Does VRControls handle the gyro/accel data differently compared to DeviceOrientationControls? Is it possible to get VRControls to smooth out its gyro/accel handling?

Thanks,
Dustin

##### Three.js version
- r81

##### Browser
- Android Chrome (others untested)

##### OS
- Android (other untested)

**Comment by dustinkerstein** [comment]
I actually think this my be resolved by a newer VRControls file. I will close this ticket for now.

**Comment by mrdoob** [comment]
VRControls doesn't handle touch. Aren't you talking about WebVR Boilerplate or something?

**Comment by dustinkerstein** [comment]
Ah yeah, that seems to be my own touch handling code which appears to be suppressed when using DeviceOrientationControls.

**Comment by dustinkerstein** [comment]
But I guess since I'm using the webvr-polyfill that the VRControls issue is actually inside the polyfill, correct?

**Comment by dustinkerstein** [comment]
Yah, this is definitely more of a polyfill issue upon further investigation. Will post back over there. Sorry for the back and forth.
