### ISSUE TITLE
Object loaded without texture and no warning

### ISSUE THREAD

**Issue by fleduc** [mrdoob/three.js#9752]
##### Description of the problem 

(This is NOT a help site. Please read the guidelines above before posting.)

##### Three.js version

- [ ] Dev
- [x ] r80
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

I have notice a strange behavior on my site after updating to version 81.  some of my models are loading only the mesh, not the texture but I receive no warning.

Look on this web site my3dalbums.com, in sample section, the two middle models are only white.  what is puzzling me is that all the others are ok... ???

Any clue?

Thanks

**Comment by cecilemuller** [comment]
I just tried the middle one of the first row and Chrome devtools says the .mlt and .jpg files are missing, specifically these urls:

 - http://my3dalbums.com/demo/1/model_mesh.obj.mtl
 - http://my3dalbums.com/images/site/modal-img-1.jpg

**Comment by fleduc** [comment]
Hi Cecile.

Thank you for helping.  The first file was missing, my mistake when I did some test yesterday. The other file is not concerning this problem...  Now that I've replaced the mtl back at its place, I still have nothing than a white model... Still investigating

Thanks again

**Comment by fleduc** [comment]
Ok, I have found the solution.  It appear that the company who provides the objects had a problem with their automation process and they were producing faulty "mtl" files...
the "map_Kd"  was not populated resulting in an object with no texture.

Thanks anyway.
