### ISSUE TITLE
Serve threejs.org site over HTTPS

### ISSUE THREAD

**Issue by cvan** [mrdoob/three.js#9753]
HTTPS will soon be required in WebVR-capable browsers. It'd be awesome if http://threejs.org was served from https://threejs.org. See [the WebVR spec issue](https://github.com/w3c/webvr/issues/60) and @toji's [blog post](http://blog.tojicode.com/2016/09/update-on-webvr-spec-chrome-and-https.html) for more info.

Since http://threejs.org is already being served from GitHub Pages, I'd recommend using [CloudFlare](https://www.cloudflare.com/)'s free tier service as a reverse cache proxy + CDN (which includes best-in-class perf server settings [gzip, SDCH, HTTP/2, sane `Cache-Control` and `E-Tag` headers, etc.]), free HTTPS (TLS) support, server-side page rules (to force HTTPS and add server-side redirects), among other awesome options.

[Here's a walkthrough I wrote of how to set up GitHub Pages + CloudFlare.](https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b)

**Comment by Mugen87** [comment]
There is already an issue for this #7678

**Comment by mrdoob** [comment]
Thanks a lot for taking the time to write the walkthrough!
Are you aware of a similar walkthrough but using https://letsencrypt.org/ instead?

**Comment by cvan** [comment]
> Thanks a lot for taking the time to write the walkthrough!

No problem!

> Are you aware of a similar walkthrough but using https://letsencrypt.org/ instead?

Currently, it looks like Let's Encrypt + GitHub Pages [isn't supported just yet](https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8).

> There is already an issue for this #7678

Apologies didn't see this issue. That issues has lots of good dialog, so I'm going to move some comments from here to there and close this issue.

**Comment by cvan** [comment]
closed in favour of #7678 (see [my latest comment there](https://github.com/mrdoob/three.js/issues/7678#issuecomment-249338077)).
