### ISSUE TITLE
Export STL Binary file from scene

### ISSUE THREAD

**Issue by alf007mx** [mrdoob/three.js#9758]
##### Description of the problem 

Hi!

I'm trying to export a STL Binary file that I loaded to the scene using the STLLoader, I use the STLBinaryExporter to export the Mesh but I only get the following output:

` DataView { }`

Here is a complete working example so you can help me out debugging and try to know why it doesn't export the model correctly. 
Link: https://www.dropbox.com/sh/hu4m3dyfdl6h36h/AAB5j30VuZDAXeEGi_X1Xx5Fa?dl=0

Just download the STLExporter folder, open the index.html and press the Export button to see the result in the console log.

It might not be a problem with the STLBinaryExporter I think it is the STLLoader because it doesn't set the faces or the triangle attribute to the object. When it parses the binary file it only adds the following attributes:

`geometry.addAttribute( 'position', new THREE.BufferAttribute( vertices, 3 ) );`
`geometry.addAttribute( 'normal', new THREE.BufferAttribute( normals, 3 ) );`

The BinaryExporter is looking up for something the object doesn't have.

I checked the properties of the STL ASCII files and it does have the faces and vertices, so in the STLBinaryExporter in line 34 is trying to get the `geometry.faces.length` but it will never find it.
In line 30, it converts the BufferGeometry to Geometry with this:

`geometry = new THREE.Geometry().fromBufferGeometry( geometry );` 
Maybe it doesn't create a correct THREE.Geometry with all the attributes that the STL ASCII THREE.Geometry object has.

Thanks.
##### Three.js version

- [ ] Dev
- [x] r78
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
None

**Comment by mrdoob** [comment]
#9689
