### ISSUE TITLE
WebVR non-positional examples does not enter in VR mode

### ISSUE THREAD

**Issue by arturitu** [mrdoob/three.js#9761]
##### Description of the problem

Some examples like (cubes, panorama...) does not enter in VR mode with the last WebVR Chromium. (Perhaps it is because the Chromium for Android webvr build is not updated yet to work with the last changes).
##### Three.js version
- [x] r81
##### Browser
- WebVR Chromium (Feb 29 chromium_webvr_v1_android.apk)
##### OS
- Android

**Comment by mrdoob** [comment]
Are you talking about Chromium WebVR build? Or Chrome for Android?

**Comment by arturitu** [comment]
Chromium WebVR build > https://webvr.info/get-chrome/ > chromium_webvr_v1_android.apk (Feb 29)

**Comment by arturitu** [comment]
In the Chrome stable for Android appears the does not supported message as expected.

**Comment by arturitu** [comment]
I think is related with this issue https://github.com/toji/chrome-webvr-issues/issues/58

**Comment by synergyseeker** [comment]
any progress on getting any of the ThreeJS WebVR demos to work on mobile? Still seeing this failing to enter VR mode ( no stereoscopic cameras, no full screen )

**Comment by mrdoob** [comment]
@toji any updates?

**Comment by Mugen87** [comment]
I think we can close this issue. Should be solved now.
