### ISSUE TITLE
why was the button to convert buffer geometry to classic geometry removed in editor?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#9775]
the problem is, that exporting json with buffer geometry explodes the file size (e g 2.7 mb obj to 31.8 mb json), making such an export useless.

**Comment by mrdoob** [comment]
I don't think converting it back to `Geometry` will help though...

Try doing this in the console:

```js
editor.selected.geometry = new THREE.Geometry().fromBufferGeometry( editor.selected.geometry );
```

**Comment by makc** [comment]
does not build the index, does it

**Comment by mrdoob** [comment]
Is the BufferGeometry you're trying to convert indexed?

**Comment by makc** [comment]
probably not, as it is far larger than obj in the end. it comes from your obj parser, so you should know.

any way, I might be wrong but I seem to remember that in good old days before buffer geometry json and obj size were comparable, but now there is no reason to convert obj offline, any kind of speed gains that might have been there are negated by json filie size.
