### ISSUE TITLE
Sprite can not use useScreenCoordinates 

### ISSUE THREAD

**Issue by SpiritBreaker** [mrdoob/three.js#9777]
##### Description of the problem 

```js
var sprite = new THREE.Sprite(new THREE.SpriteMaterial{
    map : texture,
    useScreenCoordinates : true //now on r81 this attribute had removed..
});
```

When i  want to create a sprite that can follow my mouse, how can i do??
there is no "useScreenCoordinates" can be used..

##### Three.js version

- [x] Dev
- [√] r81
- [x] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by ToJans** [comment]
The idea is that you create a second orthographic camera, and use this one to overlay the sprites; you can find the example [here](https://threejs.org/examples/?q=sprite#webgl_sprites).

The gist of the code is in the render loop, after setting `renderer.autoClear` to `false`:

```JavaScript
renderer.clear();
renderer.render( scene, camera );
renderer.clearDepth();
renderer.render( sceneOrtho, cameraOrtho );
```

**Comment by SpiritBreaker** [comment]
@ToJans Thank you very much!
Your answer help me, and it work well. But i thank API become more complex than before,isn't it?

**Comment by mrdoob** [comment]
`useScreenCoordinates` didn't actually behave as you think it did. It was for scaling I think.

**Comment by haolly** [comment]
@ToJans  It's strange if I just comment out https://github.com/mrdoob/three.js/blob/master/examples/webgl_sprites.html#L194-L219 those line, left , the sprite will disappear 😨

**Comment by Mugen87** [comment]
@haolly Please don't ask for help at github. Use stackoverflow or the [forum](https://discourse.threejs.org/) instead.
