### ISSUE TITLE
Video content-type not set to video/mp4 results in black frame

### ISSUE THREAD

**Issue by dustinkerstein** [mrdoob/three.js#9780]
If I upload to my dash fragmented h264 mp4 files to an S3 bucket using the Amazon web-based uploader, the videos play fine when directly loaded in Mobile Safari (iOS 10.0.1), but if I try to play them using my three.js viewer then I just get a black screen. However, if I upload to the S3 bucket with Cyberduck, they play fine directly in Mobile Safari and in three.js.

It looks like Cyberduck is setting the meta-data 'Content-Type=video/mp4' and the AWS uploader is 'Content-Type=application/octet-stream'. When I manually set this meta-data to video/mp4 everything works correctly.

I originally posted this to #9754 but it appears to be a different issue.

Thanks,
Dustin

##### Three.js version
- r81

##### Browser
- Mobile Safari

##### OS
-  iOS 10.0.1

**Comment by mrdoob** [comment]
I don't think there is much we can do about it?

**Comment by dustinkerstein** [comment]
Ok. I'll just make sure to set this correctly. Just figured it'd be good to bring up just in case anyone else ran into the same issue.

-Dustin
