### ISSUE TITLE
A new Face4 idea. 

### ISSUE THREAD

**Issue by brknblgc** [mrdoob/three.js#9781]
hi. As you know Face4 was removed since r60. I was trying to write a new Face4 for 2 days. However i got stuck when it comes to WireframeGeometry.js. Idea is this:

There will be a new BufferAttribute called "faceindex". If there is an index array, there must be a faceindex array too. Every 3 indices creates a face so 

```
geometry.attributes.faceindex.length  =  geometry.index.length / 3;
```

If two faceindex has same value that means the two faces creates a Face4.

```
indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 6, 9, 8, 10, 11, 12, 10, 13, 12, 14, 15, 16];
faceindex = [0, 1, 2, 2, 3, 3, 4]  ==> third and forth faces forms a Face4 as well as fifth and sixth
```

faceindex[ 2 ] and faceindex[ 3 ] has 6 indices  (6, 7, 8, 6, 9, 8) which produces 5 (1 duplicate) lines in total(6-7 , 6-8, 7-8, 6-9, 6-8, 8-9). If we can block this recurrent(6-8) line before it reaches `hash [ key ] ===undefined` section we'll have a square look. Yes we still have 12 faces in a cube however it will look like a square. I mean real square.

In Geometry, Face3() will store faceindex value with a new variable, just before materialIndex

What you think?

**Comment by mrdoob** [comment]
It sounds complicated... It may be simpler to 2 two different indices sets, one for triangles and one for lines.

**Comment by brknblgc** [comment]
i am so close to do it.  However Javascript throws this error "edges.splice is not a function" in wireframegeometry.js. Splice is an array function asseen in [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/splice). I didn't get it.

**Comment by Usnul** [comment]
you are dealing with "ArrayLike". Actually these are TypedArrays. They don't implement Array interface. For one - they are not dynamic, so you can't change their size. Only way is to make a large/smaller copy. Copying TypedArrays is super-cheap though, compared to normal arrays, since it's a memcopy more or less.
