### ISSUE TITLE
What should happen when applying opacity less than 1 to a node with descendants?

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#9782]
Hello Ricardo and contributors,

I'd like your opinions:

If we have a node (Object3D), and it has many descendants (a sub tree), what should happen when we apply opacity with a value less than `1` to it?

1. It, and all of it's children should become transparent, multiplying opacities down the scene graph.
1. It's content should become transparent but not that of its descendants.
1. Same as (1), but the whole object should be flattened into a plane.

The reason I want your opinion is because the new specs for CSS 3D (css-transforms) [state here](https://drafts.csswg.org/css-transforms/#grouping-property-values) that the answer is (3).

To see what I mean, view these two examples in Chrome 53 or higher:

- https://jsfiddle.net/trusktr/ymonmo70/16
- https://jsfiddle.net/trusktr/ymonmo70/17

The second example has opacity applied to the node that contains all the sub-nodes which compose the car. The opacity, according to spec, flattens the car into a plane (turns it into paper!).

I'm asking various 3D engine authors for opinions of what the correct or most expected behavior should be.

All the best,
~ Joe

**Comment by mrdoob** [comment]
I obviously think it should be 2. 
Have you heard from anyone developing CSS3D for the actual reason why they moved to 3?

**Comment by trusktr** [comment]
> I obviously think it should be 2. 

Thanks for your opinion. It's not obvious to me though. Why do you prefer (2)?

> Have you heard from anyone developing CSS3D for the actual reason why they moved to 3?

Because "CSS opacity is a grouping property" which means therefore it must flatten. TLDR, because the spec says so, but ultimately I'm not really sure why other than there is some pre-requisite requirement for opacity to be a grouping property. IMHO, anything in the spec can and should be changed in the name of 3D.

The behavior is honestly ugly from a 3D point of view and an HTML/CSS API point of view.

**Comment by mrdoob** [comment]
>> I obviously think it should be 2.

> Thanks for your opinion. It's not obvious to me though. Why do you prefer (2)?

I said obvious because that's how three.js behaves. I prefer (2) because I used Flash before, and Flash behaved like (1) and I always though it was a mess. Also, 3D programs behave like (2) too.

**Comment by trusktr** [comment]
@mrdoob Makes sense. I can imagine cases when it is not desirable to have opacity propagate down a 3D scene graph, and apply only to the object(s) at the current node.

If I understand correctly, Three.js opacity is done with materials, and materials do not propagate down the Object3D graph.

I also think that in some cases it may be desirable to apply opacity to a whole sub-tree in a 3D scene.

But in any case, I don't find it desirable to always flatten the transforms of a sub-tree into a flat plane for the whole sub-tree, which is the new CSS3D behavior.

In the old CSS3D behavior that they call "legacy" (i.e. behavior in Chrome 52 prior to the changes in Chrome 53), applying opacity to a parent causes the opacity to multiply down through all descendants in the 3D context. This is better than flattening, but it is still not possible to apply opacity just to the parent without affecting children.

I'm trying to see about the possibility of changing the spec to allow for all three possibilities:

1. applying to parent only
1. applying to parent while multiplying to descendants.
1. applying to parent while multiplying to descendants as well as flattening descendants onto parent plane.

The idea would be to introduce a new CSS property called `blend-3d`, which would be could be used like this:

```css
div {
  blend-3d: auto; /* Defaults to "single" which does not multiply down descendant elements in a 3D context. */
}

div {
  blend-3d: single; /* does not multiply down descendant elements in a 3D context. */
}

div {
  blend-3d: multiply; /* multiplies down descendant elements in a 3D context, and perhaps it stops at the next 3D descendant element that has "blend-3d: single". */
}
```

To achieve flattening, the user would need to change from `transforms-style:preserve-3d` to `transforms-style:flat`, in which case the `blend-3d` property has no effect on the element, and opacity behaves as a normal grouping property as we're all used to in the 2D web, and which is backwards compatible with all 2D content.

**Comment by mrdoob** [comment]
I do not think this is the right place to discuss this.

**Comment by trusktr** [comment]
True. Thanks for the opinion though. It matters. As I am collecting evidence that (hopefully) shows the CSS3D behavior is undesirable from the point-of-view of 3D engine authors who also deal with opacity in 3D scenes.

**Comment by mrdoob** [comment]
The problem with CSS3D is that they're "stuck" with how DOM/CSS works. CSS works like approach 1, but it was designed to be 2D. Things get tricky when you try to apply that approach to 3D.
