### ISSUE TITLE
Prohibit THREE.Group geometry and material, and update docs for THREE.Group?

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#9785]
##### Description of the problem 
This is a feature request, actually.

I quote @mrdoob from #8711:
> THREE.Group (which extends THREE.Object3D) is just a nicer API and it also hints the renderer to not look for geometries or materials inside.

>When dealing with a THREE.Object3D, the renderer doesn't know if it has a geometry or material, as the object could be, in fact, a THREE.Mesh.

Would it be possible to prohibit setting geometry and material of THREE.Group? (Like const undefined, but for object keys). Would you have to make geometry and material private to Object3D (which would break a lot, I suppose)?

Or at least inform in the docs that geometry and material will be ignored by the renderer (if that is the case), along with an explanation on the purpose and advantages of grouping with THREE.Group.

##### Three.js version
- [ ] Dev
- [x] r81
- [ ] ...

**Comment by mrdoob** [comment]
Hmm, did you tried adding a `geometry` to a `Group`?

**Comment by EliasHasle** [comment]
Hehe, no. Maybe I should try that before reporting an issue... I was basing
my report on the Group source and docs. I'll be back after testing, then.
;-)
Den 27. sep. 2016 16:55 skrev "Mr.doob" <notifications@github.com> følgende:
