### ISSUE TITLE
VREffect - performance issue

### ISSUE THREAD

**Issue by olivierchatry** [mrdoob/three.js#9788]
##### Description of the problem 

I'm not sure what is going on, and I'm not sure if it is a bug in three.js, but it seems the performances are getting worst and worst concerning the position tracking using the Vive. It might be a chromium issue, or something with the latest firmware of the Vive, I just wanted to know if anyone experience the same thing. Framerate seems fine, but tracking is super sluggish. 

##### Three.js version

- [x] Dev
- [x] r81

##### Browser

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

HTC Vive, Windows 10, Multiple GPU / CPU

**Comment by mkeblx** [comment]
You can try out the three.js-free WebVR samples: https://toji.github.io/webvr-samples/ and see if experience the same tracking issues.

**Comment by olivierchatry** [comment]
I tried the threejs samples, and all suffer from the same issue. I have only tried on nvidia GPU if it matter, but I don't think it is a framerate issue.

**Comment by olivierchatry** [comment]
I will try the sample tomorrow and get back to you ( sorry for the double post, I'm on mobile phone ). Thanks for the link !

**Comment by mkeblx** [comment]
I'll check on comparing the three.js vs. non-three.js demos on a Vive as well sometime this week. Unfortunately it's probably largely a qualitative thing at this point.

**Comment by olivierchatry** [comment]
The lag is really obvious, and it uses to be very smooth, so I'm really not sure what is going on :(. I will try the non three demo anyway and post my results.

**Comment by mrdoob** [comment]
Try on Firefox Nightly too!
https://blog.mozvr.com/webvr-1-0-available-in-firefox-nightly/

**Comment by olivierchatry** [comment]
Found the issue, was with NVidia driver, I had to disable VSync and then everything is back to normal. For good mesure, I also forced the number of max pre-rendered frame to 1. 

Well anyway, that was a bit scary :)
