### ISSUE TITLE
CSS3DRenderer.js flash on iOS 10

### ISSUE THREAD

**Issue by WingGao** [mrdoob/three.js#9789]
##### Description of the problem

I was working with an panorama viewer on the mobile, so I try the `CSS3DRenderer`.
It worked well on the chrome on the mac, but it failed on the iOS.

The example `./three.js/examples/css3d_panorama_deviceorientation.html` also failed.

iOS 10:
Both chrome app and safari have the same issue.
![](http://ww1.sinaimg.cn/large/801b780agw1f88ueglzyqj20jz0zkgnb.jpg)

Chrome:
![](http://ww1.sinaimg.cn/large/801b780agw1f88ufn8bowj20km0xe0vc.jpg)
##### Three.js version
- [x] r81
- [x] with `./three.js/examples/js/renderers/CSS3DRenderer.js`
  ##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

**Comment by ztxxxx0000** [comment]
I also met this problem. I need help.

**Comment by WingGao** [comment]
I found that the version v64 of three.js is working for me.
Maybe something goes wrong during the update.

**Comment by ztxxxx0000** [comment]
你说的是three.js的版本用r64?   http://cdn.bootcss.com/three.js/r64/three.min.js     我替换之后发现CSS3DRenderer.js会报错。 CSS3DRenderer.js:215 Uncaught TypeError: camera.getEffectiveFOV is not a function。

**Comment by WingGao** [comment]
The `CSS3DRender.js` file should be the same.
https://github.com/mrdoob/three.js/blob/r64/examples/js/renderers/CSS3DRenderer.js

**Comment by ztxxxx0000** [comment]
wow, it really figure it out.Cool man. Appreciate.but how do you found it? or how it works?

**Comment by ztxxxx0000** [comment]
hi WingGao,when i test the r64 vision. Between  the edge of the skyBox,there is a line. only on android but not on ios. Do you test it? thanks！

**Comment by ztxxxx0000** [comment]
Hi WingGao,i have figure out the line. demo: element.width = 1026; // 2 pixels extra to close the gap.   but div do not have width and height value。so i change div style: height:1026px; width:1026px;  . it works! thanks!
