### ISSUE TITLE
InterleavedBufferAttribute has no "needsUpdate" setter

### ISSUE THREAD

**Issue by handegar** [mrdoob/three.js#9790]
##### Description of the problem

The `InterleavedBufferAttribute` objects seems to miss the `needsUpdate` setter/getter for increasing the internal `version` counter.

To be able to trigger an re-upload of the data to the GPU one will have to increase the `Mesh.geometry.attributes.MYBUFFER.data.version` counter by hand.
##### Three.js version
- [ ] Dev
- [ x] r81
- [ ] ...

**Comment by mrdoob** [comment]
Would you like to do a PR with the fix?

**Comment by Makio64** [comment]
Bump up - needsupdate is still not implement on interleavedBuffer but written in his documentation.

**Comment by WestLangley** [comment]
For `THREE.InterleavedBufferAttribute`, this is the pattern to use:
```javascript
mesh.geometry.attributes.position.data.needsUpdate = true;
```

**Comment by Makio64** [comment]
Thanks @WestLangley ! 

I realize the InterleavedBufferAttributes were all link to their THREE.InterleavedBuffer which is the stuffs to actually update and setup drawrange for interleaved, maybe a note about it in the documentation would be good.

**Comment by holgerl** [comment]
This is problematic when using TypeScript types, as the compiler can not know if the buffer attribute has `needsUpdate` or not:

```
TS2339: Property 'needsUpdate' does not exist on type 'BufferAttribute | InterleavedBufferAttribute'.
  Property 'needsUpdate' does not exist on type 'InterleavedBufferAttribute'.
```

There should be a `needsUpdate` on `InterleavedBufferAttribute` just as on `BufferAttribute`.
