### ISSUE TITLE
OSC getLivePreview implementation

### ISSUE THREAD

**Issue by wowzaaa** [mrdoob/three.js#9791]
Hey

I need to implement the getLivePreview command from Google Open Spherical Camera API
https://developers.google.com/streetview/open-spherical-camera/reference/camera/getlivepreview

What i need to do is a POST with some data that will tell the endpoint i need the getLivePreview stream ... the output is a video stream of MOTION Jpegs at 15fps ... the pb is that i need a way to display them in javascript by executing a POST request (any other method will not work)

is there a way three.js can help me implement that?

thanks

**Comment by makc** [comment]
Wrong library? You need [jQuery](https://api.jquery.com/jquery.post/) 😁

**Comment by wowzaaa** [comment]
the pb is not doing a pot request ... the pb is handling a video stream reponse with (multipart/x-mixed-place + boundary)
