### ISSUE TITLE
Render to texture: texture.image is undefined

### ISSUE THREAD

**Issue by martinRenou** [mrdoob/three.js#9793]
Hi everyone,

I want to save vertex position of my mesh (after transformations) on a texture with renderToTexture.

I initialize my renderTarget and renderer this way:
```javascript
rtTexture = new THREE.WebGLRenderTarget(
	width, height,
	{ format: THREE.RGBAFormat, type: THREE.FloatType }
)

var rttRenderer = new THREE.WebGLRenderer();
rttRenderer.setSize( width, height );
rttRenderer.autoClear = false;
rttRenderer.extensions.get( 'OES_texture_float' )

rttRenderer.render( rttScene, camera, rtTexture, true );

// But here rtTexture.texture.image is undefined
```

I would like to read data of my image but it's undefined... And it's not my example that is not working, I checked and it's the same for [https://threejs.org/examples/webgl_rtt.html](url)

**Comment by makc** [comment]
I think .image is just to keep html image or canvas that you passed to texture constructor. You probably want to do renderer.getContext().[readPixels](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels)(...);

**Comment by martinRenou** [comment]
Ok, thanks, I'll check this.
Do you know if there's a proper way to get the vertices positions (in a buffer or directly a typed array) after transformations in shaders ?

**Comment by makc** [comment]
That depends on what you think is "proper". I think something like [rootbeer](http://www.trentonsystems.com/wp-content/uploads/2012/08/RootBeer-Seamlessly-Using-GPUs-From-Java.pdf) would be.

**Comment by martinRenou** [comment]
Well, after some researches, I found what would be really "proper" for me: [http://webglsamples.org/WebGL2Samples/#transform_feedback_separated](url). You need WebGL2 enabled with on your browser. Unfortunately it's not compatible with ThreeJS... I'll take a look at rootbeer :smile: thanks.
I close this.

**Comment by mrdoob** [comment]
> You need WebGL2 enabled with on your browser. Unfortunately it's not compatible with ThreeJS...

This experiment uses three.js and webgl2 transform feedback.
https://github.com/toji/webgl2-particles-2

**Comment by martinRenou** [comment]
Awesome ! I'll surely take a look at how they implemented that 😄 thanks @mrdoob
