### ISSUE TITLE
BoundingBoxHelper.update still uses size()

### ISSUE THREAD

**Issue by CoDanny** [mrdoob/three.js#9794]
##### Description of the problem 

BoundingBoxHelper.update still uses size() instead of getSize() causing lots of warnings on the console.

UPDATE: Looking more in the code it seems that Box3.getBoundingSphere also uses size() instead of getSize()

##### Three.js version

- [x] r81

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
This is already fixed in `dev` branch. #9739

**Comment by CoDanny** [comment]
Thanks. I wish github search was a bit better... I did search before posting
