### ISSUE TITLE
ImageLoader.load never suceeds or fails, if createElementNS fails

### ISSUE THREAD

**Issue by griffin2000** [mrdoob/three.js#9797]
##### Description of the problem 

ImageLoader.load does not handle error case for the createElementNS call (on line 30 src\loaders\ImageLoader.js). This means if createElementNS throws an error (which happens 100% of the time in my node.js setup) then ImageLoader.load the call just disappears, neither onLoad or onError are ever called.

If think all that is needed to fix this is simply add to line 32 of ImageLoader.js:
`		image.onerror = onError;`

Then you get an error callback in this case

##### Three.js version

- [X ] Dev
- [X ] r81

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Would you like to do a Pull Request with the fix?

**Comment by griffin2000** [comment]
Submitted: https://github.com/mrdoob/three.js/pull/9799
