### ISSUE TITLE
THREE.Raycaster doesn't report intersection with rotated plane

### ISSUE THREAD

**Issue by spite** [mrdoob/three.js#9798]
##### Description of the problem 

With a plane created with PlaneBufferGeometry and a OrthographicCamera, Raycaster detects intersection with the plane, but if it's rotated, it only detects on the top half.

This is a reduced case: https://jsfiddle.net/h15y7x0s/2/
The quad will turn #ff00ff if raycaster reports intersection, #00ff0 otherwise.
You'll see that when the mouse is over the bottom half it doesn't turn pink. 
If you comment line 13 (quad.rotation.x = Math.PI;), and hit Run again, it works as expected.

##### Three.js version

- [x] Dev
- [x] r81
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
Have a look at #9135.

**Comment by spite** [comment]
I think it's more because it's a plane and it detects the opposite face as a culled face, but what do i know. What #9135 doesn't explain is why with the same camera, it works with the mesh unrotated, and doesn't with the mesh rotated. 

I've fixed it by using a flat BoxBufferGeometry, but I'm betting that this will pop up more often with people creating UIs for VR using Planes and Raycasting.

**Comment by WestLangley** [comment]
Did you make the change I suggested and set a positive value for the near plane?

**Comment by WestLangley** [comment]
The fiddle crashes Safari on iOS, so I am currently unable to test.

**Comment by spite** [comment]
It does work with a veeeeeery small positive value of near plane. I still don't understand what the rotation has to do with this though 🤔

I think the using of negative values in the near plane comes from some (old) three.js examples out there.

Cool then! Thanks!
