### ISSUE TITLE
Conflict with libs adding isColor method to String prototype

### ISSUE THREAD

**Issue by nidu** [mrdoob/three.js#9800]
##### Description of the problem 

(This is NOT a help site. Please read the guidelines above before posting.)

##### Three.js version

- [ ] Dev
- [x] r81
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

Quadro K5000M

##### Explanation

Some libraries have code like `String.ptototype.isColor = ...` adding `isColor` method to all strings (e.g. [this](https://github.com/olton/Metro-UI-CSS/blob/master/js/global.js#L24)) causing three.js code like [this](https://github.com/mrdoob/three.js/blob/da9f70c7891435ddc40bdabf38baaf92ad389889/src/materials/Material.js#L106) to fail (because in the next line string doesn't have method `set`). Because of this i can't even create `WebGLRenderer`. Maybe adding these methods is a bad pattern but code like this exists currently. What do you think would be a proper way to handle it?

I created corresponding [issue](https://github.com/olton/Metro-UI-CSS/issues/872) for this particular lib, but i don't know if there are more like this. How do you think, maybe some simple type check or `set` method existence can be used in this code?

Replacing code with `(currentValue && currentValue.set && currentValue.isColor)` fixes problem with creating `WebGLRenderer`.

**Comment by Mugen87** [comment]
Extending native prototype objects in JavaScript is bad practise. Your case is a perfect example for the consequences of this approach. I can't recommend to change three.js code only because other libraries make fundamental design failures.

**Comment by mrdoob** [comment]
Totally agree. They probably were not aware of the consequences of doing that. But if they don't fix it, they'll be showing a total lack of respect to the javascript ecosystem.

They they're adding `isColor` to `String.prototype` anyone else could add `set` too and your suggested workaround would break.

**Comment by Mugen87** [comment]
Something for the `Metro-UI-CSS` developers... 

![image](https://cloud.githubusercontent.com/assets/12612165/19013952/fe7e0254-87df-11e6-8533-0b49232bd0d3.png)
