### ISSUE TITLE
TextureLoader() and ImageLoader() crossOrigin giving CORS issues

### ISSUE THREAD

**Issue by jascination** [mrdoob/three.js#9801]
##### Description of the problem 

I'm trying to load an image from AWS to my localhost, using the [example in the ImageLoader() docs](https://threejs.org/docs/api/loaders/ImageLoader.html):

```
function loadImages(){
  var images = json.images;

  var loader = new THREE.ImageLoader();
      loader.setCrossOrigin(' ');

  for(var i = 0; i<images.length; i++){

    var uri = images[i].server + '/1200x900' + images[i].uri;

    loader.load(
      uri,

      function ( image ) {
        var canvas = document.createElement( 'canvas' );
        var context = canvas.getContext( '2d' );
        context.drawImage( image, 100, 100 );
      },

      function ( xhr ) {
        console.log( (xhr.loaded / xhr.total * 100) + '% loaded' );
      },

      function ( xhr ) {
        console.log( 'An error happened' );
      }
    );
  }

}

```

I keep running into CORS issues, specifically:

> XMLHttpRequest cannot load . No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Looking in my Network tab, even though I'm setting the correct RES headers in NodeJS, the image being loaded from THREE.js doesn't have crossdomain headers on it.

All answers I've seen on SO about this suggest the way I'm using `loader.setCrossOrigin(' ');` is correct, so what's going on here? I'm using the latest build as of 30/9/16, d2842cc,

##### Three.js version

- [ ] Dev
- [X] r81
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Hanzofm** [comment]
Same problem, 
```
var loader = new THREE.TextureLoader();
            //allow cross origin loading
            loader.crossOrigin = '';

            var texture = loader.load('https://www.google.es/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png');
```


do you solved?
