### ISSUE TITLE
Argument 2 is not valid for any of the 2-argument overloads of WebGLRenderingContext.uniform2fv

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#9807]
[This codepen](http://codepen.io/randomekek/pen/YqxQra) fails with said message for r76+ (using https://cdnjs.cloudflare.com/ajax/libs/three.js/r75/three.min.js makes it work again)

**Comment by makc** [comment]
Oh and this only happens in FF, Chrome works (but gives you noisy pattern... maybe that's intended ?)

**Comment by makc** [comment]
Waaaait, this is codepen's fault for setting undefined uniforms :shit:

**Comment by mrdoob** [comment]
Codepen sets undefined uniforms?

**Comment by makc** [comment]
A ha, if you change e g event.x to event.clientX, firefox is happy.
