### ISSUE TITLE
Brave browser is unable to load three.min.js

### ISSUE THREAD

**Issue by snakecharmer1024** [mrdoob/three.js#9812]
OSX 10.11.5. 
Using the Brave browser https://www.brave.com/

I get this error on import

Uncaught TypeError: Cannot read property 'precision' of undefined

in line 19047 of the three.js build that comes in the repo.
This is the function where it breaks.

`		
     function getMaxPrecision( precision ) {

			if ( precision === 'highp' ) {

				if ( gl.getShaderPrecisionFormat( gl.VERTEX_SHADER, gl.HIGH_FLOAT ).precision > 0 &&
				     gl.getShaderPrecisionFormat( gl.FRAGMENT_SHADER, gl.HIGH_FLOAT ).precision > 0 ) {

					return 'highp';

				}

				precision = 'mediump';

			}

			if ( precision === 'mediump' ) {

				if ( gl.getShaderPrecisionFormat( gl.VERTEX_SHADER, gl.MEDIUM_FLOAT ).precision > 0 &&
				     gl.getShaderPrecisionFormat( gl.FRAGMENT_SHADER, gl.MEDIUM_FLOAT ).precision > 0 ) {

					return 'mediump';

				}

			}

			return 'lowp';

		}
`

If this is some API they are missing, I can tell them, it's open source. It may already be on their roadmap. https://github.com/brave/browser-laptop

**Comment by Mugen87** [comment]
I've tested Brave on my iMac (OSX 10.11.6) with some of our three.js examples. No errors. The result of `getShaderPrecisionFormat` isn't `undefined` on my system.

Can you create a simple reduction test (e.g. with jsfiddle) that produces your error? If there is really a problem with `getShaderPrecisionFormat` this should be posted in the issue section of Brave.

![image](https://cloud.githubusercontent.com/assets/12612165/19037825/a90edd4e-8978-11e6-8850-1a1c1f52f72d.png)

**Comment by mrdoob** [comment]
I think this should be reported to the browser developers instead.
