### ISSUE TITLE
parameter antialias: true in renderer constructor renders blank screen (mac 10.12)

### ISSUE THREAD

**Issue by raurir** [mrdoob/three.js#9814]
##### Description of the problem

Initialising renderer with antialias renders blank canvas.

blank canvas:
`renderer = new THREE.WebGLRenderer({antialias: true});`

renders without antialias as expected:
`renderer = new THREE.WebGLRenderer();`
##### Three.js version
- [ ] Dev
- [x] r81
- [ ] ...
##### Browser
- [] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
- [x] Macos
##### Hardware Requirements (graphics card, VR Device, ...)

MacBook Pro (15-inch, Late 2011)
AMD Radeon HD 6770M 1024 MB
Intel HD Graphics 3000 512 MB

**Comment by raurir** [comment]
To be clear, I assume this is an issue with the hardware/OS, but for the record here it is.

**Comment by WestLangley** [comment]
Possibly related to #9685.

**Comment by mrdoob** [comment]
> To be clear, I assume this is an issue with the hardware/OS, but for the record here it is.

I think so too...

**Comment by sunag** [comment]
Same thing in `Chrome 54.0.2840.71 ` crash with `antialias:true` using two different video-card but in canary  `Chrome 56.0.2914.0` work done, seemingly fixed
