### ISSUE TITLE
extruded circles do not close for radius<0.75

### ISSUE THREAD

**Issue by henryJack** [mrdoob/three.js#9818]
##### Description of the problem 

When you use small values for radius when creating a circle path with .absarc, the shape does not extrude properly. 

for radius = 0.70
![image](https://cloud.githubusercontent.com/assets/22593502/19067293/4d0e1b52-8a15-11e6-85c5-b83b923eb0d1.png)

for radius = 0.72
![image](https://cloud.githubusercontent.com/assets/22593502/19067353/940eb61a-8a15-11e6-87df-76da54aed3a2.png)

for radius = 0.75 (It's fine!)
![image](https://cloud.githubusercontent.com/assets/22593502/19067378/c5e1b6f6-8a15-11e6-882e-b5f7d0b0f869.png)

Change the value for radius from 0.70 to 0.72 and 0.73 on this jsfiddle https://jsfiddle.net/henryJack/884s3tgw/3/ to see the problem for yourself.

I have also found this issue for closing other small shapes but this is the simplest working example.

##### Three.js version

- [ ] r81 (latest CDN)

##### Browser

- [x] All of them

##### OS

- [ ] Windows

##### Hardware Requirements (graphics card, VR Device, ...)

None

**Comment by Mugen87** [comment]
The jsfiddle logs the following warning if the radius value is e.g. `0.70` or `0.72`:

```
THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()
```

A potential problem in the triangulation process would explain the visual error of the mesh.

**Comment by Mugen87** [comment]
After some debugging if suppose the following [line](https://github.com/mrdoob/three.js/blob/dev/src/extras/ShapeUtils.js#L57) in `THREE.ShapeUtils` is responsible for the mentioned behavior.

```
( ( bx - ax ) * ( cy - ay ) ) - ( ( by - ay ) * ( cx - ax ) )
```

The above formula provides the area of a triangle. But you can use the result for other interesting things:

- c is to the left of (a,b) iff the area of the counterclockwise triangle (a,b,c) is positive
- if the area is negative, c is to the right of (a,b)
- if the area is zero, a b c are collinear

I don't know why the code does a comparison against an epsilon value. This should also do it:

```javascript
if ( ( ( bx - ax ) * ( cy - ay ) ) - ( ( by - ay ) * ( cx - ax ) ) ) <= 0  ) return false;
```

/ping @zz85 @WestLangley

**Comment by WestLangley** [comment]
Thanks, @Mugen87. I'll ping ZZ.
