### ISSUE TITLE
Objects disappear if camera position and object position have "large" values

### ISSUE THREAD

**Issue by eggeral** [mrdoob/three.js#9820]
##### Description of the problem 

When moving a perspective camera together with an object along x, the object disappears if x gets beyond values of 30_000_000_000 (about).

See this fiddle: http://jsfiddle.net/alegger/s4tx6yyu/

##### Three.js version

- [ ] Dev
- [ ] r81
- [x] r80
- [x] r53 (JSFiddle)

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
You shouldn't use such large values. 1 unit is 1 meter. Unless you're trying to visualise the universe such large value doesn't make sense. For such case you'll have to fake it.
