### ISSUE TITLE
THREE.Mirror breaks in VR

### ISSUE THREAD

**Issue by mkeblx** [mrdoob/three.js#9821]
THREE.Mirror smears/clamps in VR under certain conditions based on camera view/position, as seen below. Continuation of #9367. (See demo links from previous issue.)

![mirror-vr](https://cloud.githubusercontent.com/assets/293795/19098097/4f0d62c4-8a5f-11e6-8a51-9b2359fb017b.png)

Three.js r82dev, WebVR Chromium, Windows, Rift

**Comment by jampekka** [comment]
This is probably due to the mirror camera having different aspect ratio than the "main" camera. I can reproduce this without VR by changing the viewport aspect ratio after the mirror has been constructed.

**Comment by mrdoob** [comment]
https://threejs.org/examples/#webvr_sandbox
