### ISSUE TITLE
Collada LoadingManager doesnt work

### ISSUE THREAD

**Issue by DanilaGRob** [mrdoob/three.js#9822]
##### Description of the problem

Cant get the loading manager to work with collada loader can any one help me with it?
Manager doesnt output to console nothing,when i use :

``` js
loadingManager.onProgress = function(item, loaded, total){
        console.log(item, loaded, total);
        console.log("loaded all resources");
    };

    loadingManager.onLoad = function(){
        console.log("loaded all resources");

    };
```
##### Three.js version
- [ ] Dev
- [ ] r81
- [x] r74
##### Browser
- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Yeah, `ColladaLoader` doesn't support `LoadingManager` yet. Is `ColladaLoader2` good enough for your scene?

**Comment by DanilaGRob** [comment]
OK,ty for help ,but now, when i load my models, my loading screen is lagging, can i fix it somehow?

**Comment by Mugen87** [comment]
@DanilaGRob If you still have problems with your loading screen, please ask a question at stackoverflow. The actual problem of this issue is solved via `ColladaLoader2`.
