### ISSUE TITLE
PMREM size choice

### ISSUE THREAD

**Issue by Astrak** [mrdoob/three.js#9827]
Hello threejs,

First a huge thank you to @bhouston for his work few months ago on PMREMs that allows to use IBL with `MeshStandardMaterial` and have a real PBR workflow in a free library. I don't think any other webgl library is at this point and I am very proud to use threejs for such contributions. I recently began to use this PBR workflow a lot and I however have to say that there is a big limitation until now : the resolution limit of 256 that gets very visible pixels on reflective monotone surfaces. I would like to discuss a way to solve that depending on what purposes user can get.

In https://github.com/mrdoob/three.js/pull/8363 @bhouston removed the resolution argument in `PMREMGenerator.js` since it has to be coded elsewhere in the `MeshStandardMaterial` anyway, and also for performance reason, I guess it was about the realtime PMREM generation performance. Unfortunately on my machine generation times are over 70ms whatever the resolution is under 512, and increases from that value. My CPU/GPU configuration is rather decent. 

On the other hand, when one needs PMREM for a static scene it would be great to allow a really bigger resolution like 1024, ie the [max well-supported resolution](http://webglstats.com/) of 4096 in the shader. 

So what about first increasing the default resolution to 512 to prevent visible pixels at all roughness values ? Then can we imagine a way to set the resolution included in the shader and bring back the generator's resolution argument ? Or set the shader's resolution automatically from the pmrem ?

Thanks !

**Comment by Mugen87** [comment]
@Astrak Feel free to reopen if you still have performance issue with the new implementation (available since `R112`).  Notice that `PMREMGenerator` is now part of the core (located in `src/extras/`).
