### ISSUE TITLE
Triangle_Fan and Triangle_Strip don't seem to work correctly in Three.js

### ISSUE THREAD

**Issue by JetStarBlues** [mrdoob/three.js#9831]
##### Description of the problem 

The TriangleFanDrawMode and TriangleStripDrawMode don't seem to be working correctly in Three.js.

For example, I have these four vertices which I use to create a buffer,
```
[ 0.5,  0.9,
  0.5, -0.9,
 -0.5,  0.9,
 -0.5, -0.9   ]
```

When I draw the shape using raw webGL, these are the results I get:

*line_strip*
![gl_one](https://cloud.githubusercontent.com/assets/4354703/19202974/43b188a8-8c92-11e6-8c8c-410511a2bb36.PNG)

*triangle_fan*
![gl_three](https://cloud.githubusercontent.com/assets/4354703/19202989/574bd314-8c92-11e6-8875-d9d7d6ab024d.PNG)

*triangle_strip*
![gl_two](https://cloud.githubusercontent.com/assets/4354703/19202998/5fefd178-8c92-11e6-88da-9c526eb04cae.PNG)

When I draw the same shape using Threejs, with the code  below, these are the results I get:

```
mesh = new THREE.Line( geometry, material );
```
![threej_one](https://cloud.githubusercontent.com/assets/4354703/19203033/84f9e1ca-8c92-11e6-8ee9-bf8c63284420.PNG)

```
mesh = new THREE.Mesh( geometry, material );
mesh.drawMode = THREE.TriangleFanDrawMode;
```
![threej_three](https://cloud.githubusercontent.com/assets/4354703/19203065/a3ef2fea-8c92-11e6-8306-9e19f0d46be5.PNG)

```
mesh = new THREE.Mesh( geometry, material );
mesh.drawMode = THREE.TriangleStripDrawMode;
```
*nothing*
![threej_two](https://cloud.githubusercontent.com/assets/4354703/19203149/efe2e900-8c92-11e6-94a2-719ee996aa47.PNG)

##### Three.js version

- [x] Dev
- [ ] r81
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by JetStarBlues** [comment]
Here are JSFiddles for the above to help with debugging.

- [Raw webGL][0]
 - see function `draw`
- [Threejs][1]
 - see `mesh.drawMode`

[0]: https://jsfiddle.net/jetRed/1cc4zbk6/
[1]: https://jsfiddle.net/jetRed/za9po4qj/

**Comment by takahirox** [comment]
It seems like the different comes from culling, not Three.js issue.

Try to add `gl.enable( gl.CULL_FACE );` into Raw webGL JSFiddle or
`material.side = THREE.DoubleSide;` into Three.js JSFiddle.

**Comment by JetStarBlues** [comment]
Ah, I see. Thank you!
