### ISSUE TITLE
THREE.Vector3.setComponent does not return vector instance (missing return statement in Vector3 source code)

### ISSUE THREAD

**Issue by matthias-w** [mrdoob/three.js#9835]
THREE.Vector3.setComponent does not return vector instance (missing return statement in Vector3 source code)

**Comment by mrdoob** [comment]
Would you like to do a PR with the fix?

**Comment by matthias-w** [comment]
Yes I'd like to do that. I guess I'll need appropriate access rights to do a pull request, right (sorry for the stupid question but I never worked with git(hub) before)?
btw: thanks @mrdoob  for the great work on Threejs

**Comment by Mugen87** [comment]
@matthias-w It would be great if you also adjust `.setComponent()` in `Vector2` and `Vector4`.

BTW: You need no special permissions. Just have a look at these sites:

[How to contribute to Three.js?](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js)
[A Contributor's Guide to the Git Galaxy](https://github.com/mrdoob/three.js/wiki/A-Contributor%27s-Guide-to-the-Git-Galaxy)

**Comment by matthias-w** [comment]
Hello @Mugen87 thanks for your help. I have created a pull request #9840 fixing also `setComponent` in `Vector2` and `Vector4` as you suggested. I hope I did nothing wrong ;)
