### ISSUE TITLE
WebVR does not work when navigating between examples without first Exiting VR.

### ISSUE THREAD

**Issue by caseyyee** [mrdoob/three.js#9837]
##### Description of the problem 

Steps to reproduce:

1. Open up any three WebVR example.

2. Click _Enter VR_ , Content is rendered into the headset.

3. Navigate to another three WebVR example.

4. Click _Enter VR_ -> Note that nothing is rendered to the headset (just shows black).

To move between examples, you must first _Exit VR_ before loading and moving to the next example.   The solution may be to `exitPresent()` on page unload.

This only effects experimental Chromium VR builds (webvr.info/get-chrome).   It seems to work fine in Firefox.   I'm not exactly sure where the responsibility lies here for this issue: a issue that should be fixed in the browser, or if it's an issue better addressed here in three).   Though, my feeling is that content shouldn't have to explicitly call exitPresent.

cc @toji @kearwood

##### Three.js version

- [ x] Dev
- [ ] r81
- [ ] ...

##### Browser

- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

Oculus Rift.  
Win 10, GTX 1080

**Comment by mrdoob** [comment]
@toji @kearwood would indeed be great to hear your thoughts whenever you have a minute 😊

**Comment by AVGP** [comment]
@mrdoob @toji This is an interesting question I was pondering for a while now:

What is the expected browser behaviour for: Tab 1 is presenting and tab 2 is requesting presentation.
[The spec](https://w3c.github.io/webvr/#dom-vrdisplay-requestpresent) is a little thin on it:

> The user agent MAY reject the promise for any other reason.

I'd say that "Something else is currently presenting on this device" is a valuable rejection reason, but it's not what's happening right now.

Meanwhile: Shall:

a. add `exitPresent` as the `unload` /  `window.onblur` event handler to the examples?
b. have `VREffect` manage these event handlers automatically when `requestPresent` was successfully called?

I'd err on the side of (a) until there is clarification from the WebVR specification. I'll add that as an issue to the specs..

**Comment by toji** [comment]
This feels like a bug in Chrome. Navigating away from content that's
presenting should end presentation. I think Chrome handles that correctly
at a page level, but maybe not a frame level? In any case, I don't think
this is Three.js' problem to solve.
