### ISSUE TITLE
Create a method to print out current three.js version.

### ISSUE THREAD

**Issue by ddemott** [mrdoob/three.js#9843]
##### Description of the problem 

While it might be apparent in the direct site, it often happens that multiple versions of three.js might be floating around on your desktop or dev environments.  A suggestion would be to create a simple method that would print out the current version of Three.js

##### Three.js version

- [ ] Dev
- [ X] r81
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
You can do this:
```javascript
console.log( THREE.REVISION );
```

**Comment by ddemott** [comment]
I did not know that.  Thanks!
