### ISSUE TITLE
Updating BufferAttribute count

### ISSUE THREAD

**Issue by gelibolue** [mrdoob/three.js#9846]
##### Description of the problem

I'm using [this library](https://github.com/squarefeet/ShaderParticleEngine) which create gpu particle systems. 
After [this commit](https://github.com/mrdoob/three.js/pull/9658) creating multiple Particle Emitters does not work because buffer sizes become fixed and there's no way to update. 
[This example](http://squarefeet.github.io/ShaderParticleEngine/examples/multipleEmitters.html) shows only one emitter with r81, works fine with r80.

I fixed the problem by updating BufferAttribute.count when BufferAttribute.needsUpdate called.
##### Three.js version
- [ ] Dev
- [x] r81
- [ ] ...

**Comment by mrdoob** [comment]
Kind of related: #9631

**Comment by Mugen87** [comment]
This should be fixed by `ShaderParticleEngine` now.
