### ISSUE TITLE
Closed surface with half CylinderGeometry

### ISSUE THREAD

**Issue by davejack1** [mrdoob/three.js#9847]
In [this](https://threejs.org/docs/index.html?q=cyli#Reference/Geometries/CylinderGeometry) example, when you change the `thetaStart` and `thetaLength` parameters from the dropdown menu, the geometry is not completely closed, for example the half cylinder does not have its side face. How can I make it a closed surface geometry? Is there an option or do I have to draw a it manually on my own?

**Comment by Mugen87** [comment]
There is no built-in option for doing this. You have to define your own custom type based on `CylinderBufferGeometry` and close the geometry manually.

An other solution is to create the geometry in Blender and import it in your application. That's maybe easier than generating the geometry in your code.
