### ISSUE TITLE
Wildcard import in three/src/Three causes bigger bundle size

### ISSUE THREAD

**Issue by dionysiusmarquis** [mrdoob/three.js#9852]
##### Description of the problem 

Hey,
I'm using npm three in my own rollup project. I'm trying to keep the bundle clean and small by only importing needed modules. It is already doable when I'm importing modules like this:
```
import { Scene } from 'three/src/scenes/Scene'
import { PerspectiveCamera } from 'three/src/cameras/PerspectiveCamera'
import { BoxGeometry } from 'three/src/geometries/Geometries'
import { MeshBasicMaterial } from 'three/src/materials/Materials'
import { Mesh } from 'three/src/objects/Mesh'
import { WebGLRenderer } from 'three/src/renderers/WebGLRenderer'
```

The more intuitive way would be:
```
import {
  Scene,
  PerspectiveCamera,
  BoxGeometry,
  MeshBasicMaterial,
  Mesh,
  WebGLRenderer
} from 'three/src/Three'
```

But I think the wildcard imports like `export * from './materials/Materials.js'` forcing rollup to bundle more modules than necessary - even with tree-shaking.

##### Three.js version

- [ ] Dev
- [x] r81
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Isn't this a Rollup issue?

**Comment by dionysiusmarquis** [comment]
Mhm, maybe. I remembered that sentence from the webpack 2 tree-shaking implementation:

```
In the following cases it's not possible to detect usage:

- import * as ... when used indirectly
- CommonJS or AMD c…
```

I thought it might be the same for export. I will ask over there :)

**Comment by Benjamin-Dobell** [comment]
@dionysiusmarquis You can import intuitively, you might have an incorrect rollup config. I'm imported like:

```
import {
    CircleGeometry,
    Geometry,
    Line,
    LineBasicMaterial,
    Mesh,
    MeshBasicMaterial,
    Object3D,
    Vector3
} from 'three';
```

Make sure you've passed `jsnext: true` in the options to the nodeResolve plugin.

```
export * from './materials/Materials.js'
```

I'm not sure about this issue specifically. I'm using `ObjectLoader` which inherently means every `Material` type must be bundled.

Nonetheless, I think it's fair for @mrdoob to close this, it does seem like a Rollup concern. The Rollup devs are great and in my experience will go above and beyond to sort out issues. Use http://rollupjs.org/ to create a repro, then copy and paste the resultant URL into an issue in Rollup's Github issue tracker.

**Comment by Benjamin-Dobell** [comment]
Whoops, just realised `jsnext:main` hasn't yet been added to `package.json`. I put it in my own fork! `import { <blah> } from 'three';` won't work unless `jsnext:main` is available to you. Nonetheless, your issue about bundle size is still a Rollup issue, not three.js.

**Comment by dionysiusmarquis** [comment]
Thank you guys <3
