### ISSUE TITLE
Large leak on integrated intel Macbooks

### ISSUE THREAD

**Issue by kevineschmidt** [mrdoob/three.js#9854]
##### Description of the problem 
I have a user seeing large leaks with THREE.js when resizing the window.  It seems to be specific to Macs (macbooks?) Integrated-only Intel graphics chips.  The memory does not show up under the browser memory profile.  It shows up as total system memory dropping in Activity Monitor or top/htop.     With Activity Monitor, it may ramp up main memory usage for a while, then memory compression kicks in and that starts growing.  In some cases, memory usage ramps up by GB in seconds.  It never comes back down until the browser is closed.  Eventually the browser will crash.  

The Intel Iris Graphics 6100 seems to be particularly bad, perhaps?

Possibly related issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=470234

I realize (and suspect) this may be a graphics driver issue.  I'm hoping you guys might know a work around.

##### Three.js version

- [ ] Dev
- [x] r81
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Intel Integrated graphics on a Mac (not a dual GPU device)

**Comment by mrdoob** [comment]
Sounds like a graphics driver issue indeed. You should probably report this to Intel instead.
