### ISSUE TITLE
LensFlarePlugin breaks on iOS10 Safari (copyTexImage2D concurrency)

### ISSUE THREAD

**Issue by mlknz** [mrdoob/three.js#9856]
##### Description of the problem

LensFlarePlugin works incorrectly on iOS10 mobile safari (iPad3 mini). Position of flares changes on camera movement causing spikes in application. Spikes are followed by weird camera position. Couldn't reproduce on multiple other iOS versions. Report on [LensFlarePlugin](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/plugins/LensFlarePlugin.js) code digging:
- commenting rows 270 - 351 leaves spikes on place
- commenting `gl.copyTexImage2D( gl.TEXTURE_2D, 0, gl.RGB, screenPositionPixels.x, screenPositionPixels.y, 16, 16, 0 );` in addition removes spike completely.
- changing parameters of `gl.copyTexImage2D` call doesn't help
- **`gl.finish()` call before `gl.copyTexImage2D` fixes issue**  (and drops FPS)
- `gl.getError()` returns 0 around `gl.copyTexImage2D` call

[Link to WebGL specification](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.8).

Any thoughts on that?
##### Three.js version
- [x] r82dev
- [x] r81
- [x] r75
##### Device
- [x] iPad 3 mini
##### Browser
- [x] Mobile Safari 10
##### OS
- [x] IOS 10.0.2
##### Any camera controls?
- [x] OrbitControls

**Comment by Mugen87** [comment]
Can you share a screenshot of the problem? Unfortunately, i have no iOS 10 device for testing right now.

**Comment by mlknz** [comment]
@Mugen87 sure, I have captured a [video](https://drive.google.com/file/d/0B6ZJhPcQ4rzKc3RCYW1tS0dWSGs/view?usp=sharing). Actually, scene is updated when `LensFlarePlugin.render()` stops passing to `gl.copyTexImage2D` call (check at row 258).

**Comment by Mugen87** [comment]
[LensFlare](https://github.com/mrdoob/three.js/blob/dev/examples/js/objects/LensFlare.js) is now part of the examples. If this issue still exists, you can perform call of `renderer.context.finish()` after `renderer.copyFramebufferToTexture()` without changing the core of the library.
