### ISSUE TITLE
AnimationMixer finished event fires prematurely

### ISSUE THREAD

**Issue by fallenoak** [mrdoob/three.js#9857]
##### Description of the problem

As far as I understand it, the `finished` event on `AnimationMixer` should only fire when an action has finished.

In practice, it seems to often fire just before I'd expect.

For a 1000ms clip, at the point in time the `finished` fires, `action.time` will often be 983.4ms. This looks a lot like a single frame gap (ie 16.6ms) from the end. In addition, the property being manipulated will be just short (say, by `16.6 / 1000`) of the lerp to the terminal value in a track associated with the clip.

Is this intended behavior? If so, can an event be added that only fires when the action is truly finished? If not, is this a matter of moving the location of the logic that fires the event to be a bit later in its code path?
##### Three.js version
- [x] Dev
- [ ] r81
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by takahirox** [comment]
Could I have an example on JSFiddle (or somewhere)?
And how did you get the exact firing time?

If what you did is like

    mixer.addEventListener( function( e ) { console.log( e.action.time ); } );

it's just showing the time before adding the last delta time.

https://github.com/mrdoob/three.js/blob/fcd6fd23b6612db1579c7d907fa0ec31156082a5/src/animation/AnimationAction.js#L548

**Comment by tschw** [comment]
Right... Thanks for looking into it. Yes, the last delta time is not yet applied when the event fires. I guess removing the two lines that say `this.time = time;` and adding them right before the events are fired, plus one in an `else` [here](https://github.com/mrdoob/three.js/blob/fcd6fd23b6612db1579c7d907fa0ec31156082a5/src/animation/AnimationAction.js#L576) will fix it.

**Comment by fallenoak** [comment]
Thanks for the insight, @takahirox and @tschw.

What you've said about `action.time` not being updated before the event fires would fit with what I'm seeing, but I'm confused why the property value (as observed after a breakpoint in the Chrome debugger) would also fail to have reached the terminal value in the track at the time the event fires.

I'll see if I can create a repro case on jsfiddle this weekend.

**Comment by takahirox** [comment]
BTW, I think 'finished' and 'loop' should be fired after accumulation here.

https://github.com/mrdoob/three.js/blob/fcd6fd23b6612db1579c7d907fa0ec31156082a5/src/animation/AnimationAction.js#L377

**Comment by fallenoak** [comment]
@takahirox I wound find that much more intuitive.

Still haven't had a chance to put together a jsfiddle showing the not-yet-final-value issue I mentioned originally, but I'll try do that this week.
