### ISSUE TITLE
FBX Binary format not supported?

### ISSUE THREAD

**Issue by RicoLiu** [mrdoob/three.js#9860]
##### Description of the problem

![qq 20161014151051](https://cloud.githubusercontent.com/assets/12722992/19379629/826cd7e4-9225-11e6-89bb-606f27ceb235.png)

FBXLoader only supports FBX text format?
##### Three.js version
- [ ] Dev
- [x] r81
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
Yes. Right now it supports only ASCII format in version 7.

**Comment by RicoLiu** [comment]
Three.js version : r77

![qq 20161014175807](https://cloud.githubusercontent.com/assets/12722992/19383647/0c558034-9238-11e6-8612-76ca2e2e5ea5.png)

Why?

**Comment by makc** [comment]
> Why?

because there is no reference open-source implementation? if you know one, I would be curious to see it.

**Comment by makc** [comment]
Ah, wait, I thought it was about binary. For ASCII FBX below v7, I had the code [here](https://github.com/AlternativaPlatform/Alternativa3D/tree/8.29.ParserFBX) and a bunch of test models somewhere in my hard drive.

**Comment by takahirox** [comment]
Anyone here who made or is making binary FBX parser?
If not, I'm feeling like trying to make that...

**Comment by makc** [comment]
you have to love reverse engineering stuff to do this ) and, you may be lucky if it is simple tags, but if they serialize every data type uniquely, you are properf-ed: you're facing tweaking one number per model and saving it to see what has changed, at a time.

**Comment by takahirox** [comment]
Thanks for the advice.
I've achieved to make a FBX binary parser by seeing this site now.

https://code.blender.org/2013/08/fbx-binary-file-format-specification/

I'll try to make ObjectParser which makes an object
from the result of the binary parser next.

**Comment by makc** [comment]
oh wow, someone already went through the hell ,and there are specs )

**Comment by yamahigashi** [comment]
https://banexdevblog.wordpress.com/2014/06/23/a-quick-tutorial-about-the-fbx-ascii-format/
I think this link also is great stuff for to do that.

**Comment by Mugen87** [comment]
@takahirox It would be great if the new parser would have a similar structure like `THREE.PLYLoader`. This implementation uses an uniform logic for creating the `THREE.BufferGeometry` object after parsing the data from an ASCII or Binary input (see usage of method `handleElement`).

**Comment by takahirox** [comment]
ok I'll try. And I'm thinking if I also can use that for `MMDLoader`.

BTW does anyone know if FBX binary format remains the same even below version 7?

**Comment by RicoLiu** [comment]
I have no idea.

Maybe @mrdoob knows?

**Comment by makc** [comment]
@takahirox did you share your binary fbx parser anywhere?

**Comment by takahirox** [comment]
Not yet... I'll do soon!

**Comment by takahirox** [comment]
Sorry I've been busy lately... but soon soon!

**Comment by jmsaulnier** [comment]
Awesome \o/

**Comment by takahirox** [comment]
I'm gonna start to work on FBX binary parser again from April.
LMK if anyone is in hurry.

**Comment by modulesio** [comment]
@takahirox Do you have something rough to share? We're doing a presentation at the end of the week and could really use FBX binary loading for the demo.

**Comment by adam-clarey** [comment]
Hi @takahirox I'm actually in a hurry, is there any update on this? I can help where able, but this is all still new to me.

**Comment by takahirox** [comment]
I'm just starting to work on that again.
At least, I still need some weeks to share that.

**Comment by adam-clarey** [comment]
How many weeks do you think?

**Comment by takahirox** [comment]
Hm, maybe two or three weeks?

**Comment by adam-clarey** [comment]
Just out of curiosity, could this be done in a week or so if i were able to sponsor some of the dev work?

**Comment by takahirox** [comment]
Well, I can't promise but I'll try.
Do you have any specific models data you can share?
Wanna work with them as reference.

**Comment by adam-clarey** [comment]
[testfile.fbx.zip](https://github.com/mrdoob/three.js/files/964433/testfile.fbx.zip)
This is similar to what we need if it helps

**Comment by mrdoob** [comment]
In the meantime...

For https://with.in/watch/under-neon-lights/ we used plain-text FBX but we changed the extension to .fbx.txt so the server would gzip it. I also optimised quite a lot the `FBXLoader2`. It ended up being a pretty decent workflow.

I wonder if there is anything`FBXLoader` supports that `FBXLoader2` doesn't or we can replace it already...

@kyle-larson?

**Comment by Mugen87** [comment]
The FBX [example](https://threejs.org/examples/webgl_loader_fbx.html) already uses `FBXLoader2`.

**Comment by Kyle-Larson** [comment]
@mrdoob The only difference between the FBXLoader and FBXLoader2 is the use of Index buffers.  FBXLoader2 does not use index buffers.  Other than that, FBXLoader2 should include all the features of the previous loader.

**Comment by mrdoob** [comment]
Ah! Time to replace it then 👌

**Comment by adam-clarey** [comment]
Is there any update on this guys? Happy to help out where I can.

**Comment by takahirox** [comment]
Do you have a text file version of testfile.fbx.zip?
I wanna compare.

**Comment by adam-clarey** [comment]
[testfile_ascii.fbx.zip](https://github.com/mrdoob/three.js/files/976247/testfile_ascii.fbx.zip)

**Comment by takahirox** [comment]
Binary parser progress...

![image](https://cloud.githubusercontent.com/assets/7637832/25732024/6344846a-3186-11e7-80be-c0691a4cdda0.png)

@adam-clarey 

Can you share the screenshot of the model?
Even the text file couldn't be loaded on the Three.js.

**Comment by takahirox** [comment]
Another model's screenshot....

![image](https://cloud.githubusercontent.com/assets/7637832/25734374/f73ab250-319c-11e7-99e5-00c835788d34.png)

Model: https://free3d.com/3d-model/robot-2162.html

**Comment by mrdoob** [comment]
Looking good! 😀

**Comment by RicoLiu** [comment]
Thank you all!

**Comment by adam-clarey** [comment]
I'll try and upload a screenshot soon. Essentially my use case is being able to bundle in material images and model into a single file

**Comment by adam-clarey** [comment]
[block.fbx.zip](https://github.com/mrdoob/three.js/files/979324/block.fbx.zip)
<img width="277" alt="screen shot 2017-05-05 at 15 19 12" src="https://cloud.githubusercontent.com/assets/907933/25749393/4944efa8-31a6-11e7-84de-53bfa2636b32.png">

Here is a simple block with an image material baked into the fbx with an accompanying image of what it looks like in blender

**Comment by takahirox** [comment]
No burger-screen.jpg in the zip file.

**Comment by takahirox** [comment]
You mean, the image data should be in the fbx file?

**Comment by adam-clarey** [comment]
Yes. I may have exported that model incorrectly

**Comment by takahirox** [comment]
I can't find the image data in the fbx binary data...
Let me know if anyone knows about it.

**Comment by adam-clarey** [comment]
maybe try this one
[block2.fbx.zip](https://github.com/mrdoob/three.js/files/980934/block2.fbx.zip)

**Comment by takahirox** [comment]
Still can't find...
Are those files be loadable on other viewers?

Please let me know if anyone knows baked image data specification.

**Comment by jostschmithals** [comment]
I just tried to open `block2.fbx.zip` with blender and with 3ds max. Both show only the filename, but no image. It seems that there is only the reference to `.../Users/adamclarey/Documents/burger-screen.jpg` in the file.

**Comment by takahirox** [comment]
Yup, my parser extracts the file name but no image data.

**Comment by adam-clarey** [comment]
Ok. I'm obviously doing something wrong. Blender isn't the most intuitive app to use. I'll try something else

**Comment by jostschmithals** [comment]
I never heard that image data could be baked into a 3D export/import format (but only relative paths to the ressources). 

Is this even possible?

**Comment by jostschmithals** [comment]
I just noticed: it is possible!

I will create such a test file and post it here.

**Comment by adam-clarey** [comment]
Great stuff.

**Comment by jostschmithals** [comment]
This FBX was created in 3ds max and exported with the "embed media" option:
[TestcubeWithImage.zip](https://github.com/mrdoob/three.js/files/981013/TestcubeWithImage.zip)

Screenshot from 3ds max:

![testcubescreenshot](https://cloud.githubusercontent.com/assets/5700294/25773761/c0d7334a-3283-11e7-9b3c-00adcae78865.jpg)

Opened in blender (on a different machine):

![screenshot_blender](https://cloud.githubusercontent.com/assets/5700294/25773849/4579be78-3285-11e7-8c8d-c6464cf028ae.JPG)

In blender I didn't find an option to export an FBX with baked images up to now.

**Comment by jostschmithals** [comment]
@takahirox Here is the same file, created in 3ds max, but exported without the "embed media" option:

[Testcube.zip](https://github.com/mrdoob/three.js/files/981107/Testcube.zip)

It might be interesting for comparising purposes.

If you need other files for testing, feel free to post it here.

**Comment by takahirox** [comment]
I found data looking like image data under Content property of TestcubeWithImage.fbx.
This doesn't exist in other binary files posted in this thread.

I'll take a look closer...

![image](https://cloud.githubusercontent.com/assets/7637832/25776615/0d57c9ee-32fe-11e7-9e09-dd20a4f13d05.png)

**Comment by takahirox** [comment]
Progress... 😄 

![image](https://cloud.githubusercontent.com/assets/7637832/25776992/ffe57084-3309-11e7-8ae5-83faf6366bb5.png)

**Comment by takahirox** [comment]
So, embedded texture looks ok now.
Can anyone share the binary fbx including animation if you have?

**Comment by jostschmithals** [comment]
Here are 3 test files with different kinds of animations:

[AnimationTranslate.zip](https://github.com/mrdoob/three.js/files/981500/AnimationTranslate.zip)
[AnimationBones.zip](https://github.com/mrdoob/three.js/files/981501/AnimationBones.zip)
[AnimationMorph.zip](https://github.com/mrdoob/three.js/files/981505/AnimationMorph.zip)

**Comment by vinaysshenoy** [comment]
@takahirox Our team has been looking for a three.js binary FBX parser for a while now, and this looks great! Have you made the source available anywhere yet? For our purposes, we need to be able to extract the meshes, the normals, UVs and the visual scene from the FBX, and it seems that that is working fine.

If the source is available, it would be great if you could point me to where it is.

Thanks for the great work!

**Comment by takahirox** [comment]
https://github.com/takahirox/three.js/blob/FixLoaderBinaryParser/examples/js/loaders/FBXLoader2.js

Note that this's very temporal.
I need to clean up and optimize the code.
And functionality could be broken right now.

**Comment by jostschmithals** [comment]
@takahirox Please note: After some testing in different programs I updated my previous comment.

**Comment by takahirox** [comment]
@jostschmithals 

Thanks.
Translate and Bone seem working now.
FBXLoader doesn't support Morph animation yet even with ascii file.
It'd be our next work....

**Comment by adam-clarey** [comment]
I've tried loading the testcube file in my three.js project but nothing loads.
I get a 404 on the image file, after inspecing the FBXTree object I can see it still holds a reference to the absolute filepath.

<img width="511" alt="screen shot 2017-05-07 at 15 01 23" src="https://cloud.githubusercontent.com/assets/907933/25781800/1755c0c6-3336-11e7-9a84-e37ea0a78a01.png">
<img width="1412" alt="screen shot 2017-05-07 at 14 59 00" src="https://cloud.githubusercontent.com/assets/907933/25781799/1751bb16-3336-11e7-899b-48c8ceef5808.png">

**Comment by jostschmithals** [comment]
I just tested it (on a machine where the original jpg is not available), and it works fine.

Note: You have to use
https://github.com/takahirox/three.js/blob/FixLoaderBinaryParser/examples/js/loaders/FBXLoader2.js,
but the loader is simply called `THREE.FBXLoader` (without the version number 2).

**Comment by adam-clarey** [comment]
That's what I'm using. I'll investigate further

**Comment by takahirox** [comment]
Try TestcubeWithImage.fbx

**Comment by jostschmithals** [comment]
@ In my test which is working fine I get exactly the same console output like @adam-clarey - except the `GET ... 404` message.

BTW: I tested on Windows 10.

**Comment by takahirox** [comment]
Progress...
Animation seems working fine now 😄 

![image](https://cloud.githubusercontent.com/assets/7637832/25785666/8fdb5bd8-33c1-11e7-94b1-8b55a60e4289.png)

**Comment by adam-clarey** [comment]
Can you paste the code you are using to load the model please? For some reason it just doesn't load for me.

**Comment by adam-clarey** [comment]
I've tried substituting the Testcube file into the webgl_loader_fbx.html example (also swapping the FBXLoader2.js file) and it still doesn't render the model.

**Comment by jostschmithals** [comment]
@adam-clarey That's exactly what I did (deactivating the animations, of course), and it worked without any other changes.

**Comment by adam-clarey** [comment]
how bizarre...

**Comment by adam-clarey** [comment]
![screen shot 2017-05-08 at 09 50 40](https://cloud.githubusercontent.com/assets/907933/25797110/d51f21e0-33d3-11e7-9f00-4c9ffbdcdeca.png)

**Comment by jostschmithals** [comment]
And it is sure that you are using **TestcubeWithImage.fbx** (as @takahirox pointed out)?
Any further error messages?
Which OS are you using?
The same in all browsers?

**Comment by adam-clarey** [comment]
AAHHH, what a numpty i am! I just scrolled up until I found the first testcube file.

My mistake

**Comment by hmtri1011** [comment]
Hi! I'm also getting this error when trying to load an external .fbx model which is export from Autodesk. Can anyone give me a solution for this

Thank you!

**Comment by RicoLiu** [comment]
> https://github.com/takahirox/three.js/blob/FixLoaderBinaryParser/examples/js/loaders/FBXLoader2.js
>Note that this's very temporal.
I need to clean up and optimize the code.
And functionality could be broken right now.

@hmtri1011

**Comment by hmtri1011** [comment]
@RicoLiu This is what I got when used THREE.FBXLoader. I implemented an loader_fbx example by replace the url of the model.

And when I used THREE.FBXLoader2 i get the errorerror `THREE.FBXLoader2 is not a constructor`


![image](https://cloud.githubusercontent.com/assets/16288424/25888392/324681a2-3590-11e7-86b4-8192f1c76c53.png)

**Comment by jostschmithals** [comment]
You can use the webgl_loader_fbx.example:
1. load https://github.com/takahirox/three.js/blob/FixLoaderBinaryParser/examples/js/loaders/FBXLoader2.js
instead of the FBXLoader2.js of the current threejs branch,
2. call in the binary section of the example `THREE.FBXLoader` (**without the version number 2 !**),
3. (deactivate the animations),

and it should work.

**Comment by hmtri1011** [comment]
@jostschmithals I follow your step then getting a new error `Zlib is not defined`

**Comment by jostschmithals** [comment]
Seems that your model file is compressed?

**Comment by hmtri1011** [comment]
![image](https://cloud.githubusercontent.com/assets/16288424/25890686/a984a3d6-3598-11e7-8500-77cecf52d027.png)
Full Error what I get

**Comment by takahirox** [comment]
Add this line in your example.

		<script src="js/libs/zlib_and_gzip.min.js"></script>

**Comment by hmtri1011** [comment]
![image](https://cloud.githubusercontent.com/assets/16288424/25903851/c9ef88a0-35c7-11e7-833a-75f688109269.png)
Done, and another error appeared.... :(

**Comment by jostschmithals** [comment]
As I wrote above, you have to deactivate the animation code (in the loading section and in the render loop), if you use the example code with a model file that doesn't contain any animations.

**Comment by adam-clarey** [comment]
I'm experiencing a different issue, im sure is related to materials. My problem is that under certain conditions some fbx models render and some dont.

To reproduce:
in the webgl_loader_fbx.html example file, just inside init() place the following code to create an environment

```
 var loadSkyDomeAndGroundBowl = function(scene, onLoad, onProgress, onError) {
                var pathtop="path/to/top.jpg";
                var pathbot="path/to/bottom.jpg";
                var radius=40;
                var bottomtopfactor=0.1;
                var sinkin=0.05;

                var texturetop;
                var texturebot;

                var onTextureLoadTop=function(texture) {
                  console.log('onTextureLoadTop');
                  texturetop=texture;
                  onTextureLoaded();
                };
                var onTextureLoadBot=function(texture) {
                  console.log('onTextureLoadBot');
                  texturebot=texture;
                  onTextureLoaded();
                };

                var onTextureProgress=function(xhr) {
                  console.log('onTextureProgress');
                  if(onProgress)
                    onProgress('Loading sky dome / ground bowl texture');
                };
                var onTextureError=function(xhr) {
                  console.log('onTextureError');
                  if(onError)
                    onError('Error loading sky dome / ground bowl texture');
                };

                var onTextureLoaded=function() {
                  console.log('onTextureLoaded');
                  if(texturetop && texturebot) {
                    console.log('onTextureLoaded 2');
                    var geometrytop = new THREE.SphereGeometry( radius*10, 600, 400, 0, Math.PI*2, 0, Math.PI*0.5);
                    var materialtop = new THREE.MeshBasicMaterial();

                    materialtop.map = texturetop;
                    materialtop.side = THREE.BackSide;
                    var skydome = new THREE.Mesh( geometrytop, materialtop );
                    skydome.position.y=bottomtopfactor*radius+sinkin;
                    scene.add( skydome );

                    var geometrybot = new THREE.SphereGeometry( radius, 60, 40, 0, Math.PI*2, Math.PI*0.5, Math.PI*0.5);
                    var materialbot = new THREE.MeshBasicMaterial();
                    materialbot.map = texturebot;
                    materialbot.side = THREE.BackSide;
                    var groundbowl = new THREE.Mesh( geometrybot, materialbot );
                    groundbowl.scale.set(1,bottomtopfactor,1);
                    groundbowl.position.y=bottomtopfactor*radius+sinkin;
                    scene.add( groundbowl );

                    if(onLoad)
                      onLoad();
                  }
                };

                var loader=new THREE.TextureLoader();
                loader.load(pathtop, onTextureLoadTop, onTextureProgress, onTextureError);
                loader.load(pathbot, onTextureLoadBot, onTextureProgress, onTextureError);
              }
```

Which basically just adds a skydome and ground with 2 images.

Then after the scene is initialized, run: loadSkyDomeAndGroundBowl(scene);

You will see that the 2 fbx models load and render fine within this new environment.

Now, if you replace the xsi_man_skinning.fbx reference with the TestcudeWithImages.fbx (also comment out animation code) you will see that the code does not render at all.

I've noticed this with other fbx files too. Binary fbx files do not seem to be compatible with environments.

Or I could just be doing something wrong...

**Comment by hmtri1011** [comment]
This is my example code:
`<body>
	<div id="info">
		<a href="http://threejs.org" target="_blank">three.js</a> - FBXLoader test
	</div>

	<script src="../build/three.js"></script>

	<script src="js/controls/OrbitControls.js"></script>

	<script src="js/curves/NURBSCurve.js"></script>
	<script src="js/curves/NURBSUtils.js"></script>
	<script src="js/loaders/FBXLoader2.js"></script>

	<script src="js/Detector.js"></script>
	<script src="js/libs/stats.min.js"></script>
	<script src="js/libs/zlib_and_gzip.min.js"></script>
	<script>
		if (!Detector.webgl) Detector.addGetWebGLMessage();

		var container, stats, controls;
		var camera, scene, renderer, light;

		var clock = new THREE.Clock();

		var mixers = [];

		init();

		function init() {

			container = document.createElement('div');
			document.body.appendChild(container);

			camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 1, 2000);

			scene = new THREE.Scene();

			// grid
			var gridHelper = new THREE.GridHelper(28, 28, 0x303030, 0x303030);
			gridHelper.position.set(0, - 0.04, 0);
			scene.add(gridHelper);

			// stats
			stats = new Stats();
			container.appendChild(stats.dom);

			// model
			var manager = new THREE.LoadingManager();
			manager.onProgress = function (item, loaded, total) {

				console.log(item, loaded, total);

			};

			var onProgress = function (xhr) {

				if (xhr.lengthComputable) {

					var percentComplete = xhr.loaded / xhr.total * 100;
					console.log(Math.round(percentComplete, 2) + '% downloaded');

				}

			};

			var onError = function (xhr) {

				console.error(xhr);

			};

			var loader = new THREE.FBXLoader(manager);
			loader.load('models/fbx/accient_2_full.fbx', function (object) {

				//object.mixer = new THREE.AnimationMixer(object);
				//mixers.push(object.mixer);

				//var action = object.mixer.clipAction(object.animations[0]);
				//action.play();

				scene.add(object);


			}, onProgress, onError);

			loader.load('models/fbx/nurbs.fbx', function (object) {

				scene.add(object);

			}, onProgress, onError);

			renderer = new THREE.WebGLRenderer();
			renderer.setPixelRatio(window.devicePixelRatio);
			renderer.setSize(window.innerWidth, window.innerHeight);
			renderer.setClearColor(0x000000);
			container.appendChild(renderer.domElement);

			// controls, camera
			controls = new THREE.OrbitControls(camera, renderer.domElement);
			controls.target.set(0, 12, 0);
			camera.position.set(2, 18, 28);
			controls.update();

			window.addEventListener('resize', onWindowResize, false);

			light = new THREE.HemisphereLight(0xffffff, 0x444444, 1.0);
			light.position.set(0, 1, 0);
			scene.add(light);

			light = new THREE.DirectionalLight(0xffffff, 1.0);
			light.position.set(0, 1, 0);
			scene.add(light);

			//animate();

		}

		function onWindowResize() {

			camera.aspect = window.innerWidth / window.innerHeight;
			camera.updateProjectionMatrix();

			renderer.setSize(window.innerWidth, window.innerHeight);

		}

		//

		function animate() {

			requestAnimationFrame(animate);

			if (mixers.length > 0) {

				for (var i = 0; i < mixers.length; i++) {

					mixers[i].update(clock.getDelta());

				}

			}

			stats.update();

			render();

		}

		function render() {

			renderer.render(scene, camera);

		}
	</script>

</body>`

**Comment by jostschmithals** [comment]
@adam-clarey I've tested it, and the reason that you are not seeing the cube is that it sits under the ground plane (if you orbit with the camera you should see it). Besides this all is working fine for me with your code.

**Comment by jostschmithals** [comment]
@takahirox: The mesh inside the group created by FBXLoader is translated and rotated, so that the pivot point is not placed in the center of the cube, but in the center of the upper side. This seems to be a minor bug?

**Comment by jostschmithals** [comment]
@hmtri1011 You have deactivated your animate() function. Therefore your scene is not rendered at all 😉

**Comment by hmtri1011** [comment]
@jostschmithals tks :D it 's work now

**Comment by adam-clarey** [comment]
Good spot @jostschmithals, thanks.

Should it matter what binary version the file is? I've got fbx files with version 7400 that render fine, but one with version 7500 and it errors out.

"FBXLoader: Unknown property type " 
where the variable 'type' is an empty string

**Comment by jostschmithals** [comment]
@adam-clarey I have no detailed knowledge of fbx. I only joined this thread because I found the question interesting whether/how image data could be baked into the model file. So I would like to forward this question to @takahirox.

**Comment by takahirox** [comment]
I know the specification of >=7500 is a bit different from < 7500, and
am working on that to support >= 7500.
Can you share the binary model data of version 7500 for the test?

**Comment by hmtri1011** [comment]
Hi all, can I have a React Component that can render a FBX Loader like the example below, I have tried React-Three-Renderer but I dont know too much about their code so I cant implement a React Component like this.

**Comment by hmtri1011** [comment]
This is the code what I want to create a React Component that can render a FBX Model, but It show a THREE.FBXLoader is not a constructor.

Am I doing wrong, really need some help

```
import React, { Component } from 'react'
import ReactDOM from 'react-dom'
import React3 from 'react-three-renderer'
import * as THREE from 'three'
import Stats from 'stats.js'

/*eslint-disable react/no-string-refs */
/*eslint-disable react/no-find-dom-node */
export default class Preview3D extends Component {
  constructor(props) {
    super(props)

    this.state = {
      cameraPosition: new THREE.Vector3(0, 50, 1500),
      lookAt: new THREE.Vector3(0, 200, 0)
    }

    this.lightPosition = new THREE.Vector3(1, 1, 1)
    this.clock = new THREE.Clock()

    this.mixers = []
    this._onAnimate = () => {}
  }

  componentDidMount() {
    const { scene } = this.refs

    // stats
    this.stats = new Stats()
    this.refs.container.appendChild(this.stats.domElement)

    const onProgress = function(xhr) {
      if (xhr.lengthComputable) {
        var percentComplete = xhr.loaded / xhr.total * 100
        console.log(Math.round(percentComplete, 2) + '% downloaded')
      }
    }

    const onError = function(xhr) {
      console.error(xhr)
    }

    const manager = new THREE.LoadingManager()
    manager.onProgress = function(item, loaded, total) {
      console.log(item, loaded, total)
    }

    const loader = new THREE.FBXLoader(manager)
    loader.load(
      '../accient_2_full.fbx',
      function(object) {
        scene.children.push(object)
      },
      onProgress,
      onError
    )

    // controls, camera
    const controls = new THREE.OrbitControls(
      this.refs.mainCamera,
      ReactDOM.findDOMNode(this.refs.react3)
    )

    controls.target.set(0, 12, 0)
    controls.addEventListener('change', () => {
      this.setState({
        cameraPosition: this.refs.mainCamera.position
      })
    })

    let light = new THREE.HemisphereLight(0xffffff, 0x444444, 1.0)
    light.position.set(0, 1, 0)
    scene.children.push(light)

    light = new THREE.DirectionalLight(0xffffff, 1.0)
    light.position.set(0, 1, 0)
    scene.children.push(light)
  }

  componentWillUnmount() {
    delete this.stats
  }

  render() {
    const width = window.innerWidth // canvas width
    const height = window.innerHeight // canvas height

    return (
      <div ref="container">
        <React3
          mainCamera="camera" // this points to the perspectiveCamera below
          width={width}
          height={height}
          onAnimate={this._onAnimate}
          ref="react3"
        >
          <scene ref="scene">
            <perspectiveCamera
              name="camera"
              fov={70}
              aspect={width / height}
              near={1}
              far={3000}
              position={this.state.cameraPosition}
              lookAt={this.state.lookAt}
            />
            <gridHelper size={1000} divisions={10} />
            <directionalLight
              color={0xffffff}
              intensity={2}
              position={this.lightPosition}
            />
            <mesh>
              <boxGeometry width={1} height={1} depth={1} />
              <meshBasicMaterial color={0x00ff00} />
            </mesh>
          </scene>
        </React3>
      </div>
    )
  }
}

```

**Comment by adam-clarey** [comment]
So after more testing, 7200 and 7500 seem to be fine.

However, 6100 and 7300 dont render.
[house_fs.fbx.zip](https://github.com/mrdoob/three.js/files/1010667/house_fs.fbx.zip)
[DutchHouse.FBX.zip](https://github.com/mrdoob/three.js/files/1010668/DutchHouse.FBX.zip)

**Comment by takahirox** [comment]
Would you share the ascii version files?
We can clarify it the issue is binary specific or not.

**Comment by takahirox** [comment]
And I hope we close this issue because `FBXLoader` supports binary now (maybe not perfect yet tho).
Let's make another issue for `FBXLoader` improvement.

**Comment by Mugen87** [comment]
@takahirox Sounds good!

**Comment by FishOrBear** [comment]
@adam-clarey  
I think i got this bug.

```
"FBXLoader: Unknown property type "
where the variable 'type' is an empty string
```

in FBXLoader.js  <line 4010>
change to 

'''
			while ( ! this.endOfContent( reader ) ) {

				var node = this.parseNode( reader, version );
				if ( node !== null ) 
					allNodes.add( node.name, node );
				else
					break;

			}
'''

**Comment by nxhoang** [comment]
Hello everyone,
I noticed that FBXLoader just supports FBX file to be >= 7.0.
Now I want to load fbx file below 7.0, please tell how to do this?
Thanks a lot.

**Comment by looeee** [comment]
@nxhoang as we discussed [here](https://discourse.threejs.org/t/load-fbx-file-with-textures-including-images/2566/27), we only support FBX versions above 6100 (Binary) or 7000 (ASCII). 

If you need to use older FBX files you'll need to update them  (best to load them into 3ds max or Maya to do this), or convert them to another format.
