### ISSUE TITLE
The xy, xz and yz translate planes are not visible from the back.  

### ISSUE THREAD

**Issue by ddemott** [mrdoob/three.js#9864]
##### Description of the problem 

When using the translate functionality (for the TransformControl.js) and are viewing the translate planes (xy, xz and/or yz) planes to move your object along those planes, if the object was rotated to face the back of these planes, they are not visible or usable.

##### Three.js version

- [ ] Dev
- [x ] r81
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mlknz** [comment]
Changing line 15 of [TransformControls](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/TransformControls.js) from `this.side = THREE.FrontSide;` to `this.side = THREE.DoubleSide;` should fix that.

**Comment by ddemott** [comment]
Worked like a charm.  Thanks!
