### ISSUE TITLE
Android devices will not render more than one point light after r75+

### ISSUE THREAD

**Issue by Glinkis** [mrdoob/three.js#9871]
Version r75 and onwards seems to have broken being able to render multiple point lights on android devices. I have tested this on a few different devices, with the primary one being my Nexus 5.

As you can see on the attached images only the red light will get rendered.

Android:
![](https://cloud.githubusercontent.com/assets/8037927/19427770/4e35f2b2-9446-11e6-84bc-4cc9c1cc7c2e.png)

Desktop:
![](https://cloud.githubusercontent.com/assets/8037927/19427812/9692a690-9446-11e6-8e78-70ce1fcf6090.png)

##### Three.js version

- [x] r75+

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

**Comment by Mugen87** [comment]
I can confirm this bug (Sony Z1 Compact, Android 5.1.1, Chrome and FF, three R81).

**Comment by mrdoob** [comment]
#9100

**Comment by Glinkis** [comment]
I apologize for the duplicate. I could not find the other one when I searched.

**Comment by bhouston** [comment]
I fixed this via this PR #9948
