### ISSUE TITLE
New shader for Pixelate Effect

### ISSUE THREAD

**Issue by robertcasanova** [mrdoob/three.js#9874]
Hi, i've just created a new Shader for a Post processing effect i need. 
If somebody find it useful i will make a PR for adding it to Shaders directory.

https://github.com/robertcasanova/pixelate-shader

Let me know, thx!

**Comment by mrdoob** [comment]
> If somebody find it useful i will make a PR for adding it to Shaders directory.

Yes please!

**Comment by Mugen87** [comment]
The [three.js forum](https://discourse.threejs.org/) is a good place for posting such projects. There is a category `Showcase` you can use.
