### ISSUE TITLE
Allow inversion of OrbitControls

### ISSUE THREAD

**Issue by andrewhosgood** [mrdoob/three.js#9875]
It would be really helpful if somehow I could invert the OrbitControls, optionally changing the following function:

https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/OrbitControls.js#L431

to use either:

```javascript
// Normal
rotateLeft( 2 * Math.PI * rotateDelta.x / element.clientWidth * scope.rotateSpeed );
//Inverted
rotateLeft( 2 * Math.PI * -rotateDelta.x / element.clientWidth * scope.rotateSpeed );
```
 and

```javascript
// Normal
rotateUp( 2 * Math.PI * rotateDelta.y / element.clientHeight * scope.rotateSpeed );
//Inverted
rotateUp( 2 * Math.PI * -rotateDelta.y / element.clientHeight * scope.rotateSpeed );
```

**Comment by WestLangley** [comment]
What object are you passing to the `OrbitControls` constructor?

**Comment by rhairston** [comment]
For this I would probably just add the functionality to your own code since it's a small change.

**Comment by andrewhosgood** [comment]
@WestLangley I am initialising the controls with `new THREE.OrbitControls( this.camera );`.

@rhairston I was hoping to keep up to date with the latest threejs versions and this would be something I have to update every time. It wouldn't be so bad if the function `handleMouseMoveRotate` belonged to `THREE.OrbitControls` rather than existing as a private method because I would have access to overwrite it with my own code.

**Comment by WestLangley** [comment]
@andrewhosgood You should be able to achieve what you want by negating `controls.rotateSpeed`.

However, I am trying to understand what you are doing that requires such a change. Is your scene a panorama, and is your camera viewing a sphere or box from the inside?

**Comment by andrewhosgood** [comment]
@WestLangley Yes, we are viewing a sphere from the inside. Setting the `controls.rotateSpeed = -1` worked a treat! I missed this due to looking at the same problem for too long.

I think you can close this issue now. Thank you all for your help!
