### ISSUE TITLE
Problem with material reuse in colladaloader2.js

### ISSUE THREAD

**Issue by BengtGustafsson** [mrdoob/three.js#9878]
##### Description of the problem

I use a tool called OarConv which produces collada files with multiple `<polylist>` elements in one `<mesh>` refering to the same material. This works in colladaloader but in colladaloader2 there seems to be a design flaw that the return value of buildGeometry() is a group which is a map indexed by the material name and which contains just one THREE.Mesh (or similar) object per material name, so when the function runs it overwrites the preceeding <polylist>'s representation with the succeding one.

I am not totally convinced that this Collada is within the specification but it seems logical that you can have multiple <polylist>s with the same material and these colladas load in blender and 3ds max and unity.

As this is an architectural level issue I don't see a possibility for me to fix it, there is no easy patch that can be done. I was thinking about uniquifying the material name and duplicating the definition but that was too much of a hack for me to bear...

[oar_house.txt](https://github.com/mrdoob/three.js/files/535814/oar_house.txt)

Attached .txt file is actually a dae file.
##### Three.js version
- [x ] Dev (also tried r74 but the code looks the same)
- [ ] r81
- [ ] ...
##### Browser
- [x] All of them (obviously)
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by BengtGustafsson** [comment]
I investigated further and there is nothing in the Collada spec to indicate that reusing a material in more than one polylist would be illegal (see page 5-99 of https://www.khronos.org/files/collada_spec_1_4.pdf). So I do think this is a bug rather than an enhancement, then of course the priorization of this bug is another matter. Note also that it works with colladaloader v1.

**Comment by Mugen87** [comment]
`ColladaLoader2` should support now this now (#11502).
