### ISSUE TITLE
distorted positioning  using draggable-cubes example as a model

### ISSUE THREAD

**Issue by pontiffpublishing** [mrdoob/three.js#9881]
##### Description of the problem 

I used the draggable-cubes example from your repository as a model and found that as I moved objects outward from the center of the screen, there was an increasing distortion of their positioning relative to the actual x,y coordinates of the mouse--I am using planer objects perpendicular to the camera, so the distorted positioning is clear 

Playing around with the original example on your site, it looks as if position reporting relative to screen coordinates might also be affected by camera perspective.  This might be related to closed issue #9587 (rounding error, nothing can be done), but I wanted to add that if you switch from the approach used in your draggable cubes example to one offered by third parties on the internet, (add a big, invisible plane perpendicular to the Camera, raycast, and get the intersection point), though the solution is not as elegant as your example, the distortion disappears.

Best Regards.

##### Three.js version

- [ ] Dev
- [ X ] r81
- [ ] ...

##### Browser

- [] All of them
- [ X] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [X ] Windows
- [ X] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
That example is actually where the invisible plane facing the camera idea comes from. We changed it eventually.
