### ISSUE TITLE
Force material to compile shader before first render

### ISSUE THREAD

**Issue by brianchirls** [mrdoob/three.js#9887]
##### Description of the problem

Shaders only get compiled the first time they are used in a visible object. And shaders can take a long time to compile because there is a GPU read to get the shader compilation/linking status. This can cause a lot of jank, especially on mobile devices.

If an object is added late in a scene, this can be particularly bad because the jank can cause you to miss the animation of the object's appearance.

It would be helpful to be able to force a material to initialize its shader in advance so you can get all the jank out of the way ahead of time before starting your animations.
##### Three.js version
- [x] Dev
- [x] r81
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

Everywhere, but mostly visible on mobile and slower GPUs.

**Comment by takahirox** [comment]
How about simply rendering all objects and clear
before invoking main animation&rendering loop like this

    // renderer, camera, scene, and objects creation here

    var tmpScene = new THREE.Scene();

    for ( var i = 0, il = objects.length; i < il; i ++ ) {

        tmpScene.add( objects[ i ] );

    }

    // off rendering with WebGLRenderTarget is another option.
    renderer.render( scene, camera );
    renderer.clear();

    // construct scene from some of objects here

    // invoke main animation & rendering loop here
    // and then add the objects left to scene at/on some timings/events

**Comment by brianchirls** [comment]
Fixed by #10960
