### ISSUE TITLE
Blender export 'material.blending' as string , but THREE required a interger

### ISSUE THREAD

**Issue by jarvis1024** [mrdoob/three.js#9889]

**Comment by jdanford** [comment]
@jarvis1024 can you explain the problem in more detail?

**Comment by wuweiweiwu** [comment]
@jdanford I think he meant https://threejs.org/docs/#api/constants/Materials like `THREE.NormalBlending` which are integer constants

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
