### ISSUE TITLE
Method to detect whether browser has reclaimed a webgl context?

### ISSUE THREAD

**Issue by abelnation** [mrdoob/three.js#9893]
##### Description of the problem

Is there a way to detect if a WebGLRenderer's WebGL context has been reclaimed by the browser?  Chromes limit is rather small and the pool is shared among all open tabs.  Let me know.  Thanks!

**Comment by mrdoob** [comment]
You mean context lost?

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L257
