### ISSUE TITLE
Some Faulty Projects in "featured projects" Section

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#9896]
I've marked the problematic projects with a red dot. They produce different errors/faulty behaviors like redirects, SSL or runtime errors. Maybe we should replace them with other projects.
Two proposals:

https://paperplanes.world
https://robertsspaceindustries.com/starmap

![projects](https://cloud.githubusercontent.com/assets/12612165/19534039/7813d1b4-9642-11e6-86a0-66f8810e8dd5.jpg)

**Comment by makc** [comment]
yes, you dont get stuff to stay around forever

**Comment by mrdoob** [comment]
I still have to add a few more projects, but I've added quite a lot! 😁
https://github.com/mrdoob/three.js/commit/06dc40190f07cd4c7becb21e5981df371c8fea7a

**Comment by Mugen87** [comment]
Cool! :wink:
