### ISSUE TITLE
TrackballControls.js zoom makes the object disappear in Chrome

### ISSUE THREAD

**Issue by AlanGrid** [mrdoob/three.js#9898]
##### Description of the problem 

TrackballControls.js zoom makes the object disappear in Chrome.

(This is NOT a help site. Please read the guidelines above before posting.)

##### Three.js version

- [ ] Dev
- [x] r81
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (NVIDIA GeForce GT 610)

[TrackballControls.js.txt](https://github.com/mrdoob/three.js/files/540531/TrackballControls.js.txt)

**Comment by Mugen87** [comment]
That's not a bug. You just have to set the 'far' property of your camera to a greater value. Example:

```javascript
camera = new THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 1, 100000 );
```

Full example: https://jsfiddle.net/rLn2Le2k/
Some background information to the topic: https://www.script-tutorials.com/webgl-with-three-js-lesson-9/

**Comment by AlanGrid** [comment]
It's not a bug just annoying issue I would like to fix.
[http://stackoverflow.com/questions/40168166/three-js-scene-that-doesnt-work-in-chrome-using-zoom-mouse-wheel](url)
