### ISSUE TITLE
Saving TextGeometry to JSON and Parsing with ObjectLoader

### ISSUE THREAD

**Issue by tmggit** [mrdoob/three.js#9905]
##### Description of the problem

I think that the ability to add and edit text to a scene would be a great addition to the three.js editor, so I started an implementation based on this example: https://threejs.org/docs/scenes/geometry-browser.html#TextGeometry
Now I am trying to figure out what the best practice would be to save TextGeometry and its parameters to a JSON file and then load it later on with the ObjectLoader. If I understand the current code correctly, TextGeometry only generates a generic Geometry object, but does not store the actual text and parameters (font, size, curvesegments, ...). Does anyone have thoughts on extending the TextGeometry object so that it stores these parameters, can be serialized to a JSON object and then loaded and edited again later on? Maybe that would also require storing the JSON font file in the exported JSON object?

Any input is welcome, as I don't want to reinvent the wheel and hopefully contribute this feature to the editor later on.
##### Three.js version
- [x] r81
##### Browser
- [x] All of them
##### OS
- [x] All of them

**Comment by mrdoob** [comment]
> Does anyone have thoughts on extending the TextGeometry object so that it stores these parameters, can be serialized to a JSON object and then loaded and edited again later on? Maybe that would also require storing the JSON font file in the exported JSON object?

Yeah, I don't know what the right solution is for all that.

**Comment by tentone** [comment]
In my project im serializing Fonts and loading them the same way three.js does with Textures (i have opened a PR once with Font / Texture / Video and Audio serialization but i closed it due to inactivity)

For Text3D objects (wich are Meshes that use TextGeometry) i dont serialize the geometry and i store: the uuid of the font used / text / bevel / size / weigth etc.

But im currently paused on fonts, i will redo them soon i want to have a font structure with enough data to generate booth  3D geometry and generate distance fields using opentype for 2D text (probably will just use opentype fonts directly)

**Comment by mrdoob** [comment]
> i have opened a PR once with Font / Texture / Video and Audio serialization but i closed it due to inactivity

Oh, you shouldn't close PRs because I haven't been able to deal with it in time...

**Comment by tentone** [comment]
Sorry, my bad, i will create a new issue then to discuss resource (Image / Video / Font / Audio) management/loading/serialization.

I am a bit short on time right now due to study and work. As soon as i have a bit free time I will review my previous pull request.

**Comment by makc** [comment]
> you shouldn't close PRs because I haven't been able to deal with it in time...

we totally should because if you haven't merged them they have conflicts and noone wants to solve that mess. we have to do things all over and submit new pr :D

**Comment by dleithinger** [comment]
Had a chance to check out your implementation of the Text3D object, looks awesome and would make a great addition to the core. There are also a bunch of really nice features in the nunuStudio editor, hope to have a chance to add some of these into the three.js editor.

**Comment by fraguada** [comment]
I thought of something over on the [discourse](https://discourse.threejs.org/t/facetype-js-a-typeface-js-generator/53/4).  What about giving `TextGeometry` a `.fontSource` or something similar that would be a link to a file to load or parse based on the content?  The change to `ObjectLoader` could be something like:
Warning untested, unconsidered code ahead...
```
...
geometry = new Geometries[ data.type ](
     data.text, {
          font: typeof(data.fontSource) === 'string' ? new FontLoader.load(data.fontSource):new Font(data.fontSource),
          size: data.data.size,
          height: data.data.height
     });

break; 
...
```

**Comment by tentone** [comment]
@fraguada Please look at my Font implementation on nunuStudio (source/resources/Font.js) i would really think that we should have a Resource abstraction for Images, Video, Audio, etc  that takes care of loading, format management etc in three.js.

**Comment by fraguada** [comment]
If we treat fonts as resources (which I think makes sense) I see two ways forward:

1. Parse fonts prior to .[parseGeometries](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ObjectLoader.js#L126) then pass fonts to `.parseGeometries`, add back the case for `TextGeometry`.
2. Parse fonts after` .parseGeometry`, pass fonts to` .parseObjects` and add a new object type 'Text' to be parsed in` .parseObjects`

**Comment by mrdoob** [comment]
I think option 1 makes more sense.

**Comment by tentone** [comment]
I think the first one makes more sense as well, that allow in the future to use the font data to create distance maps for 2D text.

@fraguada please take a look here https://github.com/tentone/nunuStudio/tree/master/source/core/resources

**Comment by fraguada** [comment]
Ok.  This is my first draft: #11026.  Only loads glyphs embedded in the file to be loaded by ObjectLoader.  When I get a bit more time I can add loading fonts from .json files.  I tested with [this scene file](https://gist.github.com/fraguada/46ffef2a262d7ebc5ab4170a436234f9), and it worked well.

@tentone this implementation is very simple (read: not complete) compared to yours.  I'll go back through your code to see the changes which can be brought through (TTF Loading for example, which is now in js/examples).  Let me know what you think.

**Comment by tentone** [comment]
@fraguada Looks nice

I think we should implement a solid base for resources, by this i mean a base resouce class that handle all sorts of data representations (XML, CSV, PlainText, JSON, Base64, ArrayBuffer, BinaryString, etc),  convert between those as required, serialize data to JSON and restore it to the pretended format etc.  (I have wrote a bunch of utils for convertion that are available in the nunuStudio repo).

I tried before to implement the resource system inside threejs but i think there isnt a lot of people interested. I belive that it would be better to move all json serialization to external modules, that would allow people to focus more on main features and rendering technologies.

**Comment by fraguada** [comment]
@tentone I generally agree. Maybe make a separate issue, and we work on it there?

**Comment by fraguada** [comment]
Can anyone suggest a technique to load fonts from .json files in a way that could be integrated into the `ObjectLoader`?  I'm attempting to use [FontLoader](https://github.com/mrdoob/three.js/blob/dev/src/loaders/FontLoader.js) as it is.  Would it need to be modified for it to work in this context ( since FontLoader.load() doesn't have a call to return a font )?  FontLoader.parse() works fine for a file with an embedded glyph set as I mentioned before.

**Comment by Mugen87** [comment]
`TextGeometry`, `FontLoader` and `Font` have been removed from core. Hence, `Font` and `TextGeometry` won't be supported by `ObjectLoader`.
