### ISSUE TITLE
[minor] Bug in ObjectLoader's URL regex

### ISSUE THREAD

**Issue by leewz** [mrdoob/three.js#9906]
The [regex](https://github.com/mrdoob/three.js/blob/247454fea12f02edb638ff0d4ce347234416e6ab/src/loaders/ObjectLoader.js#L377) in question:

```
/^(\/\/)|([a-z]+:(\/\/)?)/i
```

The second part of the branch should also have a `^`.

---

How about this instead?

```
/^(\/|[a-z][a-z0-9\+\.\-]*:)/i
```

Reasoning:
- The `^` needs to be outside of the group with `|`, so that it applies to both. Currently, it matches "a/x?y:z", which is a relative path.
- A single slash begins a relative URL to an absolute path, so only check for one slash. Currently, "/a?b=c" can turn into "http://example.com/texture/path//a?b=c".
- The URI scheme (the part before the `:`) is [as specified on Wikipedia](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax).
  - The backslashes in the character class aren't strictly necessary.
- The check for "maybe two slashes" in the second branch is redundant. (Optional tails don't affect regex tests.)
- Removed redundant parentheses.

The scheme part of the regex could be `[a-z]+` for the sake of performance. Most schemes of interest only use letters. However, the cost of the regex test will probably be much smaller than the cost of loading the image itself.

The single-leading-slash case might need to be handled separately. Maybe an absolute path should resolve to "http://example.com/a?b=c" instead of "http://example.com/texture/path//a?b=c". That's something that needs to be decided and documented.

Also, "https:/a?b=c" is [supposedly valid](http://stackoverflow.com/questions/14780350/convert-relative-path-to-absolute-using-javascript#comment49850671_25833886) as an absolute path relative to the current host over a different protocol. It's unlikely that anyone will use that, though, and both Chrome and Firefox resolve that path to "https://a?b=c".

---

Alternatively, the regex can be replaced by a path-resolving utility function. If we don't want a library, we should find a well-tested snippet somewhere.
- MDN has [a snippet that can be adapted.](https://developer.mozilla.org/en-US/docs/Web/API/document/cookie#Using_relative_URLs_in_the_path_parameter)
- [Here's a shim for URLUtils.](https://gist.github.com/Yaffle/1088850).
- [A DOM-based hack using the `<base>` tag.](http://stackoverflow.com/a/12965135/)

Since Not Invented Here is more fun, I found a few ways of implementing it. Here's one using the [`URL` constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) (which might require the above shim):

```
path = new URL(image.url, scope.texturePath).href;
```

I think `scope.texturePath` must be an absolute URL (not path) here.

---

It's, uh, just a minor bug.

**Comment by mrdoob** [comment]
How about...

```js
/^(\/\/)|^([a-z]+:(\/\/)?)/i
```

**Comment by leewz** [comment]
That should work for all sane cases except `"/relative/url/absolute/path"`.

**Comment by mrdoob** [comment]
Hmm, not sure I understand that use case...

**Comment by leewz** [comment]
One might specify an image by an absolute path. It corresponds to `<a href="/relative/url/absolute/path">`, which will go to "http://www.example\.com/relative/url/absolute/path" even if the base page is "http://www.example\.com/something/else".

I wrote that as the path because it's an absolute path, but still a relative URI.

**Comment by mrdoob** [comment]
I see. Then...?

```js
/^(\/|[a-z]+:)/i
```

**Comment by leewz** [comment]
Absolute path has to be handled separately. It's a third case. 

	var path = image.url;
	if ( /^(\/\/|[a-z]+:)/i.test( path ) ) { //absolute URL
	} else if ( path.charAt(0) === '/') {
		path = _resolveAbsolutePathSomehow(scope.texturePath, path);
	} else {
		path = scope.texturePath + path;
	}

----

Note that some other loaders should need to resolve URLs relative to a given path, but only ObjectLoader uses this regex. That might indicate more problems, if any of them can be reused.
* XHRLoader uses simple concatenation (without checking for absolute URL).
* JSONLoader uses `Loader#extractUrlBase` and delegates to `Loader#createMaterial`.
* Loader uses concatenation.

Others eventually delegate to XHRLoader and call `setPath` on it.

---

P.S.: Is there a reason to use `JSON.parse` on the response of `XHRLoader`, rather than set its `responseType` to 'json' to get a preparsed object?

**Comment by mrdoob** [comment]
> P.S.: Is there a reason to use `JSON.parse` on the response of `XHRLoader`, rather than set its `responseType` to 'json' to get a preparsed object?

Not really. Would you like to do a PR implementing that in the relevant loaders? 😊

**Comment by mrdoob** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest says that `responseType = 'json'` is not supported on Internet Explorer.

**Comment by Mugen87** [comment]
Closing. Let's only change the regex in `ObjectLoader` if other users reports issues in that regard. AFAIK, this was not the case since 2016.
