### ISSUE TITLE
[example page]

### ISSUE THREAD

**Issue by evejweinberg** [mrdoob/three.js#9908]
##### CSS YouTube example broken 

Is it ok to put issues regarding examples here? I'm trying to create a boiler plate for an html element rendered onto a 3D Plane, and thought this YouTube example would be it:
https://threejs.org/examples/?q=3d#css3d_youtube

**Comment by Mugen87** [comment]
Hi Eve!

This is a known SSL bug and already fixed in `dev` branch (see #9802).

**Comment by evejweinberg** [comment]
rad! Can I pull the dev branch or is it coming soon? Either way - thanks for the quick reply. Super appreciated.

**Comment by Mugen87** [comment]
My pleasure! 😊 

I think it's best when you work on the `dev` branch. Unfortunately, I don't know the release date of `R82`.
