### ISSUE TITLE
Any idea how to use Three.js with Oculus Mobile SDK for Android?

### ISSUE THREAD

**Issue by bot3d** [mrdoob/three.js#9911]
##### Description of the problem 

I am not sure how to use the wonderful Three.js with Oculus Mobile SDK for Android. Samsung solution is quite crappy and unusable (https://github.com/Samsung/GearVRf). Please advice if I can use Three.js on Android.

##### Three.js version

- [ ] Dev
- [ ] r81
- [ ] ...

##### OS

- [] All of them
- [ ] Windows
- [ ] Linux
- [ X] Android
- [ ] IOS

**Comment by mrdoob** [comment]
You should take a look at https://webvr.info/
