### ISSUE TITLE
Suggestion: advanced WebGL detection

### ISSUE THREAD

**Issue by Chaky74** [mrdoob/three.js#9924]
##### Description of the problem 

Some devices don't (or can't) display some aspects of models. For example, some Windows phones can't handle cubemaps properly.

I've stumbled upon this handy site: [http://webglreport.com/](http://webglreport.com/)
It reports in detail what browser/device is capable of.
I think such code could be VERY useful within three.js itself, so it could adjust its performance to the browser/device capabilities, while coder on the other side could anticipate such scenarios and prepare "fallback" modes.

##### Three.js version

- [ ] Dev
- [ ] r81
- [x] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
There is already such functionality. Just have a look at `WebGLCapabilities`. It is internally used in  `WebGLRenderer`. [Example](https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L2474)

**Comment by mrdoob** [comment]
> Some devices don't (or can't) display some aspects of models. For example, some Windows phones can't handle cubemaps properly.

What do those devices render in this example?

https://threejs.org/examples/#webgl_materials_cubemap

**Comment by mrdoob** [comment]
Also, yes. We already do that for texture sizes, anisotropy, etc
