### ISSUE TITLE
When calling .updateMatrixWorld,  .matrixWorldInverse not updated automatically, is this a bug?

### ISSUE THREAD

**Issue by ash0080** [mrdoob/three.js#9926]
##### Description of the problem 
As title
##### Three.js version
- [x] r81
##### Browser
- [x] All of them
##### OS
- [x] All of them

**Comment by ash0080** [comment]
Really hard to find this issue...

**Comment by mrdoob** [comment]
Is not a bug. `matrixWorldInverse` is only updated at render time.
Maybe it shouldn't be a public property...

**Comment by ash0080** [comment]
hmm.. 
The problem I encountered was when I match a 2D position(in a 2D canvas) to the 3D space, the matrixWorldInverse alway updated correctly in the "next frame" , so 2D position updating always one frame behind the 3D position updating, after enforce .updateMatrixWorld, and .matrixWorldInverse.getInverse, seems everything fine.

but I am not sure this is the correct solution. If the matrixWorldInverse updated at the same time of rendering as you say, maybe update the 2D draw after new frame of rendering is the right way.

**Comment by mrdoob** [comment]
> after enforcing .updateMatrixWorld, and .matrixWorldInverse.getInverse, seems everything fine. but I am not sure this is the correct solution. 

I think that's the right fix.
