### ISSUE TITLE
Flickering on iOS when drawing with LineSegment

### ISSUE THREAD

**Issue by tomchambers2** [mrdoob/three.js#9935]
(**\* This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)
##### Description of the problem

When rendering a line with LineSegment and preserveDrawingBuffer: true, the lines flicker on any iOS device. This doesn't happen anywhere else. I think this is a bug, apologies if not. I don't think it's z fighting as it happens with only a single line drawn in different places and incrementing the z value each time its drawn. I've added a simple test case.

[jsfiddle example](https://jsfiddle.net/6jw7vymo/)

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>three lines test</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    </head>

    <body>
        <script src="lib/three.min.js"></script>

        <script type="text/javascript">
            var canvasSize = { width: 300, height: 300 }
            var material = new THREE.LineBasicMaterial({
                    color: 0x000000
            })
            var geometry = new THREE.Geometry()
            geometry.vertices.push(
            new THREE.Vector3(-100, 0, 1),
            new THREE.Vector3(100, 100, 1)
        )
            var line = new THREE.LineSegments(geometry, material);

            var camera = new THREE.OrthographicCamera( canvasSize.width / - 2, canvasSize.width / 2, canvasSize.height / 2, canvasSize.height / - 2, 10, 10000 );
            camera.position.set(0, 0, -10);
            var scene = new THREE.Scene();
            scene.add(line);
            var renderer = new THREE.WebGLRenderer({
                    preserveDrawingBuffer: true,
                    alpha: true,
            });
            renderer.setPixelRatio(window.devicePixelRatio)
            renderer.setSize(canvasSize.width, canvasSize.height)
            renderer.autoClearColor = false

            camera.lookAt(scene.position)
            document.body.appendChild(renderer.domElement)

            draw()

            function draw() {
                    for (var i = 0; i < geometry.vertices.length; i+=2) {
                        geometry.vertices[i].x += 20
                        geometry.vertices[i+1].x += 20
                        geometry.vertices[i].z += 1
                        geometry.vertices[i+1].z += 1
                    }
            geometry.verticesNeedUpdate = true
            renderer.render(scene, camera)

            requestAnimationFrame(draw)
        }
        </script>
    </body>
</html>
```
##### Three.js version
- [ ] Dev
- [x] r82
- [ ] ...
##### Browser
- [] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] iOS/webkit browsers
##### OS
- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

**Comment by Mugen87** [comment]
What happens if you set `preserveDrawingBuffer` to `false`? Besides, do you think you can create a reduction test with plain WebGL? Just to be sure, it's not a problem in the library. For me this looks like an issue on iOS.

**Comment by tomchambers2** [comment]
If `preserveDrawingBuffer: false` it works fine. I'm afraid I don't have enough knowledge with plain WebGL to make a test case. You might be right that it's an iOS implementation issue, feel free to close the issue if it's the more likely case. Any idea what specifically it might relate to?

**Comment by Mugen87** [comment]
Not sure. But `preserveDrawingBuffer` is a value that `three.js` directly passes as an attribute for creating the WebGL context. Maybe you should create an issue at the official [bugzilla](https://bugs.webkit.org/) site for WebKit. 

BTW: The problem does not occur if you run your test case with Chromium or FF, right?

**Comment by Mugen87** [comment]
@tomchambers2 Do you still experience this issue with a current iOS?

**Comment by Mugen87** [comment]
Closing for now. We can reopen it if the problem still exists.
