### ISSUE TITLE
WebGL content desapear from Chrome v54 and GTS520

### ISSUE THREAD

**Issue by dpotekhin** [mrdoob/three.js#9936]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
With new Chrome (54.0.2840.71 m) WebGL content on my configuration (Win7 + GTS250) starts to throw exception:
`THREE.WebGLRenderer: Error creating WebGL context.`
And Detector.js doesn't see WebGL context on my computer.

Meanwhile, there's no exception and renderer works properly if I activate it without antialias parameter.

How is it possible? WebGL doesn't detected but working?

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
nVidia GTS250

**Comment by hauca90** [comment]
I met this bug on Version 54.0.2840.71 m (64-bit) too.  
Creating new THREE.WebGLRenderer() will return error
``` javascript
three.js:19184 Uncaught TypeError: Cannot read property 'getExtension' of null(…)  
get	@	three.js:19184   
WebGLRenderer	@	three.js:19609  
(anonymous function)	@	VM313:1
```

**Comment by mrdoob** [comment]
Sounds like Chrome blacklisted that GPU...

Do you see the cube in https://get.webgl.org/?

How about in Firefox?

**Comment by dpotekhin** [comment]
In IE11 and FF49 WebGL works fine.
Only Chrome can't detect it in most cases: http://prntscr.com/cziwmc  ( include https://get.webgl.org/ )
But I noticed, that examples with disabled antialiasing are working: http://prntscr.com/cziu5m

**Comment by mrdoob** [comment]
Sounds like it's a Chrome issue then.

**Comment by makc** [comment]
No, @mrdoob, it is actually ours, the poor users, issue. Chrome is doing well being #1 browser and has no issue with just giving 🖕 to all people with old GPUs.

![screen shot 2017-01-30 at 9 49 18](https://cloud.githubusercontent.com/assets/242577/22416954/d3aea8ac-e6d1-11e6-84cc-09aa35f6525a.png)

I am now hit by this shit and can no longer use chrome for webgl related work. In case anyone knows how to lift the GPU ban short of patching and recompiling Chrome, let me know.

**Comment by makc** [comment]
Ok, I am overreacting here, as always.

> /Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --ignore-gpu-blacklist

Annoying, but can work.

**Comment by mrdoob** [comment]
![screen shot 2017-01-30 at 18 15 23](https://cloud.githubusercontent.com/assets/97088/22449954/31069faa-e718-11e6-84a7-ceb636527792.png)

**Comment by kkarkos** [comment]
Had the same error in Chrome Version 55.0.2883.95 (64-bit) - Mac 10.9.5 and I can confirm toggling flag 'Override software rendering list' solves the issue.
