### ISSUE TITLE
Rendering issue using a 3D texture workaround

### ISSUE THREAD

**Issue by jonathanlurie** [mrdoob/three.js#9937]
I am developping a tool for performing oblique slicing of neuro images, I am using shaders for the image projection. The projection seems to work well but I have some strange rendering artifacts in shapes of dashes. This occurs only when the projection is oblique (or at least not in the native ortho). Here is [the image](https://i.imgur.com/htmv5fE.jpg) I use as a texture, it's 64 images and each is 64x64px, for a total of 64x4096px.

The workaround I use is the solution suggested by [gman on SO](https://stackoverflow.com/questions/23006414/3d-texture-in-webgl-three-js-using-2d-texture-workaround). I also tried my own version, that uses simple nearest neighbor, but I have exactly the same issue. Note that, depending on the camera positioning, the dashes appear with a different frequency, this is why I am thinking of a rendering issue rather than a sampling issue. Also, these dashes seem to show in-between the native slices (when in oblique projection).

![screenshot from 2016-10-25 11 15 18](https://cloud.githubusercontent.com/assets/1303310/19693773/b5f9ef6a-9aaa-11e6-8de2-ab6990c0ccec.png)

![screenshot from 2016-10-25 11 15 29](https://cloud.githubusercontent.com/assets/1303310/19693775/bb631eb8-9aaa-11e6-8b20-17971414f0c2.png)

[I made a fiddle](http://jsfiddle.net/jonathanlurie/Lqb1o862/2/).

Do you think it's a shader issue? Or maybe there is some OpenGL ES thingy to enable/disable?

##### Three.js version

- [ ] Dev
- [ ] r82
- [x] r79

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by jonathanlurie** [comment]
I managed to make it work by just using the nearest neighbor interpolation: 

```js
var texture = new THREE.TextureLoader().load( texFile );
texture.magFilter = THREE.NearestFilter;
texture.minFilter = THREE.NearestFilter;
```

It works for my case but is not really a fix.

**Comment by makc** [comment]
well, what do you expect, you're jumping across many tiles and mipmaps try to mix them all together. see [here](https://0fps.net/2013/07/09/texture-atlases-wrapping-and-mip-mapping/) for the workaround (involves 4x larger texture)

**Comment by makc** [comment]
also I think @spite had the shader somewhere where he used derivatives to figure out correct bias

**Comment by NicolasRannou** [comment]
FYI I ran in similar problems and as far as I can remember it was rounding issues in my case.

I also wanted to comment that you could consider using [AMI/reslicing](https://fnndsc.github.io/ami/#geometries_slice) that already addresses the problem you are facing.

AMI is not part of the ThreeJS examples/demos because it would just be too much code.

AMI is a Medical Imaging Javascript toolkit build on top and for ThreeJS. Main difference with ALL existing Medical Imaging frameworks is that is relies on WebGL (not 2D canvas) for visualization, which results in a huge performance gain. It follows same API conventions as ThreeJS and provide loaders so you can already load common file formats (Dicom, nifti, nrrd, etc.) out of the box.

Please let me know if you'd like to contribute!

**Comment by jonathanlurie** [comment]
Thanks @makc for the link! It looks like I am not the only one facing this issue :)

**Comment by jonathanlurie** [comment]
@NicolasRannou AMI looks like a great project! For the `slice` example, I understood you used a stack of 56 DICOM 2D images of 384x542x16bit. Did you try with a larger resolution of each slice?

**Comment by jonathanlurie** [comment]
@NicolasRannou AMI looks like a pretty well advance project! I had a glance at the slice code and it looks like you are loading 56 dicom images of 384x512x16bits, did you try with higher resolution?  
The project I have is to create a multiresolution 3D viewer for large neuro imaging data (the [BigBrain](https://bigbrain.loris.ca/main.php), which is about 7000x7000x7000 at 20μm), using an octree and a 3d texture workaround with dynamic fetching/loading. The cube I showed in the fiddle is only one of the chunks.

**Comment by NicolasRannou** [comment]
Nice!

Yes I tried bigger but as you said `7000x7000x7000` is definitely too big to be loaded all at once.
Right now, we can only load 14x4096x4096 16 bits voxels at once in the shaders.

Yes fetching the right data and resolution from the server on demand could work. Please do not hesitate to post on stackoverflow if you have questions or open issues on https://github.com/FNNDSC/ami/issues if you have any question, suggestions, or just to continue the conversation!

**Comment by jonathanlurie** [comment]
@NicolasRannou I'll keep you updated! if it works, it might be an interesting feature for AMI, and it's gonna be open source anyway :)
