### ISSUE TITLE
Invisible character in code at line 24664 

### ISSUE THREAD

**Issue by backspaces** [mrdoob/three.js#9939]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
Invisible character in code at line 24664
![snap 10 25 16-16 50 18](https://cloud.githubusercontent.com/assets/124366/19707209/8c309b6a-9ad3-11e6-82c8-21c1010bc6fe.jpg)

When the invisible char is removed the README program works correctly, otherwise fails.

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
Mac OS X Sierra

##### Hardware Requirements (graphics card, VR Device, ...)
Recent MBP13, works fine for older demos

**Comment by WestLangley** [comment]
It is in `TubeBufferGeometry.js`.

/ping @Mugen87

**Comment by Mugen87** [comment]
Oh dear! How could that happen? I hope, the PR fixes this issue...
