### ISSUE TITLE
webgl deferred not show in examples list

### ISSUE THREAD

**Issue by sunag** [mrdoob/three.js#9940]
##### Description of the problem 

I think this is misnamed?
https://github.com/mrdoob/three.js/blob/dev/examples/webgldeferred_animation.html
https://github.com/mrdoob/three.js/blob/master/examples/files.js#L13

##### Three.js version

- [x] Dev
- [x] r82

**Comment by takahirox** [comment]
Here :D

https://github.com/mrdoob/three.js/blob/master/examples/files.js#L263

**Comment by sunag** [comment]
Ohh thanks! @takahirox Congraths to your great work in MMD and Deferred.
