### ISSUE TITLE
Include sourcemap in the repo?

### ISSUE THREAD

**Issue by leewz** [mrdoob/three.js#9941]
I haven't yet made the move to compiling three.js myself. Once I do, I can make my own sourcemap for a fresh build. But for now, and for people who can't/won't install the software needed for compiling, it'd be convenient if there was a sourcemap from `build/three.min.js` to `build/three.js`.

I'm currently trying to profile my code, but I can either use `three.min.js` and get accurate performance, or `three.js` and know what's being profiled.

Also, from what I know, threejs.org could use the minified version on its example pages, and browser tools will recognize the sourcemap. I'm sure there are other issues there, though.

I noticed that #2654 (from 2012) implemented sourcemaps.

**Comment by mrdoob** [comment]
@Rich-Harris Does Rollup generate sourcemaps?

**Comment by Rich-Harris** [comment]
@mrdoob yes – it just needs a `sourceMap: true` option in the export from rollup.config.js

**Comment by mattdesl** [comment]
@Rich-Harris has this changed in recent rollup versions? I am trying with rollup@0.53.4 and some custom code that looks like this:

```js
const { rollup } = require('rollup');
const memory = require('rollup-plugin-memory');

function glsl () {
  return {
    transform (code, id) {
      if (/\.glsl$/.test(id) === false) return;

      var transformedCode = 'export default ' + JSON.stringify(
        code
          .replace(/[ \t]*\/\/.*\n/g, '') // remove //
          .replace(/[ \t]*\/\*[\s\S]*?\*\//g, '') // remove /* */
          .replace(/\n{2,}/g, '\n') // # \n+ to \n
      ) + ';';
      return {
        code: transformedCode,
        map: { mappings: '' }
      };
    }
  };
}

module.exports = function (dependencies, debug) {
  const entry = require.resolve('three/src/Three.js');
  return rollup({
    input: entry,
    plugins: [
      // Generated entry code
      memory({
        path: entry,
        contents: 'export { Triangle } from "./math/Triangle.js";'
      }),
      glsl()
    ]
  }).then(bundle => {
    return bundle.generate({
      sourcemap: 'inline',
      file: 'three.js',
      name: 'THREE',
      format: 'iife'
    });
  }).then(result => result.code.length);
};

if (!module.parent) {
  module.exports().then(code => console.log(code));
}
```

The file does not appear to have the inline source map at the end of the file. I've tried `sourceMap`, `sourcemap`, true/false, adding it into `rollup.output` options, etc.

**Comment by Rich-Harris** [comment]
Will concede this is a little bit confusing! `bundle.generate` resolves to a `{ code, map }` object, where `code` *doesn't* have a `//# sourceMappingURL` comment — it's deliberately a low level API. You have a couple of options. The long way...

```js
const { code, map } = await bundle.generate(opts);

const withInlineSourcemap = `${code}
//# sourceMappingURL=${map.toUrl()}`;

const withExternalSourcemap = `${code}
//# sourceMappingURL=bundle.js.map`;
const externalSourcemap = map.toString();
```

...is more or less equivalent to the short way:

```js
await bundle.write(opts);
```

`bundle.write` will write your bundle including the comment, plus a separate `.map` file (if `sourcemap: true` rather than `sourcemap: 'inline'`).

**Comment by aaaidan** [comment]
Was this closed as "wont fix", or because sourcemaps were successfully included in the build? I don't see the `build/three.js.map` and `build/three.modules.js.map` files mentioned in 373bf95a. Perhaps I need to do a local build for them to show up?

**Comment by mrdoob** [comment]
@aaaidan as far as I can remember, it seemed like a lot of noise and that a dev could configure rollup to produce those if needed.
