### ISSUE TITLE
Error in three.js :- Materials[json.type] is not a constructor

### ISSUE THREAD

**Issue by siddrizban** [mrdoob/three.js#9944]
##### Description of the problem 
Hi, i am working on a web app which will render 3D animated models. These models made by 'Maya 2016'. I am exporting these models using three.js (r81) 'maya exporter plugin'. Everything goes fine. But when i am loading this json model using below code:

`var objectLoader = new THREE.ObjectLoader(manager);
    objectLoader.load( 'assets/New-Heart/full_heart.json', function (object) {            
        scene.add(object);
 }, onProgress, onError );`

then getting this error (Error in three.js :- Materials[json.type] is not a constructor) on line no. - 31381
I have asked the same on StackOverflow. Here it is [link:](http://stackoverflow.com/questions/40259666/error-in-three-js-materialsjson-type-is-not-a-constructor)
I am attaching my json file (in txt format, because i was unable to attach .json file)
[heart-new.txt](https://github.com/mrdoob/three.js/files/553026/heart-new.txt)
.

##### Three.js version

- [ ] Dev
- [x ] r81
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
That file needs to be loaded with `THREE.JSONLoader` instead. I'll add a check for that in `THREE.ObjectLoader`.

**Comment by siddrizban** [comment]
Hi,
@mrdoob , thank for your quick reply. As per your suggestion i am moving with JSONLoader but still i am not getting model on my webpage.

Here it is changed code:

`var jsonloader = new THREE.JSONLoader( manager );
        jsonloader.load( jsonFileName, function( geometry, materials ) {
            for ( var i = 0; i < materials.length; i ++ ) {
                var m = materials[ i ];
                 m.morphTargets = true;
                 console.log(m);
            }
            mesh = new THREE.Mesh(geometry, new THREE.MeshFaceMaterial(materials));
            scene.add( mesh );
        } );`

**I have set camera.position.z = 100**

My console screen o/p: 

**MeshLambertMaterial {uuid: "5F9A718B-031F-45CC-9AF4-055345D2DA75", name: "Full_Heart1", type: "MeshLambertMaterial", fog: true, lights: true…}**

So i used 'MeshLabmertMaterial', but it is just showing white model (not with textures). I am attaching screentshot.

![screenshot](https://cloud.githubusercontent.com/assets/15338165/19758454/c1f2126a-9c45-11e6-8b67-a57874024187.png)


Here it is my json materials array :

`    "materials": [{
        "opacity": 0.0, 
        "mapDiffuseRepeat": [1, 1], 
        "mapNormalFactor": 1, 
        "depthTest": true, 
        "colorDiffuse": [0.5, 0.5, 0.5], 
        "vertexColors": false, 
        "blending": "NormalBlending", 
        "mapDiffuseAnisotropy": 4, 
        "shading": "Blinn", 
        "transparent": true, 
        "depthWrite": true, 
        "mapNormalRepeat": [1, 1], 
        "mapNormalWrap": ["repeat", "repeat"], 
        "DbgName": "orange", 
        "mapNormalAnisotropy": 4, 
        "mapNormal": "orange_bump.jpg", 
        "mapDiffuseWrap": ["repeat", "repeat"], 
        "mapDiffuse": "orange.jpg"
    }, {
        "opacity": 0.0, 
        "mapDiffuseRepeat": [1, 1], 
        "mapNormalFactor": 1, 
        "depthTest": true, 
        "colorDiffuse": [0.5, 0.5, 0.5], 
        "vertexColors": false, 
        "blending": "NormalBlending", 
        "mapDiffuseAnisotropy": 4, 
        "shading": "Blinn", 
        "transparent": true, 
        "depthWrite": true, 
        "mapNormalRepeat": [1, 1], 
        "mapNormalWrap": ["repeat", "repeat"], 
        "DbgName": "orange", 
        "mapNormalAnisotropy": 4, 
        "mapNormal": "orange_bump.jpg", 
        "mapDiffuseWrap": ["repeat", "repeat"], 
        "mapDiffuse": "orange.jpg"
    }, {
        "opacity": 0.0, 
        "colorDiffuse": [0.10324621354410368, 0.19598565393664913, 0.35121951626568304], 
        "depthWrite": true, 
        "blending": "NormalBlending", 
        "shading": "Blinn", 
        "DbgName": "plate", 
        "transparent": true, 
        "depthTest": true, 
        "vertexColors": false
    }, {
        "opacity": 0.0, 
        "mapDiffuseRepeat": [1, 1], 
        "mapNormalFactor": 1, 
        "depthTest": true, 
        "colorDiffuse": [0.5, 0.5, 0.5], 
        "vertexColors": false, 
        "blending": "NormalBlending", 
        "mapDiffuseAnisotropy": 4, 
        "shading": "Blinn", 
        "transparent": true, 
        "depthWrite": true, 
        "mapNormalRepeat": [1, 1], 
        "mapNormalWrap": ["repeat", "repeat"], 
        "DbgName": "orange", 
        "mapNormalAnisotropy": 4, 
        "mapNormal": "orange_bump.jpg", 
        "mapDiffuseWrap": ["repeat", "repeat"], 
        "mapDiffuse": "orange.jpg"
    }, {
        "opacity": 0.0, 
        "mapDiffuseRepeat": [1, 1], 
        "mapNormalFactor": 1, 
        "depthTest": true, 
        "colorDiffuse": [0.5, 0.5, 0.5], 
        "vertexColors": false, 
        "blending": "NormalBlending", 
        "mapDiffuseAnisotropy": 4, 
        "shading": "Blinn", 
        "transparent": true, 
        "depthWrite": true, 
        "mapNormalRepeat": [1, 1], 
        "mapNormalWrap": ["repeat", "repeat"], 
        "DbgName": "orange", 
        "mapNormalAnisotropy": 4, 
        "mapNormal": "orange_bump.jpg", 
        "mapDiffuseWrap": ["repeat", "repeat"], 
        "mapDiffuse": "orange.jpg"
    }, {
        "opacity": 0.0, 
        "mapDiffuseRepeat": [1, 1], 
        "mapNormalFactor": 1, 
        "depthTest": true, 
        "colorDiffuse": [0.5, 0.5, 0.5], 
        "vertexColors": false, 
        "blending": "NormalBlending", 
        "mapDiffuseAnisotropy": 4, 
        "shading": "Blinn", 
        "transparent": true, 
        "depthWrite": true, 
        "mapNormalRepeat": [1, 1], 
        "mapNormalWrap": ["repeat", "repeat"], 
        "DbgName": "orange", 
        "mapNormalAnisotropy": 4, 
        "mapNormal": "orange_bump.jpg", 
        "mapDiffuseWrap": ["repeat", "repeat"], 
        "mapDiffuse": "orange.jpg"
    }]`

**Comment by danvk** [comment]
I ran into this same error today. The issue in my case was that the JSON file referenced `MeshFaceMaterial`, which is no longer a thing. Changing it to `MeshBasicMaterial` let me load the file:

    perl -pe 's/MeshFaceMaterial/MeshBasicMaterial/g' broken.json > working.json

**Comment by Oyefes** [comment]
I keep getting this error 
![20230106-003700](https://user-images.githubusercontent.com/98193829/210900426-c9751b50-ebb9-4ad3-91f9-31f3a0f5b052.png)
And it really stressful cus am using unpkg link to import three js so does anyone one has a solution

**Comment by Oyefes** [comment]
![20230106-004205](https://user-images.githubusercontent.com/98193829/210900908-66264425-c79f-4698-976b-b26e34eae57f.png)
This is the code , thanks

**Comment by WestLangley** [comment]
@Oyefes `MeshFaceMaterial` was deprecated years ago.

This is not a help site. If you need help, try the three.js [forum](https://discourse.threejs.org).
