### ISSUE TITLE
Geometries are using an invalid reference to THREE (r82)

### ISSUE THREAD

**Issue by mikecao** [mrdoob/three.js#9950]
##### Description of the problem 

Getting the following error when trying to create some geometries: `ReferenceError: THREE is not defined`. I've traced it down to the call to `fromBufferGeometry` method using a reference to THREE instead of the imported class name.

See: https://github.com/mrdoob/three.js/blob/master/src/geometries/DodecahedronGeometry.js.

Correct usage is here: https://github.com/mrdoob/three.js/blob/master/src/geometries/PolyhedronGeometry.js

It looks like several geometries are affected.

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
#9945
