### ISSUE TITLE
Texture & animation not working using JSONLoader model exported by 'maya exporter plugin'

### ISSUE THREAD

**Issue by siddrizban** [mrdoob/three.js#9953]
Hi @mrdoob , [As per closed issue](https://github.com/mrdoob/three.js/issues/9944), i have followed your instructions (as you suggested on closed issue)
,So i am moving with JSONLoader but still i am getting model without texture.

Here it is changed code:

```js
var jsonloader = new THREE.JSONLoader( manager ); 
jsonloader.load( jsonFileName, function( geometry, materials ) { 
    for ( var i = 0; i < materials.length; i ++ ) { 
        var m = materials[ i ]; m.morphTargets = true; console.log(m); 
    } 
    mesh = new THREE.Mesh(geometry, new THREE.MeshLambertMaterial(materials)); scene.add( mesh ); 
} );
```

I am using 'MeshLabmertMaterial', becuase in materials array 'shading' type is "Lambert". 
I am attaching screentshot.

**Note : Could you suggest me what material type should i use with exported json models to render with real texture?** 

![screenshot](https://cloud.githubusercontent.com/assets/15338165/19760462/8326a1f4-9c4f-11e6-808a-8d20d05934de.png)

Here it is my json materials array :

    "materials": [{
        "opacity": 0.0, 
        "mapDiffuseRepeat": [1, 1], 
        "mapNormalFactor": 1, 
        "depthTest": true, 
        "colorDiffuse": [0.5, 0.5, 0.5], 
        "vertexColors": false, 
        "blending": "NormalBlending", 
        "mapDiffuseAnisotropy": 4, 
        "shading": "Lambert", 
        "transparent": true, 
        "depthWrite": true, 
        "mapNormalRepeat": [1, 1], 
        "mapNormalWrap": ["repeat", "repeat"], 
        "DbgName": "Arota", 
        "mapNormalAnisotropy": 4, 
        "mapNormal": "Heart_Arota_NM.jpg", 
        "mapDiffuseWrap": ["repeat", "repeat"], 
        "mapDiffuse": "Heart_Arota_Diffuse.jpg"
    }, {
        "opacity": 0.0, 
        "mapDiffuseRepeat": [1, 1], 
        "mapNormalFactor": 1, 
        "depthTest": true, 
        "colorDiffuse": [0.5, 0.5, 0.5], 
        "vertexColors": false, 
        "blending": "NormalBlending", 
        "mapDiffuseAnisotropy": 4, 
        "shading": "Lambert", 
        "transparent": true, 
        "depthWrite": true, 
        "mapNormalRepeat": [1, 1], 
        "mapNormalWrap": ["repeat", "repeat"], 
        "DbgName": "Full_Heart1", 
        "mapNormalAnisotropy": 4, 
        "mapNormal": "Full_Heart_NM.jpg", 
        "mapDiffuseWrap": ["repeat", "repeat"], 
        "mapDiffuse": "Full_Heart_Diffuse.jpg"
    }]

##### Three.js version

- [ ] Dev
- [x] r81
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
You should be using `THREE.MultiMaterial` instead of `THREE. MeshLambertMaterial `.

```js
var jsonloader = new THREE.JSONLoader( manager ); 
jsonloader.load( jsonFileName, function( geometry, materials ) { 
    for ( var i = 0; i < materials.length; i ++ ) { 
        var m = materials[ i ]; m.morphTargets = true; console.log(m); 
    } 
    mesh = new THREE.Mesh(geometry, new THREE.MultiMaterial(materials)); scene.add( mesh ); 
} );
```

**Comment by siddrizban** [comment]
Hi @mrdoob,
I am very much thankful to you for your help, but i have tried **MultiMaterial**, but it just shows blank (black) screen. I thought it might be problem with camera (z position) but i was wrong, because when i am using **MeshNormalMaterial**'then it is showing part I image:  when i am using **MultiMaterial** then it is showing black screen (part II image).

Here it is my full code:

`// common global variables for displaying file
            var container, controls, effect, clock;
            var camera, scene, renderer, tween;
            var manager, onProgress, onError;
            var ambient, directionalLight, hemisphereLight;

            var jsonFileName = 'assets/New-Heart/new-heart.json';

            init();

            function init() {
                // get div to draw canvas
                container = document.getElementById('3d-object-preview');

                // camera
                camera = new THREE.PerspectiveCamera(30, window.innerWidth / window.innerHeight, 0.1, 10000);
                camera.position.set(0, 0, 100);
                scene = new THREE.Scene();
                camera.lookAt(scene.position);

                // ambient light
                ambient = new THREE.AmbientLight(0xffffff, 1);
                scene.add(ambient);

                //loading manager
                manager = new THREE.LoadingManager();
                manager.onProgress = function (item, loaded, total) {
                    console.log(item, loaded, total);
                };

                // jsonloader
                var jsonloader = new THREE.JSONLoader(manager);
                jsonloader.load(jsonFileName, function (geometry, materials) {
                    //mesh = new THREE.Mesh(geometry, new THREE.MeshNormalMaterial(materials));
                    mesh = new THREE.Mesh(geometry, new THREE.MultiMaterial(materials));
                    scene.add(mesh);
                }, onProgress, onError);

                /* Renderer */
                renderer = new THREE.WebGLRenderer({
                    antialias: true, // to get smoother output
                    preserveDrawingBuffer: true // to allow screenshot
                });
                renderer.setPixelRatio(window.devicePixelRatio);
                renderer.setSize(window.innerWidth, window.innerHeight);
                container.appendChild(renderer.domElement);
                animate();
            }

            function animate() {
                requestAnimationFrame(animate);                
                render();
            }

            function render() {
                renderer.render(scene, camera);
            }`

I am attaching a screenshot contains both screen (Part I & II)

![part i](https://cloud.githubusercontent.com/assets/15338165/19795576/6d7eca56-9cfa-11e6-8665-acd76cead58a.png)
![part ii](https://cloud.githubusercontent.com/assets/15338165/19795577/6d8a09b6-9cfa-11e6-87bc-9866aa7f1ea8.png)

**Comment by siddrizban** [comment]
When i debug three.js (r81) and found undefind value for this **json.materials**. That's why it is not going in following block:

`// MultiMaterial
if ( json.materials !== undefined ) {
    for ( var i = 0, l = json.materials.length; i < l; i ++ ) {
    		material.materials.push( this.parse( json.materials[ i ] ) );
    }
}`

So it might be reason to not display anything.

**Comment by siddrizban** [comment]
I am attaching my json file (in txt format, because i was unable to attach .json file). I am not sure with exported file, because it does not contains **geometries** array. So could you confirm that it is in right format to **display texture and play animation**.

[heart-new.txt](https://github.com/mrdoob/three.js/files/558264/heart-new.txt)
