### ISSUE TITLE
Error: three.projector has been moved to /examples/js/renderers/projector.js

### ISSUE THREAD

**Issue by byAhmadAli** [mrdoob/three.js#9954]
Hello, 
I had this error: three.projector has been moved to /examples/js/renderers/projector.js
![bug](https://cloud.githubusercontent.com/assets/5576728/19762498/e488466c-9c42-11e6-931e-f7938e3f5b6e.png)

and I don't use projector.js in my project.

I'm using **windows 10 Pro or Enterprise OS Build 14393.321** with **Chrome browser Version 54.0.2840.71 m (64-bit)**, I get the same issue when I open http://threejs.org Examples and Editor. Or any project using threejs library.

Any suggestions ?

**Comment by makc** [comment]
> I don't use projector.js in my project
well, you should, projector is cabvasrenderer's dependency.

**Comment by byAhmadAli** [comment]
@makc I get the same issue when I open http://threejs.org Examples and Editor. Or any project using threejs library.

This issue revealed if you using windows 10 Pro or Enterprise OS Build 14393.321 with Chrome browser Version 54.0.2840.71 m (64-bit)

**Comment by makc** [comment]
No idea, man, it totally works here. Like, if I go to https://threejs.org/examples/canvas_geometry_earth.html I see the Earth and, checking the source, it has:
```javascript
		<script src="js/renderers/Projector.js"></script>
		<script src="js/renderers/CanvasRenderer.js"></script>
```
as it always did.

**Comment by byAhmadAli** [comment]
When I put **js/renderers/Projector.js** browser hang 
can you please follow up with this issue make sure you have **windows 10 Pro or Enterprise OS Build 14393.321** and **Chrome browser Version 54.0.2840.71 m (64-bit)**

Thanks
