### ISSUE TITLE
BufferAttribute named 'hidden' drops FPS ratio super low on iOS (iPhone 7)

### ISSUE THREAD

**Issue by HasanAyan** [mrdoob/three.js#9955]
##### Description of the problem

Not that it is an important issue but I wanted to point out that if you add a BufferAttribute named 'hidden' to your BufferGeometries FPS will drop to 1-10 on iOS devices. Is this a bug from iOS guys or is there something else happening in THREE?
##### Three.js version
- [ ] Dev
- [x] r82
- [ ] ...
##### Browser
- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari iOS
##### OS
- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

**Comment by mrdoob** [comment]
Do you mind creating a jsfiddle we can use to test?

**Comment by HasanAyan** [comment]
@mrdoob I realized it has nothing to do with the name of the attribute. But the issue is still strange to me.

I am working with thousands of unique shaped meshes and I have to merge them for performance issues. I have an attribute named hidden which is Uint8Array and I use it to hide some portion of the merged mesh.

And in my shaders I use it like;

vertex shader:

```
attribute vec4 color;
                varying vec4 vcol;
                varying vec3 vNormal;
                **attribute float hidden;
                varying float vHidden;**

                void main()	{
                    vHidden= hidden;
                    vNormal = normalize( normalMatrix * normal );
                    vcol=color;
                    gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0);
                }
```

fragment shader:

```
                varying vec3 vNormal;
                varying vec4 vcol;
                **varying float vHidden;**
                void main(void) {
                    **if (vHidden>0.0){
                        discard;
                    }**
                    vec3 col = vec3(vcol);
                    float factor = abs(vNormal[2]);
                    gl_FragColor = vec4(col*0.4+col*0.6*factor,vcol[3]);
                }
```


The issue is keeping my shaders as above, if I don't add the 'hidden' attribute to my meshes I get 60 fps on iPhone 7 but it drops to 1 fps just by adding the attribute. First I thought it has something to do with the number of attributes I have but if I change the name of the attribute to something else (while keeping my shader code untouched) the fps hits 60 again

**Comment by HasanAyan** [comment]
Well I changed the data type to Float32Array and the issue seems to be resolved
