### ISSUE TITLE
FontLoader.load works asynchronously

### ISSUE THREAD

**Issue by carmenbbakker** [mrdoob/three.js#9960]
##### Description of the problem 

When invoking FontLoader.load, the function argument is not executed synchronously.

    var font = 1;
    var loader = new THREE.FontLoader();
    loader.load("some_font_file.json", function(result) {
        font = result;
    });

    function print_font() {
        console.log(font);
    }

    // Prints '1'', expected font object.
    print_font();

    // Prints the font object after 500 ms delay.
    setTimeout(print_font, 500);

##### Three.js version

- [ ] Dev
- [x] r82

##### Browser

- [ ] All of them
- [x] Chromium
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

Using Intel HD graphics, but I don't suppose this is ultimately relevant.

**Comment by Mugen87** [comment]
> FontLoader.load works asynchronously

That's the intended behavior. Synchronous requests have a fundamental drawback:

From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests): _Synchronous requests block the execution of code which creates "freezing" on the screen and an unresponsive user experience._

**Comment by mrdoob** [comment]
All the loaders in the lib are asynchronous.
