### ISSUE TITLE
Smooth shading not smooth enough with VTK

### ISSUE THREAD

**Issue by kamakshidasan** [mrdoob/three.js#9967]
I am currently developing an application using Three.js. In this application, I am loading VTK files using the VTKLoader and displaying them using MeshPhongMaterial and the default Smooth Shading. However, I get to see Triangle Patches on my mesh while displaying them.

For example,

![screen shot 2016-10-29 at 12 21 43 pm](https://cloud.githubusercontent.com/assets/9362064/19827806/a5daa176-9dd2-11e6-8d28-e15074a9e3ff.png)

Is this a known bug? Can this be resolved?

Here is the demo link if you would like to test it out: http://bit.ly/2fpDS27
##### Three.js version
- [x] r82
##### Browser
- [x] All of them
##### OS
- [x] All of them

**Comment by Mugen87** [comment]
Your demo link seems to be broken...

**Comment by kamakshidasan** [comment]
Sorry about that - here is the link - http://vgl.csa.iisc.ernet.in/symmetryViewer/emd/job5814e1a5679572/VTK/browser/index.html

**Comment by WestLangley** [comment]
First, your loaded model has no vertex normals.

Second, your model faces appear to have (mostly) reversed winding order, and hence (almost all of) your computed vertex normals face the interior of each mesh. This is why you had to set `material.side = THREE.DoubleSide`.

**Comment by kamakshidasan** [comment]
@WestLangley - Thank you for your comment - Can you please tell me how I should proceed further?

**Comment by WestLangley** [comment]
I expect you will have to improve your models, and avoid calling `computeVertexNormals()` on models without sufficient detail.

**Comment by kamakshidasan** [comment]
@WestLangley, I improved my models by adding the Cell Normal Values. I still do not find noticeable difference. Here is a link: http://vgl.serc.iisc.ernet.in/symmetryViewer/emd/job5816f585f02a32/VTK/browser/index.html
