### ISSUE TITLE
MeshBasicMaterial and SpecularMap

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#9968]
(**\* This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)
##### Description of the problem

SpecularMap is not working
##### Three.js version
- [x ] Dev
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
For `MeshBasicMaterial`, the specular map requires an environment map, too. Are you using both?

**Comment by whatisor** [comment]
uhm.. no, I do not need envmap. 
OK, thanks.
In fact, I want to lightmap (ao+shadow+light) and a diffuse map.
The unique way I can do now is using ShaderMaterial, so it is not so convenient.
