### ISSUE TITLE
Is it possible to provide a public function to update the BufferAttribute immediately?  

### ISSUE THREAD

**Issue by swomack** [mrdoob/three.js#9981]
I have 80m+ vertices and corresponding color attribute (which is dynamic) in my buffer geometry. Sometimes i have to update two different portions of the color buffer. Since the buffer size is huge, i have to update the buffer by parts (`gl.bufferSubData`).

But, currently there is no way to update two different parts of a buffer in a single frame. I can update one part using `updateRange` but not multiple parts. I have to update the full buffer (`gl.bufferData`) for that.

So, what i am proposing, is it possible to provide a function to update the buffer immediately when i need to update it? How about making public function/functions in `BufferAttribute` to do that?

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by aardgoose** [comment]
I don't think that would fly, BufferAttribute doesn't have any knowledge of the renderer backend, and I can't imagine that being encouraged.  Alternatively support passing an array of offset/length values to update, that the renderer could be made to handle??

**Comment by swomack** [comment]
> Alternatively support passing an array of offset/length values to update, that the renderer could be made to handle??

Yeah, that sounds to be the proper way to handle the situation.

**Comment by aardgoose** [comment]
How does the following outline for BufferAttribute look, keeps the existing API but webGLObjects only has to loop through the new updateRanges[], rather than handle the exiting updateRange and a new list?

Constructor:
```
this.updateRanges = [ { offset: 0, count: - 1 } ];

Object.defineProperty( this, "updateRange", {
   set: function ( value ) { this.updateRanges[ 0 ] = value; };
   get: function { return this.updateRanges[ 0 ] }; 
} );
```

New method.
```
.addRange( range ) {
   this.updateRanges.push( range );
}
```

**Comment by vakorol** [comment]
@mrdoob Would it work, if the local scope function `updateBuffer` in `renderers/webgl/WebGLAttributes.js` was simply modified in the following way:

```
if ( attribute.dynamic === false ) {

	gl.bufferData( bufferType, array, gl.STATIC_DRAW );

} else if ( updateRange.count === - 1 ) {

	// Not using update ranges
	gl.bufferSubData( bufferType, 0, array );

} else if ( updateRange.count === 0 ) {

	console.error( 'THREE.WebGLObjects.updateBuffer: dynamic THREE.BufferAttribute marked as needsUpdate but updateRange.count is 0, ensure you are using set methods or updating manually.' );

} else if ( Array.isArray( updateRange ) ) {

	var _bytes_per_elem = array.BYTES_PER_ELEMENT;

	for ( var i=0, len=updateRange.length; i<len; i++ ) {

		var _range = updateRange[i];
		var _offset = _range.offset;
		gl.bufferSubData( bufferType, _offset * _bytes_per_elem, array.subarray( _offset, _offset + _range.count ) );

	}

} else {

	gl.bufferSubData( bufferType, updateRange.offset * array.BYTES_PER_ELEMENT,
				array.subarray( updateRange.offset, updateRange.offset + updateRange.count ) );

	updateRange.count = 0; // reset range

}
```

?

In this case, `updateRange` may be an array. This, of course, contradicts with @aardgoose's proposal. On the other hand, implementing `updateRanges` will also be just a matter of adding a condition to the same function `updateBuffer`.

**Comment by mrdoob** [comment]
Sorry for the delay on this one guys. I think I prefer @aardgoose approach. Anyone up for doing a PR?

**Comment by oguzeroglu** [comment]
This could be done but gl.bufferSubData does not support multiple offsets so we have to merge different typed arrays into one and since typed arrays are not flexible we have to create a new typed array in each update. That can cause memory issues.

**Comment by oguzeroglu** [comment]
In this demo using the modification in the PR, 6 random vertices are picked in every 3 seconds and only they are updated: https://oguzeroglu.com/update_ranges.html
