### ISSUE TITLE
isObjectViewable() not reliable with ShaderMaterial

### ISSUE THREAD

**Issue by wojdyr** [mrdoob/three.js#9983]
(Three.js r82, any os/browser)

I'm using custom vertex shaders in ShaderMaterial to draw a grid on a screen. The grid is in the screen coordinates, so vertices set in geometry are in this case not in the world coordinates.
The grid was sometimes disappearing. Not knowing the internals of Three.js I was scratching my head for quite a while wondering what's going on.

Now I know -- `WebGLRenderer` is checking if `isObjectViewable()` by calculating automatically `boundingSphere` under the assumption that the vertex shader does the usual matrix transformation.
I'd propose to disable this check when ShaderMaterial is used, or maybe add a warning in the ShaderMaterial documentation.

Workaround: for example explicitly set `geometry.boundingSphere` with infinite radius.

**Comment by Mugen87** [comment]
The calculation of the view frustum culling is independent of the applied material. If you properly build  your geometry via `BufferGeometry` or `Geometry` everything should work fine. 

Besides, you can disable the view frustum culling per `Object3D` via the property `frustumCulled` (see [docs](https://threejs.org/docs/index.html#Reference/Core/Object3D))

**Comment by mrdoob** [comment]
Yeah, just set `mesh.frustumCulled` to `false` when you're modifying the geometry in the vertex shader.
