### ISSUE TITLE
Missing object (Lucy100k_bin.js) in webgl_materials_cubemap_refraction example

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#9995]
##### Description of the problem 
https://threejs.org/examples/obj/lucy/Lucy100k_bin.js is missing. 
It's used in the https://threejs.org/examples/?q=map#webgl_materials_cubemap_refraction example

##### Three.js version

- [x ] Dev
- [x] r82
- [ ] ...

**Comment by mrdoob** [comment]
Ops!

**Comment by Mugen87** [comment]
Thanks to git, i've easily restored the model files from command line.

**Comment by makc** [comment]
this is still not merged, right? https://threejs.org/examples/obj/lucy/Lucy100k_bin.js is 404. @mrdoob ?

**Comment by mrdoob** [comment]
We're working on it! #9999 ✌️
