### ISSUE TITLE
MeshStandardMaterial issue with normalMap

### ISSUE THREAD

**Issue by SntsDev** [mrdoob/three.js#9998]
Hi there! Thanks for the job guys!

Problem:
When a **normalMap** is set to a MeshStandardMaterial we don't get any visual "normal" effects and no warnings in OSX + any browser. All the other maps work: map, envMap, roughnessMap and metalicMap. 

We've tried with many textures that work with MeshPhongMaterial to no sucess. Sizes tested: 256x256, 1024x1024 & 2048x2048, normal jpg textures. 

When we use iOS 10 we get the following warning and no map is shown (and thus the texture is black):

`WARNING: 0:256: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)`

The same happens on some other computers (Win).

If we don't set the normalMap the texture works Ok on iOS, but of course, we lack of bumps. I we set bumpMap instead no warning appears, the material appears ok in the screen but without bumps.

##### Three.js version

- [] Dev
- [X] r81
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [X] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
Can you provide a live example to demonstrate the problem? How are you setting `normalScale`?

**Comment by SntsDev** [comment]
In 2 ways:
* not setting it at all - default value -
* `material.normalScale.set( 1, -1 ).multiplyScalar(Math.min(1, Math.max(-1, myNormalLevel || 1)));`

Code:

```
let material, materials;

function getTextureMap(nameOfMap) { //Cached texture maps (images)
    let mat = me._mapsLoaded[nameOfMap];
    if (mat) { return mat; }
    mat = new THREE.TextureLoader().load(texturesImgsBase + nameOfMap);
    me._mapsLoaded[nameOfMap] = mat;
    return mat;
}

materials = {
    colorMap: getTextureMap(mInfo.colorMap),
    normalMap: getTextureMap(mInfo.normalMap),
    roughnessMap: getTextureMap(mInfo.roughnessMap),
    metalnessMap: getTextureMap(mInfo.metalnessMap),
};

material = new THREE.MeshStandardMaterial({ 
    //side: THREE.DoubleSide, 
    color: 0xffffff,
    roughness: mInfo.roughnessLevel || 0.5,
    metalness: mInfo.metalness || 0.5,
    refractionRatio: mInfo.refractionRatio || 0.98,
    envMapIntensity: mInfo.envMapIntensity || 1.0,
    map: materials.colorMap,
    normalMap: materials.normalMap,
    roughnessMap: materials.roughnessMap,
    metalnessMap: materials.metalnessMap,
    envMap: me.reflectionCube,
    normalScale: new THREE.Vector2( 1, -1 )
});

if (mInfo.diffuse           !== undefined) { 
    material.color.r = mInfo.diffuse[0];
    material.color.g = mInfo.diffuse[1];
    material.color.b = mInfo.diffuse[2];
}

material.normalScale.set( 1, -1 ).multiplyScalar(Math.min(1, Math.max(-1, mInfo.normalLevel || 1)));   

```

But, as I told you, setting the "bumpMap" instead of the "normalMap" throws no errors but shows no bumps.

It is under development:
@WestLangley, my client doesn't want me to make it public. If you give me a way to DM you I can send you a temporary link.

Thanks!

**Comment by WestLangley** [comment]
@SntsDev A live demo using a non-proprietary model that reproduces the issue would be best. Can you provide that?

**Comment by SntsDev** [comment]
@WestLangley, I've just created a reduced version of it:

http://lnx.saants.es/static87616tre5.html

You can access the mesh with:
`app3d.renderer3d.meshesHolder.children[1].children[0]`

Thanks!

**Comment by mrdumb** [comment]
It works fine for me.
Here is a better example:
http://necromanthus.com/Test/html5/Lara_standard.html 
Just click on the stage to switch from PHONG to STANDARD.

				normalMap: mat1.normalMap 

If you remove (comment) that line you'll see the difference in the Standard Material.

**Comment by SntsDev** [comment]
Thank you @mrdumb, but the issue is there although you don't see it on your screen. 

Let me recap: 
* You might be able to see things working and no warnings, **but in some computers don't work at all**. I haven't been able to find a computer where the normalMap is visible. Can you post here a screenshot?
* Even if rendering happens and materials are shown, normalMap texture isn't shown (no bumps).

That happens to many examples. *Even with the example you just gave me*. It works ok on OSx + Safari 10. But if you try to render this in iOS 10 you get a lot of WebGL errors and no rendering at all, **Lara doesn't appear**.

Here you can see the console of the iPhone 6s (iOS 10.1) when browsing http://necromanthus.com/Test/html5/Lara_standard.html:

![lara-example](https://cloud.githubusercontent.com/assets/4103411/20004439/9bd7e0bc-a28c-11e6-8cca-594110b46c27.png)

In my example, the rendering works in OSx + Safari 10, no normals shown. And, again, in iOS 10 you don't get any textures.

![saants-example](https://cloud.githubusercontent.com/assets/4103411/20004834/c7a598a4-a28e-11e6-8979-82ae4bdfd412.png)

As you can see, what is common to all the examples is:
**"WARNING: 0:256: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)"**


On another PC with Edge 11 + Win 10, when the normalMap is set, I get again no textures at all.

Thank you.

**Comment by mrdumb** [comment]
>  Can you post here a screenshot?

I get the same visual result on various devices (PC, Mac, tablet and Android phone).

![lara_standard](https://cloud.githubusercontent.com/assets/23124731/20005201/825d543e-a299-11e6-83bd-ec46f7cd6729.jpg)

**Comment by SntsDev** [comment]
Thanks @mrdumb, my question was regarding my own example. Can you please post a screenshot of my example that shows the bumps? Why do you say it works?

Please find here a screenshot of your url on an iPhone 6s (iOS 10.1).
![archivo 4-11-16 15 21 32](https://cloud.githubusercontent.com/assets/4103411/20008876/906b548c-a2a2-11e6-98c2-201467c52938.png)

Shader is generating a WebGL exception.

@WestLangley, can you contribute please? It is not only a matter of rendering or not, or texturing or not, but of generating WebGL errors that create different results in different GPUs.

**Comment by WestLangley** [comment]
@SntsDev wrote

>I haven't been able to find a computer where the normalMap is visible.

This `MeshStandardMaterial` with `normalMap` works for me on iOS 10 and macOS 10.12: http://threejs.org/examples/webgl_materials_displacementmap.html.

**Comment by SntsDev** [comment]
Thanks @WestLangley, that example works. But, as I mentioned, there are two examples that don't work well with normal maps. I attached screenshots of the errors.

Some might work and some might not. That is the problem, its reliability. 

I took a look at the [shader chunk](/src/renderers/shaders/ShaderChunk/normalmap_pars_fragment.glsl) and followed a [link to the inspiration source](http://hacksoflife.blogspot.com.es/2009/11/per-pixel-tangent-space-normal-mapping.html) of it. There it says that sometimes the approach might break down whenever some conditions on the models met (check the part "When Does This Break Down"): 

"**You may know from experience that tangent space normal mapping will fail if the author's UV map is zero or one dimensional (that is, the author mapped a triangle in the mesh to a line or point on the UV map)**." 

This seems to be the the problem in my case. The modeler sent me a model with a UV map and it worked. 

Do you think that you could add a way to detect this and do some logging so we can know when this is the problem?

**Comment by WestLangley** [comment]
You model must have valid UVs. You can visually inspect the UV mapping: see http://threejs.org/examples/misc_uv_tests.html.
